#ifndef SSB64_NDS_AUDIO_BGM_H
#define SSB64_NDS_AUDIO_BGM_H

#include <PR/ultratypes.h>

#define NDS_AUDIO_BGM_PASS 0x42474d31u /* BGM1 */
#define NDS_AUDIO_BGM_TRACK_PUPUPU 0u
/* P2-4 Yoster: nSYAudioBGMYoster, ninth gmMusicID entry. Render pending --
 * see scripts/sfx/bgm/render-audio-bgm-pupupu.py --sequence-index 8. */
#define NDS_AUDIO_BGM_TRACK_YOSTER 8u
#define NDS_AUDIO_BGM_TRACK_WIN_MARIO 12u
#define NDS_AUDIO_BGM_TRACK_WIN_FOX 16u
#define NDS_AUDIO_BGM_TRACK_RESULTS 22u
/* P2-1d-1. nSYAudioBGMModeSelect, gm/gmsound.h's gmMusicID enum -- verified by
 * fully parsing the enum (no REGION_US conditionals in gmMusicID, unlike
 * gmFGMVoiceID) and cross-checked against the four anchors already pinned
 * above: Pupupu 0, WinMario 12, WinFox 16, Results 22 all land exactly where
 * this file already has them, and ModeSelect follows at 44 in the same
 * parse. */
#define NDS_AUDIO_BGM_TRACK_MODE_SELECT 44u
/* P2-1e-1. nSYAudioBGMBattleSelect, gm/gmsound.h's gmMusicID enum -- verified
 * by fully parsing the enum (no REGION_US conditionals in gmMusicID) and
 * cross-checked against the five anchors already pinned above: Pupupu 0,
 * WinMario 12, WinFox 16, Results 22, ModeSelect 44 all land exactly where
 * this file already has them, and BattleSelect lands at 10 in the same
 * parse -- the eleventh declared entry, two below WinDefault (11). */
#define NDS_AUDIO_BGM_TRACK_BATTLE_SELECT 10u
/* The 33 remaining gmMusicID entries, rendered 2026-09-05 (the win themes,
 * the 1P campaign, the modes and the two item themes); same parse. */
#define NDS_AUDIO_BGM_TRACK_INISHIE_HURRY 3u
#define NDS_AUDIO_BGM_TRACK_WIN_DEFAULT 11u
#define NDS_AUDIO_BGM_TRACK_WIN_METROID 13u
#define NDS_AUDIO_BGM_TRACK_WIN_DONKEY 14u
#define NDS_AUDIO_BGM_TRACK_WIN_KIRBY 15u
#define NDS_AUDIO_BGM_TRACK_WIN_MOTHER 17u
#define NDS_AUDIO_BGM_TRACK_WIN_YOSHI 18u
#define NDS_AUDIO_BGM_TRACK_WIN_FZERO 19u
#define NDS_AUDIO_BGM_TRACK_WIN_PMONSTERS 20u
#define NDS_AUDIO_BGM_TRACK_WIN_ZELDA 21u
#define NDS_AUDIO_BGM_TRACK_BOSS_STAGE 23u
#define NDS_AUDIO_BGM_TRACK_BOSS_ENTRY 24u
#define NDS_AUDIO_BGM_TRACK_LAST 25u
#define NDS_AUDIO_BGM_TRACK_BONUS_STAGE 26u
#define NDS_AUDIO_BGM_TRACK_STAGE_CLEAR 27u
#define NDS_AUDIO_BGM_TRACK_BONUS_STAGE_CLEAR 28u
#define NDS_AUDIO_BGM_TRACK_GAME_CLEAR 29u
#define NDS_AUDIO_BGM_TRACK_BONUS_STAGE_FAILURE 30u
#define NDS_AUDIO_BGM_TRACK_GAME_END_CHOICE 31u
#define NDS_AUDIO_BGM_TRACK_GAME_OVER 32u
#define NDS_AUDIO_BGM_TRACK_OPENING 33u
#define NDS_AUDIO_BGM_TRACK_EXPLAIN 34u
#define NDS_AUDIO_BGM_TRACK_INTRO 35u
#define NDS_AUDIO_BGM_TRACK_ZAKO 36u
#define NDS_AUDIO_BGM_TRACK_METAL 37u
#define NDS_AUDIO_BGM_TRACK_ENDING 38u
#define NDS_AUDIO_BGM_TRACK_STAFFROLL 39u
#define NDS_AUDIO_BGM_TRACK_MESSAGE 40u
#define NDS_AUDIO_BGM_TRACK_CHALLENGER 41u
#define NDS_AUDIO_BGM_TRACK_TRAINING_MODE 42u
#define NDS_AUDIO_BGM_TRACK_DATA 43u
#define NDS_AUDIO_BGM_TRACK_HAMMER 45u
#define NDS_AUDIO_BGM_TRACK_STAR 46u
#define NDS_AUDIO_BGM_SAMPLE_RATE 22050u
/* P2-1L bug (b1). Regenerated by render-audio-bgm-pupupu.py after fixing
 * collect_loop_metadata() to truncate the flat trailing render pad at a
 * clean loop-period boundary instead of leaving it inside the loop as
 * measured true digital silence (offline RMS 0.0) right before the wrap.
 * loop_start_byte is unchanged -- the fix is a proven no-op there for a
 * track where every channel already agrees on one shared loop period.
 *
 * P2-1L bug (b2), 2026-08-19: the owner re-tested (b1) by ear and found
 * two further defects, both fixed at the render seam (render()/
 * decode_wave() in render-audio-bgm-pupupu.py), so every *_SHA256_LO
 * below moved again even though byte counts/loop points did not:
 * (i) notes held longer than one straight ADPCM decode pass of their
 * wavetable rendered silence for the remainder instead of looping the
 * wavetable's own authored ALADPCMloop sustain region (n_env.c's
 * n_alAdpcmPull) -- this was the surviving "quiet patch" on Battle
 * Select, located to the exact sample range of that track's one long
 * sustained note by cross-correlating the owner's DS.wav re-recording
 * against our own decoded output; (ii) every note used a flat "+2200
 * samples, 700-sample fade" release regardless of its authored envelope,
 * where this bank's own ALEnvelope data (attackTime/decayTime/
 * releaseTime/attackVolume/decayVolume, always present but previously
 * unread) gives most instruments a 25-30 ms release -- a fraction of the
 * old ~100 ms tail, and the measured mechanism behind the "smeared/
 * legato vs the N64 reference's staccato" comparison. */
#define NDS_AUDIO_BGM_PUPUPU_STREAM_BYTES 2843290u
#define NDS_AUDIO_BGM_PUPUPU_LOOP_START_BYTES 8798u
#define NDS_AUDIO_BGM_PUPUPU_STREAM_SHA256_LO 0xbad487f5u
#define NDS_AUDIO_BGM_PUPUPU_ASSET_BYTES 711920u
#define NDS_AUDIO_BGM_PUPUPU_ASSET_SHA256_LO 0x26f98d91u
#define NDS_AUDIO_BGM_PUPUPU_PACKET_COUNT 88u
#define NDS_AUDIO_BGM_PUPUPU_LOOP_PACKET 1u
#define NDS_AUDIO_BGM_PUPUPU_LOOP_RECORD 2252u
/* P2-4 Yoshi's Island, rendered 2026-09-03 from S1_music_sbk sequence 8
 * through scripts/sfx/bgm/render-audio-bgm.py, the same tool and the same
 * path as Dream Land above. The sequence index is the gmMusicID enum value
 * (gm/gmsound.h:31-40, sequential from 0 with no REGION_US arm in the BGM
 * range). Unlike Dream Land, this track's channels do NOT all agree on one
 * loop period -- the renderer took the majority-agreeing period, so the loop
 * starts at packet 10 rather than packet 1. Pins are the render metadata
 * verbatim: assets/audio/bgm_yoster_ima.json. */
#define NDS_AUDIO_BGM_YOSTER_STREAM_BYTES 2605160u
#define NDS_AUDIO_BGM_YOSTER_LOOP_START_BYTES 313088u
#define NDS_AUDIO_BGM_YOSTER_STREAM_SHA256_LO 0xf5b4ee3fu
#define NDS_AUDIO_BGM_YOSTER_ASSET_BYTES 652292u
#define NDS_AUDIO_BGM_YOSTER_ASSET_SHA256_LO 0xff8dc77bu
#define NDS_AUDIO_BGM_YOSTER_PACKET_COUNT 80u
#define NDS_AUDIO_BGM_YOSTER_LOOP_PACKET 10u
#define NDS_AUDIO_BGM_YOSTER_LOOP_RECORD 78432u
/* P2-4 Peach's Castle, rendered 2026-09-03 from S1_music_sbk sequence 6
 * through the same tool and path. Sequence 6 is nSYAudioBGMCastle, counted
 * in gm/gmsound.h:31-37. Like Yoshi's Island and unlike Dream Land its
 * channels disagree on a loop period, so the loop starts at packet 5. Pins
 * are the render metadata verbatim: assets/audio/bgm_castle_ima.json. */
#define NDS_AUDIO_BGM_CASTLE_STREAM_BYTES 3719952u
#define NDS_AUDIO_BGM_CASTLE_LOOP_START_BYTES 158986u
#define NDS_AUDIO_BGM_CASTLE_STREAM_SHA256_LO 0x85a192d2u
#define NDS_AUDIO_BGM_CASTLE_ASSET_BYTES 931400u
#define NDS_AUDIO_BGM_CASTLE_ASSET_SHA256_LO 0x65cfffd3u
#define NDS_AUDIO_BGM_CASTLE_PACKET_COUNT 114u
#define NDS_AUDIO_BGM_CASTLE_LOOP_PACKET 5u
#define NDS_AUDIO_BGM_CASTLE_LOOP_RECORD 39848u
/* P2-4 zebes, rendered 2026-09-03 from music sequence 1; pins are
 * assets/audio/bgm_zebes_ima.json verbatim. */
#define NDS_AUDIO_BGM_ZEBES_STREAM_BYTES 2466506u
#define NDS_AUDIO_BGM_ZEBES_LOOP_START_BYTES 28458u
#define NDS_AUDIO_BGM_ZEBES_STREAM_SHA256_LO 0x3df3a2e6u
#define NDS_AUDIO_BGM_ZEBES_ASSET_BYTES 617580u
#define NDS_AUDIO_BGM_ZEBES_ASSET_SHA256_LO 0x56181f34u
#define NDS_AUDIO_BGM_ZEBES_PACKET_COUNT 76u
#define NDS_AUDIO_BGM_ZEBES_LOOP_PACKET 1u
#define NDS_AUDIO_BGM_ZEBES_LOOP_RECORD 7168u
/* P2-4 hyrule, rendered 2026-09-03 from music sequence 9; pins are
 * assets/audio/bgm_hyrule_ima.json verbatim. */
#define NDS_AUDIO_BGM_HYRULE_STREAM_BYTES 1881520u
#define NDS_AUDIO_BGM_HYRULE_LOOP_START_BYTES 332478u
#define NDS_AUDIO_BGM_HYRULE_STREAM_SHA256_LO 0xfd5a656du
#define NDS_AUDIO_BGM_HYRULE_ASSET_BYTES 471132u
#define NDS_AUDIO_BGM_HYRULE_ASSET_SHA256_LO 0x2025034fu
#define NDS_AUDIO_BGM_HYRULE_PACKET_COUNT 59u
#define NDS_AUDIO_BGM_HYRULE_LOOP_PACKET 11u
#define NDS_AUDIO_BGM_HYRULE_LOOP_RECORD 83292u
/* P2-4 yamabuki, rendered 2026-09-03 from music sequence 7; pins are
 * assets/audio/bgm_yamabuki_ima.json verbatim. */
#define NDS_AUDIO_BGM_YAMABUKI_STREAM_BYTES 2330702u
#define NDS_AUDIO_BGM_YAMABUKI_LOOP_START_BYTES 559322u
#define NDS_AUDIO_BGM_YAMABUKI_STREAM_SHA256_LO 0x892e1205u
#define NDS_AUDIO_BGM_YAMABUKI_ASSET_BYTES 583596u
#define NDS_AUDIO_BGM_YAMABUKI_ASSET_SHA256_LO 0x486024c1u
#define NDS_AUDIO_BGM_YAMABUKI_PACKET_COUNT 73u
#define NDS_AUDIO_BGM_YAMABUKI_LOOP_PACKET 18u
#define NDS_AUDIO_BGM_YAMABUKI_LOOP_RECORD 140088u
/* P2-4 inishie, rendered 2026-09-03 from music sequence 2; pins are
 * assets/audio/bgm_inishie_ima.json verbatim. */
#define NDS_AUDIO_BGM_INISHIE_STREAM_BYTES 3918852u
#define NDS_AUDIO_BGM_INISHIE_LOOP_START_BYTES 114322u
#define NDS_AUDIO_BGM_INISHIE_STREAM_SHA256_LO 0x8a560cf9u
#define NDS_AUDIO_BGM_INISHIE_ASSET_BYTES 981212u
#define NDS_AUDIO_BGM_INISHIE_ASSET_SHA256_LO 0x5abfbf43u
#define NDS_AUDIO_BGM_INISHIE_PACKET_COUNT 121u
#define NDS_AUDIO_BGM_INISHIE_LOOP_PACKET 4u
#define NDS_AUDIO_BGM_INISHIE_LOOP_RECORD 28672u
/* P2-4 Sector BGM, rendered from music sequence 4. Every value here is read
 * straight out of assets/audio/bgm_sector_ima.json, the same mapping Castle's
 * block uses: STREAM_BYTES is source_pcm_bytes, LOOP_START_BYTES is
 * loop_start_byte, ASSET_BYTES is bytes, the two SHA256_LO pins are the low
 * 32 bits of source_pcm_sha256 and sha256, and the last three are
 * packet_count, loop_packet_index and loop_record_offset. The asset was
 * rendered and staged behind NDS_P2_STAGE_SECTOR, but the track table in
 * nds_audio_bgm.c never carried a row for it, so ndsAudioBgmFindTrack missed
 * and the stage played silent through gNdsAudioBgmUnsupportedTrackCount.
 * Owner playtest, 2026-09-04. Loop start at 53.62% of the stream. */
#if NDS_P2_STAGE_SECTOR
#define NDS_AUDIO_BGM_SECTOR_STREAM_BYTES 4944528u
#define NDS_AUDIO_BGM_SECTOR_LOOP_START_BYTES 2651328u
#define NDS_AUDIO_BGM_SECTOR_STREAM_SHA256_LO 0x82bdcd79u
#define NDS_AUDIO_BGM_SECTOR_ASSET_BYTES 1237984u
#define NDS_AUDIO_BGM_SECTOR_ASSET_SHA256_LO 0x15112f93u
#define NDS_AUDIO_BGM_SECTOR_PACKET_COUNT 151u
#define NDS_AUDIO_BGM_SECTOR_LOOP_PACKET 81u
#define NDS_AUDIO_BGM_SECTOR_LOOP_RECORD 663844u
#endif
/* P2-4 Jungle BGM, rendered from music sequence 5. Every value here is read
 * straight out of assets/audio/bgm_jungle_ima.json, the same mapping Castle's
 * block uses: STREAM_BYTES is source_pcm_bytes, LOOP_START_BYTES is
 * loop_start_byte, ASSET_BYTES is bytes, the two SHA256_LO pins are the low
 * 32 bits of source_pcm_sha256 and sha256, and the last three are
 * packet_count, loop_packet_index and loop_record_offset. The asset was
 * rendered and staged behind NDS_P2_STAGE_JUNGLE, but the track table in
 * nds_audio_bgm.c never carried a row for it, so ndsAudioBgmFindTrack missed
 * and the stage played silent through gNdsAudioBgmUnsupportedTrackCount.
 * Owner playtest, 2026-09-04. Loop start at 50.06% of the stream. */
#if NDS_P2_STAGE_JUNGLE
#define NDS_AUDIO_BGM_JUNGLE_STREAM_BYTES 11678048u
#define NDS_AUDIO_BGM_JUNGLE_LOOP_START_BYTES 5845846u
#define NDS_AUDIO_BGM_JUNGLE_STREAM_SHA256_LO 0x2591ae6bu
#define NDS_AUDIO_BGM_JUNGLE_ASSET_BYTES 2923840u
#define NDS_AUDIO_BGM_JUNGLE_ASSET_SHA256_LO 0x264e867au
#define NDS_AUDIO_BGM_JUNGLE_PACKET_COUNT 357u
#define NDS_AUDIO_BGM_JUNGLE_LOOP_PACKET 179u
#define NDS_AUDIO_BGM_JUNGLE_LOOP_RECORD 1463652u
#endif
#if NDS_P2_STAGE_INISHIE
/* nSYAudioBGMInishieHurry, rendered 2026-09-05 from S1_music_sbk sequence 3 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_inishie_hurry_ima.json
 * verbatim. */
#define NDS_AUDIO_BGM_INISHIE_HURRY_STREAM_BYTES 1803860u
#define NDS_AUDIO_BGM_INISHIE_HURRY_LOOP_START_BYTES 392008u
#define NDS_AUDIO_BGM_INISHIE_HURRY_STREAM_SHA256_LO 0x08052952u
#define NDS_AUDIO_BGM_INISHIE_HURRY_ASSET_BYTES 451680u
#define NDS_AUDIO_BGM_INISHIE_HURRY_ASSET_SHA256_LO 0xcf0e4fa6u
#define NDS_AUDIO_BGM_INISHIE_HURRY_PACKET_COUNT 56u
#define NDS_AUDIO_BGM_INISHIE_HURRY_LOOP_PACKET 12u
#define NDS_AUDIO_BGM_INISHIE_HURRY_LOOP_RECORD 98188u
#endif
/* nSYAudioBGMWinDefault, rendered 2026-09-05 from S1_music_sbk sequence 11 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_win_default_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_WIN_DEFAULT_STREAM_BYTES 223308u
#define NDS_AUDIO_BGM_WIN_DEFAULT_STREAM_SHA256_LO 0x3094abb2u
#define NDS_AUDIO_BGM_WIN_DEFAULT_ASSET_BYTES 55952u
#define NDS_AUDIO_BGM_WIN_DEFAULT_ASSET_SHA256_LO 0xf9c97039u
#define NDS_AUDIO_BGM_WIN_DEFAULT_PACKET_COUNT 7u
/* nSYAudioBGMWinMetroid, rendered 2026-09-05 from S1_music_sbk sequence 13 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_win_metroid_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_WIN_METROID_STREAM_BYTES 284536u
#define NDS_AUDIO_BGM_WIN_METROID_STREAM_SHA256_LO 0x583f90bau
#define NDS_AUDIO_BGM_WIN_METROID_ASSET_BYTES 71284u
#define NDS_AUDIO_BGM_WIN_METROID_ASSET_SHA256_LO 0xf4c83830u
#define NDS_AUDIO_BGM_WIN_METROID_PACKET_COUNT 9u
/* nSYAudioBGMWinDonkey, rendered 2026-09-05 from S1_music_sbk sequence 14 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_win_donkey_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_WIN_DONKEY_STREAM_BYTES 338936u
#define NDS_AUDIO_BGM_WIN_DONKEY_STREAM_SHA256_LO 0xa09c66ecu
#define NDS_AUDIO_BGM_WIN_DONKEY_ASSET_BYTES 84908u
#define NDS_AUDIO_BGM_WIN_DONKEY_ASSET_SHA256_LO 0x3cd16e99u
#define NDS_AUDIO_BGM_WIN_DONKEY_PACKET_COUNT 11u
/* nSYAudioBGMWinKirby, rendered 2026-09-05 from S1_music_sbk sequence 15 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_win_kirby_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_WIN_KIRBY_STREAM_BYTES 200252u
#define NDS_AUDIO_BGM_WIN_KIRBY_STREAM_SHA256_LO 0x49aa2430u
#define NDS_AUDIO_BGM_WIN_KIRBY_ASSET_BYTES 50188u
#define NDS_AUDIO_BGM_WIN_KIRBY_ASSET_SHA256_LO 0x51731214u
#define NDS_AUDIO_BGM_WIN_KIRBY_PACKET_COUNT 7u
/* nSYAudioBGMWinMother, rendered 2026-09-05 from S1_music_sbk sequence 17 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_win_mother_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_WIN_MOTHER_STREAM_BYTES 339282u
#define NDS_AUDIO_BGM_WIN_MOTHER_STREAM_SHA256_LO 0xc76323a9u
#define NDS_AUDIO_BGM_WIN_MOTHER_ASSET_BYTES 84996u
#define NDS_AUDIO_BGM_WIN_MOTHER_ASSET_SHA256_LO 0x5da53f35u
#define NDS_AUDIO_BGM_WIN_MOTHER_PACKET_COUNT 11u
/* nSYAudioBGMWinYoshi, rendered 2026-09-05 from S1_music_sbk sequence 18 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_win_yoshi_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_WIN_YOSHI_STREAM_BYTES 397798u
#define NDS_AUDIO_BGM_WIN_YOSHI_STREAM_SHA256_LO 0xe19fa2d9u
#define NDS_AUDIO_BGM_WIN_YOSHI_ASSET_BYTES 99648u
#define NDS_AUDIO_BGM_WIN_YOSHI_ASSET_SHA256_LO 0x3139a84au
#define NDS_AUDIO_BGM_WIN_YOSHI_PACKET_COUNT 13u
/* nSYAudioBGMWinFZero, rendered 2026-09-05 from S1_music_sbk sequence 19 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_win_fzero_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_WIN_FZERO_STREAM_BYTES 254522u
#define NDS_AUDIO_BGM_WIN_FZERO_STREAM_SHA256_LO 0x5df98378u
#define NDS_AUDIO_BGM_WIN_FZERO_ASSET_BYTES 63768u
#define NDS_AUDIO_BGM_WIN_FZERO_ASSET_SHA256_LO 0x52b95369u
#define NDS_AUDIO_BGM_WIN_FZERO_PACKET_COUNT 8u
/* nSYAudioBGMWinPMonsters, rendered 2026-09-05 from S1_music_sbk sequence 20 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_win_pmonsters_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_WIN_PMONSTERS_STREAM_BYTES 326412u
#define NDS_AUDIO_BGM_WIN_PMONSTERS_STREAM_SHA256_LO 0xe62b1528u
#define NDS_AUDIO_BGM_WIN_PMONSTERS_ASSET_BYTES 81764u
#define NDS_AUDIO_BGM_WIN_PMONSTERS_ASSET_SHA256_LO 0x2ed610ccu
#define NDS_AUDIO_BGM_WIN_PMONSTERS_PACKET_COUNT 10u
/* nSYAudioBGMWinZelda, rendered 2026-09-05 from S1_music_sbk sequence 21 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_win_zelda_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_WIN_ZELDA_STREAM_BYTES 297110u
#define NDS_AUDIO_BGM_WIN_ZELDA_STREAM_SHA256_LO 0x78275dc5u
#define NDS_AUDIO_BGM_WIN_ZELDA_ASSET_BYTES 74440u
#define NDS_AUDIO_BGM_WIN_ZELDA_ASSET_SHA256_LO 0x390fded7u
#define NDS_AUDIO_BGM_WIN_ZELDA_PACKET_COUNT 10u
#if NDS_P2_1P_GAME
/* nSYAudioBGMBossStage, rendered 2026-09-05 from S1_music_sbk sequence 23 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_boss_stage_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_BOSS_STAGE_STREAM_BYTES 602056u
#define NDS_AUDIO_BGM_BOSS_STAGE_STREAM_SHA256_LO 0x5d3bb93eu
#define NDS_AUDIO_BGM_BOSS_STAGE_ASSET_BYTES 150784u
#define NDS_AUDIO_BGM_BOSS_STAGE_ASSET_SHA256_LO 0x784ffdeeu
#define NDS_AUDIO_BGM_BOSS_STAGE_PACKET_COUNT 19u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGMBossEntry, rendered 2026-09-05 from S1_music_sbk sequence 24 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_boss_entry_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_BOSS_ENTRY_STREAM_BYTES 856458u
#define NDS_AUDIO_BGM_BOSS_ENTRY_STREAM_SHA256_LO 0xd9d78b43u
#define NDS_AUDIO_BGM_BOSS_ENTRY_ASSET_BYTES 214480u
#define NDS_AUDIO_BGM_BOSS_ENTRY_ASSET_SHA256_LO 0xdf6bb2e0u
#define NDS_AUDIO_BGM_BOSS_ENTRY_PACKET_COUNT 27u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGMLast, rendered 2026-09-05 from S1_music_sbk sequence 25 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_last_ima.json
 * verbatim. */
#define NDS_AUDIO_BGM_LAST_STREAM_BYTES 2787708u
#define NDS_AUDIO_BGM_LAST_LOOP_START_BYTES 182420u
#define NDS_AUDIO_BGM_LAST_STREAM_SHA256_LO 0x4cae43dcu
#define NDS_AUDIO_BGM_LAST_ASSET_BYTES 698004u
#define NDS_AUDIO_BGM_LAST_ASSET_SHA256_LO 0x437ce42fu
#define NDS_AUDIO_BGM_LAST_PACKET_COUNT 86u
#define NDS_AUDIO_BGM_LAST_LOOP_PACKET 6u
#define NDS_AUDIO_BGM_LAST_LOOP_RECORD 45720u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGM1PBonusStage, rendered 2026-09-05 from S1_music_sbk sequence 26 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_bonus_stage_ima.json
 * verbatim. */
#define NDS_AUDIO_BGM_BONUS_STAGE_STREAM_BYTES 1641760u
#define NDS_AUDIO_BGM_BONUS_STAGE_LOOP_START_BYTES 200536u
#define NDS_AUDIO_BGM_BONUS_STAGE_STREAM_SHA256_LO 0xbbbb8accu
#define NDS_AUDIO_BGM_BONUS_STAGE_ASSET_BYTES 411096u
#define NDS_AUDIO_BGM_BONUS_STAGE_ASSET_SHA256_LO 0xfc9e21bcu
#define NDS_AUDIO_BGM_BONUS_STAGE_PACKET_COUNT 51u
#define NDS_AUDIO_BGM_BONUS_STAGE_LOOP_PACKET 7u
#define NDS_AUDIO_BGM_BONUS_STAGE_LOOP_RECORD 50260u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGM1PStageClear, rendered 2026-09-05 from S1_music_sbk sequence 27 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_stage_clear_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_STAGE_CLEAR_STREAM_BYTES 207666u
#define NDS_AUDIO_BGM_STAGE_CLEAR_STREAM_SHA256_LO 0xf8e46ccbu
#define NDS_AUDIO_BGM_STAGE_CLEAR_ASSET_BYTES 52044u
#define NDS_AUDIO_BGM_STAGE_CLEAR_ASSET_SHA256_LO 0x85ce63b6u
#define NDS_AUDIO_BGM_STAGE_CLEAR_PACKET_COUNT 7u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGM1PBonusStageClear, rendered 2026-09-05 from S1_music_sbk sequence 28 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_bonus_stage_clear_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_BONUS_STAGE_CLEAR_STREAM_BYTES 179310u
#define NDS_AUDIO_BGM_BONUS_STAGE_CLEAR_STREAM_SHA256_LO 0x8520fd18u
#define NDS_AUDIO_BGM_BONUS_STAGE_CLEAR_ASSET_BYTES 44940u
#define NDS_AUDIO_BGM_BONUS_STAGE_CLEAR_ASSET_SHA256_LO 0x4d75e2b1u
#define NDS_AUDIO_BGM_BONUS_STAGE_CLEAR_PACKET_COUNT 6u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGM1PGameClear, rendered 2026-09-05 from S1_music_sbk sequence 29 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_game_clear_ima.json
 * verbatim. */
#define NDS_AUDIO_BGM_GAME_CLEAR_STREAM_BYTES 1038942u
#define NDS_AUDIO_BGM_GAME_CLEAR_LOOP_START_BYTES 42802u
#define NDS_AUDIO_BGM_GAME_CLEAR_STREAM_SHA256_LO 0x537b5830u
#define NDS_AUDIO_BGM_GAME_CLEAR_ASSET_BYTES 260176u
#define NDS_AUDIO_BGM_GAME_CLEAR_ASSET_SHA256_LO 0x76b1920au
#define NDS_AUDIO_BGM_GAME_CLEAR_PACKET_COUNT 33u
#define NDS_AUDIO_BGM_GAME_CLEAR_LOOP_PACKET 2u
#define NDS_AUDIO_BGM_GAME_CLEAR_LOOP_RECORD 10768u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGM1PBonusStageFailure, rendered 2026-09-05 from S1_music_sbk sequence 30 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_bonus_stage_failure_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_BONUS_STAGE_FAILURE_STREAM_BYTES 242034u
#define NDS_AUDIO_BGM_BONUS_STAGE_FAILURE_STREAM_SHA256_LO 0x959cb44fu
#define NDS_AUDIO_BGM_BONUS_STAGE_FAILURE_ASSET_BYTES 60648u
#define NDS_AUDIO_BGM_BONUS_STAGE_FAILURE_ASSET_SHA256_LO 0x5b63680cu
#define NDS_AUDIO_BGM_BONUS_STAGE_FAILURE_PACKET_COUNT 8u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGM1PGameEndChoice, rendered 2026-09-05 from S1_music_sbk sequence 31 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_game_end_choice_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_GAME_END_CHOICE_STREAM_BYTES 357614u
#define NDS_AUDIO_BGM_GAME_END_CHOICE_STREAM_SHA256_LO 0xd3ee3995u
#define NDS_AUDIO_BGM_GAME_END_CHOICE_ASSET_BYTES 89576u
#define NDS_AUDIO_BGM_GAME_END_CHOICE_ASSET_SHA256_LO 0xfc919bf9u
#define NDS_AUDIO_BGM_GAME_END_CHOICE_PACKET_COUNT 11u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGM1PGameOver, rendered 2026-09-05 from S1_music_sbk sequence 32 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_game_over_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_GAME_OVER_STREAM_BYTES 328840u
#define NDS_AUDIO_BGM_GAME_OVER_STREAM_SHA256_LO 0x6a83968fu
#define NDS_AUDIO_BGM_GAME_OVER_ASSET_BYTES 82384u
#define NDS_AUDIO_BGM_GAME_OVER_ASSET_SHA256_LO 0xb77a10ccu
#define NDS_AUDIO_BGM_GAME_OVER_PACKET_COUNT 11u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGMOpening, rendered 2026-09-05 from S1_music_sbk sequence 33 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_opening_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_OPENING_STREAM_BYTES 4038664u
#define NDS_AUDIO_BGM_OPENING_STREAM_SHA256_LO 0x9eeed0abu
#define NDS_AUDIO_BGM_OPENING_ASSET_BYTES 1011196u
#define NDS_AUDIO_BGM_OPENING_ASSET_SHA256_LO 0xb8741f92u
#define NDS_AUDIO_BGM_OPENING_PACKET_COUNT 124u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGMExplain, rendered 2026-09-05 from S1_music_sbk sequence 34 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_explain_ima.json
 * verbatim. */
#define NDS_AUDIO_BGM_EXPLAIN_STREAM_BYTES 4110224u
#define NDS_AUDIO_BGM_EXPLAIN_LOOP_START_BYTES 1378876u
#define NDS_AUDIO_BGM_EXPLAIN_STREAM_SHA256_LO 0x09d76802u
#define NDS_AUDIO_BGM_EXPLAIN_ASSET_BYTES 1029124u
#define NDS_AUDIO_BGM_EXPLAIN_ASSET_SHA256_LO 0xeed79ae8u
#define NDS_AUDIO_BGM_EXPLAIN_PACKET_COUNT 127u
#define NDS_AUDIO_BGM_EXPLAIN_LOOP_PACKET 43u
#define NDS_AUDIO_BGM_EXPLAIN_LOOP_RECORD 345276u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGM1PIntro, rendered 2026-09-05 from S1_music_sbk sequence 35 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_intro_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_INTRO_STREAM_BYTES 226900u
#define NDS_AUDIO_BGM_INTRO_STREAM_SHA256_LO 0x295da708u
#define NDS_AUDIO_BGM_INTRO_ASSET_BYTES 56852u
#define NDS_AUDIO_BGM_INTRO_ASSET_SHA256_LO 0x827cd393u
#define NDS_AUDIO_BGM_INTRO_PACKET_COUNT 7u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGMZako, rendered 2026-09-05 from S1_music_sbk sequence 36 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_zako_ima.json
 * verbatim. */
#define NDS_AUDIO_BGM_ZAKO_STREAM_BYTES 1957730u
#define NDS_AUDIO_BGM_ZAKO_LOOP_START_BYTES 76132u
#define NDS_AUDIO_BGM_ZAKO_STREAM_SHA256_LO 0xf4169bb1u
#define NDS_AUDIO_BGM_ZAKO_ASSET_BYTES 490208u
#define NDS_AUDIO_BGM_ZAKO_ASSET_SHA256_LO 0x90379034u
#define NDS_AUDIO_BGM_ZAKO_PACKET_COUNT 61u
#define NDS_AUDIO_BGM_ZAKO_LOOP_PACKET 3u
#define NDS_AUDIO_BGM_ZAKO_LOOP_RECORD 19112u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGMMetal, rendered 2026-09-05 from S1_music_sbk sequence 37 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_metal_ima.json
 * verbatim. */
#define NDS_AUDIO_BGM_METAL_STREAM_BYTES 1446538u
#define NDS_AUDIO_BGM_METAL_LOOP_START_BYTES 52764u
#define NDS_AUDIO_BGM_METAL_STREAM_SHA256_LO 0xe4b245b9u
#define NDS_AUDIO_BGM_METAL_ASSET_BYTES 362216u
#define NDS_AUDIO_BGM_METAL_ASSET_SHA256_LO 0x9b732a9du
#define NDS_AUDIO_BGM_METAL_PACKET_COUNT 45u
#define NDS_AUDIO_BGM_METAL_LOOP_PACKET 2u
#define NDS_AUDIO_BGM_METAL_LOOP_RECORD 13256u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGMEnding, rendered 2026-09-05 from S1_music_sbk sequence 38 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_ending_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_ENDING_STREAM_BYTES 747218u
#define NDS_AUDIO_BGM_ENDING_STREAM_SHA256_LO 0xdc3dc1d8u
#define NDS_AUDIO_BGM_ENDING_ASSET_BYTES 187124u
#define NDS_AUDIO_BGM_ENDING_ASSET_SHA256_LO 0xfc3ef79eu
#define NDS_AUDIO_BGM_ENDING_PACKET_COUNT 23u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGMStaffroll, rendered 2026-09-05 from S1_music_sbk sequence 39 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_staffroll_ima.json
 * verbatim. */
#define NDS_AUDIO_BGM_STAFFROLL_STREAM_BYTES 2952316u
#define NDS_AUDIO_BGM_STAFFROLL_LOOP_START_BYTES 498060u
#define NDS_AUDIO_BGM_STAFFROLL_STREAM_SHA256_LO 0x86552b25u
#define NDS_AUDIO_BGM_STAFFROLL_ASSET_BYTES 739212u
#define NDS_AUDIO_BGM_STAFFROLL_ASSET_SHA256_LO 0x455e5828u
#define NDS_AUDIO_BGM_STAFFROLL_PACKET_COUNT 91u
#define NDS_AUDIO_BGM_STAFFROLL_LOOP_PACKET 16u
#define NDS_AUDIO_BGM_STAFFROLL_LOOP_RECORD 124748u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGMMessage, rendered 2026-09-05 from S1_music_sbk sequence 40 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_message_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_MESSAGE_STREAM_BYTES 519092u
#define NDS_AUDIO_BGM_MESSAGE_STREAM_SHA256_LO 0x650c6357u
#define NDS_AUDIO_BGM_MESSAGE_ASSET_BYTES 130008u
#define NDS_AUDIO_BGM_MESSAGE_ASSET_SHA256_LO 0x624d5f7au
#define NDS_AUDIO_BGM_MESSAGE_PACKET_COUNT 16u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGM1PChallenger, rendered 2026-09-05 from S1_music_sbk sequence 41 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_challenger_ima.json
 * verbatim (one-shot, no loop). */
#define NDS_AUDIO_BGM_CHALLENGER_STREAM_BYTES 181058u
#define NDS_AUDIO_BGM_CHALLENGER_STREAM_SHA256_LO 0x049658f7u
#define NDS_AUDIO_BGM_CHALLENGER_ASSET_BYTES 45380u
#define NDS_AUDIO_BGM_CHALLENGER_ASSET_SHA256_LO 0x2b5ed785u
#define NDS_AUDIO_BGM_CHALLENGER_PACKET_COUNT 6u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGMTrainingMode, rendered 2026-09-05 from S1_music_sbk sequence 42 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_training_mode_ima.json
 * verbatim. */
#define NDS_AUDIO_BGM_TRAINING_MODE_STREAM_BYTES 11274678u
#define NDS_AUDIO_BGM_TRAINING_MODE_LOOP_START_BYTES 9909004u
#define NDS_AUDIO_BGM_TRAINING_MODE_STREAM_SHA256_LO 0xc48be030u
#define NDS_AUDIO_BGM_TRAINING_MODE_ASSET_BYTES 2822852u
#define NDS_AUDIO_BGM_TRAINING_MODE_ASSET_SHA256_LO 0x4ef9e19fu
#define NDS_AUDIO_BGM_TRAINING_MODE_PACKET_COUNT 345u
#define NDS_AUDIO_BGM_TRAINING_MODE_LOOP_PACKET 303u
#define NDS_AUDIO_BGM_TRAINING_MODE_LOOP_RECORD 2480928u
#endif
#if NDS_P2_1P_GAME
/* nSYAudioBGMData, rendered 2026-09-05 from S1_music_sbk sequence 43 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_data_ima.json
 * verbatim. */
#define NDS_AUDIO_BGM_DATA_STREAM_BYTES 728890u
#define NDS_AUDIO_BGM_DATA_LOOP_START_BYTES 23290u
#define NDS_AUDIO_BGM_DATA_STREAM_SHA256_LO 0xadb6e205u
#define NDS_AUDIO_BGM_DATA_ASSET_BYTES 182540u
#define NDS_AUDIO_BGM_DATA_ASSET_SHA256_LO 0x88e23baau
#define NDS_AUDIO_BGM_DATA_PACKET_COUNT 23u
#define NDS_AUDIO_BGM_DATA_LOOP_PACKET 1u
#define NDS_AUDIO_BGM_DATA_LOOP_RECORD 5876u
#endif
#if NDS_P2_ITEM_CORE
/* nSYAudioBGMHammer, rendered 2026-09-05 from S1_music_sbk sequence 45 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_hammer_ima.json
 * verbatim. */
#define NDS_AUDIO_BGM_HAMMER_STREAM_BYTES 127080u
#define NDS_AUDIO_BGM_HAMMER_LOOP_START_BYTES 8808u
#define NDS_AUDIO_BGM_HAMMER_STREAM_SHA256_LO 0x9abae290u
#define NDS_AUDIO_BGM_HAMMER_ASSET_BYTES 31872u
#define NDS_AUDIO_BGM_HAMMER_ASSET_SHA256_LO 0xae2cc39bu
#define NDS_AUDIO_BGM_HAMMER_PACKET_COUNT 5u
#define NDS_AUDIO_BGM_HAMMER_LOOP_PACKET 1u
#define NDS_AUDIO_BGM_HAMMER_LOOP_RECORD 2256u
#endif
#if NDS_P2_ITEM_CORE
/* nSYAudioBGMStar, rendered 2026-09-05 from S1_music_sbk sequence 46 through
 * scripts/sfx/bgm/render-audio-bgm.py; pins are assets/audio/bgm_star_ima.json
 * verbatim. */
#define NDS_AUDIO_BGM_STAR_STREAM_BYTES 162832u
#define NDS_AUDIO_BGM_STAR_LOOP_START_BYTES 20368u
#define NDS_AUDIO_BGM_STAR_STREAM_SHA256_LO 0x426d4fdcu
#define NDS_AUDIO_BGM_STAR_ASSET_BYTES 40820u
#define NDS_AUDIO_BGM_STAR_ASSET_SHA256_LO 0x2afb209au
#define NDS_AUDIO_BGM_STAR_PACKET_COUNT 6u
#define NDS_AUDIO_BGM_STAR_LOOP_PACKET 1u
#define NDS_AUDIO_BGM_STAR_LOOP_RECORD 5144u
#endif
#define NDS_AUDIO_BGM_WIN_MARIO_STREAM_BYTES 326800u
#define NDS_AUDIO_BGM_WIN_MARIO_STREAM_SHA256_LO 0xca3f0a9bu
#define NDS_AUDIO_BGM_WIN_MARIO_ASSET_BYTES 81860u
#define NDS_AUDIO_BGM_WIN_MARIO_ASSET_SHA256_LO 0xbfd3eebbu
#define NDS_AUDIO_BGM_WIN_MARIO_PACKET_COUNT 10u
#define NDS_AUDIO_BGM_WIN_FOX_STREAM_BYTES 291154u
#define NDS_AUDIO_BGM_WIN_FOX_STREAM_SHA256_LO 0x65075ffbu
#define NDS_AUDIO_BGM_WIN_FOX_ASSET_BYTES 72940u
#define NDS_AUDIO_BGM_WIN_FOX_ASSET_SHA256_LO 0xe9e3f999u
#define NDS_AUDIO_BGM_WIN_FOX_PACKET_COUNT 9u
/* P2-1L bug (b1)+(b2). Same regenerations as Pupupu above -- loop_start
 * unchanged both times (proven no-op), only the rendered content and
 * (in b1) the stream truncation point changed. */
#define NDS_AUDIO_BGM_RESULTS_STREAM_BYTES 1583786u
#define NDS_AUDIO_BGM_RESULTS_LOOP_START_BYTES 34912u
#define NDS_AUDIO_BGM_RESULTS_STREAM_SHA256_LO 0xadc651d4u
#define NDS_AUDIO_BGM_RESULTS_ASSET_BYTES 396588u
#define NDS_AUDIO_BGM_RESULTS_ASSET_SHA256_LO 0x6ba054c1u
#define NDS_AUDIO_BGM_RESULTS_PACKET_COUNT 50u
#define NDS_AUDIO_BGM_RESULTS_LOOP_PACKET 2u
#define NDS_AUDIO_BGM_RESULTS_LOOP_RECORD 8792u
/* P2-1d-1. Rendered through scripts/sfx/bgm/render-audio-bgm-pupupu.py
 * --sequence-index 44, which is the source's own S1_music_sbk sequence index
 * for nSYAudioBGMModeSelect -- exactly the invocation the four tracks above
 * use, and the same script (its name is historical, from when Pupupu was the
 * only track). All values read off the rendered artifact and its own JSON
 * metadata, never invented: check-audio-bgm-derived-assets.ps1 re-derives
 * every one of them from the same two files.
 *
 * P2-1L bug (b1), 2026-08-19: LOOP_START_BYTES moved from 477382 to
 * 2303930 (10.8s -> 52.2s into the stream). The old value came from an
 * unconditional max() over EVERY channel's raw CSEQ loop-marker tick;
 * Mode Select has 3 channels sharing a 7680-tick loop period and 4
 * outlier channels (two carrying 1-2 notes total) with four different,
 * much longer periods, and the longest outlier dominated the max(),
 * splicing a loud, musically unrelated moment straight onto dead
 * silence every loop -- measured offline as "ends, then begins again".
 * The fix (collect_loop_metadata() in the render script) anchors on the
 * majority-period channels' own latest loop entry instead, which also
 * moved the loop to 12.8s of tail material rather than the old 53.3s of
 * cross-channel-incoherent middle. See the render script's
 * collect_loop_metadata() docstring for the full mechanism.
 *
 * P2-1L bug (b2): wavetable-loop + ADSR-envelope render fix, same as
 * Pupupu above -- loop_start/loop_end/packet layout unchanged this time,
 * only the rendered content. */
#define NDS_AUDIO_BGM_MODE_SELECT_STREAM_BYTES 2868410u
#define NDS_AUDIO_BGM_MODE_SELECT_LOOP_START_BYTES 2303930u
#define NDS_AUDIO_BGM_MODE_SELECT_STREAM_SHA256_LO 0x1d34cae1u
#define NDS_AUDIO_BGM_MODE_SELECT_ASSET_BYTES 718212u
#define NDS_AUDIO_BGM_MODE_SELECT_ASSET_SHA256_LO 0x8c7ac2c6u
#define NDS_AUDIO_BGM_MODE_SELECT_PACKET_COUNT 89u
#define NDS_AUDIO_BGM_MODE_SELECT_LOOP_PACKET 71u
#define NDS_AUDIO_BGM_MODE_SELECT_LOOP_RECORD 576876u
/* P2-1e-1. Rendered through scripts/sfx/bgm/render-audio-bgm-pupupu.py
 * --sequence-index 10, the source's own S1_music_sbk sequence index for
 * nSYAudioBGMBattleSelect -- the same script and invocation shape as the
 * five tracks above. All values read off the rendered artifact and its own
 * JSON metadata, never invented: check-audio-bgm-derived-assets.ps1
 * re-derives every one of them from the same two files.
 *
 * P2-1L bug (b1), 2026-08-19: LOOP_START_BYTES is unchanged (92456) --
 * every channel already agrees on one shared 15360-tick loop period, so
 * the old max()/max() reading was already correct. What was wrong is
 * STREAM_BYTES: the old render appended a flat, content-independent
 * ~1 second of trailing silence after the last note, and that pad sat
 * INSIDE the loop region (measured offline: RMS 0.0 in the 10 ms before
 * the wrap, RMS 691 right after) -- audible as "ends, then begins
 * again" on this track's short ~13 s loop even though the loop point
 * itself was fine. The regenerated stream truncates at the loop-period
 * boundary instead.
 *
 * P2-1L bug (b2), 2026-08-19: the owner's DS.wav re-recording still had
 * a quiet patch and sounded legato against the n64.wav reference.
 * Located the quiet patch by cross-correlating DS.wav against our own
 * decoded container (0.91 match at a +1.48 s offset -- the recording's
 * own lead-in) to map its RMS dip onto container samples 280718-313967
 * exactly: channel 14's one long sustained note (program 18, note 101),
 * whose wavetable has an authored ALADPCMloop (start=15367 end=26688
 * count=0xFFFFFFFF, i.e. loop forever) that decode_wave() was not
 * honoring, so the note ran out of source samples at 13958 of its
 * 33249-sample duration and rendered silence for the remaining ~0.87 s.
 * Same render fix as Pupupu above also replaced the flat release tail
 * with this bank's authored ALEnvelope releases (this track's are
 * mostly 25-30 ms, some instruments carry multi-hundred-ms decays to
 * decayVolume=0 -- a natural fade, not a cliff). loop_start/loop_end/
 * packet layout unchanged. */
#define NDS_AUDIO_BGM_BATTLE_SELECT_STREAM_BYTES 628352u
#define NDS_AUDIO_BGM_BATTLE_SELECT_LOOP_START_BYTES 92456u
#define NDS_AUDIO_BGM_BATTLE_SELECT_STREAM_SHA256_LO 0x546a98c4u
#define NDS_AUDIO_BGM_BATTLE_SELECT_ASSET_BYTES 157372u
#define NDS_AUDIO_BGM_BATTLE_SELECT_ASSET_SHA256_LO 0xb38a7cffu
#define NDS_AUDIO_BGM_BATTLE_SELECT_PACKET_COUNT 20u
#define NDS_AUDIO_BGM_BATTLE_SELECT_LOOP_PACKET 3u
#define NDS_AUDIO_BGM_BATTLE_SELECT_LOOP_RECORD 23192u
/* Retain the first stream's names for older Boundary diagnostics. */
#define NDS_AUDIO_BGM_STREAM_BYTES NDS_AUDIO_BGM_PUPUPU_STREAM_BYTES
#define NDS_AUDIO_BGM_STREAM_SHA256_LO NDS_AUDIO_BGM_PUPUPU_STREAM_SHA256_LO
#define NDS_AUDIO_BGM_CONTAINER_MAGIC 0x31414742u /* BGA1 */
#define NDS_AUDIO_BGM_CONTAINER_VERSION 1u
#define NDS_AUDIO_BGM_CONTAINER_HEADER_BYTES 40u
#define NDS_AUDIO_BGM_PACKET_HEADER_BYTES 8u
#define NDS_AUDIO_BGM_PACKET_SAMPLES 16384u
#define NDS_AUDIO_BGM_PACKET_BYTES 8196u
#define NDS_AUDIO_BGM_BUFFER_COUNT 2u
#define NDS_AUDIO_BGM_RESIDENT_BYTES \
    (NDS_AUDIO_BGM_BUFFER_COUNT * NDS_AUDIO_BGM_PACKET_BYTES)
#define NDS_AUDIO_BGM_BYTES_PER_SECOND (NDS_AUDIO_BGM_SAMPLE_RATE * 2u)
#define NDS_AUDIO_BGM_TRACK_FRAMES 3928u
#define NDS_AUDIO_BGM_RATE_GUARD_FRAMES 3200u
#define NDS_AUDIO_BGM_RESULTS_FAST_UPDATE_MAX 600u

void ndsAudioBgmDiagnosticsReset(void);
void ndsAudioBgmUpdate(void);
void ndsAudioBgmStopAll(void);
void ndsAudioBgmSuspendForBlockingLoad(void);
void ndsAudioBgmResumeAfterBlockingLoad(void);
void ndsAudioBgmPlay(s32 player, s32 bgm_id);
s32 ndsAudioBgmCheckPlaying(s32 player);
s32 ndsAudioBgmIsPlaying(void);
void ndsAudioBgmSetVolume(s32 player, u32 vol);

extern volatile u32 gNdsAudioBgmResult;
extern volatile u32 gNdsAudioBgmMask;
extern volatile u32 gNdsAudioBgmPlaying;
extern volatile u32 gNdsAudioBgmTrackID;
extern volatile u32 gNdsAudioBgmVolume;
extern volatile u32 gNdsAudioBgmPlayCalls;
extern volatile u32 gNdsAudioBgmStopCalls;
extern volatile u32 gNdsAudioBgmCheckCalls;
extern volatile u32 gNdsAudioBgmSetVolumeCalls;
extern volatile u32 gNdsAudioBgmOpenFailCount;
extern volatile u32 gNdsAudioBgmReadFailCount;
extern volatile u32 gNdsAudioBgmUnsupportedTrackCount;
extern volatile u32 gNdsAudioBgmReadBytes;
extern volatile u32 gNdsAudioBgmResidentBytes;
extern volatile u32 gNdsAudioBgmChunkBytes;
extern volatile u32 gNdsAudioBgmChunkPlayCount;
extern volatile u32 gNdsAudioBgmStoppedOnTeardown;
extern volatile u32 gNdsAudioBgmElapsedFrames;
extern volatile u32 gNdsAudioBgmStreamedBytes;
extern volatile u32 gNdsAudioBgmStreamBytesPerSecond;
extern volatile u32 gNdsAudioBgmExpectedBytesPerSecond;
extern volatile u32 gNdsAudioBgmLoopCount;
extern volatile u32 gNdsAudioBgmRefillCount;
#if NDS_RENDERER_PROFILE_LEVEL >= 1
extern volatile u32 gNdsAudioBgmRefillTicksLast;
extern volatile u32 gNdsAudioBgmRefillTicksMax;
#endif
extern volatile u32 gNdsAudioBgmFalsifierOff;
/* Slice 48 route. Scheduler priority of the refill worker; MAIN_THREAD_PRIO + 1
 * (below main, refills in the VBlank idle) ships, 27 restores the preempting
 * arm for a same-binary A/B. See nds_audio_bgm.c for why this is the tail. */
extern volatile u32 gNdsAudioBgmWorkerPrio;
extern volatile u32 gNdsAudioBgmWorkerRunPrio;
extern volatile u32 gNdsAudioBgmWorkerPrioApplied;
extern volatile u32 gNdsAudioBgmPlaybackPositionBytes;
extern volatile u32 gNdsAudioBgmWritePositionBytes;
extern volatile u32 gNdsAudioBgmPlaybackHalf;
extern volatile u32 gNdsAudioBgmWriteHalf;
extern volatile u32 gNdsAudioBgmUnsafeWriteCount;
extern volatile u32 gNdsAudioBgmTimerTicks;
extern volatile u32 gNdsAudioBgmPlaybackBytes;
extern volatile u32 gNdsAudioBgmPlaybackLoopCount;
extern volatile u32 gNdsAudioBgmOverrunCount;
extern volatile u32 gNdsAudioBgmStreamBytes;
extern volatile u32 gNdsAudioBgmLoopStartBytes;
extern volatile u32 gNdsAudioBgmIsLooping;
extern volatile u32 gNdsAudioBgmPupupuPlayCount;
extern volatile u32 gNdsAudioBgmWinMarioPlayCount;
extern volatile u32 gNdsAudioBgmWinFoxPlayCount;
extern volatile u32 gNdsAudioBgmResultsPlayCount;
extern volatile u32 gNdsAudioBgmModeSelectPlayCount;
extern volatile u32 gNdsAudioBgmBattleSelectPlayCount;
extern volatile u32 gNdsAudioBgmNaturalStopCount;
extern volatile u32 gNdsAudioBgmLastNaturalStopTrackID;
extern volatile u32 gNdsAudioBgmPostNaturalTransitionCount;
extern volatile u32 gNdsAudioBgmPostNaturalTransitionFromTrackID;
extern volatile u32 gNdsAudioBgmPostNaturalTransitionToTrackID;
extern volatile u32 gNdsAudioBgmTrackSwitchCount;
extern volatile u32 gNdsAudioBgmFinitePaddingBytes;
extern volatile u32 gNdsAudioBgmFileOpen;
extern volatile u32 gNdsAudioBgmSoundActive;
extern volatile u32 gNdsAudioBgmPlayFailCount;
extern volatile u32 gNdsAudioBgmHeaderFailCount;
extern volatile u32 gNdsAudioBgmPacketFailCount;
extern volatile u32 gNdsAudioBgmPreparedCount;
extern volatile u32 gNdsAudioBgmSeamStartCount;
extern volatile u32 gNdsAudioBgmSeamMissCount;
extern volatile u32 gNdsAudioBgmTimerEventDropCount;
extern volatile u32 gNdsAudioBgmWorkerWakeCount;
extern volatile u32 gNdsAudioBgmErrorStopCount;
extern volatile u32 gNdsAudioBgmBlockingSuspendCount;
extern volatile u32 gNdsAudioBgmBlockingResumeCount;
extern volatile u32 gNdsAudioBgmErrorCleanupFailCount;

#endif
