#ifndef SSB64_NDS_STARTUP_H
#define SSB64_NDS_STARTUP_H

#include <stddef.h>
#include <PR/ultratypes.h>

#define NDS_STARTUP_TASKMAN_PASS 0x53545254u
#define NDS_STARTUP_FUNC_START_PASS 0x46535452u
#define NDS_TASKMAN_BRIDGE_PASS 0x5441534bu
#define NDS_TASKMAN_CLEANUP_PASS 0x434c4e50u
#define NDS_STARTUP_LOGO_RELOC_PASS 0x4c524c43u
#define NDS_STARTUP_LOGO_DRAW_PASS 0x4c445257u

#define NDS_STARTUP_LOGO_BLOCKER_NONE 0u
#define NDS_STARTUP_LOGO_BLOCKER_NO_SOBJ 1u
#define NDS_STARTUP_LOGO_BLOCKER_UNSUPPORTED_FORMAT 2u
#define NDS_STARTUP_LOGO_BLOCKER_BAD_DIMENSIONS 3u
#define NDS_STARTUP_LOGO_BLOCKER_BAD_BITMAP_TABLE 4u
#define NDS_STARTUP_LOGO_BLOCKER_BAD_BITMAP_BUFFER 5u
#define NDS_STARTUP_LOGO_BLOCKER_NO_PREVIEW_BUFFER 6u
#define NDS_STARTUP_LOGO_BLOCKER_NO_VISIBLE_SOBJ 7u
#define NDS_OPENING_ROOM_START_PASS 0x4f525354u
#define NDS_OPENING_ROOM_FUNC_START_PASS 0x4f524653u
#define NDS_OPENING_ROOM_UPDATE_PASS 0x4f525550u
#define NDS_OPENING_ROOM_PRE_ASSET_PASS 0x4f525041u
#define NDS_OPENING_ROOM_RELOC_PASS 0x4f52524cu
#define NDS_OPENING_ROOM_RELOC_MOBJ_SOURCE_PASS 0x4f524d54u
#define NDS_OPENING_ROOM_FIRST_EVENT_PASS 0x4f524631u
#define NDS_OPENING_ROOM_FIRST_EVENT_DATA_PASS 0x4f524644u
#define NDS_OPENING_ROOM_FIRST_EVENT_RUN_PASS 0x4f523238u
#define NDS_OPENING_ROOM_FIGHTER_DEFER_PASS 0x4f524646u
#define NDS_OPENING_ROOM_TICK380_DEFER_PASS 0x4f523338u
#define NDS_OPENING_ROOM_TICK450_RUN_PASS 0x4f523435u
#define NDS_OPENING_ROOM_TICK500_RUN_PASS 0x4f523530u
#define NDS_OPENING_ROOM_TICK560_RUN_PASS 0x4f523536u
#define NDS_OPENING_ROOM_OVERLAY_CREATE_PASS 0x4f524f43u
#define NDS_OPENING_ROOM_OVERLAY_EJECT_PASS 0x4f524f45u
#define NDS_OPENING_ROOM_CLOSEUP_OVERLAY_CREATE_PASS 0x4f52434fu
#define NDS_OPENING_ROOM_SPOTLIGHT_CREATE_PASS 0x4f52534cu
#define NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_PASS 0x4f523143u
#define NDS_OPENING_ROOM_SCENE2_CAMERA_EJECT_PASS 0x4f523245u
#define NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_PASS 0x4f523243u
#define NDS_OPENING_ROOM_CLOSEUP_CAMERA_CREATE_PASS 0x4f524343u
#define NDS_OPENING_ROOM_WALLPAPER_CAMERA_CREATE_PASS 0x4f525743u
#define NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_PASS 0x4f52434du
#define NDS_OPENING_ROOM_LOGO_CREATE_PASS 0x4f524c43u
#define NDS_OPENING_ROOM_LOGO_EJECT_PASS 0x4f524c45u
#define NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_PASS 0x4f524243u
#define NDS_OPENING_ROOM_BOSS_SHADOW_EJECT_PASS 0x4f524245u
#define NDS_OPENING_ROOM_PENCILS_CREATE_PASS 0x4f525043u
#define NDS_OPENING_ROOM_OUTSIDE_CREATE_PASS 0x4f524f55u
#define NDS_OPENING_ROOM_HAZE_CREATE_PASS 0x4f52485au
#define NDS_OPENING_ROOM_SUNLIGHT_CREATE_PASS 0x4f525343u
#define NDS_OPENING_ROOM_DESK_CREATE_PASS 0x4f524453u
#define NDS_OPENING_ROOM_SUNLIGHT_EJECT_PASS 0x4f525345u
#define NDS_OPENING_ROOM_DRAW_PASS 0x4f524457u
#define NDS_OPENING_MOVIE_ROOM_HANDOFF_PASS 0x4f4d5248u
#define NDS_OPENING_PORTRAITS_START_PASS 0x4f505354u
#define NDS_OPENING_PORTRAITS_FUNC_START_PASS 0x4f504653u
#define NDS_OPENING_PORTRAITS_UPDATE_PASS 0x4f505550u
#define NDS_OPENING_PORTRAITS_RELOC_PASS 0x4f50524cu
#define NDS_OPENING_PORTRAITS_DRAW_PASS 0x4f504457u
#define NDS_OPENING_PORTRAITS_NEXT_SCENE_PASS 0x4f504e58u
#define NDS_OPENING_MARIO_START_PASS 0x4f4d5354u
#define NDS_OPENING_MARIO_FUNC_START_PASS 0x4f4d4653u
#define NDS_OPENING_MARIO_UPDATE_PASS 0x4f4d5550u
#define NDS_OPENING_MARIO_RELOC_PASS 0x4f4d524cu
#define NDS_OPENING_MARIO_DRAW_PASS 0x4f4d4457u
#define NDS_OPENING_MARIO_FIGHTER_DEFER_PASS 0x4f4d4644u
#define NDS_OPENING_MARIO_NEXT_SCENE_PASS 0x4f4d4e58u
#define NDS_OPENING_NAME_START_PASS 0x4f4e5354u
#define NDS_OPENING_NAME_FUNC_START_PASS 0x4f4e4653u
#define NDS_OPENING_NAME_UPDATE_PASS 0x4f4e5550u
#define NDS_OPENING_NAME_DRAW_PASS 0x4f4e4457u
#define NDS_OPENING_NAME_FIGHTER_DEFER_PASS 0x4f4e4644u
#define NDS_OPENING_NAME_NEXT_SCENE_PASS 0x4f4e4e58u
#define NDS_OPENING_MOVIE_BRIDGE_PASS 0x4f4d4252u
#define NDS_OPENING_MOVIE_ACTION_PREVIEW_PASS 0x4f4d4150u
#define NDS_OPENING_MOVIE_TITLE_PASS 0x4f4d5449u
#define NDS_TITLE_RELOC_PASS 0x5449524cu
#define NDS_TITLE_PREVIEW_PASS 0x54495056u
#define NDS_TITLE_DRAW_PASS 0x54494457u
#define NDS_TITLE_ORIGINAL_START_PASS 0x54495354u
#define NDS_TITLE_ORIGINAL_FUNC_START_PASS 0x54494653u
#define NDS_TITLE_ORIGINAL_LOAD_PASS 0x54494c44u
#define NDS_TITLE_ORIGINAL_ACTORS_PASS 0x54494143u
#define NDS_TITLE_ORIGINAL_CAMERAS_PASS 0x54494341u
#define NDS_TITLE_ORIGINAL_VARS_PASS 0x54495652u
#define NDS_TITLE_ORIGINAL_UPDATE_PASS 0x54495550u
#define NDS_TITLE_ORIGINAL_LOGO_FIRE_PASS 0x544c4643u
#define NDS_TITLE_ORIGINAL_FIRE_PASS 0x54464952u

#define NDS_OPENING_ROOM_DRAW_BLOCKER_NONE 0u
#define NDS_OPENING_ROOM_DRAW_BLOCKER_NO_SCENE_DRAW 1u
#define NDS_OPENING_ROOM_DRAW_BLOCKER_CAMERA_BACKEND 2u
#define NDS_OPENING_ROOM_DRAW_BLOCKER_DOBJ_DISPLAY_LIST 3u

#define NDS_OPENING_ROOM_DRAW_CALLBACK_FUNC_80017EC0 0x46313745u
#define NDS_OPENING_ROOM_DRAW_CALLBACK_DOBJ_TREE 0x44545245u
#define NDS_OPENING_ROOM_DRAW_CALLBACK_DOBJ_TREE_DLLINKS 0x44544c4bu
#define NDS_OPENING_ROOM_DRAW_CALLBACK_DOBJ_DLLINKS 0x444c4e4bu
#define NDS_OPENING_ROOM_DRAW_CALLBACK_DOBJ_DLHEAD1 0x444c4831u

#define NDS_OPENING_ROOM_DRAW_DOBJ_HAS_DL (1u << 0)
#define NDS_OPENING_ROOM_DRAW_DOBJ_HAS_CHILD (1u << 1)
#define NDS_OPENING_ROOM_DRAW_DOBJ_HAS_SIBLING (1u << 2)
#define NDS_OPENING_ROOM_DRAW_DOBJ_HAS_MOBJ (1u << 3)
#define NDS_OPENING_ROOM_DRAW_DOBJ_HAS_XOBJ (1u << 4)

#define NDS_OPENING_ROOM_DRAW_MATERIAL_CANDIDATE_PASS 0x4f524d43u
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_PASS 0x4f524d42u
#define NDS_OPENING_ROOM_DRAW_MATERIAL_EMIT_PASS 0x4f524d45u
#define NDS_OPENING_ROOM_DRAW_TEXTURE_MATERIAL_PASS 0x4f525458u

#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_SEGMENT (1u << 0)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_TABLE (1u << 1)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_PALETTE_IMAGE (1u << 2)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_PALETTE_TLUT (1u << 3)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_LIGHT (1u << 4)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_PRIMCOLOR (1u << 5)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_ENVCOLOR (1u << 6)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_BLENDCOLOR (1u << 7)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_NEXT_IMAGE (1u << 8)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_LOADBLOCK (1u << 9)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_CURRENT_IMAGE (1u << 10)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_TILESIZE (1u << 11)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_SCROLL_TILESIZE (1u << 12)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_TEXTURE (1u << 13)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_END (1u << 14)
#define NDS_OPENING_ROOM_DRAW_MATERIAL_BRANCH_ADJUSTED_ST (1u << 15)

#define NDS_OPENING_ROOM_DRAW_MATERIAL_EMIT_BLOCKER_NONE 0u
#define NDS_OPENING_ROOM_DRAW_MATERIAL_EMIT_BLOCKER_NO_MOBJ 1u
#define NDS_OPENING_ROOM_DRAW_MATERIAL_EMIT_BLOCKER_NO_HEAP 2u
#define NDS_OPENING_ROOM_DRAW_MATERIAL_EMIT_BLOCKER_HEAP_RANGE 3u
#define NDS_OPENING_ROOM_DRAW_MATERIAL_EMIT_BLOCKER_UNSUPPORTED_FAMILY 4u
#define NDS_OPENING_ROOM_DRAW_MATERIAL_EMIT_BLOCKER_NO_TEXTURE 5u
#define NDS_OPENING_ROOM_DRAW_MATERIAL_EMIT_BLOCKER_TOO_MANY_MOBJS 6u

#define NDS_OPENING_ROOM_DL_PREVIEW_PASS 0x4f524450u
#define NDS_OPENING_ROOM_MATERIAL_DL_PROBE_PASS 0x4f524d44u
#define NDS_OPENING_ROOM_MATERIAL_DL_EXPAND_PASS 0x4f524d58u
#define NDS_OPENING_ROOM_DL_PREVIEW_MATERIAL_BRANCH_PASS 0x4f524d50u

#define NDS_OPENING_ROOM_DL_PREVIEW_BLOCKER_NONE 0u
#define NDS_OPENING_ROOM_DL_PREVIEW_BLOCKER_NO_DL_LINK 1u
#define NDS_OPENING_ROOM_DL_PREVIEW_BLOCKER_NO_VERTEX_LOAD 2u
#define NDS_OPENING_ROOM_DL_PREVIEW_BLOCKER_NO_TRIANGLES 3u
#define NDS_OPENING_ROOM_DL_PREVIEW_BLOCKER_NO_PIXELS 4u
#define NDS_OPENING_ROOM_DL_PREVIEW_BLOCKER_UNSUPPORTED_CMD 5u

#define NDS_OPENING_ROOM_MATERIAL_DL_PROBE_BLOCKER_NONE 0u
#define NDS_OPENING_ROOM_MATERIAL_DL_PROBE_BLOCKER_NO_CANDIDATE 1u
#define NDS_OPENING_ROOM_MATERIAL_DL_PROBE_BLOCKER_NO_DL 2u
#define NDS_OPENING_ROOM_MATERIAL_DL_PROBE_BLOCKER_UNSUPPORTED 3u
#define NDS_OPENING_ROOM_MATERIAL_DL_PROBE_BLOCKER_NO_VERTICES 4u
#define NDS_OPENING_ROOM_MATERIAL_DL_PROBE_BLOCKER_NO_TRIANGLES 5u
#define NDS_OPENING_ROOM_MATERIAL_DL_PROBE_BLOCKER_NO_END 6u

#define NDS_OPENING_ROOM_MATERIAL_DL_EXPAND_BLOCKER_NONE 0u
#define NDS_OPENING_ROOM_MATERIAL_DL_EXPAND_BLOCKER_NO_CANDIDATE 1u
#define NDS_OPENING_ROOM_MATERIAL_DL_EXPAND_BLOCKER_NO_DL 2u
#define NDS_OPENING_ROOM_MATERIAL_DL_EXPAND_BLOCKER_BAD_BRANCH 3u
#define NDS_OPENING_ROOM_MATERIAL_DL_EXPAND_BLOCKER_TOO_DEEP 4u
#define NDS_OPENING_ROOM_MATERIAL_DL_EXPAND_BLOCKER_BUDGET 5u
#define NDS_OPENING_ROOM_MATERIAL_DL_EXPAND_BLOCKER_UNSUPPORTED 6u
#define NDS_OPENING_ROOM_MATERIAL_DL_EXPAND_BLOCKER_NO_VERTICES 7u
#define NDS_OPENING_ROOM_MATERIAL_DL_EXPAND_BLOCKER_NO_TRIANGLES 8u
#define NDS_OPENING_ROOM_MATERIAL_DL_EXPAND_BLOCKER_NO_END 9u

#define NDS_OPENING_ROOM_DL_PREVIEW_MATERIAL_BRANCH_BLOCKER_NONE 0u
#define NDS_OPENING_ROOM_DL_PREVIEW_MATERIAL_BRANCH_BLOCKER_NO_EMIT 1u
#define NDS_OPENING_ROOM_DL_PREVIEW_MATERIAL_BRANCH_BLOCKER_NO_BRANCH 2u
#define NDS_OPENING_ROOM_DL_PREVIEW_MATERIAL_BRANCH_BLOCKER_NO_PRIM 3u
#define NDS_OPENING_ROOM_DL_PREVIEW_MATERIAL_BRANCH_BLOCKER_NO_END 4u
#define NDS_OPENING_ROOM_DL_PREVIEW_MATERIAL_BRANCH_BLOCKER_UNSUPPORTED 5u

#define NDS_OPENING_ROOM_DL_PREVIEW_TRANSFORM_DOBJ (1u << 0)
#define NDS_OPENING_ROOM_DL_PREVIEW_TRANSFORM_TRANSLATE (1u << 1)
#define NDS_OPENING_ROOM_DL_PREVIEW_TRANSFORM_SCALE (1u << 2)
#define NDS_OPENING_ROOM_DL_PREVIEW_TRANSFORM_XOBJ (1u << 3)
#define NDS_OPENING_ROOM_DL_PREVIEW_TRANSFORM_ROTATE (1u << 4)
#define NDS_OPENING_ROOM_DL_PREVIEW_TRANSFORM_READY_MASK \
    (NDS_OPENING_ROOM_DL_PREVIEW_TRANSFORM_DOBJ | \
     NDS_OPENING_ROOM_DL_PREVIEW_TRANSFORM_TRANSLATE | \
     NDS_OPENING_ROOM_DL_PREVIEW_TRANSFORM_SCALE | \
     NDS_OPENING_ROOM_DL_PREVIEW_TRANSFORM_XOBJ | \
     NDS_OPENING_ROOM_DL_PREVIEW_TRANSFORM_ROTATE)

#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_CAMERA (1u << 0)
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_VIEWPORT (1u << 1)
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_PERSP (1u << 2)
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_LOOKAT (1u << 3)
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_VERTICES (1u << 4)
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_TRIANGLES (1u << 5)
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_DRAWN (1u << 6)
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_READY_MASK \
    (NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_CAMERA | \
     NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_VIEWPORT | \
     NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_PERSP | \
     NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_LOOKAT | \
     NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_VERTICES | \
     NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_TRIANGLES | \
     NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_DRAWN)

#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_MODE_NONE 0u
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_MODE_CAMERA 1u
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_MODE_FALLBACK 2u

#define NDS_OPENING_ROOM_DL_PREVIEW_FALLBACK_AXIS_XY 0u
#define NDS_OPENING_ROOM_DL_PREVIEW_FALLBACK_AXIS_XZ 1u
#define NDS_OPENING_ROOM_DL_PREVIEW_FALLBACK_AXIS_YZ 2u

#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_BLOCKER_NONE 0u
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_BLOCKER_NO_CAMERA 1u
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_BLOCKER_BAD_VIEWPORT 2u
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_BLOCKER_BAD_PERSP 3u
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_BLOCKER_BAD_LOOKAT 4u
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_BLOCKER_NO_VERTICES 5u
#define NDS_OPENING_ROOM_DL_PREVIEW_PROJECTION_BLOCKER_NO_TRIANGLES 6u

#define NDS_OPENING_ROOM_DL_GEOMETRY_SEEN (1u << 0)
#define NDS_OPENING_ROOM_DL_GEOMETRY_ZBUFFER (1u << 1)
#define NDS_OPENING_ROOM_DL_GEOMETRY_SHADE (1u << 2)
#define NDS_OPENING_ROOM_DL_GEOMETRY_CULL_FRONT (1u << 3)
#define NDS_OPENING_ROOM_DL_GEOMETRY_CULL_BACK (1u << 4)
#define NDS_OPENING_ROOM_DL_GEOMETRY_LIGHTING (1u << 5)
#define NDS_OPENING_ROOM_DL_GEOMETRY_SHADING_SMOOTH (1u << 6)

#define NDS_OPENING_ROOM_DL_TEXTURE_SETCOMBINE (1u << 0)
#define NDS_OPENING_ROOM_DL_TEXTURE_SETTILE (1u << 1)
#define NDS_OPENING_ROOM_DL_TEXTURE_TEXTURE (1u << 2)
#define NDS_OPENING_ROOM_DL_TEXTURE_SETTILESIZE (1u << 3)
#define NDS_OPENING_ROOM_DL_TEXTURE_SETTIMG (1u << 4)
#define NDS_OPENING_ROOM_DL_TEXTURE_LOADBLOCK (1u << 5)
#define NDS_OPENING_ROOM_DL_TEXTURE_READY_MASK \
    (NDS_OPENING_ROOM_DL_TEXTURE_SETCOMBINE | \
     NDS_OPENING_ROOM_DL_TEXTURE_SETTILE | \
     NDS_OPENING_ROOM_DL_TEXTURE_TEXTURE | \
     NDS_OPENING_ROOM_DL_TEXTURE_SETTILESIZE | \
     NDS_OPENING_ROOM_DL_TEXTURE_SETTIMG | \
     NDS_OPENING_ROOM_DL_TEXTURE_LOADBLOCK)

#define NDS_OPENING_ROOM_DL_TILE_RENDER_SEEN (1u << 0)
#define NDS_OPENING_ROOM_DL_TILE_LOAD_SEEN (1u << 1)
#define NDS_OPENING_ROOM_DL_TILE_S_CLAMP (1u << 2)
#define NDS_OPENING_ROOM_DL_TILE_S_MIRROR (1u << 3)
#define NDS_OPENING_ROOM_DL_TILE_S_MASKED (1u << 4)
#define NDS_OPENING_ROOM_DL_TILE_T_CLAMP (1u << 5)
#define NDS_OPENING_ROOM_DL_TILE_T_MIRROR (1u << 6)
#define NDS_OPENING_ROOM_DL_TILE_T_MASKED (1u << 7)

#define NDS_OPENING_ROOM_DL_TEXTURE_STATE_SEEN (1u << 0)
#define NDS_OPENING_ROOM_DL_TEXTURE_STATE_ON (1u << 1)
#define NDS_OPENING_ROOM_DL_TEXTURE_STATE_SCALE_S (1u << 2)
#define NDS_OPENING_ROOM_DL_TEXTURE_STATE_SCALE_T (1u << 3)

#define NDS_OPENING_ROOM_DL_TEXTURE_SAMPLE_NONE 0u
#define NDS_OPENING_ROOM_DL_TEXTURE_SAMPLE_RGBA16 1u
#define NDS_OPENING_ROOM_DL_TEXTURE_SAMPLE_I16 2u

#define NDS_OPENING_ROOM_DL_COMBINE_MODE_UNKNOWN 0u
#define NDS_OPENING_ROOM_DL_COMBINE_MODE_MODULATERGBDECALA 1u

#define NDS_OPENING_ROOM_DL_COMBINE_SEEN (1u << 0)
#define NDS_OPENING_ROOM_DL_COMBINE_RGB_TEXEL0 (1u << 1)
#define NDS_OPENING_ROOM_DL_COMBINE_RGB_SHADE (1u << 2)
#define NDS_OPENING_ROOM_DL_COMBINE_RGB_MODULATE (1u << 3)
#define NDS_OPENING_ROOM_DL_COMBINE_ALPHA_TEXEL0 (1u << 4)
#define NDS_OPENING_ROOM_DL_COMBINE_EXACT_MODULATERGBDECALA (1u << 5)

#define NDS_OPENING_ROOM_DL_MATERIAL_DOBJ_SEEN (1u << 0)
#define NDS_OPENING_ROOM_DL_MATERIAL_HAS_MOBJ (1u << 1)
#define NDS_OPENING_ROOM_DL_MATERIAL_DEFAULT_FLAGS (1u << 2)
#define NDS_OPENING_ROOM_DL_MATERIAL_TEXTURE (1u << 3)
#define NDS_OPENING_ROOM_DL_MATERIAL_ALPHA (1u << 4)
#define NDS_OPENING_ROOM_DL_MATERIAL_TILESIZE (1u << 5)
#define NDS_OPENING_ROOM_DL_MATERIAL_SCROLL_TILESIZE (1u << 6)
#define NDS_OPENING_ROOM_DL_MATERIAL_PALETTE (1u << 7)
#define NDS_OPENING_ROOM_DL_MATERIAL_FRAC (1u << 8)
#define NDS_OPENING_ROOM_DL_MATERIAL_SPLIT (1u << 9)
#define NDS_OPENING_ROOM_DL_MATERIAL_COLOR (1u << 10)
#define NDS_OPENING_ROOM_DL_MATERIAL_LIGHT (1u << 11)
#define NDS_OPENING_ROOM_DL_MATERIAL_HAS_SPRITE_ARRAY (1u << 12)
#define NDS_OPENING_ROOM_DL_MATERIAL_HAS_CURR_SPRITE (1u << 13)
#define NDS_OPENING_ROOM_DL_MATERIAL_HAS_NEXT_SPRITE (1u << 14)
#define NDS_OPENING_ROOM_DL_MATERIAL_HAS_PALETTE_ARRAY (1u << 15)
#define NDS_OPENING_ROOM_DL_MATERIAL_HAS_PALETTE_PTR (1u << 16)

#define NDS_OPENING_ROOM_OVERLAY_EJECT_COMMON_UNLINKED (1u << 0)
#define NDS_OPENING_ROOM_OVERLAY_EJECT_DL_UNLINKED (1u << 1)
#define NDS_OPENING_ROOM_OVERLAY_EJECT_UNLINKED_MASK \
    (NDS_OPENING_ROOM_OVERLAY_EJECT_COMMON_UNLINKED | \
     NDS_OPENING_ROOM_OVERLAY_EJECT_DL_UNLINKED)

#define NDS_OPENING_ROOM_TICK280_DEFER_FIGHTER (1u << 0)
#define NDS_OPENING_ROOM_TICK280_DEFER_LOGO_EJECT (1u << 1)
#define NDS_OPENING_ROOM_TICK280_DEFER_OVERLAY_EJECT (1u << 2)
#define NDS_OPENING_ROOM_TICK280_DEFER_BOSS_SHADOW_EJECT (1u << 3)
#define NDS_OPENING_ROOM_TICK280_DEFER_MASK \
    (NDS_OPENING_ROOM_TICK280_DEFER_FIGHTER)

#define NDS_OPENING_ROOM_TICK380_DEFER_FIGHTER_STATUS (1u << 0)
#define NDS_OPENING_ROOM_TICK380_DEFER_MASK \
    (NDS_OPENING_ROOM_TICK380_DEFER_FIGHTER_STATUS)

#define NDS_OPENING_ROOM_TICK450_DEFER_MASK 0u

#define NDS_OPENING_ROOM_OUTSIDE_ASSET_DISPLAY_READY (1u << 0)
#define NDS_OPENING_ROOM_OUTSIDE_ASSET_READY_MASK \
    (NDS_OPENING_ROOM_OUTSIDE_ASSET_DISPLAY_READY)

#define NDS_OPENING_ROOM_OUTSIDE_CREATE_GOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_OUTSIDE_CREATE_DOBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_OUTSIDE_CREATE_XOBJ_READY (1u << 2)
#define NDS_OPENING_ROOM_OUTSIDE_CREATE_DISPLAY_READY (1u << 3)
#define NDS_OPENING_ROOM_OUTSIDE_CREATE_READY_MASK \
    (NDS_OPENING_ROOM_OUTSIDE_CREATE_GOBJ_READY | \
     NDS_OPENING_ROOM_OUTSIDE_CREATE_DOBJ_READY | \
     NDS_OPENING_ROOM_OUTSIDE_CREATE_XOBJ_READY | \
     NDS_OPENING_ROOM_OUTSIDE_CREATE_DISPLAY_READY)

#define NDS_OPENING_ROOM_HAZE_ASSET_DISPLAY_READY (1u << 0)
#define NDS_OPENING_ROOM_HAZE_ASSET_READY_MASK \
    (NDS_OPENING_ROOM_HAZE_ASSET_DISPLAY_READY)

#define NDS_OPENING_ROOM_HAZE_CREATE_GOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_HAZE_CREATE_DOBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_HAZE_CREATE_XOBJ_READY (1u << 2)
#define NDS_OPENING_ROOM_HAZE_CREATE_DISPLAY_READY (1u << 3)
#define NDS_OPENING_ROOM_HAZE_CREATE_READY_MASK \
    (NDS_OPENING_ROOM_HAZE_CREATE_GOBJ_READY | \
     NDS_OPENING_ROOM_HAZE_CREATE_DOBJ_READY | \
     NDS_OPENING_ROOM_HAZE_CREATE_XOBJ_READY | \
     NDS_OPENING_ROOM_HAZE_CREATE_DISPLAY_READY)

#define NDS_OPENING_ROOM_SUNLIGHT_ASSET_DISPLAY_READY (1u << 0)
#define NDS_OPENING_ROOM_SUNLIGHT_ASSET_READY_MASK \
    (NDS_OPENING_ROOM_SUNLIGHT_ASSET_DISPLAY_READY)

#define NDS_OPENING_ROOM_SUNLIGHT_CREATE_GOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_SUNLIGHT_CREATE_DOBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_SUNLIGHT_CREATE_XOBJ_READY (1u << 2)
#define NDS_OPENING_ROOM_SUNLIGHT_CREATE_DISPLAY_READY (1u << 3)
#define NDS_OPENING_ROOM_SUNLIGHT_CREATE_READY_MASK \
    (NDS_OPENING_ROOM_SUNLIGHT_CREATE_GOBJ_READY | \
     NDS_OPENING_ROOM_SUNLIGHT_CREATE_DOBJ_READY | \
     NDS_OPENING_ROOM_SUNLIGHT_CREATE_XOBJ_READY | \
     NDS_OPENING_ROOM_SUNLIGHT_CREATE_DISPLAY_READY)

#define NDS_OPENING_ROOM_DESK_ASSET_DOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_DESK_ASSET_READY_MASK \
    (NDS_OPENING_ROOM_DESK_ASSET_DOBJ_READY)

#define NDS_OPENING_ROOM_DESK_CREATE_GOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_DESK_CREATE_DOBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_DESK_CREATE_XOBJ_READY (1u << 2)
#define NDS_OPENING_ROOM_DESK_CREATE_DISPLAY_READY (1u << 3)
#define NDS_OPENING_ROOM_DESK_CREATE_READY_MASK \
    (NDS_OPENING_ROOM_DESK_CREATE_GOBJ_READY | \
     NDS_OPENING_ROOM_DESK_CREATE_DOBJ_READY | \
     NDS_OPENING_ROOM_DESK_CREATE_XOBJ_READY | \
     NDS_OPENING_ROOM_DESK_CREATE_DISPLAY_READY)

#define NDS_OPENING_ROOM_SUNLIGHT_EJECT_COMMON_UNLINKED (1u << 0)
#define NDS_OPENING_ROOM_SUNLIGHT_EJECT_DL_UNLINKED (1u << 1)
#define NDS_OPENING_ROOM_SUNLIGHT_EJECT_UNLINKED_MASK \
    (NDS_OPENING_ROOM_SUNLIGHT_EJECT_COMMON_UNLINKED | \
     NDS_OPENING_ROOM_SUNLIGHT_EJECT_DL_UNLINKED)

#define NDS_OPENING_ROOM_TICK500_DEFER_PULLED_FIGHTER_DL (1u << 0)
#define NDS_OPENING_ROOM_TICK500_DEFER_MASK \
    (NDS_OPENING_ROOM_TICK500_DEFER_PULLED_FIGHTER_DL)

#define NDS_OPENING_ROOM_TICK560_DEFER_BOSS_STATUS (1u << 0)
#define NDS_OPENING_ROOM_TICK560_DEFER_MASK \
    (NDS_OPENING_ROOM_TICK560_DEFER_BOSS_STATUS)

#define NDS_OPENING_ROOM_CLOSEUP_OVERLAY_CREATE_GOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_CLOSEUP_OVERLAY_CREATE_DISPLAY_READY (1u << 1)
#define NDS_OPENING_ROOM_CLOSEUP_OVERLAY_CREATE_ALPHA_READY (1u << 2)
#define NDS_OPENING_ROOM_CLOSEUP_OVERLAY_CREATE_READY_MASK \
    (NDS_OPENING_ROOM_CLOSEUP_OVERLAY_CREATE_GOBJ_READY | \
     NDS_OPENING_ROOM_CLOSEUP_OVERLAY_CREATE_DISPLAY_READY | \
     NDS_OPENING_ROOM_CLOSEUP_OVERLAY_CREATE_ALPHA_READY)

#define NDS_OPENING_ROOM_SPOTLIGHT_ASSET_DISPLAY_READY (1u << 0)
#define NDS_OPENING_ROOM_SPOTLIGHT_ASSET_MOBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_SPOTLIGHT_ASSET_MATANIM_READY (1u << 2)
#define NDS_OPENING_ROOM_SPOTLIGHT_ASSET_READY_MASK \
    (NDS_OPENING_ROOM_SPOTLIGHT_ASSET_DISPLAY_READY | \
     NDS_OPENING_ROOM_SPOTLIGHT_ASSET_MOBJ_READY | \
     NDS_OPENING_ROOM_SPOTLIGHT_ASSET_MATANIM_READY)

#define NDS_OPENING_ROOM_SPOTLIGHT_CREATE_GOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_SPOTLIGHT_CREATE_DOBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_SPOTLIGHT_CREATE_XOBJ_READY (1u << 2)
#define NDS_OPENING_ROOM_SPOTLIGHT_CREATE_MOBJ_READY (1u << 3)
#define NDS_OPENING_ROOM_SPOTLIGHT_CREATE_DISPLAY_READY (1u << 4)
#define NDS_OPENING_ROOM_SPOTLIGHT_CREATE_PROCESS_READY (1u << 5)
#define NDS_OPENING_ROOM_SPOTLIGHT_CREATE_MATANIM_READY (1u << 6)
#define NDS_OPENING_ROOM_SPOTLIGHT_CREATE_POSITION_READY (1u << 7)
#define NDS_OPENING_ROOM_SPOTLIGHT_CREATE_READY_MASK \
    (NDS_OPENING_ROOM_SPOTLIGHT_CREATE_GOBJ_READY | \
     NDS_OPENING_ROOM_SPOTLIGHT_CREATE_DOBJ_READY | \
     NDS_OPENING_ROOM_SPOTLIGHT_CREATE_XOBJ_READY | \
     NDS_OPENING_ROOM_SPOTLIGHT_CREATE_MOBJ_READY | \
     NDS_OPENING_ROOM_SPOTLIGHT_CREATE_DISPLAY_READY | \
     NDS_OPENING_ROOM_SPOTLIGHT_CREATE_PROCESS_READY | \
     NDS_OPENING_ROOM_SPOTLIGHT_CREATE_MATANIM_READY | \
     NDS_OPENING_ROOM_SPOTLIGHT_CREATE_POSITION_READY)

#define NDS_OPENING_ROOM_LOGO_CAMERA_ASSET_CAMANIM_READY (1u << 0)
#define NDS_OPENING_ROOM_LOGO_CAMERA_ASSET_READY_MASK \
    (NDS_OPENING_ROOM_LOGO_CAMERA_ASSET_CAMANIM_READY)

#define NDS_OPENING_ROOM_SCENE2_CAMERA_ASSET_CAMANIM_READY (1u << 0)
#define NDS_OPENING_ROOM_SCENE2_CAMERA_ASSET_READY_MASK \
    (NDS_OPENING_ROOM_SCENE2_CAMERA_ASSET_CAMANIM_READY)

#define NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_MAIN_GOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_FIGHTER_GOBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_COBJ_READY (1u << 2)
#define NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_XOBJ_READY (1u << 3)
#define NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_DISPLAY_READY (1u << 4)
#define NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_PROCESS_READY (1u << 5)
#define NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_CAMANIM_READY (1u << 6)
#define NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_VIEWPORT_READY (1u << 7)
#define NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_DLBUFFER_READY (1u << 8)
#define NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_READY_MASK \
    (NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_MAIN_GOBJ_READY | \
     NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_FIGHTER_GOBJ_READY | \
     NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_COBJ_READY | \
     NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_XOBJ_READY | \
     NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_DISPLAY_READY | \
     NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_PROCESS_READY | \
     NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_CAMANIM_READY | \
     NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_VIEWPORT_READY | \
     NDS_OPENING_ROOM_SCENE1_CAMERA_CREATE_DLBUFFER_READY)

#define NDS_OPENING_ROOM_SCENE2_CAMERA_EJECT_MAIN_UNLINKED (1u << 0)
#define NDS_OPENING_ROOM_SCENE2_CAMERA_EJECT_FIGHTER_UNLINKED (1u << 1)
#define NDS_OPENING_ROOM_SCENE2_CAMERA_EJECT_COBJ_FREED (1u << 2)
#define NDS_OPENING_ROOM_SCENE2_CAMERA_EJECT_READY_MASK \
    (NDS_OPENING_ROOM_SCENE2_CAMERA_EJECT_MAIN_UNLINKED | \
     NDS_OPENING_ROOM_SCENE2_CAMERA_EJECT_FIGHTER_UNLINKED | \
     NDS_OPENING_ROOM_SCENE2_CAMERA_EJECT_COBJ_FREED)

#define NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_MAIN_GOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_FIGHTER_GOBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_COBJ_READY (1u << 2)
#define NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_XOBJ_READY (1u << 3)
#define NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_DISPLAY_READY (1u << 4)
#define NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_PROCESS_READY (1u << 5)
#define NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_CAMANIM_READY (1u << 6)
#define NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_VIEWPORT_READY (1u << 7)
#define NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_DLBUFFER_READY (1u << 8)
#define NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_READY_MASK \
    (NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_MAIN_GOBJ_READY | \
     NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_FIGHTER_GOBJ_READY | \
     NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_COBJ_READY | \
     NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_XOBJ_READY | \
     NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_DISPLAY_READY | \
     NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_PROCESS_READY | \
     NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_CAMANIM_READY | \
     NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_VIEWPORT_READY | \
     NDS_OPENING_ROOM_SCENE2_CAMERA_CREATE_DLBUFFER_READY)

#define NDS_OPENING_ROOM_CLOSEUP_CAMERA_CREATE_GOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_CLOSEUP_CAMERA_CREATE_COBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_CLOSEUP_CAMERA_CREATE_XOBJ_READY (1u << 2)
#define NDS_OPENING_ROOM_CLOSEUP_CAMERA_CREATE_DISPLAY_READY (1u << 3)
#define NDS_OPENING_ROOM_CLOSEUP_CAMERA_CREATE_VIEWPORT_READY (1u << 4)
#define NDS_OPENING_ROOM_CLOSEUP_CAMERA_CREATE_READY_MASK \
    (NDS_OPENING_ROOM_CLOSEUP_CAMERA_CREATE_GOBJ_READY | \
     NDS_OPENING_ROOM_CLOSEUP_CAMERA_CREATE_COBJ_READY | \
     NDS_OPENING_ROOM_CLOSEUP_CAMERA_CREATE_XOBJ_READY | \
     NDS_OPENING_ROOM_CLOSEUP_CAMERA_CREATE_DISPLAY_READY | \
     NDS_OPENING_ROOM_CLOSEUP_CAMERA_CREATE_VIEWPORT_READY)

#define NDS_OPENING_ROOM_WALLPAPER_CAMERA_CREATE_GOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_WALLPAPER_CAMERA_CREATE_COBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_WALLPAPER_CAMERA_CREATE_XOBJ_READY (1u << 2)
#define NDS_OPENING_ROOM_WALLPAPER_CAMERA_CREATE_DISPLAY_READY (1u << 3)
#define NDS_OPENING_ROOM_WALLPAPER_CAMERA_CREATE_VIEWPORT_READY (1u << 4)
#define NDS_OPENING_ROOM_WALLPAPER_CAMERA_CREATE_READY_MASK \
    (NDS_OPENING_ROOM_WALLPAPER_CAMERA_CREATE_GOBJ_READY | \
     NDS_OPENING_ROOM_WALLPAPER_CAMERA_CREATE_COBJ_READY | \
     NDS_OPENING_ROOM_WALLPAPER_CAMERA_CREATE_XOBJ_READY | \
     NDS_OPENING_ROOM_WALLPAPER_CAMERA_CREATE_DISPLAY_READY | \
     NDS_OPENING_ROOM_WALLPAPER_CAMERA_CREATE_VIEWPORT_READY)

#define NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_GOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_COBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_XOBJ_READY (1u << 2)
#define NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_DISPLAY_READY (1u << 3)
#define NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_PROCESS_READY (1u << 4)
#define NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_CAMANIM_READY (1u << 5)
#define NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_VIEWPORT_READY (1u << 6)
#define NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_READY_MASK \
    (NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_GOBJ_READY | \
     NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_COBJ_READY | \
     NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_XOBJ_READY | \
     NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_DISPLAY_READY | \
     NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_PROCESS_READY | \
     NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_CAMANIM_READY | \
     NDS_OPENING_ROOM_LOGO_CAMERA_CREATE_VIEWPORT_READY)

#define NDS_OPENING_ROOM_LOGO_ASSET_DOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_LOGO_ASSET_MOBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_LOGO_ASSET_MATANIM_READY (1u << 2)
#define NDS_OPENING_ROOM_LOGO_ASSET_READY_MASK \
    (NDS_OPENING_ROOM_LOGO_ASSET_DOBJ_READY | \
     NDS_OPENING_ROOM_LOGO_ASSET_MOBJ_READY | \
     NDS_OPENING_ROOM_LOGO_ASSET_MATANIM_READY)

#define NDS_OPENING_ROOM_LOGO_CREATE_GOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_LOGO_CREATE_DOBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_LOGO_CREATE_XOBJ_READY (1u << 2)
#define NDS_OPENING_ROOM_LOGO_CREATE_MOBJ_READY (1u << 3)
#define NDS_OPENING_ROOM_LOGO_CREATE_DISPLAY_READY (1u << 4)
#define NDS_OPENING_ROOM_LOGO_CREATE_MATANIM_READY (1u << 5)
#define NDS_OPENING_ROOM_LOGO_CREATE_READY_MASK \
    (NDS_OPENING_ROOM_LOGO_CREATE_GOBJ_READY | \
     NDS_OPENING_ROOM_LOGO_CREATE_DOBJ_READY | \
     NDS_OPENING_ROOM_LOGO_CREATE_XOBJ_READY | \
     NDS_OPENING_ROOM_LOGO_CREATE_MOBJ_READY | \
     NDS_OPENING_ROOM_LOGO_CREATE_DISPLAY_READY | \
     NDS_OPENING_ROOM_LOGO_CREATE_MATANIM_READY)

#define NDS_OPENING_ROOM_BOSS_SHADOW_ASSET_DISPLAY_READY (1u << 0)
#define NDS_OPENING_ROOM_BOSS_SHADOW_ASSET_ANIM_READY (1u << 1)
#define NDS_OPENING_ROOM_BOSS_SHADOW_ASSET_READY_MASK \
    (NDS_OPENING_ROOM_BOSS_SHADOW_ASSET_DISPLAY_READY | \
     NDS_OPENING_ROOM_BOSS_SHADOW_ASSET_ANIM_READY)

#define NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_GOBJ_READY (1u << 0)
#define NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_DOBJ_READY (1u << 1)
#define NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_XOBJ_READY (1u << 2)
#define NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_PROCESS_READY (1u << 3)
#define NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_DISPLAY_READY (1u << 4)
#define NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_ANIM_READY (1u << 5)
#define NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_READY_MASK \
    (NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_GOBJ_READY | \
     NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_DOBJ_READY | \
     NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_XOBJ_READY | \
     NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_PROCESS_READY | \
     NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_DISPLAY_READY | \
     NDS_OPENING_ROOM_BOSS_SHADOW_CREATE_ANIM_READY)

void ndsResetStartupDiagnostics(void);
void *ndsTaskmanArenaStart(void);
size_t ndsTaskmanArenaSize(void);
void ndsOpeningRoomCapturePencilsCountsBefore(void);
void ndsOpeningRoomCapturePencilsCreation(void);
void ndsOpeningRoomRecordOverlayEject(void *gobj);
void ndsOpeningRoomCaptureCloseUpOverlayCountsBefore(void);
void ndsOpeningRoomCaptureCloseUpOverlayCreation(void *gobj);
void ndsOpeningRoomCaptureScene1CameraCountsBefore(void);
void ndsOpeningRoomCaptureScene1CameraCreation(void);
void ndsOpeningRoomCaptureScene2CameraEjectBefore(void);
void ndsOpeningRoomRecordScene2CameraEject(void);
void ndsOpeningRoomCaptureScene2CameraCountsBefore(void);
void ndsOpeningRoomCaptureScene2CameraCreation(void);
void ndsOpeningRoomCaptureCloseUpOverlayCameraCountsBefore(void);
void ndsOpeningRoomCaptureCloseUpOverlayCameraCreation(void *gobj);
void ndsOpeningRoomCaptureWallpaperCameraCountsBefore(void);
void ndsOpeningRoomCaptureWallpaperCameraCreation(void *gobj);
void ndsOpeningRoomCaptureLogoCameraCountsBefore(void);
void ndsOpeningRoomCaptureLogoCameraCreation(void *gobj);
void ndsOpeningRoomCaptureLogoCountsBefore(void);
void ndsOpeningRoomCaptureLogoCreation(void *gobj);
void ndsOpeningRoomRecordLogoEject(void *gobj);
void ndsOpeningRoomCaptureBossShadowCountsBefore(void);
void ndsOpeningRoomCaptureBossShadowCreation(void *gobj);
void ndsOpeningRoomRecordBossShadowEject(void *gobj);
void ndsOpeningRoomCaptureOutsideCountsBefore(void);
void ndsOpeningRoomCaptureOutsideCreation(void *gobj);
void ndsOpeningRoomCaptureHazeCountsBefore(void);
void ndsOpeningRoomCaptureHazeCreation(void *gobj);
void ndsOpeningRoomCaptureSunlightCountsBefore(void);
void ndsOpeningRoomCaptureSunlightCreation(void *gobj);
void ndsOpeningRoomCaptureDeskCountsBefore(void);
void ndsOpeningRoomCaptureDeskCreation(void *gobj);
void ndsOpeningRoomRecordSunlightEject(void *gobj);
void ndsOpeningRoomCaptureSpotlightCountsBefore(void);
void ndsOpeningRoomCaptureSpotlightCreation(void *gobj);

extern volatile u32 gNdsStartupTaskmanResult;
extern volatile u32 gNdsStartupTaskmanSceneKind;
extern volatile u32 gNdsStartupTaskmanDL0Size;
extern volatile u32 gNdsStartupTaskmanDL1Size;
extern volatile u32 gNdsStartupTaskmanControllerSet;
extern volatile u32 gNdsStartupFuncStartResult;
extern volatile u32 gNdsStartupSkipAllowWait;
extern volatile u32 gNdsStartupProceedOpening;
extern volatile u32 gNdsStartupGObjCreateCount;
extern volatile u32 gNdsStartupCameraCreateCount;
extern volatile u32 gNdsStartupRelocInitCount;
extern volatile u32 gNdsStartupSpriteCreateCount;
extern volatile u32 gNdsStartupFadeCreateCount;
extern volatile u32 gNdsStartupWallpaperParentValid;
extern volatile u32 gNdsStartupLogoPosX;
extern volatile u32 gNdsStartupLogoPosY;
extern volatile u32 gNdsStartupLogoFastcopyCleared;
extern volatile u32 gNdsStartupLogoRelocResult;
extern volatile u32 gNdsStartupLogoRelocSize;
extern volatile u32 gNdsStartupLogoRelocWordSwapCount;
extern volatile u32 gNdsStartupLogoRelocPointerFixupCount;
extern volatile u32 gNdsStartupLogoDrawResult;
extern volatile u32 gNdsStartupLogoDrawBlocker;
extern volatile u32 gNdsStartupLogoDrawCallbackCount;
extern volatile u32 gNdsStartupLogoDrawUpdateCount;
extern volatile u32 gNdsStartupLogoDrawWidth;
extern volatile u32 gNdsStartupLogoDrawHeight;
extern volatile u32 gNdsStartupLogoDrawFormat;
extern volatile u32 gNdsStartupLogoDrawSize;
extern volatile u32 gNdsStartupLogoDrawBitmaps;
extern volatile u32 gNdsStartupLogoDrawPixels;
extern volatile u32 gNdsStartupLogoDrawGObjID;
extern volatile u32 gNdsStartupLogoDrawGObjObjKind;
extern volatile u32 gNdsStartupLogoDrawSObjAttr;
extern volatile u32 gNdsStartupLogoDrawTexshuf;
extern volatile u32 gNdsStartupLogoDrawTexshufSamples;
extern volatile u32 gNdsStartupLogoDrawVisibleSObjCount;
extern volatile u32 gNdsStartupActorFuncSet;
extern volatile u32 gNdsStartupWallpaperProcessKind;
extern volatile u32 gNdsStartupWallpaperProcessPriority;
extern volatile u32 gNdsStartupWallpaperDisplaySet;
extern volatile u32 gNdsStartupWallpaperCameraMaskLow;
extern volatile u32 gNdsStartupDefaultCameraColor;
extern volatile u32 gNdsTaskmanBridgeResult;
extern volatile u32 gNdsTaskmanContexts;
extern volatile u32 gNdsTaskmanTaskGfxNum;
extern volatile u32 gNdsTaskmanGraphicsHeapSize;
extern volatile u32 gNdsTaskmanRdpKind;
extern volatile u32 gNdsTaskmanRdpBufferSize;
extern volatile u32 gNdsTaskmanMallocCount;
extern volatile u32 gNdsStartupTaskmanMallocCount;
extern volatile u32 gNdsTaskmanGeneralHeapUsed;
extern volatile u32 gNdsTaskmanDLContextsValid;
extern volatile u32 gNdsTaskmanControllerAutoRead;
extern volatile u32 gNdsTaskmanSceneUpdateSet;
extern volatile u32 gNdsTaskmanSceneDrawSet;
extern volatile u32 gNdsTaskmanLightsSet;
extern volatile u32 gNdsTaskmanLoopReached;
extern volatile u32 gNdsTaskmanBoundedUpdateCount;
extern volatile u32 gNdsTaskmanPostUpdateSkip;
extern volatile u32 gNdsTaskmanGObjThreadSleeps;
extern volatile u32 gNdsTaskmanPostUpdateLogoPosX;
extern volatile u32 gNdsTaskmanPostUpdateLogoPosY;
extern volatile u32 gNdsTaskmanPostUpdateOpening;
extern volatile u32 gNdsTaskmanPostUpdateSceneKind;
extern volatile u32 gNdsTaskmanPostUpdateScenePrev;
extern volatile u32 gNdsTaskmanPostUpdateStatus;
extern volatile u32 gNdsTaskmanPostUpdateGObjCount;
extern volatile u32 gNdsTaskmanPostUpdateFadeCount;
extern volatile u32 gNdsTaskmanCleanupResult;
extern volatile u32 gNdsTaskmanCleanupQueuesEmpty;
extern volatile u32 gNdsTaskmanCleanupMode;
extern volatile u32 gNdsTaskmanReturnCount;
extern volatile u32 gNdsOpeningRoomDispatchCount;
extern volatile u32 gNdsOpeningRoomStartResult;
extern volatile u32 gNdsOpeningRoomFuncStartResult;
extern volatile u32 gNdsOpeningRoomUpdateResult;
extern volatile u32 gNdsOpeningRoomTickCount;
extern volatile u32 gNdsOpeningMovieRoomHandoffResult;
extern volatile u32 gNdsOpeningMovieRoomHandoffTick;
extern volatile u32 gNdsOpeningMovieRoomHandoffScene;
extern volatile u32 gNdsOpeningPortraitsDispatchCount;
extern volatile u32 gNdsOpeningPortraitsStartResult;
extern volatile u32 gNdsOpeningPortraitsFuncStartResult;
extern volatile u32 gNdsOpeningPortraitsUpdateResult;
extern volatile u32 gNdsOpeningPortraitsTickCount;
extern volatile u32 gNdsOpeningPortraitsRelocResult;
extern volatile u32 gNdsOpeningPortraitsSpriteNormalizeCount;
extern volatile u32 gNdsOpeningPortraitsSpriteNormalizeFailCount;
extern volatile u32 gNdsOpeningPortraitsDrawResult;
extern volatile u32 gNdsOpeningPortraitsDrawBlocker;
extern volatile u32 gNdsOpeningPortraitsDrawCallbackCount;
extern volatile u32 gNdsOpeningPortraitsDrawVisibleSObjCount;
extern volatile u32 gNdsOpeningPortraitsDrawWidth;
extern volatile u32 gNdsOpeningPortraitsDrawHeight;
extern volatile u32 gNdsOpeningPortraitsDrawFormat;
extern volatile u32 gNdsOpeningPortraitsDrawSize;
extern volatile u32 gNdsOpeningPortraitsDrawBitmaps;
extern volatile u32 gNdsOpeningPortraitsDrawPixels;
extern volatile u32 gNdsOpeningPortraitsNextSceneResult;
extern volatile u32 gNdsOpeningPortraitsNextSceneKind;
extern volatile u32 gNdsOpeningMarioDispatchCount;
extern volatile u32 gNdsOpeningMarioStartResult;
extern volatile u32 gNdsOpeningMarioFuncStartResult;
extern volatile u32 gNdsOpeningMarioUpdateResult;
extern volatile u32 gNdsOpeningMarioTickCount;
extern volatile u32 gNdsOpeningMarioRelocResult;
extern volatile u32 gNdsOpeningMarioSpriteNormalizeCount;
extern volatile u32 gNdsOpeningMarioSpriteNormalizeFailCount;
extern volatile u32 gNdsOpeningMarioDrawResult;
extern volatile u32 gNdsOpeningMarioDrawBlocker;
extern volatile u32 gNdsOpeningMarioDrawCallbackCount;
extern volatile u32 gNdsOpeningMarioDrawVisibleSObjCount;
extern volatile u32 gNdsOpeningMarioDrawWidth;
extern volatile u32 gNdsOpeningMarioDrawHeight;
extern volatile u32 gNdsOpeningMarioDrawFormat;
extern volatile u32 gNdsOpeningMarioDrawSize;
extern volatile u32 gNdsOpeningMarioDrawBitmaps;
extern volatile u32 gNdsOpeningMarioDrawPixels;
extern volatile u32 gNdsOpeningMarioFighterDeferredResult;
extern volatile u32 gNdsOpeningMarioFighterDeferredTick;
extern volatile u32 gNdsOpeningMarioNextSceneResult;
extern volatile u32 gNdsOpeningMarioNextSceneKind;
extern volatile u32 gNdsOpeningNameSceneDispatchMask;
extern volatile u32 gNdsOpeningNameSceneFuncStartMask;
extern volatile u32 gNdsOpeningNameSceneUpdateMask;
extern volatile u32 gNdsOpeningNameSceneFighterDeferMask;
extern volatile u32 gNdsOpeningNameSceneNextMask;
extern volatile u32 gNdsOpeningNameSceneDrawMask;
extern volatile u32 gNdsOpeningNameSceneDispatchCount;
extern volatile u32 gNdsOpeningNameSceneLastKind;
extern volatile u32 gNdsOpeningNameSceneLastTick;
extern volatile u32 gNdsOpeningNameSceneLastNextKind;
extern volatile u32 gNdsOpeningNameSceneDrawResult;
extern volatile u32 gNdsOpeningNameSceneDrawBlocker;
extern volatile u32 gNdsOpeningNameSceneDrawCallbackCount;
extern volatile u32 gNdsOpeningNameSceneDrawVisibleSObjCount;
extern volatile u32 gNdsOpeningNameSceneDrawWidth;
extern volatile u32 gNdsOpeningNameSceneDrawHeight;
extern volatile u32 gNdsOpeningNameSceneDrawFormat;
extern volatile u32 gNdsOpeningNameSceneDrawSize;
extern volatile u32 gNdsOpeningNameSceneDrawBitmaps;
extern volatile u32 gNdsOpeningNameSceneDrawPixels;
extern volatile u32 gNdsOpeningMovieBridgeResult;
extern volatile u32 gNdsOpeningMovieBridgeMask;
extern volatile u32 gNdsOpeningMovieBridgeCount;
extern volatile u32 gNdsOpeningMovieBridgeLastKind;
extern volatile u32 gNdsOpeningMovieBridgeLastNextKind;
extern volatile u32 gNdsOpeningMovieActionPreviewResult;
extern volatile u32 gNdsOpeningMovieActionPreviewMask;
extern volatile u32 gNdsOpeningMovieActionPreviewCount;
extern volatile u32 gNdsOpeningMovieActionPreviewFrameCount;
extern volatile u32 gNdsOpeningMoviePresentFrameCount;
extern volatile u32 gNdsOpeningMovieActionPreviewPixels;
extern volatile u32 gNdsOpeningMovieActionPreviewSpriteNormalizeCount;
extern volatile u32 gNdsOpeningMovieActionPreviewSpriteNormalizeFailCount;
extern volatile u32 gNdsOpeningMovieActionPreviewLastKind;
extern volatile u32 gNdsOpeningMovieActionPreviewLastWidth;
extern volatile u32 gNdsOpeningMovieActionPreviewLastHeight;
extern volatile u32 gNdsOpeningMovieActionPreviewLastFormat;
extern volatile u32 gNdsOpeningMovieActionPreviewLastSize;
extern volatile u32 gNdsOpeningMovieTitleResult;
extern volatile u32 gNdsTitleRelocResult;
extern volatile u32 gNdsTitlePreviewResult;
extern volatile u32 gNdsTitleDrawResult;
extern volatile u32 gNdsTitleSpriteNormalizeCount;
extern volatile u32 gNdsTitleSpriteNormalizeFailCount;
extern volatile u32 gNdsTitleFireSpriteNormalizeCount;
extern volatile u32 gNdsTitleFireSpriteNormalizeFailCount;
extern volatile u32 gNdsTitleDrawVisibleSObjCount;
extern volatile u32 gNdsTitleDrawRenderableSObjCount;
extern volatile u32 gNdsTitleDrawSObjCount;
extern volatile u32 gNdsTitleDrawPixels;
extern volatile u32 gNdsTitleDrawLastWidth;
extern volatile u32 gNdsTitleDrawLastHeight;
extern volatile u32 gNdsTitleDrawLastFormat;
extern volatile u32 gNdsTitleDrawLastSize;
extern volatile u32 gNdsTitleOriginalStartResult;
extern volatile u32 gNdsTitleOriginalFuncStartResult;
extern volatile u32 gNdsTitleOriginalSetupMask;
extern volatile u32 gNdsTitleOriginalLoadedFileCount;
extern volatile u32 gNdsTitleOriginalGObjCount;
extern volatile u32 gNdsTitleOriginalCameraCount;
extern volatile u32 gNdsTitleOriginalMainGObjID;
extern volatile u32 gNdsTitleOriginalTransitionGObjID;
extern volatile u32 gNdsTitleOriginalDeferredMask;
extern volatile u32 gNdsTitleOriginalLogoFireResult;
extern volatile u32 gNdsTitleOriginalLogoFireMask;
extern volatile u32 gNdsTitleOriginalLogoFireGObjDelta;
extern volatile u32 gNdsTitleOriginalLogoFireLinkID;
extern volatile u32 gNdsTitleOriginalLogoFireDLLinkID;
extern volatile u32 gNdsTitleOriginalLogoFireCameraMaskLo;
extern volatile u32 gNdsTitleOriginalLogoFireParticleBank;
extern volatile u32 gNdsTitleOriginalFireResult;
extern volatile u32 gNdsTitleOriginalFireMask;
extern volatile u32 gNdsTitleOriginalFireGObjDelta;
extern volatile u32 gNdsTitleOriginalFireSObjDelta;
extern volatile u32 gNdsTitleOriginalFireGObjFlags;
extern volatile u32 gNdsTitleOriginalFireSObjCount;
extern volatile u32 gNdsTitleOriginalFireFrames;
extern volatile u32 gNdsTitleOriginalFireAlpha;
extern volatile u32 gNdsTitleOriginalUpdateResult;
extern volatile u32 gNdsTitleOriginalUpdateCount;
extern volatile u32 gNdsTitleOriginalLayout;
extern volatile u32 gNdsTitleOriginalTransitionTics;
extern volatile u32 gNdsTitleOriginalStartActorProcess;
extern volatile u32 gNdsTitleOriginalProceedScene;
extern volatile u32 gNdsTitleOriginalProceedWait;
extern volatile u32 gNdsOpeningRoomGObjCount;
extern volatile u32 gNdsOpeningRoomCameraCount;
extern volatile u32 gNdsOpeningRoomDL0Size;
extern volatile u32 gNdsOpeningRoomDL1Size;
extern volatile u32 gNdsOpeningRoomGraphicsHeapSize;
extern volatile u32 gNdsOpeningRoomRdpBufferSize;
extern volatile u32 gNdsOpeningRoomMallocCount;
extern volatile u32 gNdsOpeningRoomPreAssetResult;
extern volatile u32 gNdsOpeningRoomFirstEventResult;
extern volatile u32 gNdsOpeningRoomFirstEventTick;
extern volatile u32 gNdsOpeningRoomFirstEventProbeMask;
extern volatile u32 gNdsOpeningRoomFirstEventPencilsDObjOffset;
extern volatile u32 gNdsOpeningRoomFirstEventPencilsAnimOffset;
extern volatile u32 gNdsOpeningRoomFirstEventDataResult;
extern volatile u32 gNdsOpeningRoomFirstEventDataMask;
extern volatile u32 gNdsOpeningRoomFirstEventPencilsDObjEntries;
extern volatile u32 gNdsOpeningRoomFirstEventPencilsDLPtrs;
extern volatile u32 gNdsOpeningRoomFirstEventPencilsAnimJoints;
extern volatile u32 gNdsOpeningRoomFirstEventPencilsAnimFirstOpcode;
extern volatile u32 gNdsOpeningRoomFirstEventRunResult;
extern volatile u32 gNdsOpeningRoomFirstEventDeferredMask;
extern volatile u32 gNdsOpeningRoomFighterDeferredResult;
extern volatile u32 gNdsOpeningRoomFighterDeferredKind;
extern volatile u32 gNdsOpeningRoomTick380DeferredResult;
extern volatile u32 gNdsOpeningRoomTick380DeferredMask;
extern volatile u32 gNdsOpeningRoomTick450RunResult;
extern volatile u32 gNdsOpeningRoomTick450DeferredMask;
extern volatile u32 gNdsOpeningRoomTick500RunResult;
extern volatile u32 gNdsOpeningRoomTick500DeferredMask;
extern volatile u32 gNdsOpeningRoomTick560RunResult;
extern volatile u32 gNdsOpeningRoomTick560DeferredMask;
extern volatile u32 gNdsOpeningRoomDrawResult;
extern volatile u32 gNdsOpeningRoomDrawBlocker;
extern volatile u32 gNdsOpeningRoomDrawTickCount;
extern volatile u32 gNdsOpeningRoomDrawFrameCount;
extern volatile u32 gNdsOpeningRoomDrawProbeCount;
extern volatile u32 gNdsOpeningRoomDrawReuseCount;
extern volatile u32 gNdsOpeningRoomDrawCameraCallbackCount;
extern volatile u32 gNdsOpeningRoomDrawDisplayCallbackCount;
extern volatile u32 gNdsOpeningRoomDrawDObjCallbackCount;
extern volatile u32 gNdsOpeningRoomDrawFirstCameraMaskLow;
extern volatile u32 gNdsOpeningRoomDrawFirstCameraPriority;
extern volatile u32 gNdsOpeningRoomDrawFirstCameraFlags;
extern volatile u32 gNdsOpeningRoomDrawFirstCameraXObjCount;
extern volatile u32 gNdsOpeningRoomDrawFirstCameraXObjKind0;
extern volatile u32 gNdsOpeningRoomDrawFirstCameraXObjKind1;
extern volatile s32 gNdsOpeningRoomDrawFirstCameraViewportScaleX;
extern volatile s32 gNdsOpeningRoomDrawFirstCameraViewportScaleY;
extern volatile s32 gNdsOpeningRoomDrawFirstCameraViewportTransX;
extern volatile s32 gNdsOpeningRoomDrawFirstCameraViewportTransY;
extern volatile u32 gNdsRdpDefaultViewportSetCount;
extern volatile s32 gNdsRdpDefaultViewportScaleX;
extern volatile s32 gNdsRdpDefaultViewportScaleY;
extern volatile s32 gNdsRdpDefaultViewportTransX;
extern volatile s32 gNdsRdpDefaultViewportTransY;
extern volatile s32 gNdsRdpDefaultViewportScaleZ;
extern volatile s32 gNdsRdpDefaultViewportTransZ;
extern volatile s32 gNdsOpeningRoomDrawFirstCameraNear100;
extern volatile s32 gNdsOpeningRoomDrawFirstCameraFar100;
extern volatile s32 gNdsOpeningRoomDrawFirstCameraFovY100;
extern volatile s32 gNdsOpeningRoomDrawFirstCameraEyeX100;
extern volatile s32 gNdsOpeningRoomDrawFirstCameraEyeY100;
extern volatile s32 gNdsOpeningRoomDrawFirstCameraEyeZ100;
extern volatile s32 gNdsOpeningRoomDrawFirstCameraAtX100;
extern volatile s32 gNdsOpeningRoomDrawFirstCameraAtY100;
extern volatile s32 gNdsOpeningRoomDrawFirstCameraAtZ100;
extern volatile u32 gNdsOpeningRoomDrawFirstObjectDLLink;
extern volatile u32 gNdsOpeningRoomDrawFirstObjectID;
extern volatile u32 gNdsOpeningRoomDrawFirstObjectKind;
extern volatile u32 gNdsOpeningRoomDrawFirstCallback;
extern volatile u32 gNdsOpeningRoomDrawFirstDObjDL;
extern volatile u32 gNdsOpeningRoomDrawFirstDObjMeta;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateResult;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateCount;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateCameraMaskLow;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateCameraPriority;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateObjectDLLink;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateObjectID;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateObjectKind;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateCallback;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateDObjDL;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateDObjMeta;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjCount;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjFlags;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjEffectiveFlags;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjMask;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjTextureCurr;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjTextureNext;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjPaletteIndex;
extern volatile s32 gNdsOpeningRoomDrawMaterialCandidateMObjLfrac100;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjFormat;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjSize;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjBlockFormat;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjBlockSize;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjTileWidth;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjTileHeight;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjScrollWidth;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjScrollHeight;
extern volatile s32 gNdsOpeningRoomDrawMaterialCandidateMObjScaleS100;
extern volatile s32 gNdsOpeningRoomDrawMaterialCandidateMObjScaleT100;
extern volatile s32 gNdsOpeningRoomDrawMaterialCandidateMObjTranslateS100;
extern volatile s32 gNdsOpeningRoomDrawMaterialCandidateMObjTranslateT100;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjSpriteArray;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjPaletteArray;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjSpriteCurr;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjSpriteNext;
extern volatile u32 gNdsOpeningRoomDrawMaterialCandidateMObjPalettePtr;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialResult;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialCandidateCount;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialMObjCount;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialSpriteArrayCount;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialSpriteCurrCount;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialSpriteNextCount;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialObjectDLLink;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialObjectID;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialObjectKind;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialCallback;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialDObjDL;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialDObjMeta;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialMObjFlags;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialMObjEffectiveFlags;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialMObjMask;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialMObjTextureCurr;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialMObjTextureNext;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialMObjSpriteArray;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialMObjSpriteCurr;
extern volatile u32 gNdsOpeningRoomDrawTextureMaterialMObjSpriteNext;
extern volatile u32 gNdsOpeningRoomDrawMaterialBranchResult;
extern volatile u32 gNdsOpeningRoomDrawMaterialBranchMObjCount;
extern volatile u32 gNdsOpeningRoomDrawMaterialBranchSegmentCommands;
extern volatile u32 gNdsOpeningRoomDrawMaterialBranchTableCommands;
extern volatile u32 gNdsOpeningRoomDrawMaterialBranchGeneratedCommands;
extern volatile u32 gNdsOpeningRoomDrawMaterialBranchFirstMask;
extern volatile u32 gNdsOpeningRoomDrawMaterialBranchFirstGeneratedCommands;
extern volatile u32 gNdsOpeningRoomDrawMaterialBranchFirstTextureScaleS;
extern volatile u32 gNdsOpeningRoomDrawMaterialBranchFirstTextureScaleT;
extern volatile s32 gNdsOpeningRoomDrawMaterialBranchFirstTileUls;
extern volatile s32 gNdsOpeningRoomDrawMaterialBranchFirstTileUlt;
extern volatile s32 gNdsOpeningRoomDrawMaterialBranchFirstTileLrs;
extern volatile s32 gNdsOpeningRoomDrawMaterialBranchFirstTileLrt;
extern volatile s32 gNdsOpeningRoomDrawMaterialBranchFirstScrollUls;
extern volatile s32 gNdsOpeningRoomDrawMaterialBranchFirstScrollUlt;
extern volatile s32 gNdsOpeningRoomDrawMaterialBranchFirstScrollLrs;
extern volatile s32 gNdsOpeningRoomDrawMaterialBranchFirstScrollLrt;
extern volatile u32 gNdsOpeningRoomDrawMaterialBranchFirstLoadBlockTexels;
extern volatile u32 gNdsOpeningRoomDrawMaterialBranchFirstLoadBlockDxt;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitResult;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitBlocker;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitUnsupportedMask;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitMObjCount;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitTableCommands;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitGeneratedCommands;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitHeapStart;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitBranchStart;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitHeapAfter;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitHeapBytes;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitFirstTableOp;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitFirstBranchOp0;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitFirstBranchOp1;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitFirstBranchOp2;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitFirstBranchW0_0;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitFirstBranchW1_0;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitFirstBranchW0_1;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitFirstBranchW1_1;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitFirstBranchW0_2;
extern volatile u32 gNdsOpeningRoomDrawMaterialEmitFirstBranchW1_2;
extern volatile u32 gNdsOpeningRoomDLPreviewResult;
extern volatile u32 gNdsOpeningRoomDLPreviewBlocker;
extern volatile u32 gNdsOpeningRoomDLPreviewCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewVertexCount;
extern volatile u32 gNdsOpeningRoomDLPreviewTriangleCount;
extern volatile u32 gNdsOpeningRoomDLPreviewPixelCount;
extern volatile u32 gNdsOpeningRoomDLPreviewFirstOpcode;
extern volatile u32 gNdsOpeningRoomDLPreviewUnsupportedOpcode;
extern volatile u32 gNdsOpeningRoomDLPreviewUnsupportedCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewVertexCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewTriangleCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewSyncCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewEndCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewBranchCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewBranchCallCount;
extern volatile u32 gNdsOpeningRoomDLPreviewBranchJumpCount;
extern volatile u32 gNdsOpeningRoomDLPreviewSegmentResolveCount;
extern volatile u32 gNdsOpeningRoomDLPreviewColorCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewPrimColor;
extern volatile u32 gNdsOpeningRoomDLPreviewOtherModeCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewFirstDL;
extern volatile u32 gNdsOpeningRoomDLPreviewTransformMask;
extern volatile u32 gNdsOpeningRoomDLPreviewXObjCount;
extern volatile u32 gNdsOpeningRoomDLPreviewFirstXObjKind;
extern volatile s32 gNdsOpeningRoomDLPreviewTranslateX100;
extern volatile s32 gNdsOpeningRoomDLPreviewTranslateY100;
extern volatile s32 gNdsOpeningRoomDLPreviewTranslateZ100;
extern volatile s32 gNdsOpeningRoomDLPreviewRotateX100;
extern volatile s32 gNdsOpeningRoomDLPreviewRotateY100;
extern volatile s32 gNdsOpeningRoomDLPreviewRotateZ100;
extern volatile s32 gNdsOpeningRoomDLPreviewScaleX100;
extern volatile s32 gNdsOpeningRoomDLPreviewScaleY100;
extern volatile s32 gNdsOpeningRoomDLPreviewScaleZ100;
extern volatile s32 gNdsOpeningRoomDLPreviewMinX;
extern volatile s32 gNdsOpeningRoomDLPreviewMaxX;
extern volatile s32 gNdsOpeningRoomDLPreviewMinY;
extern volatile s32 gNdsOpeningRoomDLPreviewMaxY;
extern volatile u32 gNdsOpeningRoomDLPreviewProjectionMask;
extern volatile u32 gNdsOpeningRoomDLPreviewProjectionMode;
extern volatile u32 gNdsOpeningRoomDLPreviewProjectionBlocker;
extern volatile u32 gNdsOpeningRoomDLPreviewProjectedVertexCount;
extern volatile u32 gNdsOpeningRoomDLPreviewProjectedTriangleCount;
extern volatile s32 gNdsOpeningRoomDLPreviewProjectedMinX;
extern volatile s32 gNdsOpeningRoomDLPreviewProjectedMaxX;
extern volatile s32 gNdsOpeningRoomDLPreviewProjectedMinY;
extern volatile s32 gNdsOpeningRoomDLPreviewProjectedMaxY;
extern volatile s32 gNdsOpeningRoomDLPreviewProjectedMinDepth100;
extern volatile s32 gNdsOpeningRoomDLPreviewProjectedMaxDepth100;
extern volatile u32 gNdsOpeningRoomDLPreviewFallbackAxis;
extern volatile u32 gNdsOpeningRoomDLPreviewFallbackArea;
extern volatile u32 gNdsOpeningRoomDLPreviewGeometryCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewGeometryClearMask;
extern volatile u32 gNdsOpeningRoomDLPreviewGeometrySetMask;
extern volatile u32 gNdsOpeningRoomDLPreviewGeometryFinalMode;
extern volatile u32 gNdsOpeningRoomDLPreviewGeometryFlags;
extern volatile u32 gNdsOpeningRoomDLPreviewGeometryPositiveWinding;
extern volatile u32 gNdsOpeningRoomDLPreviewGeometryNegativeWinding;
extern volatile u32 gNdsOpeningRoomDLPreviewGeometryZeroArea;
extern volatile u32 gNdsOpeningRoomDLPreviewGeometryDrawnTriangles;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureMask;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureImage;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureFormat;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureSize;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureImageWidth;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureTileWidth;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureTileHeight;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureTexelWidth;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureTexelHeight;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureLoadTexels;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureLoadBlockTile;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureLoadBlockUls;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureLoadBlockUlt;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureLoadBlockLrs;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureLoadBlockDxt;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureTileSizeTile;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureTileSizeUls;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureTileSizeUlt;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureTileSizeLrs;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureTileSizeLrt;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureSamplePixels;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureSetTileCount;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureCombineW0;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureCombineW1;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureCombineMode;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureCombineFlags;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureModulatedPixels;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureRenderTile;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureRenderTileLine;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureRenderTileTmem;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureRenderTilePalette;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureRenderTileCms;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureRenderTileCmt;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureRenderTileMasks;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureRenderTileMaskt;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureRenderTileShifts;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureRenderTileShiftt;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureRenderTileFlags;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureReady;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureSampleMode;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureScaleS;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureScaleT;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureLevel;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureTile;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureOn;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureXParam;
extern volatile u32 gNdsOpeningRoomDLPreviewTextureStateFlags;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialCount;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialFlags;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialEffectiveFlags;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialMask;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialTextureCurr;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialTextureNext;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialPaletteIndex;
extern volatile s32 gNdsOpeningRoomDLPreviewMaterialLfrac100;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialFormat;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialSize;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialBlockFormat;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialBlockSize;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialTileWidth;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialTileHeight;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialScrollWidth;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialScrollHeight;
extern volatile s32 gNdsOpeningRoomDLPreviewMaterialScaleS100;
extern volatile s32 gNdsOpeningRoomDLPreviewMaterialScaleT100;
extern volatile s32 gNdsOpeningRoomDLPreviewMaterialTranslateS100;
extern volatile s32 gNdsOpeningRoomDLPreviewMaterialTranslateT100;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialSpriteCurr;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialSpriteNext;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialPalettePtr;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialBranchResult;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialBranchBlocker;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialBranchCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialBranchPrimCount;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialBranchEndCount;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialBranchUnsupportedOp;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialBranchFirstOp;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialBranchSecondOp;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialBranchPrimColor;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialBranchPrimLod;
extern volatile u32 gNdsOpeningRoomDLPreviewMaterialBranchPrimM;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererParsedCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererStateCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererSkippedCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererRenderedCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureMask;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureImage;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureFormat;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureSize;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureImageWidth;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureLoadTexels;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureSetTileCount;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureCommandCount;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureStateFlags;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureTileWidth;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureTileHeight;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureRenderTile;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureRenderTileLine;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureRenderTileFlags;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureLoadBlockLrs;
extern volatile u32 gNdsOpeningRoomDLPreviewRendererTextureLoadBlockDxt;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeResult;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeBlocker;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeFirstDL;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeVertexCount;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeTriangleCount;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeFirstOpcode;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeUnsupportedOpcode;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeVertexCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeTriangleCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeSyncCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeEndCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeBranchCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeOtherModeCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLProbeUnsupportedCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandResult;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandBlocker;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandFirstDL;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandFirstBranchDL;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandFirstResolvedBranchDL;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandVertexCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandTriangleCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandFirstOpcode;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandUnsupportedOpcode;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandVertexCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandTriangleCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandSyncCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandEndCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandBranchCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandBranchCallCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandBranchJumpCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandSegmentResolveCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandOtherModeCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandColorCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandUnsupportedCommandCount;
extern volatile u32 gNdsOpeningRoomMaterialDLExpandMaxDepth;
extern volatile u32 gNdsOpeningRoomOutsideAssetMask;
extern volatile u32 gNdsOpeningRoomOutsideDisplayListOffset;
extern volatile u32 gNdsOpeningRoomOutsideCreateResult;
extern volatile u32 gNdsOpeningRoomOutsideCreateMask;
extern volatile u32 gNdsOpeningRoomOutsideCreateGObjCount;
extern volatile u32 gNdsOpeningRoomOutsideGObjDelta;
extern volatile u32 gNdsOpeningRoomOutsideDObjDelta;
extern volatile u32 gNdsOpeningRoomOutsideXObjDelta;
extern volatile u32 gNdsOpeningRoomOutsideDisplaySet;
extern volatile u32 gNdsOpeningRoomHazeAssetMask;
extern volatile u32 gNdsOpeningRoomHazeDisplayListOffset;
extern volatile u32 gNdsOpeningRoomHazeCreateResult;
extern volatile u32 gNdsOpeningRoomHazeCreateMask;
extern volatile u32 gNdsOpeningRoomHazeCreateGObjCount;
extern volatile u32 gNdsOpeningRoomHazeGObjDelta;
extern volatile u32 gNdsOpeningRoomHazeDObjDelta;
extern volatile u32 gNdsOpeningRoomHazeXObjDelta;
extern volatile u32 gNdsOpeningRoomHazeDisplaySet;
extern volatile u32 gNdsOpeningRoomSunlightAssetMask;
extern volatile u32 gNdsOpeningRoomSunlightDisplayListOffset;
extern volatile u32 gNdsOpeningRoomSunlightCreateResult;
extern volatile u32 gNdsOpeningRoomSunlightCreateMask;
extern volatile u32 gNdsOpeningRoomSunlightCreateGObjCount;
extern volatile u32 gNdsOpeningRoomSunlightGObjDelta;
extern volatile u32 gNdsOpeningRoomSunlightDObjDelta;
extern volatile u32 gNdsOpeningRoomSunlightXObjDelta;
extern volatile u32 gNdsOpeningRoomSunlightDisplaySet;
extern volatile u32 gNdsOpeningRoomDeskAssetMask;
extern volatile u32 gNdsOpeningRoomDeskDObjOffset;
extern volatile u32 gNdsOpeningRoomDeskCreateResult;
extern volatile u32 gNdsOpeningRoomDeskCreateMask;
extern volatile u32 gNdsOpeningRoomDeskCreateGObjCount;
extern volatile u32 gNdsOpeningRoomDeskGObjDelta;
extern volatile u32 gNdsOpeningRoomDeskDObjDelta;
extern volatile u32 gNdsOpeningRoomDeskXObjDelta;
extern volatile u32 gNdsOpeningRoomDeskDisplaySet;
extern volatile u32 gNdsOpeningRoomSunlightEjectResult;
extern volatile u32 gNdsOpeningRoomSunlightEjectBeforeGObjCount;
extern volatile u32 gNdsOpeningRoomSunlightEjectAfterGObjCount;
extern volatile u32 gNdsOpeningRoomSunlightEjectUnlinkedMask;
extern volatile u32 gNdsOpeningRoomOverlayCreateResult;
extern volatile u32 gNdsOpeningRoomOverlayDisplaySet;
extern volatile u32 gNdsOpeningRoomOverlayAlphaInit;
extern volatile u32 gNdsOpeningRoomOverlayCreateGObjCount;
extern volatile u32 gNdsOpeningRoomOverlayEjectResult;
extern volatile u32 gNdsOpeningRoomOverlayEjectBeforeGObjCount;
extern volatile u32 gNdsOpeningRoomOverlayEjectAfterGObjCount;
extern volatile u32 gNdsOpeningRoomOverlayEjectUnlinkedMask;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayCreateResult;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayCreateMask;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayCreateTick;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayCreateGObjCount;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayGObjDelta;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayDisplaySet;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayAlphaInit;
extern volatile u32 gNdsOpeningRoomSpotlightAssetMask;
extern volatile u32 gNdsOpeningRoomSpotlightDisplayListOffset;
extern volatile u32 gNdsOpeningRoomSpotlightMObjOffset;
extern volatile u32 gNdsOpeningRoomSpotlightMatAnimOffset;
extern volatile u32 gNdsOpeningRoomSpotlightCreateResult;
extern volatile u32 gNdsOpeningRoomSpotlightCreateMask;
extern volatile u32 gNdsOpeningRoomSpotlightCreateTick;
extern volatile u32 gNdsOpeningRoomSpotlightCreateGObjCount;
extern volatile u32 gNdsOpeningRoomSpotlightGObjDelta;
extern volatile u32 gNdsOpeningRoomSpotlightDObjDelta;
extern volatile u32 gNdsOpeningRoomSpotlightXObjDelta;
extern volatile u32 gNdsOpeningRoomSpotlightMObjDelta;
extern volatile u32 gNdsOpeningRoomSpotlightAObjDelta;
extern volatile u32 gNdsOpeningRoomSpotlightDisplaySet;
extern volatile u32 gNdsOpeningRoomSpotlightProcessSet;
extern volatile u32 gNdsOpeningRoomSpotlightMObjSet;
extern volatile u32 gNdsOpeningRoomSpotlightMatAnimSet;
extern volatile u32 gNdsOpeningRoomSpotlightPositionSet;
extern volatile u32 gNdsOpeningRoomScene1CameraCreateResult;
extern volatile u32 gNdsOpeningRoomScene1CameraCreateMask;
extern volatile u32 gNdsOpeningRoomScene1CameraCreateGObjCount;
extern volatile u32 gNdsOpeningRoomScene1CameraGObjDelta;
extern volatile u32 gNdsOpeningRoomScene1CameraCObjDelta;
extern volatile u32 gNdsOpeningRoomScene1CameraXObjDelta;
extern volatile u32 gNdsOpeningRoomScene1CameraAObjDelta;
extern volatile u32 gNdsOpeningRoomScene1CameraDisplaySet;
extern volatile u32 gNdsOpeningRoomScene1CameraProcessSet;
extern volatile u32 gNdsOpeningRoomScene1CameraAnimSet;
extern volatile u32 gNdsOpeningRoomScene1CameraViewportSet;
extern volatile u32 gNdsOpeningRoomScene1CameraDLBufferSet;
extern volatile u32 gNdsOpeningRoomScene2CameraAssetMask;
extern volatile u32 gNdsOpeningRoomScene2CameraAnimOffset;
extern volatile u32 gNdsOpeningRoomScene2CameraEjectResult;
extern volatile u32 gNdsOpeningRoomScene2CameraEjectMask;
extern volatile u32 gNdsOpeningRoomScene2CameraEjectBeforeGObjCount;
extern volatile u32 gNdsOpeningRoomScene2CameraEjectAfterGObjCount;
extern volatile u32 gNdsOpeningRoomScene2CameraEjectBeforeCameraCount;
extern volatile u32 gNdsOpeningRoomScene2CameraEjectAfterCameraCount;
extern volatile u32 gNdsOpeningRoomScene2CameraCreateResult;
extern volatile u32 gNdsOpeningRoomScene2CameraCreateMask;
extern volatile u32 gNdsOpeningRoomScene2CameraCreateGObjCount;
extern volatile u32 gNdsOpeningRoomScene2CameraGObjDelta;
extern volatile u32 gNdsOpeningRoomScene2CameraCObjDelta;
extern volatile u32 gNdsOpeningRoomScene2CameraXObjDelta;
extern volatile u32 gNdsOpeningRoomScene2CameraAObjDelta;
extern volatile u32 gNdsOpeningRoomScene2CameraDisplaySet;
extern volatile u32 gNdsOpeningRoomScene2CameraProcessSet;
extern volatile u32 gNdsOpeningRoomScene2CameraAnimSet;
extern volatile u32 gNdsOpeningRoomScene2CameraViewportSet;
extern volatile u32 gNdsOpeningRoomScene2CameraDLBufferSet;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayCameraCreateResult;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayCameraCreateMask;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayCameraCreateGObjCount;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayCameraGObjDelta;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayCameraCObjDelta;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayCameraXObjDelta;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayCameraDisplaySet;
extern volatile u32 gNdsOpeningRoomCloseUpOverlayCameraViewportSet;
extern volatile u32 gNdsOpeningRoomWallpaperCameraCreateResult;
extern volatile u32 gNdsOpeningRoomWallpaperCameraCreateMask;
extern volatile u32 gNdsOpeningRoomWallpaperCameraCreateGObjCount;
extern volatile u32 gNdsOpeningRoomWallpaperCameraGObjDelta;
extern volatile u32 gNdsOpeningRoomWallpaperCameraCObjDelta;
extern volatile u32 gNdsOpeningRoomWallpaperCameraXObjDelta;
extern volatile u32 gNdsOpeningRoomWallpaperCameraDisplaySet;
extern volatile u32 gNdsOpeningRoomWallpaperCameraViewportSet;
extern volatile u32 gNdsOpeningRoomLogoCameraAssetMask;
extern volatile u32 gNdsOpeningRoomLogoCameraAnimOffset;
extern volatile u32 gNdsOpeningRoomLogoCameraCreateResult;
extern volatile u32 gNdsOpeningRoomLogoCameraCreateMask;
extern volatile u32 gNdsOpeningRoomLogoCameraCreateGObjCount;
extern volatile u32 gNdsOpeningRoomLogoCameraGObjDelta;
extern volatile u32 gNdsOpeningRoomLogoCameraCObjDelta;
extern volatile u32 gNdsOpeningRoomLogoCameraXObjDelta;
extern volatile u32 gNdsOpeningRoomLogoCameraAObjDelta;
extern volatile u32 gNdsOpeningRoomLogoCameraDisplaySet;
extern volatile u32 gNdsOpeningRoomLogoCameraProcessSet;
extern volatile u32 gNdsOpeningRoomLogoCameraAnimSet;
extern volatile u32 gNdsOpeningRoomLogoCameraViewportSet;
extern volatile u32 gNdsOpeningRoomLogoAssetMask;
extern volatile u32 gNdsOpeningRoomLogoDObjOffset;
extern volatile u32 gNdsOpeningRoomLogoMObjOffset;
extern volatile u32 gNdsOpeningRoomLogoMatAnimOffset;
extern volatile u32 gNdsOpeningRoomLogoCreateResult;
extern volatile u32 gNdsOpeningRoomLogoCreateMask;
extern volatile u32 gNdsOpeningRoomLogoCreateGObjCount;
extern volatile u32 gNdsOpeningRoomLogoGObjDelta;
extern volatile u32 gNdsOpeningRoomLogoDObjDelta;
extern volatile u32 gNdsOpeningRoomLogoXObjDelta;
extern volatile u32 gNdsOpeningRoomLogoMObjDelta;
extern volatile u32 gNdsOpeningRoomLogoAObjDelta;
extern volatile u32 gNdsOpeningRoomLogoDisplaySet;
extern volatile u32 gNdsOpeningRoomLogoMObjSet;
extern volatile u32 gNdsOpeningRoomLogoMatAnimSet;
extern volatile u32 gNdsOpeningRoomLogoEjectResult;
extern volatile u32 gNdsOpeningRoomLogoEjectBeforeGObjCount;
extern volatile u32 gNdsOpeningRoomLogoEjectAfterGObjCount;
extern volatile u32 gNdsOpeningRoomLogoEjectUnlinkedMask;
extern volatile u32 gNdsOpeningRoomBossShadowAssetMask;
extern volatile u32 gNdsOpeningRoomBossShadowDisplayListOffset;
extern volatile u32 gNdsOpeningRoomBossShadowAnimOffset;
extern volatile u32 gNdsOpeningRoomBossShadowCreateResult;
extern volatile u32 gNdsOpeningRoomBossShadowCreateMask;
extern volatile u32 gNdsOpeningRoomBossShadowCreateGObjCount;
extern volatile u32 gNdsOpeningRoomBossShadowGObjDelta;
extern volatile u32 gNdsOpeningRoomBossShadowDObjDelta;
extern volatile u32 gNdsOpeningRoomBossShadowXObjDelta;
extern volatile u32 gNdsOpeningRoomBossShadowAObjDelta;
extern volatile u32 gNdsOpeningRoomBossShadowProcessSet;
extern volatile u32 gNdsOpeningRoomBossShadowDisplaySet;
extern volatile u32 gNdsOpeningRoomBossShadowAnimSet;
extern volatile u32 gNdsOpeningRoomBossShadowEjectResult;
extern volatile u32 gNdsOpeningRoomBossShadowEjectBeforeGObjCount;
extern volatile u32 gNdsOpeningRoomBossShadowEjectAfterGObjCount;
extern volatile u32 gNdsOpeningRoomBossShadowEjectUnlinkedMask;
extern volatile u32 gNdsOpeningRoomPencilsCreateResult;
extern volatile u32 gNdsOpeningRoomPencilsCreateMask;
extern volatile u32 gNdsOpeningRoomPencilsGObjDelta;
extern volatile u32 gNdsOpeningRoomPencilsDObjDelta;
extern volatile u32 gNdsOpeningRoomPencilsXObjDelta;
extern volatile u32 gNdsOpeningRoomPencilsAObjDelta;
extern volatile u32 gNdsOpeningRoomPencilsProcessSet;
extern volatile u32 gNdsOpeningRoomPencilsDisplaySet;
extern volatile u32 gNdsOpeningRoomPencilsDObjTreeCount;
extern volatile u32 gNdsOpeningRoomPencilsAnimRootCount;
extern volatile u32 gNdsOpeningRoomControllerCheckCount;
extern volatile u32 gNdsOpeningRoomPulledFighterKind;
extern volatile u32 gNdsOpeningRoomDroppedFighterKind;
extern volatile u32 gNdsOpeningRoomSkipToTitleCount;
extern volatile u32 gNdsOpeningRoomRelocResult;
extern volatile u32 gNdsOpeningRoomRelocInitCount;
extern volatile u32 gNdsOpeningRoomRelocLoadCount;
extern volatile u32 gNdsOpeningRoomRelocFileMask;
extern volatile u32 gNdsOpeningRoomRelocHeaderMask;
extern volatile u32 gNdsOpeningRoomRelocPayloadMask;
extern volatile u32 gNdsOpeningRoomRelocContentReady;
extern volatile u32 gNdsOpeningRoomRelocFixupReady;
extern volatile u32 gNdsOpeningRoomRelocBytesLoaded;
extern volatile u32 gNdsOpeningRoomRelocLastFileID;
extern volatile u32 gNdsOpeningRoomRelocLastSize;
extern volatile u32 gNdsOpeningRoomRelocWordSwapMask;
extern volatile u32 gNdsOpeningRoomRelocWordSwapCount;
extern volatile u32 gNdsOpeningRoomRelocWordSwapFailCount;
extern volatile u32 gNdsOpeningRoomRelocPointerFixupMask;
extern volatile u32 gNdsOpeningRoomRelocPointerFixupCount;
extern volatile u32 gNdsOpeningRoomRelocPointerFixupFailCount;
extern volatile u32 gNdsOpeningRoomRelocSymbolResolveCount;
extern volatile u32 gNdsOpeningRoomRelocSymbolResolveFailCount;
extern volatile u32 gNdsOpeningRoomRelocSymbolProbeMask;
extern volatile u32 gNdsOpeningRoomRelocLastSymbolOffset;
extern volatile u32 gNdsOpeningRoomRelocMObjSubNormalizeCount;
extern volatile u32 gNdsOpeningRoomRelocMObjSubNormalizeFailCount;
extern volatile u32 gNdsOpeningRoomRelocMObjSubFirstFlags;
extern volatile u32 gNdsOpeningRoomRelocMObjSubSourceResult;
extern volatile u32 gNdsOpeningRoomRelocMObjSubTextureFlagCount;
extern volatile u32 gNdsOpeningRoomRelocMObjSubZeroFlagCount;
extern volatile u32 gNdsOpeningRoomRelocMObjSubPrimColorCount;
extern volatile u32 gNdsOpeningRoomRelocMObjSubLightCount;
extern volatile u32 gNdsOpeningRoomRelocMObjSubFirstTextureOffset;
extern volatile u32 gNdsOpeningRoomRelocMObjSubFirstTextureFlags;

#endif
