#ifndef SSB64_NDS_AUDIO_BGM_H
#define SSB64_NDS_AUDIO_BGM_H

#include <PR/ultratypes.h>

#define NDS_AUDIO_BGM_PASS 0x42474d31u /* BGM1 */
#define NDS_AUDIO_BGM_TRACK_PUPUPU 0u
/* P2-4 Yoster: nSYAudioBGMYoster, ninth gmMusicID entry. Render pending --
 * see scripts/sfx/bgm/render-audio-bgm-pupupu.py --sequence-index 8. */
#define NDS_AUDIO_BGM_TRACK_YOSTER 8u
#define NDS_AUDIO_BGM_TRACK_WIN_MARIO 12u
#define NDS_AUDIO_BGM_TRACK_WIN_FOX 16u
#define NDS_AUDIO_BGM_TRACK_RESULTS 22u
/* P2-1d-1. nSYAudioBGMModeSelect, gm/gmsound.h's gmMusicID enum -- verified by
 * fully parsing the enum (no REGION_US conditionals in gmMusicID, unlike
 * gmFGMVoiceID) and cross-checked against the four anchors already pinned
 * above: Pupupu 0, WinMario 12, WinFox 16, Results 22 all land exactly where
 * this file already has them, and ModeSelect follows at 44 in the same
 * parse. */
#define NDS_AUDIO_BGM_TRACK_MODE_SELECT 44u
/* P2-1e-1. nSYAudioBGMBattleSelect, gm/gmsound.h's gmMusicID enum -- verified
 * by fully parsing the enum (no REGION_US conditionals in gmMusicID) and
 * cross-checked against the five anchors already pinned above: Pupupu 0,
 * WinMario 12, WinFox 16, Results 22, ModeSelect 44 all land exactly where
 * this file already has them, and BattleSelect lands at 10 in the same
 * parse -- the eleventh declared entry, two below WinDefault (11). */
#define NDS_AUDIO_BGM_TRACK_BATTLE_SELECT 10u
#define NDS_AUDIO_BGM_SAMPLE_RATE 22050u
/* P2-1L bug (b1). Regenerated by render-audio-bgm-pupupu.py after fixing
 * collect_loop_metadata() to truncate the flat trailing render pad at a
 * clean loop-period boundary instead of leaving it inside the loop as
 * measured true digital silence (offline RMS 0.0) right before the wrap.
 * loop_start_byte is unchanged -- the fix is a proven no-op there for a
 * track where every channel already agrees on one shared loop period.
 *
 * P2-1L bug (b2), 2026-08-19: the owner re-tested (b1) by ear and found
 * two further defects, both fixed at the render seam (render()/
 * decode_wave() in render-audio-bgm-pupupu.py), so every *_SHA256_LO
 * below moved again even though byte counts/loop points did not:
 * (i) notes held longer than one straight ADPCM decode pass of their
 * wavetable rendered silence for the remainder instead of looping the
 * wavetable's own authored ALADPCMloop sustain region (n_env.c's
 * n_alAdpcmPull) -- this was the surviving "quiet patch" on Battle
 * Select, located to the exact sample range of that track's one long
 * sustained note by cross-correlating the owner's DS.wav re-recording
 * against our own decoded output; (ii) every note used a flat "+2200
 * samples, 700-sample fade" release regardless of its authored envelope,
 * where this bank's own ALEnvelope data (attackTime/decayTime/
 * releaseTime/attackVolume/decayVolume, always present but previously
 * unread) gives most instruments a 25-30 ms release -- a fraction of the
 * old ~100 ms tail, and the measured mechanism behind the "smeared/
 * legato vs the N64 reference's staccato" comparison. */
#define NDS_AUDIO_BGM_PUPUPU_STREAM_BYTES 2843290u
#define NDS_AUDIO_BGM_PUPUPU_LOOP_START_BYTES 8798u
#define NDS_AUDIO_BGM_PUPUPU_STREAM_SHA256_LO 0xbad487f5u
#define NDS_AUDIO_BGM_PUPUPU_ASSET_BYTES 711920u
#define NDS_AUDIO_BGM_PUPUPU_ASSET_SHA256_LO 0x26f98d91u
#define NDS_AUDIO_BGM_PUPUPU_PACKET_COUNT 88u
#define NDS_AUDIO_BGM_PUPUPU_LOOP_PACKET 1u
#define NDS_AUDIO_BGM_PUPUPU_LOOP_RECORD 2252u
/* P2-4 Yoshi's Island, rendered 2026-09-03 from S1_music_sbk sequence 8
 * through scripts/sfx/bgm/render-audio-bgm.py, the same tool and the same
 * path as Dream Land above. The sequence index is the gmMusicID enum value
 * (gm/gmsound.h:31-40, sequential from 0 with no REGION_US arm in the BGM
 * range). Unlike Dream Land, this track's channels do NOT all agree on one
 * loop period -- the renderer took the majority-agreeing period, so the loop
 * starts at packet 10 rather than packet 1. Pins are the render metadata
 * verbatim: assets/audio/bgm_yoster_ima.json. */
#define NDS_AUDIO_BGM_YOSTER_STREAM_BYTES 2605160u
#define NDS_AUDIO_BGM_YOSTER_LOOP_START_BYTES 313088u
#define NDS_AUDIO_BGM_YOSTER_STREAM_SHA256_LO 0xf5b4ee3fu
#define NDS_AUDIO_BGM_YOSTER_ASSET_BYTES 652292u
#define NDS_AUDIO_BGM_YOSTER_ASSET_SHA256_LO 0xff8dc77bu
#define NDS_AUDIO_BGM_YOSTER_PACKET_COUNT 80u
#define NDS_AUDIO_BGM_YOSTER_LOOP_PACKET 10u
#define NDS_AUDIO_BGM_YOSTER_LOOP_RECORD 78432u
#define NDS_AUDIO_BGM_WIN_MARIO_STREAM_BYTES 326800u
#define NDS_AUDIO_BGM_WIN_MARIO_STREAM_SHA256_LO 0xca3f0a9bu
#define NDS_AUDIO_BGM_WIN_MARIO_ASSET_BYTES 81860u
#define NDS_AUDIO_BGM_WIN_MARIO_ASSET_SHA256_LO 0xbfd3eebbu
#define NDS_AUDIO_BGM_WIN_MARIO_PACKET_COUNT 10u
#define NDS_AUDIO_BGM_WIN_FOX_STREAM_BYTES 291154u
#define NDS_AUDIO_BGM_WIN_FOX_STREAM_SHA256_LO 0x65075ffbu
#define NDS_AUDIO_BGM_WIN_FOX_ASSET_BYTES 72940u
#define NDS_AUDIO_BGM_WIN_FOX_ASSET_SHA256_LO 0xe9e3f999u
#define NDS_AUDIO_BGM_WIN_FOX_PACKET_COUNT 9u
/* P2-1L bug (b1)+(b2). Same regenerations as Pupupu above -- loop_start
 * unchanged both times (proven no-op), only the rendered content and
 * (in b1) the stream truncation point changed. */
#define NDS_AUDIO_BGM_RESULTS_STREAM_BYTES 1583786u
#define NDS_AUDIO_BGM_RESULTS_LOOP_START_BYTES 34912u
#define NDS_AUDIO_BGM_RESULTS_STREAM_SHA256_LO 0xadc651d4u
#define NDS_AUDIO_BGM_RESULTS_ASSET_BYTES 396588u
#define NDS_AUDIO_BGM_RESULTS_ASSET_SHA256_LO 0x6ba054c1u
#define NDS_AUDIO_BGM_RESULTS_PACKET_COUNT 50u
#define NDS_AUDIO_BGM_RESULTS_LOOP_PACKET 2u
#define NDS_AUDIO_BGM_RESULTS_LOOP_RECORD 8792u
/* P2-1d-1. Rendered through scripts/sfx/bgm/render-audio-bgm-pupupu.py
 * --sequence-index 44, which is the source's own S1_music_sbk sequence index
 * for nSYAudioBGMModeSelect -- exactly the invocation the four tracks above
 * use, and the same script (its name is historical, from when Pupupu was the
 * only track). All values read off the rendered artifact and its own JSON
 * metadata, never invented: check-audio-bgm-derived-assets.ps1 re-derives
 * every one of them from the same two files.
 *
 * P2-1L bug (b1), 2026-08-19: LOOP_START_BYTES moved from 477382 to
 * 2303930 (10.8s -> 52.2s into the stream). The old value came from an
 * unconditional max() over EVERY channel's raw CSEQ loop-marker tick;
 * Mode Select has 3 channels sharing a 7680-tick loop period and 4
 * outlier channels (two carrying 1-2 notes total) with four different,
 * much longer periods, and the longest outlier dominated the max(),
 * splicing a loud, musically unrelated moment straight onto dead
 * silence every loop -- measured offline as "ends, then begins again".
 * The fix (collect_loop_metadata() in the render script) anchors on the
 * majority-period channels' own latest loop entry instead, which also
 * moved the loop to 12.8s of tail material rather than the old 53.3s of
 * cross-channel-incoherent middle. See the render script's
 * collect_loop_metadata() docstring for the full mechanism.
 *
 * P2-1L bug (b2): wavetable-loop + ADSR-envelope render fix, same as
 * Pupupu above -- loop_start/loop_end/packet layout unchanged this time,
 * only the rendered content. */
#define NDS_AUDIO_BGM_MODE_SELECT_STREAM_BYTES 2868410u
#define NDS_AUDIO_BGM_MODE_SELECT_LOOP_START_BYTES 2303930u
#define NDS_AUDIO_BGM_MODE_SELECT_STREAM_SHA256_LO 0x1d34cae1u
#define NDS_AUDIO_BGM_MODE_SELECT_ASSET_BYTES 718212u
#define NDS_AUDIO_BGM_MODE_SELECT_ASSET_SHA256_LO 0x8c7ac2c6u
#define NDS_AUDIO_BGM_MODE_SELECT_PACKET_COUNT 89u
#define NDS_AUDIO_BGM_MODE_SELECT_LOOP_PACKET 71u
#define NDS_AUDIO_BGM_MODE_SELECT_LOOP_RECORD 576876u
/* P2-1e-1. Rendered through scripts/sfx/bgm/render-audio-bgm-pupupu.py
 * --sequence-index 10, the source's own S1_music_sbk sequence index for
 * nSYAudioBGMBattleSelect -- the same script and invocation shape as the
 * five tracks above. All values read off the rendered artifact and its own
 * JSON metadata, never invented: check-audio-bgm-derived-assets.ps1
 * re-derives every one of them from the same two files.
 *
 * P2-1L bug (b1), 2026-08-19: LOOP_START_BYTES is unchanged (92456) --
 * every channel already agrees on one shared 15360-tick loop period, so
 * the old max()/max() reading was already correct. What was wrong is
 * STREAM_BYTES: the old render appended a flat, content-independent
 * ~1 second of trailing silence after the last note, and that pad sat
 * INSIDE the loop region (measured offline: RMS 0.0 in the 10 ms before
 * the wrap, RMS 691 right after) -- audible as "ends, then begins
 * again" on this track's short ~13 s loop even though the loop point
 * itself was fine. The regenerated stream truncates at the loop-period
 * boundary instead.
 *
 * P2-1L bug (b2), 2026-08-19: the owner's DS.wav re-recording still had
 * a quiet patch and sounded legato against the n64.wav reference.
 * Located the quiet patch by cross-correlating DS.wav against our own
 * decoded container (0.91 match at a +1.48 s offset -- the recording's
 * own lead-in) to map its RMS dip onto container samples 280718-313967
 * exactly: channel 14's one long sustained note (program 18, note 101),
 * whose wavetable has an authored ALADPCMloop (start=15367 end=26688
 * count=0xFFFFFFFF, i.e. loop forever) that decode_wave() was not
 * honoring, so the note ran out of source samples at 13958 of its
 * 33249-sample duration and rendered silence for the remaining ~0.87 s.
 * Same render fix as Pupupu above also replaced the flat release tail
 * with this bank's authored ALEnvelope releases (this track's are
 * mostly 25-30 ms, some instruments carry multi-hundred-ms decays to
 * decayVolume=0 -- a natural fade, not a cliff). loop_start/loop_end/
 * packet layout unchanged. */
#define NDS_AUDIO_BGM_BATTLE_SELECT_STREAM_BYTES 628352u
#define NDS_AUDIO_BGM_BATTLE_SELECT_LOOP_START_BYTES 92456u
#define NDS_AUDIO_BGM_BATTLE_SELECT_STREAM_SHA256_LO 0x546a98c4u
#define NDS_AUDIO_BGM_BATTLE_SELECT_ASSET_BYTES 157372u
#define NDS_AUDIO_BGM_BATTLE_SELECT_ASSET_SHA256_LO 0xb38a7cffu
#define NDS_AUDIO_BGM_BATTLE_SELECT_PACKET_COUNT 20u
#define NDS_AUDIO_BGM_BATTLE_SELECT_LOOP_PACKET 3u
#define NDS_AUDIO_BGM_BATTLE_SELECT_LOOP_RECORD 23192u
/* Retain the first stream's names for older Boundary diagnostics. */
#define NDS_AUDIO_BGM_STREAM_BYTES NDS_AUDIO_BGM_PUPUPU_STREAM_BYTES
#define NDS_AUDIO_BGM_STREAM_SHA256_LO NDS_AUDIO_BGM_PUPUPU_STREAM_SHA256_LO
#define NDS_AUDIO_BGM_CONTAINER_MAGIC 0x31414742u /* BGA1 */
#define NDS_AUDIO_BGM_CONTAINER_VERSION 1u
#define NDS_AUDIO_BGM_CONTAINER_HEADER_BYTES 40u
#define NDS_AUDIO_BGM_PACKET_HEADER_BYTES 8u
#define NDS_AUDIO_BGM_PACKET_SAMPLES 16384u
#define NDS_AUDIO_BGM_PACKET_BYTES 8196u
#define NDS_AUDIO_BGM_BUFFER_COUNT 2u
#define NDS_AUDIO_BGM_RESIDENT_BYTES \
    (NDS_AUDIO_BGM_BUFFER_COUNT * NDS_AUDIO_BGM_PACKET_BYTES)
#define NDS_AUDIO_BGM_BYTES_PER_SECOND (NDS_AUDIO_BGM_SAMPLE_RATE * 2u)
#define NDS_AUDIO_BGM_TRACK_FRAMES 3928u
#define NDS_AUDIO_BGM_RATE_GUARD_FRAMES 3200u
#define NDS_AUDIO_BGM_RESULTS_FAST_UPDATE_MAX 600u

void ndsAudioBgmDiagnosticsReset(void);
void ndsAudioBgmUpdate(void);
void ndsAudioBgmStopAll(void);
void ndsAudioBgmSuspendForBlockingLoad(void);
void ndsAudioBgmResumeAfterBlockingLoad(void);
void ndsAudioBgmPlay(s32 player, s32 bgm_id);
s32 ndsAudioBgmCheckPlaying(s32 player);
s32 ndsAudioBgmIsPlaying(void);
void ndsAudioBgmSetVolume(s32 player, u32 vol);

extern volatile u32 gNdsAudioBgmResult;
extern volatile u32 gNdsAudioBgmMask;
extern volatile u32 gNdsAudioBgmPlaying;
extern volatile u32 gNdsAudioBgmTrackID;
extern volatile u32 gNdsAudioBgmVolume;
extern volatile u32 gNdsAudioBgmPlayCalls;
extern volatile u32 gNdsAudioBgmStopCalls;
extern volatile u32 gNdsAudioBgmCheckCalls;
extern volatile u32 gNdsAudioBgmSetVolumeCalls;
extern volatile u32 gNdsAudioBgmOpenFailCount;
extern volatile u32 gNdsAudioBgmReadFailCount;
extern volatile u32 gNdsAudioBgmUnsupportedTrackCount;
extern volatile u32 gNdsAudioBgmReadBytes;
extern volatile u32 gNdsAudioBgmResidentBytes;
extern volatile u32 gNdsAudioBgmChunkBytes;
extern volatile u32 gNdsAudioBgmChunkPlayCount;
extern volatile u32 gNdsAudioBgmStoppedOnTeardown;
extern volatile u32 gNdsAudioBgmElapsedFrames;
extern volatile u32 gNdsAudioBgmStreamedBytes;
extern volatile u32 gNdsAudioBgmStreamBytesPerSecond;
extern volatile u32 gNdsAudioBgmExpectedBytesPerSecond;
extern volatile u32 gNdsAudioBgmLoopCount;
extern volatile u32 gNdsAudioBgmRefillCount;
#if NDS_RENDERER_PROFILE_LEVEL >= 1
extern volatile u32 gNdsAudioBgmRefillTicksLast;
extern volatile u32 gNdsAudioBgmRefillTicksMax;
#endif
extern volatile u32 gNdsAudioBgmFalsifierOff;
/* Slice 48 route. Scheduler priority of the refill worker; MAIN_THREAD_PRIO + 1
 * (below main, refills in the VBlank idle) ships, 27 restores the preempting
 * arm for a same-binary A/B. See nds_audio_bgm.c for why this is the tail. */
extern volatile u32 gNdsAudioBgmWorkerPrio;
extern volatile u32 gNdsAudioBgmWorkerRunPrio;
extern volatile u32 gNdsAudioBgmWorkerPrioApplied;
extern volatile u32 gNdsAudioBgmPlaybackPositionBytes;
extern volatile u32 gNdsAudioBgmWritePositionBytes;
extern volatile u32 gNdsAudioBgmPlaybackHalf;
extern volatile u32 gNdsAudioBgmWriteHalf;
extern volatile u32 gNdsAudioBgmUnsafeWriteCount;
extern volatile u32 gNdsAudioBgmTimerTicks;
extern volatile u32 gNdsAudioBgmPlaybackBytes;
extern volatile u32 gNdsAudioBgmPlaybackLoopCount;
extern volatile u32 gNdsAudioBgmOverrunCount;
extern volatile u32 gNdsAudioBgmStreamBytes;
extern volatile u32 gNdsAudioBgmLoopStartBytes;
extern volatile u32 gNdsAudioBgmIsLooping;
extern volatile u32 gNdsAudioBgmPupupuPlayCount;
extern volatile u32 gNdsAudioBgmWinMarioPlayCount;
extern volatile u32 gNdsAudioBgmWinFoxPlayCount;
extern volatile u32 gNdsAudioBgmResultsPlayCount;
extern volatile u32 gNdsAudioBgmModeSelectPlayCount;
extern volatile u32 gNdsAudioBgmBattleSelectPlayCount;
extern volatile u32 gNdsAudioBgmNaturalStopCount;
extern volatile u32 gNdsAudioBgmLastNaturalStopTrackID;
extern volatile u32 gNdsAudioBgmPostNaturalTransitionCount;
extern volatile u32 gNdsAudioBgmPostNaturalTransitionFromTrackID;
extern volatile u32 gNdsAudioBgmPostNaturalTransitionToTrackID;
extern volatile u32 gNdsAudioBgmTrackSwitchCount;
extern volatile u32 gNdsAudioBgmFinitePaddingBytes;
extern volatile u32 gNdsAudioBgmFileOpen;
extern volatile u32 gNdsAudioBgmSoundActive;
extern volatile u32 gNdsAudioBgmPlayFailCount;
extern volatile u32 gNdsAudioBgmHeaderFailCount;
extern volatile u32 gNdsAudioBgmPacketFailCount;
extern volatile u32 gNdsAudioBgmPreparedCount;
extern volatile u32 gNdsAudioBgmSeamStartCount;
extern volatile u32 gNdsAudioBgmSeamMissCount;
extern volatile u32 gNdsAudioBgmTimerEventDropCount;
extern volatile u32 gNdsAudioBgmWorkerWakeCount;
extern volatile u32 gNdsAudioBgmErrorStopCount;
extern volatile u32 gNdsAudioBgmBlockingSuspendCount;
extern volatile u32 gNdsAudioBgmBlockingResumeCount;
extern volatile u32 gNdsAudioBgmErrorCleanupFailCount;

#endif
