/* Generated by scripts/generate_pupupu_water_tiled_aot.py. */
/* Host-exact M4 packet; device draw integration remains unproven. */
#ifndef SSB64_NDS_PUPUPU_WATER_TILED_AOT_H
#define SSB64_NDS_PUPUPU_WATER_TILED_AOT_H

#include <PR/ultratypes.h>

#define NDS_PUPUPU_WATER_TILED_CYCLE_FRAMES 216u
#define NDS_PUPUPU_WATER_TILED_OWNER_COUNT 2u
#define NDS_PUPUPU_WATER_TILED_TILE_WIDTH 32u
#define NDS_PUPUPU_WATER_TILED_TILE_HEIGHT 8u
#define NDS_PUPUPU_WATER_TILED_MASKED_TILE_COUNT 572u
#define NDS_PUPUPU_WATER_TILED_PRIMARY_TILE_FIRST 0u
#define NDS_PUPUPU_WATER_TILED_PRIMARY_TILE_COUNT 512u
#define NDS_PUPUPU_WATER_TILED_PRIMARY_TILE_CAPACITY 512u
#define NDS_PUPUPU_WATER_TILED_PRIMARY_ATLAS_WIDTH 512u
#define NDS_PUPUPU_WATER_TILED_PRIMARY_ATLAS_HEIGHT 256u
#define NDS_PUPUPU_WATER_TILED_PRIMARY_ATLAS_BYTES 131072u
#define NDS_PUPUPU_WATER_TILED_SECONDARY_TILE_FIRST 512u
#define NDS_PUPUPU_WATER_TILED_SECONDARY_TILE_COUNT 60u
#define NDS_PUPUPU_WATER_TILED_SECONDARY_TILE_CAPACITY 64u
#define NDS_PUPUPU_WATER_TILED_SECONDARY_ATLAS_WIDTH 256u
#define NDS_PUPUPU_WATER_TILED_SECONDARY_ATLAS_HEIGHT 64u
#define NDS_PUPUPU_WATER_TILED_SECONDARY_ATLAS_BYTES 16384u
#define NDS_PUPUPU_WATER_TILED_FRACTION_MIN 114u
#define NDS_PUPUPU_WATER_TILED_FRACTION_MAX 153u
#define NDS_PUPUPU_WATER_TILED_FRACTION_COUNT 40u
#define NDS_PUPUPU_WATER_TILED_PALETTE_ENTRIES 256u
#define NDS_PUPUPU_WATER_TILED_PALETTE_BYTES 20480u
#define NDS_PUPUPU_WATER_TILED_PRIMARY_ATLAS_OFFSET 0u
#define NDS_PUPUPU_WATER_TILED_SECONDARY_ATLAS_OFFSET 131072u
#define NDS_PUPUPU_WATER_TILED_PALETTES_OFFSET 147456u
#define NDS_PUPUPU_WATER_TILED_RESIDENCY_PAYLOAD_BYTES 167936u
#define NDS_PUPUPU_WATER_TILED_RESIDENCY_PAYLOAD_PATH "nitro:/renderer/pupupu_water_tiled_aot.bin"
#define NDS_PUPUPU_WATER_TILED_STATE_TABLE_BYTES 6032u
#define NDS_PUPUPU_WATER_TILED_PLAN_CELL_COUNT 68u
#define NDS_PUPUPU_WATER_TILED_PLAN_VERTEX_COUNT 274u
#define NDS_PUPUPU_WATER_TILED_LOGICAL_CELL_SUBMISSIONS 68u
#define NDS_PUPUPU_WATER_TILED_TOTAL_TRIANGLES 138u
#define NDS_PUPUPU_WATER_TILED_GX_BEGIN_BATCHES_MIN 1u
#define NDS_PUPUPU_WATER_TILED_GX_BEGIN_BATCHES_MAX 2u
#define NDS_PUPUPU_WATER_TILED_SECONDARY_FRAMES 48u
#define NDS_PUPUPU_WATER_TILED_EMITTED_VERTICES 414u
#define NDS_PUPUPU_WATER_TILED_VERTEX_ATTRIBUTE_WRITES 1242u
#define NDS_PUPUPU_WATER_TILED_DEVICE_TICK_BUDGET 40000u
#define NDS_PUPUPU_WATER_TILED_DEVICE_TICK_REJECT 50000u
#define NDS_PUPUPU_WATER_TILED_MIN_NET_OWNER_DRAW_SAVING 100000u

#define NDS_PUPUPU_WATER_TILED_PRIMARY_ATLAS_SHA256 "ecc0b1b90d5f3f573f1658444a8d68fd308b058b354daf074b5c0e35edf49c8f"
#define NDS_PUPUPU_WATER_TILED_CLIPPED_ORACLE_SHA256 "7e3989a8ced63e5a2a7b3534d686b189a624acfae73fc7eac98ea292da3657ec"
#define NDS_PUPUPU_WATER_TILED_SECONDARY_ATLAS_SHA256 "5db8bbbbc30b264fbcf43acaf387924742e50e48a41c1a6d12560c88e91eaf25"
#define NDS_PUPUPU_WATER_TILED_PALETTES_SHA256 "b55d60bedc30df55fc92197b839e97c1ce2dc733f7055ea9e824ddea095d6d47"
#define NDS_PUPUPU_WATER_TILED_RESIDENCY_PAYLOAD_SHA256 "af052624915c87205bfbff8e0db1e3365d3d7a30758fba74b32fdaf39c364982"
#define NDS_PUPUPU_WATER_TILED_STATE_TABLES_SHA256 "eed2d0e6c4bddaeec60f6399b3937f7a1ecc3d38e7b94b0e5968a2f4d4f07281"
#define NDS_PUPUPU_WATER_TILED_GEOMETRY_PLAN_SHA256 "cbe6f7546a0ea6c13e3c28fd055634d4170d0f3dc6df48f3a50c610ae91c483b"
#define NDS_PUPUPU_WATER_TILED_COMBINED_SHA256 "a5dce81ca54ff6d67ecf327640b43c006201e80d28840f363b07df38fd028745"

enum NDSPupupuWaterTiledOwner {
    NDS_PUPUPU_WATER_TILED_OWNER_LARGE = 0,
    NDS_PUPUPU_WATER_TILED_OWNER_SMALL = 1
};

enum NDSPupupuWaterTiledResult {
    NDS_PUPUPU_WATER_TILED_INVALID = -1,
    NDS_PUPUPU_WATER_TILED_OK = 1
};

/* Texture-domain polygon vertices are clockwise fans. x/z are layer-parent
 * stage coordinates in 20.12 after applying each source pond DObj's exact
 * static translation; this permits one shared-matrix batch for both owners.
 * s/t are logical pond texels in 16.16. Device integration must still prove
 * this clipping plan and shared parent matrix against the live source mesh. */
typedef struct NDSPupupuWaterTiledPlanVertex {
    s32 x_q12;
    s32 z_q12;
    s32 s_q16;
    s32 t_q16;
} NDSPupupuWaterTiledPlanVertex;

typedef struct NDSPupupuWaterTiledPlanCell {
    u16 first_vertex;
    u8 owner;
    u8 cell_index;
    u8 cell_x;
    u8 cell_y;
    u8 vertex_count;
    u8 triangle_count;
} NDSPupupuWaterTiledPlanCell;

typedef struct NDSPupupuWaterTiledAssets {
    const NDSPupupuWaterTiledPlanCell *plan_cells;
    const NDSPupupuWaterTiledPlanVertex *plan_vertices;
    u16 plan_cell_count;
    u16 plan_vertex_count;
} NDSPupupuWaterTiledAssets;

typedef struct NDSPupupuWaterTiledFrame {
    const u16 *tile_ids;
    u16 state_cell_count;
    u8 state_columns;
    u8 state_rows;
    u8 state;
    u8 palette_index;
    u8 reserved[2];
} NDSPupupuWaterTiledFrame;

/* Atlas contract:
 * - IDs 0..511 address the 512x256 primary GL_RGB256 atlas in 16 columns.
 * - IDs 512..571 address the 256x64 secondary GL_RGB256 atlas in 8 columns
 *   after subtracting NDS_PUPUPU_WATER_TILED_SECONDARY_TILE_FIRST.
 * - each texel is (CI4_0 << 4) | CI4_1 when source-visible, otherwise zero.
 *   Both atlases require GL_TEXTURE_COLOR0_TRANSPARENT and TEXGEN_OFF.
 * - the NitroFS payload stores primary atlas, secondary atlas, then all 40
 *   RGB555 palettes. It is loaded once before GO; gameplay only binds the
 *   resident atlas and frame.palette_index.
 * - cell-local atlas coordinates subtract cell_x * 32 and cell_y * 8 from
 *   each plan vertex's logical s/t before adding the selected tile origin. */

/* The caller supplies the live source material fraction and the corresponding
 * 0..215 material-cycle frame. No upload, allocation, I/O, or conversion is
 * performed by these borrowed immutable views. Each plan cell's cell_index
 * addresses the corresponding 64-entry large or 8-entry small state array.
 * Expand every clockwise fan to GL_TRIANGLES and group by atlas: one primary
 * BEGIN plus one secondary BEGIN only when referenced. The one semantic pass
 * is 68 cells, 138 triangles, 414 vertices, and 1,242 TEXCOORD/VTX16 writes. */
s32 ndsPupupuWaterTiledGetAssets(NDSPupupuWaterTiledAssets *out_assets);
s32 ndsPupupuWaterTiledGetFrame(
    u32 owner, u32 cycle_frame, u32 source_fraction,
    NDSPupupuWaterTiledFrame *out_frame);

#endif
