/* Generated by scripts/generate_pupupu_water_tiled_aot.py. */
/* Host-exact M4 packet only; device integration remains unproven. */
#ifndef SSB64_NDS_PUPUPU_WATER_TILED_AOT_H
#define SSB64_NDS_PUPUPU_WATER_TILED_AOT_H

#include <PR/ultratypes.h>

#define NDS_PUPUPU_WATER_TILED_CYCLE_FRAMES 216u
#define NDS_PUPUPU_WATER_TILED_OWNER_COUNT 2u
#define NDS_PUPUPU_WATER_TILED_PAIR_TILE_WIDTH 32u
#define NDS_PUPUPU_WATER_TILED_PAIR_TILE_HEIGHT 8u
#define NDS_PUPUPU_WATER_TILED_PAIR_TILE_COUNT 494u
#define NDS_PUPUPU_WATER_TILED_VISIBILITY_TILE_COUNT 243u
#define NDS_PUPUPU_WATER_TILED_PAIR_ATLAS_WIDTH 512u
#define NDS_PUPUPU_WATER_TILED_PAIR_ATLAS_HEIGHT 256u
#define NDS_PUPUPU_WATER_TILED_PAIR_ATLAS_BYTES 131072u
#define NDS_PUPUPU_WATER_TILED_VISIBILITY_ATLAS_WIDTH 256u
#define NDS_PUPUPU_WATER_TILED_VISIBILITY_ATLAS_HEIGHT 256u
#define NDS_PUPUPU_WATER_TILED_VISIBILITY_ATLAS_BYTES 16384u
#define NDS_PUPUPU_WATER_TILED_FRACTION_MIN 114u
#define NDS_PUPUPU_WATER_TILED_FRACTION_MAX 153u
#define NDS_PUPUPU_WATER_TILED_FRACTION_COUNT 40u
#define NDS_PUPUPU_WATER_TILED_PALETTE_ENTRIES 256u
#define NDS_PUPUPU_WATER_TILED_PALETTE_BYTES 20480u
#define NDS_PUPUPU_WATER_TILED_STATE_TABLE_BYTES 8544u
#define NDS_PUPUPU_WATER_TILED_PLAN_CELL_COUNT 68u
#define NDS_PUPUPU_WATER_TILED_PLAN_VERTEX_COUNT 274u
#define NDS_PUPUPU_WATER_TILED_LOGICAL_CELLS_PER_PASS 68u
#define NDS_PUPUPU_WATER_TILED_TRIANGLES_PER_PASS 138u
#define NDS_PUPUPU_WATER_TILED_LOGICAL_CELL_SUBMISSIONS 136u
#define NDS_PUPUPU_WATER_TILED_TOTAL_TRIANGLES 276u
#define NDS_PUPUPU_WATER_TILED_PLANNED_GX_BEGIN_BATCHES 2u
#define NDS_PUPUPU_WATER_TILED_EMITTED_VERTICES 828u
#define NDS_PUPUPU_WATER_TILED_VERTEX_ATTRIBUTE_WRITES 2484u
#define NDS_PUPUPU_WATER_TILED_DEVICE_TICK_BUDGET 40000u
#define NDS_PUPUPU_WATER_TILED_DEVICE_TICK_REJECT 50000u
#define NDS_PUPUPU_WATER_TILED_MIN_NET_OWNER_DRAW_SAVING 100000u

#define NDS_PUPUPU_WATER_TILED_PAIR_ATLAS_SHA256 "203e36a96c8125df5204baf02f271a07e0248b8aa51a50bff32715ccfa117f9f"
#define NDS_PUPUPU_WATER_TILED_CLIPPED_ORACLE_SHA256 "7e3989a8ced63e5a2a7b3534d686b189a624acfae73fc7eac98ea292da3657ec"
#define NDS_PUPUPU_WATER_TILED_VISIBILITY_ATLAS_SHA256 "80e31c49f39e1ca704fb83e3b9d403f19cd6e7afb1491308b26321a276fcba44"
#define NDS_PUPUPU_WATER_TILED_PALETTES_SHA256 "b55d60bedc30df55fc92197b839e97c1ce2dc733f7055ea9e824ddea095d6d47"
#define NDS_PUPUPU_WATER_TILED_STATE_TABLES_SHA256 "6405e1a67c07b88efe90885d0b746eb5635de4bfcda7ad331aa79f66bdad2d4e"
#define NDS_PUPUPU_WATER_TILED_GEOMETRY_PLAN_SHA256 "cbe6f7546a0ea6c13e3c28fd055634d4170d0f3dc6df48f3a50c610ae91c483b"
#define NDS_PUPUPU_WATER_TILED_COMBINED_SHA256 "36fbc1c7f4d08f178ac7564b8d5c9c3e3f1dbc2ee1b0f7a60e09ab096b3b2018"

enum NDSPupupuWaterTiledOwner {
    NDS_PUPUPU_WATER_TILED_OWNER_LARGE = 0,
    NDS_PUPUPU_WATER_TILED_OWNER_SMALL = 1
};

enum NDSPupupuWaterTiledResult {
    NDS_PUPUPU_WATER_TILED_INVALID = -1,
    NDS_PUPUPU_WATER_TILED_OK = 1
};

/* Texture-domain polygon vertices are clockwise fans. x/z are layer-parent
 * stage coordinates in 20.12 after applying each source pond DObj's exact
 * static translation; this permits one shared-matrix batch for both owners.
 * s/t are logical pond texels in 16.16. Device integration must still prove
 * this clipping plan and shared parent matrix against the live source mesh. */
typedef struct NDSPupupuWaterTiledPlanVertex {
    s32 x_q12;
    s32 z_q12;
    s32 s_q16;
    s32 t_q16;
} NDSPupupuWaterTiledPlanVertex;

typedef struct NDSPupupuWaterTiledPlanCell {
    u16 first_vertex;
    u8 owner;
    u8 cell_index;
    u8 cell_x;
    u8 cell_y;
    u8 vertex_count;
    u8 triangle_count;
} NDSPupupuWaterTiledPlanCell;

typedef struct NDSPupupuWaterTiledAssets {
    const u8 *pair_atlas;
    const u8 *visibility_atlas;
    const u16 *pair_palettes;
    const NDSPupupuWaterTiledPlanCell *plan_cells;
    const NDSPupupuWaterTiledPlanVertex *plan_vertices;
    u16 plan_cell_count;
    u16 plan_vertex_count;
} NDSPupupuWaterTiledAssets;

typedef struct NDSPupupuWaterTiledFrame {
    const u16 *pair_tile_ids;
    const u8 *visibility_tile_ids;
    const u16 *pair_palette;
    u16 state_cell_count;
    u8 state_columns;
    u8 state_rows;
    u8 pair_state;
    u8 visibility_state;
    u8 palette_index;
    u8 reserved;
} NDSPupupuWaterTiledFrame;

/* Atlas contract:
 * - pair_atlas is one 512x256 GL_RGB256 image. A u16 pair tile ID selects
 *   (id % 16) * 32, (id / 16) * 8. Its texel is (CI4_0 << 4) | CI4_1.
 * - visibility_atlas is one 256x256 GL_RGB4 image, four low-to-high 2-bit
 *   indices per byte. A u8 tile ID selects (id % 8) * 32, (id / 8) * 8;
 *   every texel is exactly 0 or 1, with texture index zero transparent.
 * - pair_palette is the 256-entry RGB555 palette selected by live fraction.
 * - cell-local atlas coordinates subtract cell_x * 32 and cell_y * 8 from
 *   each plan vertex's logical s/t before adding the selected tile origin. */

/* The caller supplies the live source material fraction and the corresponding
 * 0..215 material-cycle frame. No upload, allocation, I/O, or conversion is
 * performed by these borrowed immutable views. The intended device path is:
 * RGB4 visibility/depth pass, then RGB256 pair-color pass at equal depth.
 * Each plan cell's cell_index addresses the corresponding 64-entry large or
 * 8-entry small state arrays; state_cell_count is that rectangular grid size,
 * not the number of occupied geometry cells. Expand every clockwise cell fan
 * to GL_TRIANGLES inside one BEGIN per pass: 136 logical cell submissions are
 * two GX primitive batches, 276 triangles, 828 vertices, and 2,484 texture /
 * VTX16 register writes. Device timing and depth behavior remain keep gates. */
s32 ndsPupupuWaterTiledGetAssets(NDSPupupuWaterTiledAssets *out_assets);
s32 ndsPupupuWaterTiledGetFrame(
    u32 owner, u32 cycle_frame, u32 source_fraction,
    NDSPupupuWaterTiledFrame *out_frame);

#endif
