#include "nds_renderer_preamble.c"
#include "nds_renderer_assets.c"
#include "nds_renderer_dl_core.c"
#include "nds_renderer_textures_effects.c"
#include "nds_renderer_native_common.c"
#include "nds_renderer_native_owners.c"
#include "nds_renderer_native_fighter_production.c"
#include "nds_renderer_dispatch_profile.c"
