#include <nds.h>
#include <math.h>
#include <string.h>

#include <nds/nds_native_wallpaper.h>
#include <nds/nds_platform.h>
#include <nds/nds_reloc_assets.h>
#include <nds/nds_r2_hwmath_unit.h>
#include <nds/nds_r2_collision_mtx.h>
#include <nds/nds_fixed_convert.h>

#include "generated/native_wallpapers.generated.inc"

/* Only one BG2 image is resident. Row staging is main RAM and all VRAM
 * stores are halfwords; fread must never write directly to VRAM. */
static u16 sWallpaperRow[240] __attribute__((aligned(32)));
static const NDSNativeWallpaper *sWallpaperAsset;
static u32 sWallpaperEpoch;
static u16 sWallpaperPalette[16];

volatile u32 gNdsNativeWallpaperLoadCount;
volatile u32 gNdsNativeWallpaperReuseCount;
volatile u32 gNdsNativeWallpaperReadFailureCount;

/* P2-4 stage-background proof. These are shipping-path observations, not
 * selectors: the stage owner writes the source-derived transform before the
 * existing BG2 affine queue consumes it. They make one captured frame directly
 * comparable with grwallpaper.c without retaining an SObj or N64 renderer. */
__attribute__((used)) volatile u32 gNdsNativeBattleWallpaperDrawCount;
__attribute__((used)) volatile u32 gNdsNativeBattleWallpaperFailureCount;
__attribute__((used)) volatile u32 gNdsNativeBattleWallpaperDeferCount;
__attribute__((used)) volatile u32 gNdsNativeBattleWallpaperGKind = 0xffffffffu;
__attribute__((used)) volatile s32 gNdsNativeBattleWallpaperOriginX;
__attribute__((used)) volatile s32 gNdsNativeBattleWallpaperOriginY;
__attribute__((used)) volatile u32 gNdsNativeBattleWallpaperScaleQ16;
__attribute__((used)) volatile s32 gNdsNativeWallpaperAffinePa;
__attribute__((used)) volatile s32 gNdsNativeWallpaperAffinePd;
__attribute__((used)) volatile s32 gNdsNativeWallpaperAffineDx;
__attribute__((used)) volatile s32 gNdsNativeWallpaperAffineDy;

enum NDSNativeBattleWallpaperMotion
{
    NDS_NATIVE_BATTLE_WALLPAPER_COMMON = 0,
    NDS_NATIVE_BATTLE_WALLPAPER_SECTOR,
    NDS_NATIVE_BATTLE_WALLPAPER_STATIC,
    NDS_NATIVE_BATTLE_WALLPAPER_NONE
};

typedef struct NDSNativeBattleWallpaperBinding
{
    u32 asset_id;
    u32 bitmap_offset;
    u8 motion;
} NDSNativeBattleWallpaperBinding;

/* One shared binding table in BattleShip gr/grdef.h order. The asset identities
 * are the converted providers generated by generate_native_wallpapers.py. This
 * is data selection only; all stages share the same upload and affine owner. */
static const NDSNativeBattleWallpaperBinding sBattleWallpaperBindings[9] =
{
    { 0x5Au,    0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_COMMON }, /* Castle */
    { 0x10063u, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_SECTOR }, /* Sector */
    { 0x1005Cu, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_COMMON }, /* Jungle */
    { 0x10059u, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_COMMON }, /* Zebes */
    { 0x1005Fu, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_COMMON }, /* Hyrule */
    { 0x1005Du, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_STATIC }, /* Yoster */
    { 0u,       0u,       NDS_NATIVE_BATTLE_WALLPAPER_NONE },   /* Pupupu */
    { 0x1005Eu, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_COMMON }, /* Yamabuki */
    { 0x1005Bu, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_COMMON }  /* Inishie */
};

#define NDS_NATIVE_WALLPAPER_STRETCH_SHIFT 3u

static s32 ndsNativeWallpaperMul9Div8Signed(s32 value)
{
    u32 magnitude = (value < 0) ? (u32)(-value) : (u32)value;
    s32 scaled = (s32)(((magnitude << NDS_NATIVE_WALLPAPER_STRETCH_SHIFT) +
                        magnitude) >> NDS_NATIVE_WALLPAPER_STRETCH_SHIFT);

    return (value < 0) ? -scaled : scaled;
}

/* battleship_sys_utils.c: atan2 at Q30 on two integers of one scale. */
int64_t ndsUtilsAtan2Q30(int64_t y, int64_t x);

#define NDS_WALLPAPER_Q 12u
#define NDS_WALLPAPER_PI_Q30 INT64_C(3373259426)
/* 1.004 and 2.0 at Q16. */
#define NDS_WALLPAPER_SCALE_MIN_Q16 65798
#define NDS_WALLPAPER_SCALE_MAX_Q16 131072

/* 20000 / (mag + bias) at Q16 from a Q12 magnitude, clamped as the source. */
static s32 ndsWallpaperScaleQ16(s64 mag_q, s32 bias)
{
    const s64 den = mag_q + ((s64)bias << NDS_WALLPAPER_Q);
    s64 scale = (den > 0) ?
        ndsR2HwMathDivideFast((s64)20000 << (NDS_WALLPAPER_Q + 16u), den) :
        NDS_WALLPAPER_SCALE_MAX_Q16;

    if (scale < NDS_WALLPAPER_SCALE_MIN_Q16)
    {
        scale = NDS_WALLPAPER_SCALE_MIN_Q16;
    }
    else if (scale > NDS_WALLPAPER_SCALE_MAX_Q16)
    {
        scale = NDS_WALLPAPER_SCALE_MAX_Q16;
    }
    return (s32)scale;
}

/* grWallpaperCalcPersp (gr/grwallpaper.c:45) and grWallpaperSectorProcUpdate
 * in integers (P2-2p8, 2026-10-06; owner: "Software floating point should not
 * exist, fixed point only"). The eye-to-target offset enters at Q12, its
 * length is the math unit's square root, the two angles come from the
 * syUtilsArcTan2 kernel at Q30 and the scale and position leave at Q16:
 * the source's two square roots, two arctangents and ~40 float operations a
 * tick, twice a frame between the source SObj update and this owner. Every
 * branch and clamp is the source's, in its order. Render only. */
/* The last answer and its inputs' bits: the frame's present asks with the
 * same eye and target as the tick's SObj update before it. */
static u32 sNdsWallpaperPerspKey[7];
static s32 sNdsWallpaperPerspOut[3];
static u32 sNdsWallpaperPerspValid;

static s32 ndsWallpaperPerspCompute(u32 motion, const Vec3f *eye,
                                    const Vec3f *at, s32 *pos_x_q16,
                                    s32 *pos_y_q16, s32 *scale_q16);

s32 __attribute__((target("arm")))
ndsWallpaperPerspQ(u32 motion, const Vec3f *eye, const Vec3f *at,
                   s32 *pos_x_q16, s32 *pos_y_q16, s32 *scale_q16)
{
    u32 key[7];
    s32 ok;

    key[0] = motion;
    __builtin_memcpy(&key[1], eye, sizeof(Vec3f));
    __builtin_memcpy(&key[4], at, sizeof(Vec3f));
    if ((sNdsWallpaperPerspValid != 0u) &&
        (__builtin_memcmp(key, sNdsWallpaperPerspKey, sizeof(key)) == 0))
    {
        *pos_x_q16 = sNdsWallpaperPerspOut[0];
        *pos_y_q16 = sNdsWallpaperPerspOut[1];
        *scale_q16 = sNdsWallpaperPerspOut[2];
        return TRUE;
    }
    ok = ndsWallpaperPerspCompute(motion, eye, at, pos_x_q16, pos_y_q16,
                                  scale_q16);
    sNdsWallpaperPerspValid = (ok != FALSE) ? 1u : 0u;
    if (ok != FALSE)
    {
        __builtin_memcpy(sNdsWallpaperPerspKey, key, sizeof(key));
        sNdsWallpaperPerspOut[0] = *pos_x_q16;
        sNdsWallpaperPerspOut[1] = *pos_y_q16;
        sNdsWallpaperPerspOut[2] = *scale_q16;
    }
    return ok;
}

static s32 __attribute__((noinline, target("arm")))
ndsWallpaperPerspCompute(u32 motion, const Vec3f *eye, const Vec3f *at,
                         s32 *pos_x_q16, s32 *pos_y_q16, s32 *scale_q16)
{
    s32 dx;
    s32 dy;
    s32 dz;
    s64 mag;
    s32 scale;

    if (motion == NDS_NATIVE_BATTLE_WALLPAPER_STATIC)
    {
        *pos_x_q16 = 10 << 16;
        *pos_y_q16 = 10 << 16;
        *scale_q16 = 1 << 16;
        return TRUE;
    }
    dx = ndsF32ToFixed(eye->x, NDS_WALLPAPER_Q);
    dy = ndsF32ToFixed(eye->y, NDS_WALLPAPER_Q);
    dz = ndsF32ToFixed(eye->z, NDS_WALLPAPER_Q);
    {
        const s32 ax = ndsF32ToFixed(at->x, NDS_WALLPAPER_Q);
        const s32 ay = ndsF32ToFixed(at->y, NDS_WALLPAPER_Q);
        const s32 az = ndsF32ToFixed(at->z, NDS_WALLPAPER_Q);

        if ((dx == NDS_R2_COLLISION_F32_OVERFLOW) ||
            (dy == NDS_R2_COLLISION_F32_OVERFLOW) ||
            (dz == NDS_R2_COLLISION_F32_OVERFLOW) ||
            (ax == NDS_R2_COLLISION_F32_OVERFLOW) ||
            (ay == NDS_R2_COLLISION_F32_OVERFLOW) ||
            (az == NDS_R2_COLLISION_F32_OVERFLOW))
        {
            return FALSE;
        }
        dx -= ax;
        dy -= ay;
        dz -= az;
    }
    mag = (s64)ndsR2HwMathSqrt64Fast(((u64)((s64)dx * dx)) +
                                     ((u64)((s64)dy * dy)) +
                                     ((u64)((s64)dz * dz)));
    if (motion == NDS_NATIVE_BATTLE_WALLPAPER_SECTOR)
    {
        /* zoom = (scale - 1) * 0.5; pos = 10 - extent * zoom. */
        s32 zoom;

        scale = ndsWallpaperScaleQ16(mag, 10000);
        zoom = (scale - (1 << 16)) >> 1;
        *pos_x_q16 = (10 << 16) - (300 * zoom);
        *pos_y_q16 = (10 << 16) - (220 * zoom);
        *scale_q16 = scale;
        return TRUE;
    }
    if (motion == NDS_NATIVE_BATTLE_WALLPAPER_COMMON)
    {
        s64 angle_x = 0;
        s64 angle_y = 0;
        s32 width;
        s32 height;
        s32 pos_x;
        s32 pos_y;
        s32 minimum;

        if (dz >= 0)
        {
            angle_y = ndsUtilsAtan2Q30(dx, dz);
            angle_x = ndsUtilsAtan2Q30(dy, dz);
        }
        scale = ndsWallpaperScaleQ16(mag, 8000);
        width = 300 * scale;
        height = 220 * scale;
        /* (angle / pi) * extent - (extent - screen) * 0.5 */
        pos_x = (s32)ndsR2HwMathDivideFast(angle_y * width,
                                           NDS_WALLPAPER_PI_Q30) -
                ((width - (320 << 16)) >> 1);
        pos_y = (s32)ndsR2HwMathDivideFast(-angle_x * height,
                                           NDS_WALLPAPER_PI_Q30) -
                ((height - (240 << 16)) >> 1);
        if (pos_x > (10 << 16))
        {
            pos_x = 10 << 16;
        }
        else
        {
            minimum = (-width - (10 << 16)) + (320 << 16);
            if (pos_x < minimum)
            {
                pos_x = minimum;
            }
        }
        if (pos_y > (10 << 16))
        {
            pos_y = 10 << 16;
        }
        else
        {
            minimum = (-height - (10 << 16)) + (240 << 16);
            if (pos_y < minimum)
            {
                pos_y = minimum;
            }
        }
        *pos_x_q16 = pos_x;
        *pos_y_q16 = pos_y;
        *scale_q16 = scale;
        return TRUE;
    }
    return FALSE;
}

/* Native transcription of grWallpaperCalcPersp / grWallpaperSectorProcUpdate
 * plus grWallpaperMakeStatic. The final 9/8 centre stretch is the existing DS
 * overscan correction already used by the SObj preview path. */
static s32 ndsNativeBattleWallpaperTransform(
    const NDSNativeBattleWallpaperBinding *binding,
    f32 eye_x, f32 eye_y, f32 eye_z,
    f32 at_x, f32 at_y, f32 at_z,
    s32 *origin_x, s32 *origin_y, u32 *scale_q16)
{
    Vec3f eye;
    Vec3f at;
    s32 pos_x;
    s32 pos_y;
    s32 scale;

    if ((binding == NULL) || (origin_x == NULL) || (origin_y == NULL) ||
        (scale_q16 == NULL))
    {
        return FALSE;
    }
    eye.x = eye_x;
    eye.y = eye_y;
    eye.z = eye_z;
    at.x = at_x;
    at.y = at_y;
    at.z = at_z;
    if (ndsWallpaperPerspQ(binding->motion, &eye, &at, &pos_x, &pos_y,
                           &scale) == FALSE)
    {
        return FALSE;
    }
    if ((scale < (1 << 16)) || (scale > (2 << 16)))
    {
        return FALSE;
    }
    /* (s32)pos: the cast truncates toward zero. */
    *origin_x = (pos_x >= 0) ? (pos_x >> 16) : -((-pos_x) >> 16);
    *origin_y = (pos_y >= 0) ? (pos_y >> 16) : -((-pos_y) >> 16);
    *scale_q16 = (u32)scale;

    /* Existing port presentation law: compensate for N64 overscan while
     * preserving the source camera transform itself. */
    *origin_x = 160 + ndsNativeWallpaperMul9Div8Signed(*origin_x - 160);
    *origin_y = 120 + ndsNativeWallpaperMul9Div8Signed(*origin_y - 120);
    *scale_q16 += (*scale_q16 + 4u) >> NDS_NATIVE_WALLPAPER_STRETCH_SHIFT;
    return TRUE;
}

void ndsNativeWallpaperInvalidate(void)
{
    sWallpaperAsset = NULL;
    sWallpaperEpoch = 0u;
    (void)ndsPlatformQueueNativeWallpaperAffine(256, 256, 0, 0);
}

static s32 ndsNativeWallpaperUpload(const NDSNativeWallpaper *asset,
                                   u16 *dest, u32 pitch, const u16 *palette)
{
    NdsRelocAssetStream stream = { NULL };
    char path[96];
    u32 y;
    u32 bytes_per_row = asset->native_w * ((asset->format == 0u) ? 2u : 1u);
    const char prefix[] = "nitro:/wallpapers/";
    size_t name_bytes = strlen(asset->nitro_filename) + 1u;

    if (name_bytes > sizeof(path) - (sizeof(prefix) - 1u))
    {
        return FALSE;
    }
    memcpy(path, prefix, sizeof(prefix) - 1u);
    memcpy(path + sizeof(prefix) - 1u, asset->nitro_filename, name_bytes);
    if (ndsRelocAssetStreamOpen(&stream, path) == FALSE)
    {
        return FALSE;
    }
    dmaFillHalfWords(0x8000u, dest, 256u * 192u * sizeof(u16));
    for (y = 0u; y < asset->native_h; y++)
    {
        u32 x;
        if (ndsRelocAssetStreamRead(&stream, y * bytes_per_row,
                                    sWallpaperRow, bytes_per_row) == FALSE)
        {
            ndsRelocAssetStreamClose(&stream);
            return FALSE;
        }
        if (asset->format == 1u)
        {
            /* The converted file contains intensity bytes, not source I4
             * strips. Expand backwards so input and output share one row. */
            const u8 *indices = (const u8 *)sWallpaperRow;
            for (x = asset->native_w; x != 0u; x--)
            {
                /* A valid intensity is a replicated nibble (0x00, 0x11 ..
                 * 0xff): exactly the bytes with x % 17 == 0, and x / 17 is
                 * then the nibble. -Os made both a libcall per pixel (~1M
                 * ticks for the Results wallpaper; results-pacing report C). */
                u32 intensity = indices[x - 1u];
                if ((intensity >> 4) != (intensity & 15u))
                {
                    ndsRelocAssetStreamClose(&stream);
                    return FALSE;
                }
                sWallpaperRow[x - 1u] = palette[intensity & 15u];
            }
        }
        for (x = 0u; x < asset->native_w; x++)
        {
            if ((sWallpaperRow[x] & 0x8000u) == 0u)
            {
                ndsRelocAssetStreamClose(&stream);
                return FALSE;
            }
            ((volatile u16 *)dest)[y * pitch + x] = sWallpaperRow[x];
        }
    }
    ndsRelocAssetStreamClose(&stream);
    return TRUE;
}

/* Converted texels already include the 4/5 source-to-DS scale. For battle,
 * BG source x = (screen x - source_origin * 4/5) / source_scale.
 * Match pixel centres when converting that inverse transform to Q8.
 * Results uses its existing (10,10)-(310,230) full-screen crop. */
static s32 ndsNativeWallpaperAffine(const NDSNativeWallpaper *asset,
                                   s32 origin_x, s32 origin_y,
                                   u32 scale_x_q16, u32 scale_y_q16,
                                   s32 *pa, s32 *pd, s32 *dx, s32 *dy)
{
    s64 x;
    s64 y;
    if ((scale_x_q16 == 0u) || (scale_y_q16 == 0u) ||
        (origin_x < -32768) || (origin_x > 32767) ||
        (origin_y < -32768) || (origin_y > 32767))
    {
        return FALSE;
    }
    if (asset->format == 1u)
    {
        *pa = ((u32)asset->native_w * 256u + 128u) / 256u;
        *pd = ((u32)asset->native_h * 256u + 96u) / 192u;
        *dx = *pa / 2;
        *dy = *pd / 2;
        return TRUE;
    }
    *pa = (s32)(((1u << 24) + scale_x_q16 / 2u) / scale_x_q16);
    *pd = (s32)(((1u << 24) + scale_y_q16 / 2u) / scale_y_q16);
    if ((*pa <= 0) || (*pa > 32767) || (*pd <= 0) || (*pd > 32767))
    {
        return FALSE;
    }
    /* The DS divide unit: C's truncating s64 division (the unit's own rule),
     * in place of a bit-by-bit __aeabi_ldivmod twice a frame. */
    x = (s64)*pa / 2 -
        ndsR2HwMathDivideLead((s64)origin_x * 4 * *pa, 5);
    y = (s64)*pd / 2 -
        ndsR2HwMathDivideLead((s64)origin_y * 4 * *pd, 5);
    if ((x < -134217728) || (x > 134217727) ||
        (y < -134217728) || (y > 134217727))
    {
        return FALSE;
    }
    *dx = (s32)x;
    *dy = (s32)y;
    return TRUE;
}

s32 ndsNativeWallpaperDraw(u32 asset_id, u32 bitmap_offset,
                          s32 origin_x, s32 origin_y,
                          u32 scale_x_q16, u32 scale_y_q16,
                          const u16 *palette)
{
    const NDSNativeWallpaper *asset = NULL;
    u32 i, pitch, width, height, epoch;
    u16 *dest;
    s32 pa, pd, dx, dy;
    for (i = 0u; i < kNDSNativeWallpaperCount; i++)
    {
        if ((kNDSNativeWallpapers[i].asset_id == asset_id) &&
            (kNDSNativeWallpapers[i].src_offset == bitmap_offset))
        {
            asset = &kNDSNativeWallpapers[i];
            break;
        }
    }
    if ((asset == NULL) || (asset->native_w != 240u) ||
        (asset->native_h != 176u) || (asset->format > 1u) ||
        ((asset->format == 1u) != (palette != NULL)) ||
        (ndsNativeWallpaperAffine(asset, origin_x, origin_y,
                                  scale_x_q16, scale_y_q16,
                                  &pa, &pd, &dx, &dy) == FALSE))
    {
        return FALSE;
    }
    gNdsNativeWallpaperAffinePa = pa;
    gNdsNativeWallpaperAffinePd = pd;
    gNdsNativeWallpaperAffineDx = dx;
    gNdsNativeWallpaperAffineDy = dy;
    dest = ndsPlatformGetOriginalSpriteOverlayLayer(FALSE, &pitch, &width,
                                                   &height, &epoch);
    if ((dest == NULL) || (pitch != 256u) || (width != 256u) || (height != 192u))
    {
        return FALSE;
    }
    if ((sWallpaperAsset != asset) || (sWallpaperEpoch != epoch) ||
        ((palette != NULL) &&
         (memcmp(palette, sWallpaperPalette, sizeof(sWallpaperPalette)) != 0)))
    {
        sWallpaperAsset = NULL;
        /* The upload writes the visible bitmap row by row: hidden until this
         * frame's commit, so the new picture appears whole and under the
         * owner's tint of the same frame (Results tic 80). */
        ndsPlatformHideOriginalSpriteOverlayUntilCommit(FALSE);
        if (ndsNativeWallpaperUpload(asset, dest, pitch, palette) == FALSE)
        {
            gNdsNativeWallpaperReadFailureCount++;
            return FALSE;
        }
        epoch = ndsPlatformCommitOriginalSpriteFinalLayer(FALSE, 256u * 192u);
        if (epoch == 0u)
        {
            return FALSE;
        }
        sWallpaperAsset = asset;
        sWallpaperEpoch = epoch;
        if (palette != NULL)
        {
            memcpy(sWallpaperPalette, palette, sizeof(sWallpaperPalette));
        }
        gNdsNativeWallpaperLoadCount++;
    }
    else
    {
        NDS_DIAG(gNdsNativeWallpaperReuseCount++);
    }
    return ndsPlatformQueueNativeWallpaperAffine(pa, pd, dx, dy);
}

s32 ndsNativeBattleWallpaperPreload(u32 gkind)
{
    const NDSNativeBattleWallpaperBinding *binding;
    s32 origin_x = 10;
    s32 origin_y = 10;
    u32 scale_q16;

    /* This owner is intentionally scoped to the nine VS stages. Other battle
     * kinds keep their existing background contracts, and Dream Land keeps its
     * accepted DObj backdrop without ever writing BG2 here. */
    if ((gkind >= (sizeof(sBattleWallpaperBindings) /
                   sizeof(sBattleWallpaperBindings[0]))) ||
        (gkind == 6u))
    {
        return TRUE;
    }
    binding = &sBattleWallpaperBindings[gkind];
    if (binding->motion == NDS_NATIVE_BATTLE_WALLPAPER_NONE)
    {
        return TRUE;
    }
    /* The frame the previous scene left (the 1P intro's still) is held in
     * BG2's bank until the battle presents: the first presented draw pays
     * the read instead, after the hold ends. */
    if (ndsPlatformTransitionSnapshotHoldsBg2() != FALSE)
    {
        NDS_DIAG(gNdsNativeBattleWallpaperDeferCount++);
        return TRUE;
    }

    /* Match the source constructor's first pose closely enough to make the
     * load legal. The first native-stage prepare overwrites this affine from
     * the live camera before the first battle present; the purpose here is to
     * pay the NitroFS read during scene setup rather than inside that frame. */
    scale_q16 = (binding->motion == NDS_NATIVE_BATTLE_WALLPAPER_COMMON) ?
        (u32)(1.004F * 65536.0F + 0.5F) : (1u << 16);
    origin_x = 160 + ndsNativeWallpaperMul9Div8Signed(origin_x - 160);
    origin_y = 120 + ndsNativeWallpaperMul9Div8Signed(origin_y - 120);
    scale_q16 += (scale_q16 + 4u) >> NDS_NATIVE_WALLPAPER_STRETCH_SHIFT;

    if (ndsNativeWallpaperDraw(binding->asset_id, binding->bitmap_offset,
                               origin_x, origin_y, scale_q16, scale_q16,
                               NULL) == FALSE)
    {
        gNdsNativeBattleWallpaperFailureCount++;
        return FALSE;
    }
    return TRUE;
}

s32 ndsNativeBattleWallpaperDraw(u32 gkind,
                                 f32 eye_x, f32 eye_y, f32 eye_z,
                                 f32 at_x, f32 at_y, f32 at_z)
{
    const NDSNativeBattleWallpaperBinding *binding;
    s32 origin_x;
    s32 origin_y;
    u32 scale_q16;

    if ((gkind >= (sizeof(sBattleWallpaperBindings) /
                   sizeof(sBattleWallpaperBindings[0]))) ||
        (gkind == 6u))
    {
        return TRUE;
    }
    binding = &sBattleWallpaperBindings[gkind];
    if ((binding->motion == NDS_NATIVE_BATTLE_WALLPAPER_NONE) ||
        (ndsNativeBattleWallpaperTransform(binding,
            eye_x, eye_y, eye_z, at_x, at_y, at_z,
            &origin_x, &origin_y, &scale_q16) == FALSE))
    {
        gNdsNativeBattleWallpaperFailureCount++;
        return FALSE;
    }

    gNdsNativeBattleWallpaperGKind = gkind;
    gNdsNativeBattleWallpaperOriginX = origin_x;
    gNdsNativeBattleWallpaperOriginY = origin_y;
    gNdsNativeBattleWallpaperScaleQ16 = scale_q16;
    /* Not yet the presented draw while a held frame owns BG2's bank: the
     * stage owner's prepare runs before the frame's own wallpaper commit,
     * which ends the hold (ndsPlatformTransitionSnapshotHoldsBg2). */
    if (ndsPlatformTransitionSnapshotHoldsBg2() != FALSE)
    {
        NDS_DIAG(gNdsNativeBattleWallpaperDeferCount++);
        return TRUE;
    }
    if (ndsNativeWallpaperDraw(binding->asset_id, binding->bitmap_offset,
                               origin_x, origin_y, scale_q16, scale_q16,
                               NULL) == FALSE)
    {
        gNdsNativeBattleWallpaperFailureCount++;
        return FALSE;
    }
    gNdsNativeBattleWallpaperDrawCount++;
    return TRUE;
}
