#include <nds.h>
#include <math.h>
#include <string.h>

#include <nds/nds_native_wallpaper.h>
#include <nds/nds_platform.h>
#include <nds/nds_reloc_assets.h>

#include "generated/native_wallpapers.generated.inc"

/* Only one BG2 image is resident. Row staging is main RAM and all VRAM
 * stores are halfwords; fread must never write directly to VRAM. */
static u16 sWallpaperRow[240] __attribute__((aligned(32)));
static const NDSNativeWallpaper *sWallpaperAsset;
static u32 sWallpaperEpoch;
static u16 sWallpaperPalette[16];

volatile u32 gNdsNativeWallpaperLoadCount;
volatile u32 gNdsNativeWallpaperReuseCount;
volatile u32 gNdsNativeWallpaperReadFailureCount;

/* P2-4 stage-background proof. These are shipping-path observations, not
 * selectors: the stage owner writes the source-derived transform before the
 * existing BG2 affine queue consumes it. They make one captured frame directly
 * comparable with grwallpaper.c without retaining an SObj or N64 renderer. */
__attribute__((used)) volatile u32 gNdsNativeBattleWallpaperDrawCount;
__attribute__((used)) volatile u32 gNdsNativeBattleWallpaperFailureCount;
__attribute__((used)) volatile u32 gNdsNativeBattleWallpaperGKind = 0xffffffffu;
__attribute__((used)) volatile s32 gNdsNativeBattleWallpaperOriginX;
__attribute__((used)) volatile s32 gNdsNativeBattleWallpaperOriginY;
__attribute__((used)) volatile u32 gNdsNativeBattleWallpaperScaleQ16;
__attribute__((used)) volatile s32 gNdsNativeWallpaperAffinePa;
__attribute__((used)) volatile s32 gNdsNativeWallpaperAffinePd;
__attribute__((used)) volatile s32 gNdsNativeWallpaperAffineDx;
__attribute__((used)) volatile s32 gNdsNativeWallpaperAffineDy;

enum NDSNativeBattleWallpaperMotion
{
    NDS_NATIVE_BATTLE_WALLPAPER_COMMON = 0,
    NDS_NATIVE_BATTLE_WALLPAPER_SECTOR,
    NDS_NATIVE_BATTLE_WALLPAPER_STATIC,
    NDS_NATIVE_BATTLE_WALLPAPER_NONE
};

typedef struct NDSNativeBattleWallpaperBinding
{
    u32 asset_id;
    u32 bitmap_offset;
    u8 motion;
} NDSNativeBattleWallpaperBinding;

/* One shared binding table in BattleShip gr/grdef.h order. The asset identities
 * are the converted providers generated by generate_native_wallpapers.py. This
 * is data selection only; all stages share the same upload and affine owner. */
static const NDSNativeBattleWallpaperBinding sBattleWallpaperBindings[9] =
{
    { 0x5Au,    0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_COMMON }, /* Castle */
    { 0x10063u, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_SECTOR }, /* Sector */
    { 0x1005Cu, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_COMMON }, /* Jungle */
    { 0x10059u, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_COMMON }, /* Zebes */
    { 0x1005Fu, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_COMMON }, /* Hyrule */
    { 0x1005Du, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_STATIC }, /* Yoster */
    { 0u,       0u,       NDS_NATIVE_BATTLE_WALLPAPER_NONE },   /* Pupupu */
    { 0x1005Eu, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_COMMON }, /* Yamabuki */
    { 0x1005Bu, 0x269C8u, NDS_NATIVE_BATTLE_WALLPAPER_COMMON }  /* Inishie */
};

#define NDS_NATIVE_WALLPAPER_PI 3.14159265358979323846F
#define NDS_NATIVE_WALLPAPER_STRETCH_SHIFT 3u

static s32 ndsNativeWallpaperMul9Div8Signed(s32 value)
{
    u32 magnitude = (value < 0) ? (u32)(-value) : (u32)value;
    s32 scaled = (s32)(((magnitude << NDS_NATIVE_WALLPAPER_STRETCH_SHIFT) +
                        magnitude) >> NDS_NATIVE_WALLPAPER_STRETCH_SHIFT);

    return (value < 0) ? -scaled : scaled;
}

/* Native transcription of grWallpaperCalcPersp / grWallpaperSectorProcUpdate
 * plus grWallpaperMakeStatic. The final 9/8 centre stretch is the existing DS
 * overscan correction already used by the SObj preview path. */
static s32 ndsNativeBattleWallpaperTransform(
    const NDSNativeBattleWallpaperBinding *binding,
    f32 eye_x, f32 eye_y, f32 eye_z,
    f32 at_x, f32 at_y, f32 at_z,
    s32 *origin_x, s32 *origin_y, u32 *scale_q16)
{
    f32 dist_x;
    f32 dist_y;
    f32 dist_z;
    f32 mag;
    f32 scale;
    f32 pos_x;
    f32 pos_y;

    if ((binding == NULL) || (origin_x == NULL) || (origin_y == NULL) ||
        (scale_q16 == NULL))
    {
        return FALSE;
    }
    if (binding->motion == NDS_NATIVE_BATTLE_WALLPAPER_STATIC)
    {
        pos_x = 10.0F;
        pos_y = 10.0F;
        scale = 1.0F;
    }
    else
    {
        dist_x = eye_x - at_x;
        dist_y = eye_y - at_y;
        dist_z = eye_z - at_z;
        mag = sqrtf((dist_x * dist_x) + (dist_y * dist_y) +
                    (dist_z * dist_z));
        if (!(mag >= 0.0F))
        {
            return FALSE;
        }
        if (binding->motion == NDS_NATIVE_BATTLE_WALLPAPER_SECTOR)
        {
            f32 zoom;

            scale = 20000.0F / (mag + 10000.0F);
            if (scale < 1.004F) scale = 1.004F;
            else if (scale > 2.0F) scale = 2.0F;
            zoom = (scale - 1.0F) * 0.5F;
            pos_x = 10.0F - (300.0F * zoom);
            pos_y = 10.0F - (220.0F * zoom);
        }
        else if (binding->motion == NDS_NATIVE_BATTLE_WALLPAPER_COMMON)
        {
            f32 angle_x = 0.0F;
            f32 angle_y = 0.0F;
            f32 width;
            f32 height;
            f32 minimum;

            if (dist_z >= 0.0F)
            {
                angle_y = atan2f(dist_x, dist_z);
                angle_x = atan2f(dist_y, dist_z);
            }
            scale = 20000.0F / (mag + 8000.0F);
            if (scale < 1.004F) scale = 1.004F;
            else if (scale > 2.0F) scale = 2.0F;
            width = 300.0F * scale;
            height = 220.0F * scale;
            pos_x = ((angle_y / NDS_NATIVE_WALLPAPER_PI) * width) -
                    ((width - 320.0F) * 0.5F);
            pos_y = ((-angle_x / NDS_NATIVE_WALLPAPER_PI) * height) -
                    ((height - 240.0F) * 0.5F);
            if (pos_x > 10.0F) pos_x = 10.0F;
            minimum = (-width - 10.0F) + 320.0F;
            if (pos_x < minimum) pos_x = minimum;
            if (pos_y > 10.0F) pos_y = 10.0F;
            minimum = (-height - 10.0F) + 240.0F;
            if (pos_y < minimum) pos_y = minimum;
        }
        else
        {
            return FALSE;
        }
    }

    if ((pos_x < -32768.0F) || (pos_x > 32767.0F) ||
        (pos_y < -32768.0F) || (pos_y > 32767.0F) ||
        (scale < 1.0F) || (scale > 2.0F))
    {
        return FALSE;
    }
    *origin_x = (s32)pos_x;
    *origin_y = (s32)pos_y;
    *scale_q16 = (u32)((scale * 65536.0F) + 0.5F);

    /* Existing port presentation law: compensate for N64 overscan while
     * preserving the source camera transform itself. */
    *origin_x = 160 + ndsNativeWallpaperMul9Div8Signed(*origin_x - 160);
    *origin_y = 120 + ndsNativeWallpaperMul9Div8Signed(*origin_y - 120);
    *scale_q16 += (*scale_q16 + 4u) >> NDS_NATIVE_WALLPAPER_STRETCH_SHIFT;
    return TRUE;
}

void ndsNativeWallpaperInvalidate(void)
{
    sWallpaperAsset = NULL;
    sWallpaperEpoch = 0u;
    (void)ndsPlatformQueueNativeWallpaperAffine(256, 256, 0, 0);
}

static s32 ndsNativeWallpaperUpload(const NDSNativeWallpaper *asset,
                                   u16 *dest, u32 pitch, const u16 *palette)
{
    NdsRelocAssetStream stream = { NULL };
    char path[96];
    u32 y;
    u32 bytes_per_row = asset->native_w * ((asset->format == 0u) ? 2u : 1u);
    const char prefix[] = "nitro:/wallpapers/";
    size_t name_bytes = strlen(asset->nitro_filename) + 1u;

    if (name_bytes > sizeof(path) - (sizeof(prefix) - 1u))
    {
        return FALSE;
    }
    memcpy(path, prefix, sizeof(prefix) - 1u);
    memcpy(path + sizeof(prefix) - 1u, asset->nitro_filename, name_bytes);
    if (ndsRelocAssetStreamOpen(&stream, path) == FALSE)
    {
        return FALSE;
    }
    dmaFillHalfWords(0x8000u, dest, 256u * 192u * sizeof(u16));
    for (y = 0u; y < asset->native_h; y++)
    {
        u32 x;
        if (ndsRelocAssetStreamRead(&stream, y * bytes_per_row,
                                    sWallpaperRow, bytes_per_row) == FALSE)
        {
            ndsRelocAssetStreamClose(&stream);
            return FALSE;
        }
        if (asset->format == 1u)
        {
            /* The converted file contains intensity bytes, not source I4
             * strips. Expand backwards so input and output share one row. */
            const u8 *indices = (const u8 *)sWallpaperRow;
            for (x = asset->native_w; x != 0u; x--)
            {
                u32 intensity = indices[x - 1u];
                if ((intensity % 17u) != 0u)
                {
                    ndsRelocAssetStreamClose(&stream);
                    return FALSE;
                }
                sWallpaperRow[x - 1u] = palette[intensity / 17u];
            }
        }
        for (x = 0u; x < asset->native_w; x++)
        {
            if ((sWallpaperRow[x] & 0x8000u) == 0u)
            {
                ndsRelocAssetStreamClose(&stream);
                return FALSE;
            }
            ((volatile u16 *)dest)[y * pitch + x] = sWallpaperRow[x];
        }
    }
    ndsRelocAssetStreamClose(&stream);
    return TRUE;
}

/* Converted texels already include the 4/5 source-to-DS scale. For battle,
 * BG source x = (screen x - source_origin * 4/5) / source_scale.
 * Match pixel centres when converting that inverse transform to Q8.
 * Results uses its existing (10,10)-(310,230) full-screen crop. */
static s32 ndsNativeWallpaperAffine(const NDSNativeWallpaper *asset,
                                   s32 origin_x, s32 origin_y,
                                   u32 scale_x_q16, u32 scale_y_q16,
                                   s32 *pa, s32 *pd, s32 *dx, s32 *dy)
{
    s64 x;
    s64 y;
    if ((scale_x_q16 == 0u) || (scale_y_q16 == 0u) ||
        (origin_x < -32768) || (origin_x > 32767) ||
        (origin_y < -32768) || (origin_y > 32767))
    {
        return FALSE;
    }
    if (asset->format == 1u)
    {
        *pa = ((u32)asset->native_w * 256u + 128u) / 256u;
        *pd = ((u32)asset->native_h * 256u + 96u) / 192u;
        *dx = *pa / 2;
        *dy = *pd / 2;
        return TRUE;
    }
    *pa = (s32)(((1u << 24) + scale_x_q16 / 2u) / scale_x_q16);
    *pd = (s32)(((1u << 24) + scale_y_q16 / 2u) / scale_y_q16);
    if ((*pa <= 0) || (*pa > 32767) || (*pd <= 0) || (*pd > 32767))
    {
        return FALSE;
    }
    x = (s64)*pa / 2 - ((s64)origin_x * 4 * *pa) / 5;
    y = (s64)*pd / 2 - ((s64)origin_y * 4 * *pd) / 5;
    if ((x < -134217728) || (x > 134217727) ||
        (y < -134217728) || (y > 134217727))
    {
        return FALSE;
    }
    *dx = (s32)x;
    *dy = (s32)y;
    return TRUE;
}

s32 ndsNativeWallpaperDraw(u32 asset_id, u32 bitmap_offset,
                          s32 origin_x, s32 origin_y,
                          u32 scale_x_q16, u32 scale_y_q16,
                          const u16 *palette)
{
    const NDSNativeWallpaper *asset = NULL;
    u32 i, pitch, width, height, epoch;
    u16 *dest;
    s32 pa, pd, dx, dy;
    for (i = 0u; i < kNDSNativeWallpaperCount; i++)
    {
        if ((kNDSNativeWallpapers[i].asset_id == asset_id) &&
            (kNDSNativeWallpapers[i].src_offset == bitmap_offset))
        {
            asset = &kNDSNativeWallpapers[i];
            break;
        }
    }
    if ((asset == NULL) || (asset->native_w != 240u) ||
        (asset->native_h != 176u) || (asset->format > 1u) ||
        ((asset->format == 1u) != (palette != NULL)) ||
        (ndsNativeWallpaperAffine(asset, origin_x, origin_y,
                                  scale_x_q16, scale_y_q16,
                                  &pa, &pd, &dx, &dy) == FALSE))
    {
        return FALSE;
    }
    gNdsNativeWallpaperAffinePa = pa;
    gNdsNativeWallpaperAffinePd = pd;
    gNdsNativeWallpaperAffineDx = dx;
    gNdsNativeWallpaperAffineDy = dy;
    dest = ndsPlatformGetOriginalSpriteOverlayLayer(FALSE, &pitch, &width,
                                                   &height, &epoch);
    if ((dest == NULL) || (pitch != 256u) || (width != 256u) || (height != 192u))
    {
        return FALSE;
    }
    if ((sWallpaperAsset != asset) || (sWallpaperEpoch != epoch) ||
        ((palette != NULL) &&
         (memcmp(palette, sWallpaperPalette, sizeof(sWallpaperPalette)) != 0)))
    {
        sWallpaperAsset = NULL;
        if (ndsNativeWallpaperUpload(asset, dest, pitch, palette) == FALSE)
        {
            gNdsNativeWallpaperReadFailureCount++;
            return FALSE;
        }
        epoch = ndsPlatformCommitOriginalSpriteFinalLayer(FALSE, 256u * 192u);
        if (epoch == 0u)
        {
            return FALSE;
        }
        sWallpaperAsset = asset;
        sWallpaperEpoch = epoch;
        if (palette != NULL)
        {
            memcpy(sWallpaperPalette, palette, sizeof(sWallpaperPalette));
        }
        gNdsNativeWallpaperLoadCount++;
    }
    else
    {
        gNdsNativeWallpaperReuseCount++;
    }
    return ndsPlatformQueueNativeWallpaperAffine(pa, pd, dx, dy);
}

s32 ndsNativeBattleWallpaperPreload(u32 gkind)
{
    const NDSNativeBattleWallpaperBinding *binding;
    s32 origin_x = 10;
    s32 origin_y = 10;
    u32 scale_q16;

    /* This owner is intentionally scoped to the nine VS stages. Other battle
     * kinds keep their existing background contracts, and Dream Land keeps its
     * accepted DObj backdrop without ever writing BG2 here. */
    if ((gkind >= (sizeof(sBattleWallpaperBindings) /
                   sizeof(sBattleWallpaperBindings[0]))) ||
        (gkind == 6u))
    {
        return TRUE;
    }
    binding = &sBattleWallpaperBindings[gkind];
    if (binding->motion == NDS_NATIVE_BATTLE_WALLPAPER_NONE)
    {
        return TRUE;
    }

    /* Match the source constructor's first pose closely enough to make the
     * load legal. The first native-stage prepare overwrites this affine from
     * the live camera before the first battle present; the purpose here is to
     * pay the NitroFS read during scene setup rather than inside that frame. */
    scale_q16 = (binding->motion == NDS_NATIVE_BATTLE_WALLPAPER_COMMON) ?
        (u32)(1.004F * 65536.0F + 0.5F) : (1u << 16);
    origin_x = 160 + ndsNativeWallpaperMul9Div8Signed(origin_x - 160);
    origin_y = 120 + ndsNativeWallpaperMul9Div8Signed(origin_y - 120);
    scale_q16 += (scale_q16 + 4u) >> NDS_NATIVE_WALLPAPER_STRETCH_SHIFT;

    if (ndsNativeWallpaperDraw(binding->asset_id, binding->bitmap_offset,
                               origin_x, origin_y, scale_q16, scale_q16,
                               NULL) == FALSE)
    {
        gNdsNativeBattleWallpaperFailureCount++;
        return FALSE;
    }
    return TRUE;
}

s32 ndsNativeBattleWallpaperDraw(u32 gkind,
                                 f32 eye_x, f32 eye_y, f32 eye_z,
                                 f32 at_x, f32 at_y, f32 at_z)
{
    const NDSNativeBattleWallpaperBinding *binding;
    s32 origin_x;
    s32 origin_y;
    u32 scale_q16;

    if ((gkind >= (sizeof(sBattleWallpaperBindings) /
                   sizeof(sBattleWallpaperBindings[0]))) ||
        (gkind == 6u))
    {
        return TRUE;
    }
    binding = &sBattleWallpaperBindings[gkind];
    if ((binding->motion == NDS_NATIVE_BATTLE_WALLPAPER_NONE) ||
        (ndsNativeBattleWallpaperTransform(binding,
            eye_x, eye_y, eye_z, at_x, at_y, at_z,
            &origin_x, &origin_y, &scale_q16) == FALSE))
    {
        gNdsNativeBattleWallpaperFailureCount++;
        return FALSE;
    }

    gNdsNativeBattleWallpaperGKind = gkind;
    gNdsNativeBattleWallpaperOriginX = origin_x;
    gNdsNativeBattleWallpaperOriginY = origin_y;
    gNdsNativeBattleWallpaperScaleQ16 = scale_q16;
    if (ndsNativeWallpaperDraw(binding->asset_id, binding->bitmap_offset,
                               origin_x, origin_y, scale_q16, scale_q16,
                               NULL) == FALSE)
    {
        gNdsNativeBattleWallpaperFailureCount++;
        return FALSE;
    }
    gNdsNativeBattleWallpaperDrawCount++;
    return TRUE;
}
