/* Generated by scripts/generate_pupupu_water_tiled_aot.py. */
/* Host-exact M4 packet only; absent from the production build by design. */
#include "nds/pupupu_water_tiled_aot.h"

#include "generated/pupupu_water_tiled_aot.generated.inc"

_Static_assert(sizeof(NDSPupupuWaterTiledPlanVertex) == 16u,
               "tiled-water plan vertex ABI changed");
_Static_assert(sizeof(NDSPupupuWaterTiledPlanCell) == 8u,
               "tiled-water plan cell ABI changed");
_Static_assert(sizeof(NDSPupupuWaterTiledAssets) == 12u,
               "tiled-water asset-view ABI changed");
_Static_assert(sizeof(NDSPupupuWaterTiledFrame) == 12u,
               "tiled-water frame-view ABI changed");
_Static_assert(sizeof(sNdsPupupuWaterLargeStates) +
                   sizeof(sNdsPupupuWaterSmallStates) +
                   sizeof(sNdsPupupuWaterLargeFrames) +
                   sizeof(sNdsPupupuWaterSmallFrames) ==
                   NDS_PUPUPU_WATER_TILED_STATE_TABLE_BYTES,
               "tiled-water compact state footprint changed");
_Static_assert(sizeof(sNdsPupupuWaterPlanCells) ==
                   NDS_PUPUPU_WATER_TILED_PLAN_CELL_COUNT *
                       sizeof(NDSPupupuWaterTiledPlanCell),
               "tiled-water plan-cell footprint changed");
_Static_assert(sizeof(sNdsPupupuWaterPlanVertices) ==
                   NDS_PUPUPU_WATER_TILED_PLAN_VERTEX_COUNT *
                       sizeof(NDSPupupuWaterTiledPlanVertex),
               "tiled-water plan-vertex footprint changed");
_Static_assert(NDS_PUPUPU_WATER_TILED_PLAN_CELL_COUNT ==
                   NDS_PUPUPU_WATER_TILED_LOGICAL_CELL_SUBMISSIONS,
               "logical plan-cell submission count changed");
_Static_assert(NDS_PUPUPU_WATER_TILED_TOTAL_TRIANGLES * 3u ==
                   NDS_PUPUPU_WATER_TILED_EMITTED_VERTICES,
               "GL_TRIANGLES vertex expansion changed");
_Static_assert(NDS_PUPUPU_WATER_TILED_EMITTED_VERTICES * 3u ==
                   NDS_PUPUPU_WATER_TILED_VERTEX_ATTRIBUTE_WRITES,
               "TEXCOORD/VTX16 register-write count changed");
static void ndsPupupuWaterTiledClearFrame(NDSPupupuWaterTiledFrame *frame)
{
    if (frame == 0)
    {
        return;
    }
    frame->tile_ids = 0;
    frame->state_cell_count = 0u;
    frame->state_columns = 0u;
    frame->state_rows = 0u;
    frame->state = 0u;
    frame->palette_index = 0u;
    frame->reserved[0] = 0u;
    frame->reserved[1] = 0u;
}

s32 ndsPupupuWaterTiledGetAssets(NDSPupupuWaterTiledAssets *out_assets)
{
    if (out_assets == 0)
    {
        return NDS_PUPUPU_WATER_TILED_INVALID;
    }
    out_assets->plan_cells = sNdsPupupuWaterPlanCells;
    out_assets->plan_vertices = sNdsPupupuWaterPlanVertices;
    out_assets->plan_cell_count = NDS_PUPUPU_WATER_TILED_PLAN_CELL_COUNT;
    out_assets->plan_vertex_count = NDS_PUPUPU_WATER_TILED_PLAN_VERTEX_COUNT;
    return NDS_PUPUPU_WATER_TILED_OK;
}

s32 ndsPupupuWaterTiledGetFrame(
    u32 owner, u32 cycle_frame, u32 source_fraction,
    NDSPupupuWaterTiledFrame *out_frame)
{
    u8 state;
    u32 palette_index;

    ndsPupupuWaterTiledClearFrame(out_frame);
    if ((out_frame == 0) ||
        (cycle_frame >= NDS_PUPUPU_WATER_TILED_CYCLE_FRAMES) ||
        (source_fraction < NDS_PUPUPU_WATER_TILED_FRACTION_MIN) ||
        (source_fraction > NDS_PUPUPU_WATER_TILED_FRACTION_MAX))
    {
        return NDS_PUPUPU_WATER_TILED_INVALID;
    }
    palette_index = source_fraction - NDS_PUPUPU_WATER_TILED_FRACTION_MIN;
    if (owner == NDS_PUPUPU_WATER_TILED_OWNER_LARGE)
    {
        state = sNdsPupupuWaterLargeFrames[cycle_frame];
        out_frame->tile_ids = sNdsPupupuWaterLargeStates[state];
        out_frame->state_cell_count = 64u;
        out_frame->state_columns = 4u;
        out_frame->state_rows = 16u;
    }
    else if (owner == NDS_PUPUPU_WATER_TILED_OWNER_SMALL)
    {
        state = sNdsPupupuWaterSmallFrames[cycle_frame];
        out_frame->tile_ids = sNdsPupupuWaterSmallStates[state];
        out_frame->state_cell_count = 8u;
        out_frame->state_columns = 1u;
        out_frame->state_rows = 8u;
    }
    else
    {
        return NDS_PUPUPU_WATER_TILED_INVALID;
    }
    out_frame->state = state;
    out_frame->palette_index = (u8)palette_index;
    return NDS_PUPUPU_WATER_TILED_OK;
}
