#!/usr/bin/env python3
"""Export effective Meta Knight tables from Bass's linked EXTRA image.

This is host-side source admission, not a runtime loader. The review include
appends metadata after the donor ROM's existing padding; it uses the donor's
actual constants instead of interpreting Character macros or guessing addresses.
The exported addresses remain explicitly in the donor domain until native
callback, event and resource conversion has qualified them.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import struct


MAGIC = b"S64P4EX1"
VERSION = 1
HEADER_WORDS = 13
HEADER_SIZE = len(MAGIC) + HEADER_WORDS * 4
REVIEW_INCLUDE = "p4_native_review_export.asm"
HOOKS = (
    ("ground_nsp", 4), ("air_nsp", 4),
    ("ground_usp", 4), ("air_usp", 4),
    ("ground_dsp", 4), ("air_dsp", 4),
    ("ai_behaviour", 4), ("on_action_changed", 4),
    ("initial_script", 4), ("grounded_script", 4),
    ("action_replace_map", 4), ("custom_capture_dk_interrupt", 4),
    ("entry_script", 4), ("static_part", 8),
    ("crowd_chant_fgm", 2), ("kirby_inhale_struct", 12),
    ("default_costume", 8), ("costume_shield_color", 4),
)


def review_assembly() -> str:
    lines = [
        "// Generated by extra_resolved_actions.py. Review-only donor metadata.",
        "// Append after the final donor ROM padding. No gameplay pointers use it.",
        "endian msb", "OS.align(4)",
        "constant S64P4ReviewOrigin(origin())", "S64P4ReviewExport:",
        'db "S64P4EX1"', f"dw {VERSION}", "dw S64P4ReviewOrigin",
        "dw {Character.METAKNIGHT_character_struct_origin}",
        "dw {Character.METAKNIGHT_param_array_origin}",
        "dw Character.METAKNIGHT_param_array_size",
        "dw {Character.METAKNIGHT_action_array_origin}",
        "dw (Character.action_array_size.JIGGLYPUFF / 0x14) + {MetaKnight.METAKNIGHT_new_actions}",
        "dw Character.SHARED_ACTION_ARRAY", "dw 0xDC",
        "dw {Character.METAKNIGHT_menu_array_origin}", "dw 0xF",
        "dw Character.id.METAKNIGHT", f"dw {len(HOOKS)}",
    ]
    for index, (name, size) in enumerate(HOOKS):
        lines += [f"// {name}", f"dw {index}",
                  f"dw Character.{name}.TABLE_ORIGIN + (Character.id.METAKNIGHT * {size})",
                  f"dw {size}"]
    return "\n".join(lines) + "\n"


def install_review_export(stage: Path, repo_root: Path | None = None) -> Path:
    """Install through the producer only in this checkout's disposable builds."""
    root = (repo_root or Path(__file__).resolve().parents[2]).resolve()
    stage = stage.resolve()
    if not stage.is_relative_to(root / "builds"):
        raise ValueError("review export destination must be inside this checkout's builds/")
    main = stage / "main.asm"
    output = stage / REVIEW_INCLUDE
    if main.is_symlink() or output.is_symlink():
        raise ValueError("review export refuses symlinked source/output files")
    if not main.is_file():
        raise ValueError("run the pinned EXTRA appender before installing review export")
    original = main.read_text(encoding="utf-8")
    marker = f'include "{REVIEW_INCLUDE}"'
    if REVIEW_INCLUDE in original and original.count(marker) != 1:
        raise ValueError("ambiguous existing review export include")
    output.write_text(review_assembly(), encoding="utf-8", newline="\n")
    if marker not in original:
        main.write_text(original.rstrip() + "\n\n" + marker + "\n",
                        encoding="utf-8", newline="\n")
    return output


def parse_symbols(text: str) -> dict[int, list[str]]:
    result: dict[int, list[str]] = {}
    names: dict[str, int] = {}
    for line in text.splitlines():
        if not line.strip():
            continue
        match = re.fullmatch(r"([0-9A-Fa-f]{8})\s+([^\s]+)\s*", line)
        if match is None:
            raise ValueError(f"unsupported Bass symbol line: {line!r}")
        address, name = int(match[1], 16), match[2]
        if name in names and names[name] != address:
            raise ValueError(f"conflicting Bass symbol: {name}")
        names[name] = address
        if name not in result.setdefault(address, []):
            result[address].append(name)
    return {address: sorted(labels) for address, labels in result.items()}


def span(rom: bytes, offset: int, count: int, width: int, label: str) -> bytes:
    if offset < 0 or count < 0 or width <= 0 or offset % min(width, 4):
        raise ValueError(f"unaligned/invalid {label} span")
    size = count * width
    if offset > len(rom) or size > len(rom) - offset:
        raise ValueError(f"{label} span outside donor ROM")
    return rom[offset:offset + size]


def decode_export(rom: bytes, symbols: dict[int, list[str]]) -> dict:
    starts = [match.start() for match in re.finditer(re.escape(MAGIC), rom)]
    if len(starts) != 1:
        raise ValueError(f"expected one review export, found {len(starts)}")
    start = starts[0]
    header = span(rom, start, 1, HEADER_SIZE, "review header")
    (version, export_offset, char_offset, params_offset, params_count,
     specials_offset, specials_count, shared_offset, shared_count,
     menu_offset, menu_count, donor_id, hook_count) = struct.unpack_from(
         ">13I", header, len(MAGIC))
    if version != VERSION or export_offset != start:
        raise ValueError("review export version/location mismatch")
    if shared_count != 0xDC or menu_count != 15 or hook_count != len(HOOKS):
        raise ValueError("review table shape differs from pinned Character.asm")
    if not 1 <= params_count < 0x3FF or not 1 <= specials_count < 0x3FF:
        raise ValueError("invalid parameter/action count")
    char_data = span(rom, char_offset, 1, 0x78, "character descriptor")
    if struct.unpack_from(">I", char_data, 0x6C)[0] != params_count:
        raise ValueError("character parameter count disagrees with export")
    param_data = span(rom, params_offset, params_count, 12, "parameters")
    menu_data = span(rom, menu_offset, menu_count, 12, "menu parameters")
    params = []
    for index, (animation, script, flags) in enumerate(struct.iter_unpack(">III", param_data)):
        params.append({"index": index, "animation_file_id": animation,
                       "script_donor_value": script, "flags": flags,
                       "script_state": "no_script" if script == 0x80000000 else "unconverted"})

    callbacks: dict[int, dict] = {}
    actions = []
    for first, offset, count in ((0, shared_offset, shared_count),
                                 (shared_count, specials_offset, specials_count)):
        data = span(rom, offset, count, 20, "actions")
        for index, row in enumerate(struct.iter_unpack(">HHIIII", data)):
            packed, unknown, *callback_values = row
            param_index = packed >> 6
            # EXTRA's overwritten Character macro recognizes both reserved
            # values. They must not be interpreted as parameter-array indices.
            no_parameters = param_index in (0x3FE, 0x3FF)
            if not no_parameters and param_index >= params_count:
                raise ValueError(f"action {first + index}: invalid parameter index {param_index}")
            for value in callback_values:
                if value:
                    callbacks[value] = {"donor_address": value,
                                        "symbols": symbols.get(value, []),
                                        "native_conversion": "unresolved"}
            actions.append({"status_id": first + index,
                            "parameter_index": None if no_parameters else param_index,
                            "parameter_sentinel": param_index if no_parameters else None,
                            "stale_id": packed & 0x3F, "unknown_flags": unknown,
                            "callbacks_donor": dict(zip(
                                ("update", "interrupt", "physics", "map"), callback_values))})

    hook_data = span(rom, start + HEADER_SIZE, hook_count, 12, "hook directory")
    hooks = []
    for expected, (index, offset, size) in enumerate(struct.iter_unpack(">III", hook_data)):
        if index != expected or size != HOOKS[index][1]:
            raise ValueError("unexpected hook identity/width")
        raw = span(rom, offset, 1, size, HOOKS[index][0])
        hooks.append({"name": HOOKS[index][0], "rom_offset": offset,
                      "bytes_big_endian": raw.hex(), "native_conversion": "unresolved"})

    return {"schema": "smash64ds.extra-resolved-actions.v1",
            "character": "MetaKnight", "donor_character_id": donor_id,
            "address_domain": "N64 donor; never a DS runtime pointer",
            "admission": "UNRESOLVED_NATIVE_CONVERSION",
            "rom_sha256": hashlib.sha256(rom).hexdigest(),
            "review_export_rom_offset": start,
            "core_file_ids": list(struct.unpack_from(">9I", char_data)),
            "attribute_offset": struct.unpack_from(">I", char_data, 0x60)[0],
            "parameters": params, "actions": actions,
            "menu_parameters": [dict(zip(("animation_file_id", "script_donor_value", "flags"), row))
                                for row in struct.iter_unpack(">III", menu_data)],
            "character_hooks": hooks,
            "callbacks": [callbacks[address] for address in sorted(callbacks)],
            "remaining": ["typed resource closure and native model/motion conversion",
                          "event control-flow validation and lowering",
                          "native callbacks, CPU, copy and hook semantics",
                          "CSS/HUD/results/audio integration and DS runtime qualification"]}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--install-review-export", type=Path)
    parser.add_argument("--rom", type=Path)
    parser.add_argument("--symbols", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    try:
        if args.install_review_export:
            if any((args.rom, args.symbols, args.output)):
                parser.error("choose installation or extraction")
            print(install_review_export(args.install_review_export))
        else:
            if not all((args.rom, args.symbols, args.output)):
                parser.error("extraction requires --rom, --symbols and --output")
            data = decode_export(args.rom.read_bytes(), parse_symbols(args.symbols.read_text(encoding="utf-8")))
            data["symbols_sha256"] = hashlib.sha256(args.symbols.read_bytes()).hexdigest()
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
            print(f"{len(data['actions'])} actions, {len(data['callbacks'])} callback addresses; native conversion unresolved")
    except (OSError, ValueError) as exc:
        parser.exit(1, f"EXTRA export refused: {exc}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
