# Auto-generated by scripts/fighters/generate_fighter_production_manifest.py.
# Source of truth: BattleShip FTData + generated relocData + US O2R headers.
# Do not edit by hand; run `make p2-fighter-production-manifest`.

NDS_P2_LUIGI_FIGHTER_RELOC_FILES := \
	reloc_fighters_main/LuigiMain \
	reloc_fighters_main/LuigiMainMotion \
	reloc_fighters_main/LuigiSpecial1 \
	reloc_fighters_main/LuigiModel \
	reloc_animations/FTLuigiAnim000 \
	reloc_animations/FTLuigiAnim001 \
	reloc_animations/FTLuigiAnim002 \
	reloc_animations/FTLuigiAnim003 \
	reloc_animations/FTLuigiAnim004 \
	reloc_animations/FTLuigiAnim005 \
	reloc_animations/FTLuigiAnim006 \
	reloc_animations/FTLuigiAnim007 \
	reloc_animations/FTLuigiAnim008 \
	reloc_animations/FTLuigiAnim009 \
	reloc_animations/FTLuigiAnim010 \
	reloc_animations/FTLuigiAnim011
