#!/usr/bin/env python3
"""Pin published Meta FPC2/BEX2 artifacts against the frozen native source.

This creates the small existing-loader contract for Meta only. Legacy shared
manifests and resource loaders remain unchanged. Exact extern rows are checked
before any runtime pointer mutation because BEX2's bank hash excludes rows.
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct

import extra_native_asset_adapter as assets
import generate_preview_core_packs as fpc
import generate_battle_core_packs as battle


def qualify(native_dir: Path, preview_dir: Path, battle_dir: Path) -> dict:
    bindings = json.loads((native_dir / 'native-runtime-bindings.json').read_text())
    source_entry = next(row for row in bindings['assets'] if row['native_file_id'] == assets.MAIN_ID)
    source_path = native_dir / source_entry['path']
    if hashlib.sha256(source_path.read_bytes()).hexdigest() != source_entry['container_sha256']:
        raise ValueError('Meta core contract: frozen Main source changed')
    file_id, main = assets.load_o2r(source_path)
    if file_id != assets.MAIN_ID:
        raise ValueError('Meta core contract: Main source identity changed')
    expected_rows = [(slot, pointer.dependency.file_id, pointer.offset)
                     for slot, pointer in main.external.items()
                     if pointer.dependency.file_id != assets.MODEL_ID]
    expected_rows.sort()
    receipt = None
    for directory in (preview_dir, battle_dir):
        blob, extern = (directory / '29.fpc').read_bytes(), (directory / '29.ext').read_bytes()
        packed = fpc.decode_pack(blob)
        if packed['header'][3] != 29 or packed['header'][12:15] != (5455, 5456, 75296):
            raise ValueError('Meta core contract: FPC source identity changed')
        header = struct.unpack_from(battle.EXTERN_HEADER_FMT, extern)
        if (header[:2] != (battle.EXTERN_MAGIC, battle.EXTERN_VERSION) or
                header[3:] != (0, 0, fpc.fnv1a32(b''), 0) or
                len(extern) != struct.calcsize(battle.EXTERN_HEADER_FMT) + header[2] * 6):
            raise ValueError('Meta core contract: BEX2 shape/bank mismatch')
        rows = list(struct.iter_unpack(battle.EXTERN_ROW_FMT,
                                      extern[struct.calcsize(battle.EXTERN_HEADER_FMT):]))
        if rows != expected_rows or len(rows) != 11:
            raise ValueError('Meta core contract: BEX2 omits or changes source Main dependency rows')
        current = {'fpc_header': list(packed['header']), 'external_rows': rows,
                   'source_rom_sha256': bindings['source_rom_sha256'],
                   'fpc_sha256': hashlib.sha256(blob).hexdigest(),
                   'bex_sha256': hashlib.sha256(extern).hexdigest(),
                   'main_asset': assets.MAIN_ID, 'model_asset': assets.MODEL_ID,
                   'motion_asset': assets.MOTION_ID}
        if receipt is not None and current != receipt:
            raise ValueError('Meta preview/battle core artifacts differ from their shared source contract')
        receipt = current
    return receipt


def render_header(receipt: dict) -> str:
    continuation = ' ' + chr(92)
    lines = ['/* Generated by generate_metaknight_core_contract.py; do not edit. */',
             f"/* Source review ROM SHA256: {receipt['source_rom_sha256']} */",
             f"/* FPC SHA256: {receipt['fpc_sha256']} */",
             f"/* BEX SHA256: {receipt['bex_sha256']} */",
             '#ifndef NDS_METAKNIGHT_CORE_CONTRACT_GENERATED_H',
             '#define NDS_METAKNIGHT_CORE_CONTRACT_GENERATED_H', '',
             f"#define NDS_META_CORE_MOTION_ASSET {receipt['motion_asset']}u",
             f"#define NDS_META_CORE_EXTERN_COUNT {len(receipt['external_rows'])}u",
             '#define NDS_META_CORE_FPC_HEADER_WORDS {' + continuation]
    for index in range(0, 16, 4):
        lines.append('    ' + ', '.join(f'0x{word:08X}u' for word in receipt['fpc_header'][index:index+4]) +
                     (',' + continuation if index < 12 else continuation))
    lines += ['}', '', '#define NDS_META_CORE_EXTERN_ROWS(X)' + continuation]
    for index, row in enumerate(receipt['external_rows']):
        lines.append('    X(%du, %du, %du)' % row + (continuation if index + 1 < len(receipt['external_rows']) else ''))
    return '\n'.join(lines + ['', '#endif', ''])


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--native-dir', type=Path, required=True)
    parser.add_argument('--preview-dir', type=Path, required=True)
    parser.add_argument('--battle-dir', type=Path, required=True)
    parser.add_argument('--header', type=Path, required=True)
    args = parser.parse_args(argv)
    receipt = qualify(args.native_dir, args.preview_dir, args.battle_dir)
    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text(render_header(receipt), encoding='utf-8', newline='\n')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
