#!/usr/bin/env python3
"""Bind the linked EXTRA Meta Knight inventory to typed native consumers.

The linked action export is the authority, including inherited common actions.
No donor address is emitted as a runtime pointer. Resource bindings come from
the native resource producer, and every unsupported callback rejects emission.
BattleShip stays read-only: narrowly transformed include files are produced in
a build-owned include directory. --imports-only needs no donor/native assets.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
from pathlib import Path
import re
import struct

ROOT = Path(__file__).resolve().parents[2]
BS = Path("decomp/BattleShip-main/decomp/src")
MK_CALLBACKS = {
    "Jab.Start.update": "ndsMetaKnightJabStartUpdate",
    "Jab.Loop.update": "ndsMetaKnightJabLoopUpdate",
    "TiltF.update": "ndsMetaKnightTiltFUpdate",
    "USP.air_start_update": "ndsMetaKnightUSPAirStartUpdate",
    "USP.main": "ndsMetaKnightUSPUpdate",
    "USP.collision": "ndsMetaKnightUSPMap",
    "USP.physics": "ndsMetaKnightUSPPhysics",
    "USP.interrupt": "ndsMetaKnightUSPInterrupt",
    "NSP.Start.update": "ndsMetaKnightNSPStartUpdate",
    "NSP.Loop.update": "ndsMetaKnightNSPLoopUpdate",
    "NSP.Loop.physics": "ndsMetaKnightNSPLoopPhysics",
    "NSP.Loop.collision": "ndsMetaKnightNSPLoopMap",
    "NSP.End.air_collision": "ndsMetaKnightNSPEndAirMap",
    "DSP.Start.update": "ndsMetaKnightDSPStartUpdate",
    "DSP.Start.physics": "ndsMetaKnightDSPStartPhysics",
    "DSP.Start.air_collision": "ndsMetaKnightDSPStartAirMap",
    "DSP.Start.ground_collision": "ndsMetaKnightDSPStartGroundMap",
    "DSP.Attack.air_main": "ndsMetaKnightDSPAttackAirUpdate",
    "DSP.Attack.air_physics": "ndsMetaKnightDSPAttackAirPhysics",
}
CPU_CUSTOM = {"FAIR": 49, "BAIR": 50, "DASH_ATTACK": 51}
SOURCE_HOOKS = {
    "ground_nsp": "80596f10", "air_nsp": "80596e80",
    "ground_usp": "80596b44", "air_usp": "80596b00",
    "ground_dsp": "8059730c", "air_dsp": "80597358",
    "ai_behaviour": "80597980", "on_action_changed": "80596750",
    "initial_script": "80599864", "grounded_script": "8059985c",
    "action_replace_map": "80599608", "custom_capture_dk_interrupt": "80599614",
    # An interior skip-VFX continuation: validation only, never a C callback.
    "entry_script": "8013dd68",
    # These data hooks belong to native model/UI/audio/copy owning consumers.
    "static_part": "0080000000000000", "crowd_chant_fgm": "060d",
    "kirby_inhale_struct": "000800003fcccccd00000011",
    "default_costume": "0001040502000303", "costume_shield_color": "8059961c",
}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def replace_exact(text: str, old: str, new: str, count: int) -> str:
    require(text.count(old) == count,
            f"source drift: {old!r}: expected {count}, found {text.count(old)}")
    return text.replace(old, new)


def transformed_imports(root: Path) -> dict[str, str]:
    paths = {}
    for name in ("ftmanager", "ftmain", "ftcomputer"):
        path = root / BS / "ft" / f"{name}.c"
        source = path.read_text(encoding="utf-8")
        prefix = ("/* Generated by generate_p4_runtime_data.py; source SHA256 "
                  + hashlib.sha256(path.read_bytes()).hexdigest() + ". */\n")
        if name == "ftmanager":
            pattern = r"dFTManagerDataFiles\[([^\[\]]+)\]"
            source, count = re.subn(pattern, r"ndsP4GetFighterData(\1)", source)
            require(count == 7, f"ftmanager data seam drift: {count} accesses")
            source = replace_exact(source,
                "    fp->coll_data.pos_prev = DObjGetStruct(fighter_gobj)->translate.vec.f;\n\n    switch (fp->fkind)",
                "    fp->coll_data.pos_prev = DObjGetStruct(fighter_gobj)->translate.vec.f;\n"
                "    if (ndsP4IsMetaKnight(fp->fkind))\n"
                "        ndsMetaKnightInitPassiveVars(fighter_gobj);\n\n    switch (fp->fkind)", 1)
        elif name == "ftmain":
            source = replace_exact(source, "            fkind = fp->throw_fkind;",
                "            fkind = ndsP4GetThrownScriptColumn(fp->throw_fkind);", 1)
            source = replace_exact(source, "    fp->status_id = status_id;",
                "    status_id = ndsP4ReplaceStatus(fp->fkind, status_id);\n"
                "    if (ndsP4IsMetaKnight(fp->fkind))\n"
                "        ndsMetaKnightSetCapeEnvironment(fighter_gobj, FALSE);\n"
                "    fp->status_id = status_id;", 1)
            source = replace_exact(source,
                "    if (status_id >= FTSTAT_OPENING1_START) // Check if Opening status ID 1",
                "    if (ndsP4IsMetaKnight(fp->fkind) && (status_id < FTSTAT_OPENING2_START))\n"
                "    {\n"
                "        status_struct = ndsP4GetStatusDesc(fp->fkind, status_id);\n"
                "        status_struct_id = 0;\n"
                "    }\n"
                "    else if (status_id >= FTSTAT_OPENING1_START) // Check if Opening status ID 1", 1)
            source = replace_exact(source, "D_ovl1_80390D20[fp->fkind]",
                                   "ndsP4GetOpeningDescs(fp->fkind)", 1)
            source = replace_exact(source,
                "                event_script_ptr = (void*) motion_desc->offset;",
                "                event_script_ptr = ndsP4GetMenuEventScript(fp, motion_desc);", 1)
            source = replace_exact(source, "    else fp->proc_update = NULL;\n}",
                "    else fp->proc_update = NULL;\n"
                "    if (ndsP4IsMetaKnight(fp->fkind))\n"
                "        ndsMetaKnightOnActionChanged(fp, fp->status_id);\n}", 1)
        else:
            source = replace_exact(source,
                "dFTComputerAttackList[this_fp->fkind]",
                "ndsP4GetComputerAttacks(this_fp->fkind)", 1)
            source = replace_exact(source, "dFTComputerPlayerInputScripts[index]",
                "ndsP4GetComputerInputScript(index)", 3)
            source = replace_exact(source,
                "                        default:\n"
                "                            this_fp->input.cp.stick_range.x = *p_command++;\n"
                "                            break;",
                "                        /* EXTRA AI.asm facing-direction commands used\n"
                "                         * by Meta Knight's explicit FAIR/BAIR scripts. */\n"
                "                        case 0x83:\n"
                "                            this_fp->input.cp.stick_range.x =\n"
                "                                (this_fp->lr >= 0.0F) ? 80 : -80;\n"
                "                            p_command++;\n"
                "                            break;\n"
                "                        case 0x84:\n"
                "                            this_fp->input.cp.stick_range.x =\n"
                "                                (this_fp->lr >= 0.0F) ? -80 : 80;\n"
                "                            p_command++;\n"
                "                            break;\n"
                "                        default:\n"
                "                            this_fp->input.cp.stick_range.x = *p_command++;\n"
                "                            break;", 1)
        paths[f"battleship_{name}.generated.inc"] = prefix + source
    return paths


def callback_bindings(root: Path, resolved: dict) -> dict[int, str]:
    # Only line-leading source address comments followed by actual function
    # definitions count. Data tables and declarations cannot become callbacks.
    pattern = re.compile(r"^//\s*0x([0-9A-Fa-f]{8})[^\n]*\n"
                         r"(?:\s*\n)*[A-Za-z_][\w\s*]*?\b(\w+)\s*"
                         r"\([^;{}]*\)\s*\{", re.MULTILINE)
    native: dict[int, str] = {}
    wanted = {row["donor_address"] for row in resolved["callbacks"]}
    for path in sorted((root / BS).rglob("*.c")):
        for address, symbol in pattern.findall(path.read_text(encoding="utf-8")):
            address_int = int(address, 16)
            if address_int not in wanted:
                continue
            if address_int in native:
                require(native[address_int] == symbol,
                        f"ambiguous callback address {address}")
            native[address_int] = symbol
    # ftcommonturn.c has lost the source address comment. This constant is the
    # linked common Turn action's interrupt address and its verified definition.
    turn = (root / BS / "ft/ftcommon/ftcommonturn.c").read_text(encoding="utf-8")
    require("void ftCommonTurnProcInterrupt(GObj *fighter_gobj)" in turn,
            "Turn callback declaration drift")
    native[0x8013E700] = "ftCommonTurnProcInterrupt"
    result: dict[int, str] = {}
    unsupported = []
    for row in resolved["callbacks"]:
        address = row["donor_address"]
        names = row["symbols"]
        mapped = native.get(address)
        for label in names:
            if label.startswith("MetaKnightSpecial."):
                mapped = MK_CALLBACKS.get(label.removeprefix("MetaKnightSpecial."), mapped)
            elif label == "AerialAttackFastFall.fast_fall_check":
                # P4's declared vanilla-rules profile and the pinned donor's
                # FALSE toggle use the source ordinary air-drift continuation.
                mapped = "ndsMetaKnightAerialAttackPhysics"
        if not mapped:
            unsupported.append(f"0x{address:08X} {names}")
        else:
            result[address] = mapped
    require(not unsupported, "unsupported native callbacks: " + "; ".join(unsupported))
    require(len(result) == 205, "Meta Knight callback inventory changed")
    return result


def integer_expression(text: str) -> int:
    def walk(node: ast.AST) -> int:
        if isinstance(node, ast.Constant) and type(node.value) is int:
            return node.value
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
            return -walk(node.operand)
        if isinstance(node, ast.BinOp) and isinstance(node.op, (ast.Add, ast.Sub)):
            a, b = walk(node.left), walk(node.right)
            return a + b if isinstance(node.op, ast.Add) else a - b
        raise ValueError(f"unsupported CPU constant expression: {text}")
    return walk(ast.parse(text.strip(), mode="eval").body)


def cpu_attacks(donor: Path) -> str:
    ai = (donor / "smashremix_overwrite/AI.asm").read_text(encoding="utf-8")
    table = ai.split("scope ATTACK_TABLE", 1)[1].split("macro edit_attack_behavior", 1)[0]
    inputs = dict((name, int(value, 16)) for name, value in re.findall(
        r"scope (\w+):?\s*\{\s*constant INPUT\(0x([0-9A-Fa-f]+)\)", table))
    source = (donor / "extra_characters/MetaKnight/CPU.asm").read_text(encoding="utf-8")
    rows = []
    for line in source.splitlines():
        line = line.split("//", 1)[0].strip()
        if not line:
            continue
        if line == "AI.END_ATTACKS()":
            rows.append("    { -1, 0, 0, 0, 0, 0, 0 },")
            continue
        match = re.fullmatch(r"AI.add_(custom_attack|attack)_behaviour\((.*)\)", line)
        if not match:
            continue
        args = [x.strip() for x in match[2].split(",")]
        require(len(args) == 6, f"invalid Meta Knight CPU row: {line}")
        if match[1] == "custom_attack":
            require(args[0].startswith("AI.ROUTINE."), "invalid custom CPU routine")
            key = args[0].removeprefix("AI.ROUTINE.")
            require(key in CPU_CUSTOM, f"unsupported custom CPU input: {key}")
            input_id = CPU_CUSTOM[key]
        else:
            require(args[0] in inputs, f"unknown source CPU attack: {args[0]}")
            input_id = inputs[args[0]]
        values = [integer_expression(x) for x in args[1:]]
        rows.append(f"    {{ {input_id}, {values[0]}, 0, "
                    + ", ".join(f"{v}.0F" for v in values[1:]) + " },")
    require(len(rows) == 31 and sum("{ -1," in x for x in rows) == 2,
            f"Meta Knight CPU table drift: {len(rows)} rows")
    return ("static FTComputerAttack sNdsP4MetaKnightComputerAttacks[] = {\n"
            + "\n".join(rows) + "\n};\n")


def cpu_scripts() -> str:
    lines = ["enum { NDS_P4_CPU_FAIR = 49, NDS_P4_CPU_BAIR = 50, NDS_P4_CPU_DASH_ATTACK = 51 };",
             "_Static_assert(nFTComputerInputNessSpecialHiAim == 48, \"legacy CPU input IDs moved\");"]
    for name, facing in (("FAir", 0x83), ("BAir", 0x84), ("DashAttack", 0x7F)):
        lines += [f"static u8 sNdsP4Computer{name}[] = {{",
            "    FTCOMPUTER_EVENT_INSTRUCTION(nFTComputerCommandButtonZRelease, 0),",
            "    FTCOMPUTER_EVENT_INSTRUCTION(nFTComputerCommandButtonARelease, 0),",
            "    FTCOMPUTER_EVENT_INSTRUCTION(nFTComputerCommandButtonBRelease, 0),",
            "    FTCOMPUTER_EVENT_STICK_Y(0, 0),",
            f"    FTCOMPUTER_EVENT_STICK_X(0x{facing:02X}, {5 if name == 'DashAttack' else 0}),",
            "    FTCOMPUTER_EVENT_INSTRUCTION(nFTComputerCommandButtonAPress, 1),"]
        lines.append("    FTCOMPUTER_EVENT_STICK_Y(0, 0)," if name == "DashAttack" else
                     "    FTCOMPUTER_EVENT_STICK_X(0x7F, 0),")
        lines += ["    FTCOMPUTER_EVENT_INSTRUCTION(nFTComputerCommandButtonARelease, 0),",
                  "    FTCOMPUTER_EVENT_END()", "};"]
    return "\n".join(lines) + "\n"


def validate_bindings(resolved: dict, bindings: dict) -> None:
    require(bindings.get("schema") == "smash64ds.p4-native-runtime-bindings.v1",
            "native resource binding schema missing")
    require(bindings.get("source_rom_sha256") == resolved["rom_sha256"],
            "native resource bindings belong to another donor")
    require(len(resolved["actions"]) == 252 and len(resolved["parameters"]) == 225
            and len(resolved["menu_parameters"]) == 15,
            "Meta Knight linked table counts changed")
    files = bindings["core_files"]
    require(len(files) == 9, "FTData core bindings must contain nine source slots")
    for index, (source_id, row) in enumerate(zip(resolved["core_file_ids"], files)):
        require(row["donor_file_id"] == source_id,
                f"core source identity differs at slot {index}")
        require(type(row["native_file_id"]) is int and 0 <= row["native_file_id"] < 0x80000000,
                f"slot {index}: native FileID required, donor pointer forbidden")
        require(type(row["size"]) is int and row["size"] >= 0, "native file size unknown")
        if row["native_file_id"]:
            require(row["size"] > 0, f"native file size unknown at slot {index}")
    require(files[1]["native_file_id"] != resolved["core_file_ids"][1],
            "Meta Knight's event closure must use its own native MainMotion file")
    require(files[2]["native_file_id"] == files[1]["native_file_id"],
            "menu and gameplay descriptors must bind the same native motion closure")
    require(bindings["mainmotion_table_offset"] == 0 and
            bindings["menu_table_offset"] == 225 * 12,
            "native motion table layout differs from the source-qualified resource producer")
    require(0 <= bindings["attribute_offset"] < files[0]["size"],
            "native attributes lie outside Main")
    for key in ("max_main_animation_size", "max_menu_animation_size"):
        require(type(bindings[key]) is int and bindings[key] > 0,
                f"{key} is unknown")


def validate_hook_inventory(resolved: dict) -> None:
    hooks = resolved["character_hooks"]
    require(len(hooks) == len(SOURCE_HOOKS), "character hook inventory changed")
    seen = set()
    for row in hooks:
        name = row["name"]
        require(name not in seen and name in SOURCE_HOOKS,
                f"unsupported/duplicate character hook: {name}")
        require(row["bytes_big_endian"].lower() == SOURCE_HOOKS[name],
                f"unqualified character hook semantics: {name}")
        seen.add(name)


def callback_return_types(root: Path, symbols: set[str]) -> dict[str, str]:
    """Keep actual unary-GObj function types, including bool map callbacks."""
    result = {}
    pattern = re.compile(r"\b(void|sb32|s32|u32|f32)\s+(\w+)\s*"
                         r"\(\s*GObj\s*\*\s*\w+\s*\)\s*\{")
    sources = list((root / BS).rglob("*.c"))
    sources.append(root / "src/port/nds_metaknight_special.c")
    for source in sources:
        for return_type, symbol in pattern.findall(source.read_text(encoding="utf-8", errors="replace")):
            if symbol not in symbols:
                continue
            require(symbol not in result or result[symbol] == return_type,
                    f"conflicting callback return type: {symbol}")
            result[symbol] = return_type
    require(set(result) == symbols, f"unclassified callback signatures: {sorted(symbols - set(result))}")
    return result


def runtime_data(root: Path, donor: Path, resolved: dict, bindings: dict) -> str:
    validate_bindings(resolved, bindings)
    validate_hook_inventory(resolved)
    callbacks = callback_bindings(root, resolved)
    return_types = callback_return_types(root, set(callbacks.values()))
    lines = ["/* Generated typed native Meta Knight data. No donor code pointers. */",
             "_Static_assert(nFTKindEnumCount == 27 && nFTKindNull == 28, \"legacy fighter IDs moved\");"]
    for symbol in sorted(set(callbacks.values())):
        lines.append(f"extern {return_types[symbol]} {symbol}(GObj *fighter_gobj);")
    lines.append("static FTStatusDesc sNdsP4MetaKnightStatus[] = {")
    for expected_status, action in enumerate(resolved["actions"]):
        require(action["status_id"] == expected_status, "action table identity is not contiguous")
        motion = action["parameter_index"]
        if motion is None:
            require(action["parameter_sentinel"] in (0x3FE, 0x3FF), "invalid motion sentinel")
            motion = -2 if action["parameter_sentinel"] == 0x3FE else -1
        flags = action["unknown_flags"]
        cb = ["NULL" if action["callbacks_donor"][key] == 0 else
              callbacks[action["callbacks_donor"][key]]
              for key in ("update", "interrupt", "physics", "map")]
        # The original status callback ABI discards map return values.
        # Preserve the callee's declaration and make that adaptation explicit.
        cb = [f"(void (*)(GObj *)){symbol}" if symbol != "NULL" and
              return_types[symbol] != "void" else symbol for symbol in cb]
        lines += [f"    /* Source action {expected_status} */",
            "    { .mflags = { .motion_id = " + str(motion) +
            f", .attack_id = {action['stale_id']} }},",
            "      .sflags = { .unused = " + str((flags >> 13) & 7) +
            f", .is_smash_attack = {(flags >> 12) & 1}, .ga = {(flags >> 11) & 1},"
            f" .is_projectile = {(flags >> 10) & 1}, .attack_id = {flags & 1023} }},",
            "      .proc_update = " + cb[0] + ", .proc_interrupt = " + cb[1] + ",",
            "      .proc_physics = " + cb[2] + ", .proc_map = " + cb[3] + " },"]
    lines += ["};", cpu_attacks(donor), cpu_scripts(),
              "static void *sNdsP4MetaKnightMain;",
              "static void *sNdsP4MetaKnightMotion;",
              "static void *sNdsP4MetaKnightModel;",
              "static s32 sNdsP4MetaKnightParticle;",
              "static s32 sNdsP4MetaKnightMenuCount = 15;"]
    scalar = {
        "NDS_P4_MAIN_FILE_SIZE": bindings["core_files"][0]["size"],
        "NDS_P4_MAIN_ANIM_SIZE": bindings["max_main_animation_size"],
        "NDS_P4_MENU_ANIM_SIZE": bindings["max_menu_animation_size"],
        "NDS_P4_MAIN_TABLE_OFFSET": bindings["mainmotion_table_offset"],
        "NDS_P4_MENU_TABLE_OFFSET": bindings["menu_table_offset"],
    }
    lines.extend(f"#define {key} {value}u" for key, value in scalar.items())
    lines.append("static FTData sNdsP4MetaKnightData = {")
    fields = ("main", "mainmotion", "submotion", "model", "shieldpose",
              "special1", "special2", "special3", "special4")
    for field, row in zip(fields, bindings["core_files"]):
        lines.append(f"    .file_{field}_id = {row['native_file_id']}u,")
    for field, storage in (("main", "Main"), ("mainmotion", "Motion"),
                           ("submotion", "Motion"), ("model", "Model")):
        lines.append(f"    .p_file_{field} = &sNdsP4MetaKnight{storage},")
    lines += ["    .p_particle = &sNdsP4MetaKnightParticle,",
              f"    .o_attributes = {bindings['attribute_offset']}u,",
              "    .mainmotion_array_count = 225,",
              "    .submotion_array_count = &sNdsP4MetaKnightMenuCount,", "};"]
    return "\n".join(lines) + "\n"


def emit(destination: Path, files: dict[str, str], check: bool) -> None:
    for filename, content in files.items():
        path = destination / "nds/generated" / filename
        if check:
            require(path.is_file() and path.read_text(encoding="utf-8") == content,
                    f"stale generated P4 runtime file: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--imports-only", action="store_true")
    parser.add_argument("--resolved-actions", type=Path)
    parser.add_argument("--native-bindings", type=Path)
    parser.add_argument("--donor-source", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        root = args.root.resolve()
        require(args.out_dir.resolve().is_relative_to(root / "builds"),
                "runtime output must be in this isolated checkout's builds/")
        files = transformed_imports(root)
        if not args.imports_only:
            require(all((args.resolved_actions, args.native_bindings, args.donor_source)),
                    "runtime emission needs linked actions, native bindings and pinned donor source")
            resolved_bytes = args.resolved_actions.read_bytes()
            resolved = json.loads(resolved_bytes)
            bindings = json.loads(args.native_bindings.read_text(encoding="utf-8"))
            require(bindings.get("resolved_actions_sha256") == hashlib.sha256(resolved_bytes).hexdigest(),
                    "native bindings were built from another action inventory")
            files["nds_p4_runtime.generated.inc"] = runtime_data(
                root, args.donor_source, resolved, bindings)
        emit(args.out_dir, files, args.check)
        print(f"P4 runtime {'checked' if args.check else 'generated'}: {len(files)} typed files")
    except (KeyError, OSError, ValueError) as exc:
        parser.exit(1, f"P4 runtime import refused: {exc}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
