#!/usr/bin/env python3
"""Derive runtime FGM pins from the verified private EXTRA pack and receipt."""
import argparse
import hashlib
import json
from pathlib import Path
import struct


def generate(pack_path: Path, metadata_path: Path) -> str:
    pack = pack_path.read_bytes()
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    if len(pack) < 16:
        raise ValueError("truncated FGM header")
    magic, version, count, size, mapping = struct.unpack_from("<4sHHII", pack)
    if magic != b"FGM1" or version != 4 or size != len(pack):
        raise ValueError("invalid native FGM1-v4 pack")
    if (count != metadata["entry_count"] or size != metadata["pack_bytes"] or
            mapping != int(metadata["mapping_sha256_lo"], 16) or
            hashlib.sha256(pack).hexdigest() != metadata["pack_sha256"] or
            metadata["original_records_preserved"] is not True):
        raise ValueError("pack and source-qualified receipt disagree")
    return ("/* Generated by generate_p4_audio_header.py; do not edit. */\n"
            "#ifndef NDS_P4_AUDIO_GENERATED_H\n#define NDS_P4_AUDIO_GENERATED_H\n"
            f"#define NDS_P4_AUDIO_ENTRY_COUNT {count}u\n"
            f"#define NDS_P4_AUDIO_PACK_BYTES {size}u\n"
            f"#define NDS_P4_AUDIO_MAPPING_SHA256_LO 0x{mapping:08x}u\n"
            f"#define NDS_P4_METAKNIGHT_ANNOUNCER_FGM {metadata['announcer_fgm']}u\n"
            f"#define NDS_P4_METAKNIGHT_CHANT_FGM {metadata['crowd_chant_fgm'][0]}u\n"
            "#endif\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pack", type=Path, required=True)
    parser.add_argument("--metadata", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    header = generate(args.pack, args.metadata)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header, encoding="utf-8", newline="\n")
