"""Source-derived electric bodies, compiled with the ordinary fighter IR."""
from pathlib import Path
import re
import struct

import generate_nds_native_owners as owners
import preview_source_metadata as source


OWNERS = tuple(key for _display, key, _selected in source.KINDS)
# Current live ftParamCheckSetSkeletonColAnimID mapping. Other source bodies
# remain required when that compatibility seam admits the rest of the roster.
PROGRAMS = (("mario", 1), ("fox", 1))
IMAGE_OWNERS = tuple(f"{name}_skeleton{sid}" for name, sid in PROGRAMS)


def root_offsets(repo: Path, name: str, skeleton_id=1) -> tuple[int, ...]:
    title = owners._owner_title(name)
    matches = list((repo / "decomp/BattleShip-main/decomp/src/relocData").glob(
        f"*_{title}Main.c"))
    if len(matches) != 1:
        raise ValueError(f"{name}: ambiguous Main source")
    path = matches[0]
    text = path.read_text()
    symbol = f"d{title}Main_skeleton_dls"
    match = re.search(r"/\* @ 0x([\da-fA-F]+),\s*(\d+) bytes:(?:(?!\*/).)*\*/"
                      r"\s*FTSkeleton " + symbol + r"\[(\d+)\]", text, re.S)
    if match is None:
        raise ValueError(f"{name}: missing annotated skeleton table")
    offset, size, count = int(match[1], 16), int(match[2]), int(match[3])
    payload, _ = source.oler_data(source.o2r_path_by_id(int(path.name.split('_')[0])))
    if size != count * 8 or payload is None or offset + size > len(payload):
        raise ValueError(f"{name}: invalid skeleton extent")
    table = re.search(r"/\* @ 0x([\da-fA-F]+),\s*12 bytes:(?:(?!\*/).)*\*/"
                      r"\s*FTSkeleton \*d" + title + r"Main_skeleton\[3\]", text, re.S)
    if table is None:
        raise ValueError(f"{name}: missing skeleton selector")
    gate, pointer, end = struct.unpack_from(">III", payload, int(table[1], 16))
    if source.decode_ptr(pointer) != offset or not 4 <= gate < count + 4:
        raise ValueError(f"{name}: unsupported skeleton selector")
    # Independent relocation metadata proves every pointer is a Model DL.
    reloc = path.with_suffix(".reloc").read_text()
    if skeleton_id == 2:
        if not end:
            raise ValueError(f"{name}: no second skeleton")
        offset = source.decode_ptr(end)
        target = re.search(r"^intern d" + title + r"Main_skeleton\+0x8 (\w+)$", reloc, re.M)
        if target is None:
            raise ValueError(f"{name}: missing second skeleton relocation")
        symbol = target[1]
    elif skeleton_id != 1:
        raise ValueError("invalid skeleton id")
    edges = {int(m[1] or "0", 16): (int(m[2], 16), int(m[3]))
             for m in re.finditer(r"^extern " + symbol +
                 r"(?:\+0x([\da-fA-F]+))? 0x([\da-fA-F]+) # -> file (\d+)", reloc, re.M)}
    selected = set(owners._owner_selected_descriptor_indices(name, count))
    roots = []
    model = owners.load_o2r_payload(repo, name)
    for joint, (word, flags) in enumerate(struct.iter_unpack(">II", payload[offset:offset + size])):
        mode = flags >> 24 & 15
        if mode not in (0, 1):
            raise ValueError(f"{name}: skeleton joint {joint + 4} needs pair/flag support")
        if not word:
            continue
        root = source.decode_ptr(word)
        if edges.get(joint * 8) != (root, owners.P2_O2R_ASSETS[name][1]):
            raise ValueError(f"{name}: skeleton joint {joint + 4} relocation mismatch")
        if joint not in selected:
            raise ValueError(f"{name}: skeleton uses a noncanonical joint {joint + 4}")
        if mode == 1:
            pre, post = owners._dl_pair_slots(model, name, root)
            if pre is not None:
                raise ValueError(f"{name}: skeleton pair {root:x} needs pre-matrix support")
            if post is None:
                continue
            root = post
        roots.append(root)
    if not roots:
        raise ValueError(f"{name}: empty skeleton")
    return tuple(roots)


def contexts(repo: Path):
    result = {}
    for name, sid in PROGRAMS:
        context = owners.build_p2_root_set_runtime_context(
            repo, name, "high", root_offsets(repo, name, sid))
        # The source skeleton has one DL vector, independent of body detail.
        for detail in ("high", "low"):
            result[(f"{name}_skeleton{sid}", detail)] = context
    return result


def render_runtime(contexts):
    lines = ["/* Generated by generate_nds_native_owner_images.py. Do not edit. */",
             "#define NDS_NATIVE_SKELETON_PROGRAM 0xfeu"]
    for name, sid in PROGRAMS:
        context = contexts[(f"{name}_skeleton{sid}", "high")]
        title = owners._owner_title(name) + str(sid)
        guard = "1" if name in ("mario", "fox") else f"NDS_P2_{name.upper()}"
        lines += [f"#if {guard}",
                  f"static NDSNativeFighterRuntimeTables sNds{title}SkeletonTables;",
                  f"static const NDSNativeRoot sNds{title}SkeletonRoots[] = {{"]
        for root, light in zip(context["roots"], context["light_preamble_indices"]):
            lines.append("    { " + ", ".join(f"{v}u" for v in (*root[:7], light)) + " },")
        lines += ["};", f"static const u32 sNds{title}SkeletonLights[][2] = {{"]
        lines += [f"    {{ 0x{a:08x}u, 0x{b:08x}u }}," for a, b in context["light_preambles"]]
        lines += ["};", f"static const NDSNativeFighterOwnerRuntime sNds{title}SkeletonOwner = {{",
                  f"    &sNds{title}SkeletonTables, sNds{title}SkeletonRoots, {len(context['roots'])}u,",
                  f"    sNdsSkeletonCrossSlots, sNds{title}SkeletonLights,",
                  f"    {len(context['light_preambles'])}u, {context['asset_data_size']}u",
                  "};", "#endif"]
    lines += ["static const NDSNativeFighterOwnerRuntime *ndsNativeSkeletonOwner(u32 slot, u32 sid)", "{"]
    for name, sid in PROGRAMS:
        guard = "1" if name in ("mario", "fox") else f"NDS_P2_{name.upper()}"
        lines += [f"#if {guard}", f"    if (slot == NDS_RENDERER_NATIVE_FIGHTER_OWNER_{name.upper()} && sid == {sid}u)",
                  f"        return &sNds{owners._owner_title(name)}{sid}SkeletonOwner;", "#endif"]
    lines += ["    return NULL;", "}", ""]
    return "\n".join(lines)
