#!/usr/bin/env python3
"""P4 character select: the 30-cell grid and its donor art, for the UI kit bake.

The P4 roster is the 12 originals plus the 18 Remix selections
(docs/P4/New_Characters.md). The select screen uses Smash Remix's own layout
(src/CharacterSelect.asm): a 10x3 grid of 24-pixel cells whose 32x32
portraits from CHARACTER_PORTRAITS (file 0xA05) draw at scale 0.8125, with the
originals in the same 6x2 block they hold in the vanilla grid. Remix's six
selections that are not P4 roster (Marina, Dr. Mario, Young Link, Goemon,
Conker, Mewtwo) give their cells to the six P4 selections Remix's main grid
does not carry (Metal Mario, Roy, Lanky, Meta Knight, MRGAW, Snake), each
next to its series where the grid allows.

Writes, under --out (a build directory: everything here is derived from the
user's ROM):
  o2r/0a05 o2r/0011 o2r/0014   the donor's portrait, name and logo files
  css.json                     grid cells and per-fighter rows the bake and the
                               runtime tables read
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import remix_rom as R  # noqa: E402

PORTRAIT_FILE = 0xA05   # File.CHARACTER_PORTRAITS
NAME_FILE = 0x11        # name textures (Remix-extended MNPlayersCommon)
LOGO_FILE = 0x14        # series logos (Remix-extended FTEmblemSprites)
FLASH_STRIDE = 0x860    # CharacterSelect.asm: the white flash follows each portrait

# CharacterSelect.asm layout constants.
GRID = {"columns": 10, "rows": 3, "pitch": 24, "x": 39, "y": 44,
        "scale_num": 13, "scale_den": 16,          # PORTRAIT_SCALE 0.8125
        "hit_x": 29, "hit_y": 35}                  # START_X - TOKEN_OFFSET_X, START_Y - TOKEN_OFFSET_Y

# The DS P4 grid, row-major. Originals keep Remix's (and the vanilla grid's)
# cells; each P4 replacement names the Remix cell it takes.
LAYOUT = (
    "MRGAW", "METAL", "LUIGI", "MARIO", "DONKEY", "LINK", "SAMUS", "CAPTAIN", "GND", "SONIC",
    "DEDEDE", "METAKNIGHT", "NESS", "YOSHI", "KIRBY", "FOX", "PIKACHU", "JIGGLYPUFF", "FALCO", "SHEIK",
    "SNAKE", "CRASH", "WARIO", "PEACH", "BOWSER", "WOLF", "LANKY", "ROY", "MARTH", "BANJO",
)
# Original cast: Remix constant name -> fkind.
ORIGINALS = {"MARIO": 0, "FOX": 1, "DONKEY": 2, "SAMUS": 3, "LUIGI": 4, "LINK": 5,
             "YOSHI": 6, "CAPTAIN": 7, "KIRBY": 8, "PIKACHU": 9, "JIGGLYPUFF": 10, "NESS": 11}
# P4 selections: Remix constant name -> DS content id (include/nds/nds_p4.h).
# Content ids follow the production waves; a selection without a compiled
# content draws its portrait locked.
CONTENT = {"FALCO": 1}
# EXTRA-tree selections (Meta Knight, MRGAW, Snake) have no portrait in the main
# tree's file 0xA05 until the EXTRA staging lands; they draw the NONE plate.
EXTRA_TREE = {"METAKNIGHT", "MRGAW", "SNAKE"}


class CssError(SystemExit):
    pass


def asm_scope_constants(text: str, scope: str) -> dict[str, int]:
    """`constant NAME(expr)` rows inside `scope <scope> {`, expr a hex sum."""
    m = re.search(r"scope\s+" + re.escape(scope) + r"\s*:?\s*\{", text)
    if m is None:
        raise CssError(f"scope {scope} not found")
    depth, i = 1, m.end()
    while depth and i < len(text):
        depth += {"{": 1, "}": -1}.get(text[i], 0)
        i += 1
    body = text[m.end():i]
    out = {}
    for name, expr in re.findall(r"constant\s+(\w+)\(([^)]*)\)", body):
        try:
            out[name] = sum(int(t.strip(), 0) for t in expr.split("+"))
        except ValueError:
            continue
    return out


def add_to_css_rows(text: str) -> dict[str, dict]:
    rows = {}
    pat = re.compile(r"add_to_css\(Character\.id\.(\w+),\s*([\w.]+),\s*([\d.]+),\s*(0x[0-9A-Fa-f]+),"
                     r"\s*(\w+),\s*name_texture\.(\w+),\s*portrait_offsets\.(\w+),\s*(-?\w+)\)")
    for m in pat.finditer(text):
        rows[m.group(1)] = {"fgm": m.group(2), "circle": float(m.group(3)),
                            "action": int(m.group(4), 16), "logo": m.group(5),
                            "name": m.group(6), "portrait": m.group(7)}
    return rows


def announcer_ids(fgm_text: str) -> dict[str, int]:
    return asm_scope_constants(fgm_text, "names")


def write_c_tables(path: Path, cells: list[dict], fighters: list[dict]) -> None:
    """The runtime half of the grid (src/nds/nds_menu_shell_css.c, P4 arm)."""
    def sel(cell: dict) -> str:
        if cell["fkind"] is not None:
            return f"{cell['fkind']}u"
        if cell["locked"]:
            return "(u8)nFTKindNull"
        return f"NDS_P4_SEL_BASE + {cell['content']}u"

    gate_index = {f["content"]: i for i, f in enumerate(fighters)}
    last = fighters[-1]["token"] if fighters else None
    lines = [
        "/* Generated by scripts/p4/p4_css.py from the staged Remix donor build",
        " * (CharacterSelect.asm). Build output only, never tracked. */",
        f"#define NDS_P4_CSS_CELLS {len(cells)}u",
        f"#define NDS_P4_CSS_COLUMNS {GRID['columns']}",
        f"#define NDS_P4_CSS_ROWS {GRID['rows']}",
        f"#define NDS_P4_CSS_PITCH {GRID['pitch']}",
        f"#define NDS_P4_CSS_X {GRID['x']}",
        f"#define NDS_P4_CSS_Y {GRID['y']}",
        "/* Each cell's selection: an original's fkind, NDS_P4_SEL_BASE + content,",
        " * or nFTKindNull for a selection this build does not compile. */",
        "static const u8 kNdsP4CssCellSel[NDS_P4_CSS_CELLS] = {",
    ]
    for row in range(GRID["rows"]):
        chunk = cells[row * GRID["columns"]:(row + 1) * GRID["columns"]]
        lines.append("    " + ", ".join(sel(c) for c in chunk) + ",")
    lines += ["};",
              "/* Remix selections with gate art, after the originals' twelve, in bake",
              " * order (generate_mn_ui_kit.py CSS_FIGHTER_TOKEN); 0xff = none. */",
              f"#define NDS_P4_CSS_GATE_FIGHTERS {len(fighters)}u",
              "static const u8 kNdsP4CssGateIndex[NDS_P4_CONTENT_LIMIT] = {"]
    lines += [f"    [{c}] = {i}u," for c, i in sorted(gate_index.items())]
    lines += ["};",
              "/* add_to_css: the announcer's name call when the token lands. */",
              "static const u16 kNdsP4CssAnnounceFgm[NDS_P4_CONTENT_LIMIT] = {"]
    lines += [f"    [{f['content']}] = {f['announce_fgm']:#x}u," for f in fighters]
    lines += ["};"]
    if last is not None:
        lines += [f"#define NDS_P4_CSS_GATE_LAST_FFA NDS_MN_UI_KIT_SURFACE_CSS_GATE_3_HOLD_{last}",
                  f"#define NDS_P4_CSS_GATE_LAST_TEAM NDS_MN_UI_KIT_SURFACE_CSS_GATE_TEAM_GREEN_3_HOLD_{last}"]
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--staging", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--contents", default="",
                    help="comma-separated Remix names of the contents this build compiles (e.g. FALCO)")
    args = ap.parse_args()

    src = args.staging / "src"
    css_text = (src / "CharacterSelect.asm").read_text(encoding="utf-8", errors="replace")
    fgm_text = (src / "FGM.asm").read_text(encoding="utf-8", errors="replace")
    portraits = asm_scope_constants(css_text, "portrait_offsets")
    names = asm_scope_constants(css_text, "name_texture")
    logo_offsets = asm_scope_constants(css_text, "offset")
    logo_pos = asm_scope_constants(css_text, "position")
    rows = add_to_css_rows(css_text)
    announce = announcer_ids(fgm_text)
    built = {c.strip().upper() for c in args.contents.split(",") if c.strip()}
    unknown = built - set(CONTENT)
    if unknown:
        raise CssError(f"no content id for {sorted(unknown)}")

    rom = R.Rom(args.staging / "ssb64asm.z64")
    o2r = args.out / "o2r"
    o2r.mkdir(parents=True, exist_ok=True)
    for fid in (PORTRAIT_FILE, NAME_FILE, LOGO_FILE):
        (o2r / f"{fid:04x}").write_bytes(rom.o2r(fid))

    cells = []
    for index, token in enumerate(LAYOUT):
        row, col = divmod(index, GRID["columns"])
        cell = {"cell": index, "row": row, "col": col, "token": token,
                "x": GRID["x"] + col * GRID["pitch"], "y": GRID["y"] + row * GRID["pitch"]}
        if token in ORIGINALS:
            cell.update(fkind=ORIGINALS[token], content=0, locked=False)
        else:
            content = CONTENT.get(token, 0)
            cell.update(fkind=None, content=content, locked=token not in built)
        # A selection this build does not compile shows Remix's NONE plate (the
        # question mark), as do the EXTRA-tree three until their staging lands.
        key = token if token in portraits else None
        if token in EXTRA_TREE or key is None or cell["locked"]:
            key = "NONE"
        cell["portrait"] = portraits[key]
        cell["flash"] = portraits[key] + FLASH_STRIDE
        cells.append(cell)

    fighters = []
    for token in sorted(built, key=lambda t: CONTENT[t]):
        row = rows.get(token)
        if row is None:
            raise CssError(f"{token}: no add_to_css row")
        fgm_name = row["fgm"].rsplit(".", 1)[-1]
        if fgm_name not in announce:
            raise CssError(f"{token}: announcer FGM {row['fgm']} not found")
        logo = row["logo"]
        fighters.append({
            "token": token, "content": CONTENT[token],
            "name_sprite": names[row["name"]],
            "logo": logo, "logo_sprite": logo_offsets[logo],
            "logo_x": logo_pos.get("X_" + logo, 0), "logo_y": logo_pos.get("Y_" + logo, 0),
            "announce_fgm": announce[fgm_name], "circle": row["circle"], "action": row["action"],
        })

    spec = {"schema": "p4-css-v1", "grid": GRID, "cells": cells, "fighters": fighters,
            "files": {"portraits": str(o2r / f"{PORTRAIT_FILE:04x}"),
                      "names": str(o2r / f"{NAME_FILE:04x}"),
                      "logos": str(o2r / f"{LOGO_FILE:04x}")}}
    (args.out / "css.json").write_text(json.dumps(spec, indent=1), encoding="utf-8", newline="\n")
    write_c_tables(args.out / "nds_p4_css.generated.inc", cells, fighters)
    print(f"p4_css: {len(cells)} cells, {len(fighters)} P4 fighters -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
