#!/usr/bin/env python3
"""P4 content list: the build's compiled contents as C rows.

Reads the registry (scripts/p4/contents.json) and each enabled content's
export, and writes into the build-local P4 directory:

- nds_p4_contents.generated.h: NDS_P4_CONTENT_ROWS(X), one row per enabled
  content, X(id, Title, NAME, name, parent_kind, model_file_id, main_file_id).
  Every per-content site in shared code (content rows, renderer owner slots,
  native-owner tables, profile owners, the character select's preview kinds)
  expands this list instead of naming a fighter.
- nds_p4_contents_data.generated.inc: one #include per content of its
  generated data (scripts/p4/generate_p4_fighter.py), for the single data TU
  src/port/nds_p4_data.c. The generated symbols carry the content's title, so
  the contents share one translation unit.

Nothing here derives from ROM bytes beyond the export's file ids.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REGISTRY = HERE / "contents.json"

# Remix define_character parents (the vanilla kinds) -> FTKind enumerators.
PARENT_KINDS = {
    "MARIO": "nFTKindMario", "FOX": "nFTKindFox", "DONKEY": "nFTKindDonkey",
    "SAMUS": "nFTKindSamus", "LUIGI": "nFTKindLuigi", "LINK": "nFTKindLink",
    "YOSHI": "nFTKindYoshi", "CAPTAIN": "nFTKindCaptain", "KIRBY": "nFTKindKirby",
    "PIKACHU": "nFTKindPikachu", "JIGGLY": "nFTKindPurin", "NESS": "nFTKindNess",
}


def load_registry(path: Path = REGISTRY) -> list[dict]:
    rows = json.loads(path.read_text(encoding="utf-8"))["contents"]
    ids, names = set(), set()
    for row in rows:
        if row["id"] in ids or row["name"] in names:
            raise SystemExit(f"{path}: duplicate content {row}")
        if not (1 <= row["id"] <= 20):
            raise SystemExit(f"{path}: content id {row['id']} out of range 1..20")
        ids.add(row["id"])
        names.add(row["name"])
    return rows


def enabled_rows(names: list[str], registry: list[dict] | None = None) -> list[dict]:
    """The registry rows for `names`, in registry order (image slots follow it)."""
    registry = registry if registry is not None else load_registry()
    known = {r["name"]: r for r in registry}
    for name in names:
        if name not in known:
            raise SystemExit(f"unknown P4 content {name!r} (scripts/p4/contents.json)")
    return [r for r in registry if r["name"] in names]


def export_facts(export_root: Path, name: str) -> dict:
    resolved = json.loads((export_root / name / "resolved.json").read_text(encoding="utf-8"))
    files = resolved["descriptor"]["file_ids"]
    parent = resolved["parent"]
    if parent not in PARENT_KINDS:
        raise SystemExit(f"{name}: unsupported parent {parent}")
    return {"parent_kind": PARENT_KINDS[parent], "main": files[0], "model": files[3],
            "attributes": resolved["descriptor"]["o_attributes"]}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--list", action="store_true",
                    help="print name:NAME:REMIX:id per registry row (the Makefile's view)")
    ap.add_argument("--contents", help="enabled content names, space separated")
    ap.add_argument("--export-root", type=Path)
    ap.add_argument("--out", type=Path, help="the build's P4 directory")
    args = ap.parse_args()

    if args.list:
        print(" ".join(f"{r['name']}:{r['name'].upper()}:{r['remix']}:{r['id']}"
                       for r in load_registry()))
        return 0
    if args.contents is None or args.export_root is None or args.out is None:
        ap.error("--contents, --export-root and --out are required")
    rows = enabled_rows(args.contents.split())
    header = [
        "/* Generated by scripts/p4/p4_contents.py from scripts/p4/contents.json and",
        " * the enabled contents' exports. Do not edit. */",
        "#ifndef NDS_P4_CONTENTS_GENERATED_H",
        "#define NDS_P4_CONTENTS_GENERATED_H",
        "",
        "/* X(id, Title, NAME, name, parent_kind, model_file_id, main_file_id) */",
        "#define NDS_P4_CONTENT_ROWS(X) \\",
    ]
    data = ["/* Generated by scripts/p4/p4_contents.py. Do not edit. */"]
    for row in rows:
        facts = export_facts(args.export_root, row["name"])
        header.append(f"    X({row['id']}, {row['title']}, {row['name'].upper()}, {row['name']}, "
                      f"{facts['parent_kind']}, {facts['model']:#x}u, {facts['main']:#x}u) \\")
        data.append(f"#include \"{row['name']}/nds_p4_{row['name']}.generated.c\"")
    header += ["    /* end */",
               f"#define NDS_P4_CONTENT_MAX_ID {max((r['id'] for r in rows), default=0)}",
               "", "#endif /* NDS_P4_CONTENTS_GENERATED_H */", ""]
    args.out.mkdir(parents=True, exist_ok=True)
    # Every TU sees the list through nds_p4.h: an unchanged file keeps its
    # mtime, so a re-run (make re-runs this whenever an input is newer) does
    # not rebuild the world.
    for path, text in ((args.out / "nds_p4_contents.generated.h", "\n".join(header)),
                       (args.out / "nds_p4_contents_data.generated.inc", "\n".join(data) + "\n")):
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8", newline="\n")
    print(f"{len(rows)} contents: {' '.join(r['name'] for r in rows)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
