#!/usr/bin/env python3
"""Bake Samus's Bomb weapon: one CI4 billboard whose live MObj swaps palettes."""
import argparse
import struct
from pathlib import Path
import generate_nds_native_stage as sm

REPO = Path(__file__).resolve().parents[2]
SPEC = sm.InputSpec("decomp/BattleShip-main/BattleShip_o2r/reloc_fighters_main/SamusModel",
                    "67f9646c0a019704dcae5e3307df2cf8e4e7846339537a70a64f77d42284bbf5", 320)
ROOT, WORDS, VERTS, IMAGE, MOBJSUB = 0xE0D8, 28, 0xE098, 0xDF88, 0xE018
HEADER = REPO / "include/nds/generated/nds_native_samus_bomb.generated.h"
PACKET = REPO / "src/nds/generated/nds_native_samus_bomb.generated.inc"


def generate():
    f = sm.load_o2r(REPO, SPEC)
    # MObjSub.flags at +0x30: MOBJ_FLAG_PALETTE only, so the live material is
    # exactly one palette image and the DL keeps its own LOADTLUT and texels.
    assert struct.unpack_from('>H', f.payload, MOBJSUB + 0x30)[0] == 0x0004
    calls = {0xFC: 'SetCombine', 0xF5: 'SetTile', 0xF2: 'SetTileSize',
             0xD7: 'TextureState', 0xF3: 'LoadBlock'}
    before, after, triangles = [], [], []
    for word in range(WORDS):
        slot = ROOT + word * 8
        w0, w1 = struct.unpack_from('>II', f.payload, slot)
        op = w0 >> 24
        target = after if triangles else before
        if op == 0x01:
            ref = f.pointer_at(slot + 4)
            assert (ref.asset_id, ref.offset) == (f.file_id, VERTS)
            assert ((w0 >> 12) & 255, (w0 >> 1) & 127) == (4, 4)
        elif op in (0x05, 0x06):
            triangles.extend(sm.decode_triangles(op, w0, w1))
        elif op == 0xFD:
            ref = f.pointer_at(slot + 4)
            assert (ref.asset_id, ref.offset) == (f.file_id, IMAGE)
            target.append(f'    ndsRendererRecordSetImage(stats, 0x{w0:08x}u, (u32)(uintptr_t)image);')
        elif op == 0xDE:
            assert w1 == 0x0e000000
            target.append('    ndsRendererNativeApplyMaterial(material, stats, state);')
        elif op == 0xD9:
            target.append(f'    stats->geometry_mode = (stats->geometry_mode & 0x{w0:08x}u) | 0x{w1:08x}u;')
        elif op == 0xF9:
            target.append(f'    stats->blend_color = 0x{w1:08x}u;')
        elif op == 0xF0:
            target.append(f'    ndsRendererRecordLoadTlut(stats, 0x{w1:08x}u);')
        elif op in (0xE2, 0xE3):
            target.append(f'    ndsRendererRecordOtherMode(stats, 0x{op:x}u, 0x{w0:08x}u, 0x{w1:08x}u);')
        elif op in calls:
            target.append(f'    ndsRendererRecord{calls[op]}(stats, 0x{w0:08x}u, 0x{w1:08x}u);')
        else:
            assert op in (0xE6, 0xE7, 0xE8, 0xDF), (word, op)
    assert len(triangles) == 2 and all(0 <= v < 4 for t in triangles for v in t)
    vertices = [sm.decode_vertex(f, VERTS + i * 16) for i in range(4)]
    packet = '\n'.join([
        '/* Source-pinned Samus Bomb quad; the live MObj palette swap stays authoritative. */',
        '#include <nds/generated/nds_native_samus_bomb.generated.h>',
        'static const s16 sSamusBombVerts[20] = {' + ','.join(str(x) for v in vertices for x in v[:5]) + '};',
        'static const u32 sSamusBombColors[4] = {' + ','.join(f'0x{v[5]:08x}u' for v in vertices) + '};',
        'static const u16 sSamusBombIndices[6] = {' + ','.join(str(x) for t in triangles for x in t) + '};',
        'static void ndsSamusBombSetup(NDSRendererStats *stats, NDSRendererTraversalState *state,',
        '    const NDSRendererNativeMaterial *material, const void *image) {', *before, '}',
        'static void ndsSamusBombFinish(NDSRendererStats *stats) {', *after, '}']) + '\n'
    header = f"""/* Generated by generate_nds_native_samus_bomb.py. */
#ifndef NDS_NATIVE_SAMUS_BOMB_GENERATED_H
#define NDS_NATIVE_SAMUS_BOMB_GENERATED_H
#define NDS_NATIVE_SAMUS_BOMB_ASSET 320u
#define NDS_NATIVE_SAMUS_BOMB_ROOT 0x{ROOT:04x}u
#define NDS_NATIVE_SAMUS_BOMB_IMAGE 0x{IMAGE:04x}u
#define NDS_NATIVE_SAMUS_BOMB_IMAGE_END 0x{IMAGE + 128:04x}u
#define NDS_NATIVE_SAMUS_BOMB_MATERIAL 0x0001u
#endif
"""
    return header, packet


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--emit', action='store_true'); ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    for path, data in zip((HEADER, PACKET), generate()):
        if args.emit and (not path.exists() or path.read_text() != data): path.write_text(data)
        if args.check or not args.emit: assert path.read_text() == data, path
    print('SAMUS_BOMB_NATIVE_OK root=0xe0d8 triangles=2 live-palette/fixed-CI4')


if __name__ == '__main__': main()
