#!/usr/bin/env python3
"""Bake Thunder head/trail and both source side-smash ThunderShock roots."""
import argparse
import struct
from pathlib import Path
import generate_nds_native_stage as sm

REPO = Path(__file__).resolve().parents[2]
SPECS = (
    sm.InputSpec("decomp/BattleShip-main/BattleShip_o2r/reloc_fighters_main/PikachuModel",
                 "12c543dc39b62b7669cc5453d97af142a1af987c4f5a8098814da214e14da9f1", 341),
    sm.InputSpec("decomp/BattleShip-main/BattleShip_o2r/reloc_fighters_main/PikachuSpecial2",
                 "ce5517554528101f5ecb66ec54bf5531a6f84a3dc050adc2ffd0abbff019838c", 347))
ROOTS = ((0, 0x94f8, 23, 0x94b8), (1, 0x14b8, 28, 0x1438), (1, 0x1598, 17, 0x1478))
HEADER = REPO / "include/nds/generated/nds_native_pikachu_thunder.generated.h"
PACKET = REPO / "src/nds/generated/nds_native_pikachu_thunder.generated.inc"


def generate():
    files = [sm.load_o2r(REPO, spec) for spec in SPECS]
    out = ['/* Source-pinned Thunder quads; live source MObj animation remains authoritative. */',
           '#include <nds/generated/nds_native_pikachu_thunder.generated.h>']
    calls = {0xFC: 'SetCombine', 0xF5: 'SetTile', 0xF2: 'SetTileSize',
             0xD7: 'TextureState', 0xF3: 'LoadBlock'}
    for index, (file_index, root, count, vertex_offset) in enumerate(ROOTS):
        f = files[file_index]
        vertices = [sm.decode_vertex(f, vertex_offset + i * 16) for i in range(4)]
        before, after, triangles = [], [], []
        if index == 2:
            # Inherits texture enable from the first Shock child in source.
            before.append('    ndsRendererRecordTextureState(stats, 0xd7000002u, 0xffffffffu);')
        for word in range(count):
            slot = root + word * 8
            w0, w1 = struct.unpack_from('>II', f.payload, slot)
            op = w0 >> 24
            target = after if triangles else before
            if op == 0x01:
                ref = f.pointer_at(slot + 4)
                assert (ref.asset_id, ref.offset) == (f.file_id, vertex_offset)
                assert ((w0 >> 12) & 255, (w0 >> 1) & 127) == (4, 4)
            elif op in (0x05, 0x06):
                triangles.extend(sm.decode_triangles(op, w0, w1))
            elif op == 0xFD:
                ref = f.pointer_at(slot + 4)
                assert index == 1 and ref.asset_id == 347 and ref.offset in (0x968, 0x11a0)
                pointer = 'palette' if ref.offset == 0x968 else 'image'
                target.append(f'    ndsRendererRecordSetImage(stats, 0x{w0:08x}u, (u32)(uintptr_t){pointer});')
            elif op == 0xDE:
                assert index in (0, 2) and w1 == 0x0e000000
                target.append('    ndsRendererNativeApplyMaterial(material, stats, state);')
            elif op == 0xDB:
                assert (w0 & 0xffff0000) == 0xdb0a0000
                target.append(f'    ndsRendererRecordLightColorMoveWord(stats, 0x{w0 & 0xffff:x}u, 0x{w1:08x}u);')
            elif op == 0xD9:
                target.append(f'    stats->geometry_mode = (stats->geometry_mode & 0x{w0:08x}u) | 0x{w1:08x}u;')
            elif op in (0xFA, 0xFB, 0xF9):
                field = {0xFA: 'prim_color', 0xFB: 'env_color', 0xF9: 'blend_color'}[op]
                target.append(f'    stats->{field} = 0x{w1:08x}u;')
            elif op == 0xF0:
                target.append(f'    ndsRendererRecordLoadTlut(stats, 0x{w1:08x}u);')
            elif op in (0xE2, 0xE3):
                target.append(f'    ndsRendererRecordOtherMode(stats, 0x{op:x}u, 0x{w0:08x}u, 0x{w1:08x}u);')
            elif op in calls:
                target.append(f'    ndsRendererRecord{calls[op]}(stats, 0x{w0:08x}u, 0x{w1:08x}u);')
            else:
                assert op in (0xE6, 0xE7, 0xE8, 0xDF), (index, word, op)
        assert len(triangles) == 2 and all(0 <= v < 4 for t in triangles for v in t)
        out += [f'static const s16 sThunderVerts{index}[20] = {{' + ','.join(str(x) for v in vertices for x in v[:5]) + '};',
                f'static const u32 sThunderColors{index}[4] = {{' + ','.join(f'0x{v[5]:08x}u' for v in vertices) + '};',
                f'static const u16 sThunderIndices{index}[6] = {{' + ','.join(str(x) for t in triangles for x in t) + '};',
                f'static void ndsThunderSetup{index}(NDSRendererStats *stats, NDSRendererTraversalState *state,',
                '    const NDSRendererNativeMaterial *material, const void *palette, const void *image) {',
                '    (void)state; (void)material; (void)palette; (void)image;', *before, '}',
                f'static void ndsThunderFinish{index}(NDSRendererStats *stats) {{', *after, '}']
    header = """/* Generated by generate_nds_native_pikachu_thunder.py. */
#ifndef NDS_NATIVE_PIKACHU_THUNDER_GENERATED_H
#define NDS_NATIVE_PIKACHU_THUNDER_GENERATED_H
#define NDS_NATIVE_PIKACHU_THUNDER_MODEL 341u
#define NDS_NATIVE_PIKACHU_THUNDER_SPECIAL 347u
#define NDS_NATIVE_PIKACHU_THUNDER_ROOT 0x94f8u
#define NDS_NATIVE_PIKACHU_SHOCK_ROOT0 0x14b8u
#define NDS_NATIVE_PIKACHU_SHOCK_ROOT1 0x1598u
#define NDS_NATIVE_PIKACHU_THUNDER_MATERIAL 0x1600u
#define NDS_NATIVE_PIKACHU_SHOCK_PALETTE 0x968u
#define NDS_NATIVE_PIKACHU_SHOCK_IMAGE 0x11a0u
#endif
"""
    return header, '\n'.join(out) + '\n'


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--emit', action='store_true'); ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    for path, data in zip((HEADER, PACKET), generate()):
        if args.emit and (not path.exists() or path.read_text() != data): path.write_text(data)
        if args.check or not args.emit: assert path.read_text() == data, path
    print('PIKACHU_THUNDER_NATIVE_OK roots=3 triangles=6 live-material/fixed-CI4')


if __name__ == '__main__': main()
