#!/usr/bin/env python3
"""Bake Ness's PK Thunder tail EFFECT: the last trail segment, a fixed IA8 quad."""
import argparse
import struct
from pathlib import Path
import generate_nds_native_stage as sm

REPO = Path(__file__).resolve().parents[2]
SPEC = sm.InputSpec("decomp/BattleShip-main/BattleShip_o2r/reloc_fighters_main/NessModel",
                    "d4d8f1dfe24667fb1274dbeb82dd18fcb7b274d31db223bbab9f633a6b9a378a", 335, 364, 4,
                    "c191a9494c41d56060748bc1447028bd7e8c1781245fc72110b624dd49d198ad")
ROOT, WORDS, VERTS, IMAGE = 0x8F98, 23, 0x8F58, 0x8B58
HEADER = REPO / "include/nds/generated/nds_native_ness_pktail.generated.h"
PACKET = REPO / "src/nds/generated/nds_native_ness_pktail.generated.inc"


def generate():
    f = sm.load_o2r(REPO, SPEC)
    # efManagerNessPKThunderTrailMakeEffect's list: no segment-E material call,
    # so prim, env, tile and the one IA8 image are all the source list's own.
    calls = {0xFC: 'SetCombine', 0xF5: 'SetTile', 0xF2: 'SetTileSize',
             0xD7: 'TextureState', 0xF3: 'LoadBlock'}
    before, after, triangles = [], [], []
    for word in range(WORDS):
        slot = ROOT + word * 8
        w0, w1 = struct.unpack_from('>II', f.payload, slot)
        op = w0 >> 24
        target = after if triangles else before
        if op == 0x01:
            ref = f.pointer_at(slot + 4)
            assert (ref.asset_id, ref.offset) == (f.file_id, VERTS)
            assert ((w0 >> 12) & 255, (w0 >> 1) & 127) == (4, 4)
        elif op in (0x05, 0x06):
            triangles.extend(sm.decode_triangles(op, w0, w1))
        elif op == 0xFD:
            ref = f.pointer_at(slot + 4)
            assert (ref.asset_id, ref.offset) == (f.file_id, IMAGE)
            target.append(f'    ndsRendererRecordSetImage(stats, 0x{w0:08x}u, (u32)(uintptr_t)image);')
        elif op == 0xDB:
            assert (w0 & 0xffff0000) == 0xdb0a0000
            target.append(f'    ndsRendererRecordLightColorMoveWord(stats, 0x{w0 & 0xffff:x}u, 0x{w1:08x}u);')
        elif op in (0xFA, 0xFB):
            field = {0xFA: 'prim_color', 0xFB: 'env_color'}[op]
            target.append(f'    stats->{field} = 0x{w1:08x}u;')
        elif op == 0xD9:
            target.append(f'    stats->geometry_mode = (stats->geometry_mode & 0x{w0:08x}u) | 0x{w1:08x}u;')
        elif op == 0xF9:
            target.append(f'    stats->blend_color = 0x{w1:08x}u;')
        elif op == 0xF0:
            target.append(f'    ndsRendererRecordLoadTlut(stats, 0x{w1:08x}u);')
        elif op in (0xE2, 0xE3):
            target.append(f'    ndsRendererRecordOtherMode(stats, 0x{op:x}u, 0x{w0:08x}u, 0x{w1:08x}u);')
        elif op in calls:
            target.append(f'    ndsRendererRecord{calls[op]}(stats, 0x{w0:08x}u, 0x{w1:08x}u);')
        else:
            assert op in (0xE6, 0xE7, 0xE8, 0xDF), (word, op)
    assert len(triangles) == 2 and all(0 <= v < 4 for t in triangles for v in t)
    vertices = [sm.decode_vertex(f, VERTS + i * 16) for i in range(4)]
    packet = '\n'.join([
        '/* Source-pinned PK Thunder tail effect quad; position and lifetime stay with the source effect. */',
        '#include <nds/generated/nds_native_ness_pktail.generated.h>',
        'static const s16 sNessPKTailVerts[20] = {' + ','.join(str(x) for v in vertices for x in v[:5]) + '};',
        'static const u32 sNessPKTailColors[4] = {' + ','.join(f'0x{v[5]:08x}u' for v in vertices) + '};',
        'static const u16 sNessPKTailIndices[6] = {' + ','.join(str(x) for t in triangles for x in t) + '};',
        'static void ndsNessPKTailSetup(NDSRendererStats *stats, const void *image) {', *before, '}',
        'static void ndsNessPKTailFinish(NDSRendererStats *stats) {', *after, '}']) + '\n'
    header = f"""/* Generated by generate_nds_native_ness_pktail.py. */
#ifndef NDS_NATIVE_NESS_PKTAIL_GENERATED_H
#define NDS_NATIVE_NESS_PKTAIL_GENERATED_H
#define NDS_NATIVE_NESS_PKTAIL_ASSET 335u
#define NDS_NATIVE_NESS_PKTAIL_ROOT 0x{ROOT:04x}u
#define NDS_NATIVE_NESS_PKTAIL_IMAGE 0x{IMAGE:04x}u
#define NDS_NATIVE_NESS_PKTAIL_IMAGE_END 0x{IMAGE + 1024:04x}u
#endif
"""
    return header, packet


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--emit', action='store_true'); ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    for path, data in zip((HEADER, PACKET), generate()):
        if args.emit and (not path.exists() or path.read_text() != data): path.write_text(data)
        if args.check or not args.emit: assert path.read_text() == data, path
    print('NESS_PKTAIL_NATIVE_OK root=0x8f98 triangles=2 fixed-IA8')


if __name__ == '__main__': main()
