#!/usr/bin/env python3
"""Bake Sing's four source quads; retain live DObj and PRIM animation."""
import argparse
import struct
from pathlib import Path

import generate_nds_native_stage as sm

REPO = Path(__file__).resolve().parents[2]
SPEC = sm.InputSpec(
    "decomp/BattleShip-main/BattleShip_o2r/reloc_fighters_main/PurinSpecial2",
    "ab535d861d906d71ee968f827a8f8092bf980e07cc6d0cfbb7d3bf866ef56d67",
    351, 38, 0,
    "581bdca95909ee3c6ada9a29560f06aeb7b2b2c1cbeea060bfa98eab452d021b")
ROOTS = (0x1F38, 0x1FD0, 0x2048, 0x2090)
IMAGES = (0x1820, 0x1018, 0x810, 8)
VERTICES = (0x1E38, 0x1E78, 0x1EB8, 0x1EF8)
HEADER = REPO / "include/nds/generated/nds_native_purin_sing.generated.h"
PACKET = REPO / "src/nds/generated/nds_native_purin_sing.generated.inc"


def generate():
    source = sm.load_o2r(REPO, SPEC)

    def commands(root, count):
        return [(root + i * 8, *struct.unpack_from(">II", source.payload, root + i * 8))
                for i in range(count)]

    # The original siblings inherit the ring's texture-enable and the first
    # note's combiner/tile state. Bake those dominators into each independent
    # native submission; never depend on another, possibly alpha-zero child.
    preamble = commands(0x1F38, 4)
    programs = (preamble + commands(0x1F68, 13),
                preamble + commands(0x1FD0, 15),
                preamble + commands(0x1FD0, 7) + commands(0x2048, 9),
                preamble + commands(0x1FD0, 7) + commands(0x2090, 12))
    link = source.pointer_at(0x1F38 + 4 * 8 + 4)
    assert (link.asset_id, link.offset) == (351, 0x1F68)
    header = ["/* Generated by generate_nds_native_purin_sing.py. */",
              "#ifndef NDS_NATIVE_PURIN_SING_GENERATED_H",
              "#define NDS_NATIVE_PURIN_SING_GENERATED_H",
              "#define NDS_NATIVE_PURIN_SING_ASSET 351u",
              "#define NDS_NATIVE_PURIN_SING_ROOT_COUNT 4u",
              "#define NDS_NATIVE_PURIN_SING_VERTEX_COUNT 4u",
              "#define NDS_NATIVE_PURIN_SING_TRIANGLE_COUNT 2u",
              "#define NDS_NATIVE_PURIN_SING_MATERIAL_EFFECTS 0x10u"]
    for i, (root, image) in enumerate(zip(ROOTS, IMAGES)):
        header += [f"#define NDS_NATIVE_PURIN_SING_ROOT_{i} 0x{root:x}u",
                   f"#define NDS_NATIVE_PURIN_SING_IMAGE_{i} 0x{image:x}u"]
    header += ["#endif", ""]
    vertices = [sm.decode_vertex(source, offset + i * 16)
                for offset in VERTICES for i in range(4)]
    packet = ['/* Source-pinned native Sing, no runtime display-list execution. */',
              '#include <nds/generated/nds_native_purin_sing.generated.h>',
              'static const s16 sNdsNativePurinSingVerts[80] = {']
    packet += ["    " + ", ".join(str(v) for v in row[:5]) + "," for row in vertices]
    packet += ['};', 'static const u32 sNdsNativePurinSingColors[16] = {',
               ', '.join(f'0x{row[5]:08x}u' for row in vertices), '};',
               'static const u16 sNdsNativePurinSingTriangles[6] = {3, 2, 1, 0, 3, 1};',
               'static void ndsNativePurinSingSetup(u32 root_index, const void *image,',
               '    const NDSRendererNativeMaterial *material, NDSRendererStats *stats,',
               '    NDSRendererTraversalState *state)', '{', '    switch (root_index) {']
    calls = {0xD7: 'TextureState', 0xFC: 'SetCombine', 0xF5: 'SetTile',
             0xF2: 'SetTileSize', 0xF3: 'LoadBlock'}
    for i, program in enumerate(programs):
        packet += [f'    case {i}u:']
        seen = set()
        for slot, w0, w1 in program:
            op = w0 >> 24
            if op == 0x01:
                ref = source.pointer_at(slot + 4)
                assert (ref.asset_id, ref.offset) == (351, VERTICES[i])
                assert ((w0 >> 12) & 255, ((w0 >> 1) & 127)) == (4, 4)
                seen.add('vertices')
            elif op == 0x06:
                assert tuple(sm.decode_triangles(op, w0, w1)) == ((3, 2, 1), (0, 3, 1))
                seen.add('triangles')
                break  # The sole restoring tail is handled by Finish below.
            elif op == 0xFD:
                ref = source.pointer_at(slot + 4)
                assert (ref.asset_id, ref.offset) == (351, IMAGES[i])
                packet += [f'        ndsRendererRecordSetImage(stats, 0x{w0:08x}u, (u32)(uintptr_t)image);']
                seen.add('image')
            elif op == 0xDE:
                assert w1 == 0x0E000000
                packet += ['        ndsRendererNativeApplyMaterial(material, stats, state);']
                seen.add('material')
            elif op == 0xD9:
                packet += [f'        stats->geometry_mode = (stats->geometry_mode & 0x{w0:08x}u) | 0x{w1:08x}u;']
            elif op in (0xFB, 0xF9):
                field = 'env_color' if op == 0xFB else 'blend_color'
                packet += [f'        stats->{field} = 0x{w1:08x}u;']
            elif op in (0xE2, 0xE3):
                packet += [f'        ndsRendererRecordOtherMode(stats, 0x{op:x}u, 0x{w0:08x}u, 0x{w1:08x}u);']
            elif op in calls:
                packet += [f'        ndsRendererRecord{calls[op]}(stats, 0x{w0:08x}u, 0x{w1:08x}u);']
            else:
                assert op in (0xE6, 0xE7), (hex(slot), hex(op))
        assert seen == {'vertices', 'triangles', 'image', 'material'}
        packet += ['        break;']
    packet += ['    }', '}',
               'static void ndsNativePurinSingFinish(u32 root_index, NDSRendererStats *stats)',
               '{', '    if (root_index == 3u) {',
               '        stats->geometry_mode |= 0x00220000u;',
               '        ndsRendererRecordOtherMode(stats, 0xe2u, 0xe2001e01u, 0u);',
               '    }', '}', '']
    return '\n'.join(header), '\n'.join(packet)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--emit', action='store_true')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in zip((HEADER, PACKET), generate()):
        if args.emit:
            if not path.exists() or path.read_text() != content:
                path.write_text(content)
        if args.check or not args.emit:
            assert path.read_text() == content, f'Stale generated output: {path}'
    print('PURIN_SING_NATIVE_OK roots=4 vertices=16 triangles=8 material=PRIM')


if __name__ == '__main__':
    main()
