#!/usr/bin/env python3
"""Bake Vulcan Jab geometry and disjoint A5I3 color banks, without alpha loss."""
import argparse
import struct
from pathlib import Path

import generate_nds_native_stage as sm

REPO = Path(__file__).resolve().parents[2]
SPEC = sm.InputSpec(
    "decomp/BattleShip-main/BattleShip_o2r/reloc_fighters_main/KirbySpecial2",
    "170aa45c1fb013717928f18d0fd51830a087ed48112bcfdc8e7eb3c8c1efc885",
    348, 52, 0, "9a1ab4b4029ba11451c6150763b9e50279dd575a0e4522b06b8977cbee6a51ec")
HEADER = REPO / "include/nds/generated/nds_native_kirby_vulcan.generated.h"
PACKET = REPO / "src/nds/generated/nds_native_kirby_vulcan.generated.inc"


def color_banks(rgba):
    rgb5 = lambda c: (c[0] >> 3) | ((c[1] >> 3) << 5) | ((c[2] >> 3) << 10)
    colors = sorted({rgb5(c) for c in rgba if c[3]})
    palettes = [colors[i:i + 8] + [0] * (8 - len(colors[i:i + 8]))
                for i in range(0, len(colors), 8)]
    banks = [bytearray(len(rgba)) for _ in palettes]
    for pixel, c in enumerate(rgba):
        if c[3]:
            index = colors.index(rgb5(c))
            banks[index // 8][pixel] = ((c[3] * 31 + 127) // 255 << 3) | (index % 8)
    # Each pixel is covered by at most one pass; no layered alpha accumulation.
    for pixel, c in enumerate(rgba):
        live = [(p, bank[pixel]) for p, bank in enumerate(banks) if bank[pixel] >> 3]
        want_alpha = (c[3] * 31 + 127) // 255
        assert len(live) == (1 if want_alpha else 0)
        if live:
            bank, value = live[0]
            assert value >> 3 == want_alpha
            assert palettes[bank][value & 7] == rgb5(c)
    return palettes, banks


def generate():
    f = sm.load_o2r(REPO, SPEC)
    rgba = list(struct.iter_unpack("BBBB", f.payload[0x90:0x890]))
    palettes, banks = color_banks(rgba)
    assert len(banks) == 4
    # The second list's combiner uses primitive RGB and intensity as alpha.
    intensity = [v for byte in f.payload[8:136] for v in (byte >> 4, byte & 15)]
    banks.append(bytearray(((v * 31 + 7) // 15) << 3 for v in intensity))
    palettes.append([0x7fff] * 8)

    def words(root, count):
        return [(root + i * 8, *struct.unpack_from(">II", f.payload, root + i * 8))
                for i in range(count)]

    branch = f.pointer_at(0x9b0 + 6 * 8 + 4)
    assert (branch.asset_id, branch.offset) == (348, 0x9f0)
    prefix = words(0x9b0, 6)
    programs = (prefix + words(0x9f0, 17), prefix + words(0xa78, 17))
    vertices, triangles, setup, finish = [], [], [], []
    functions = {0xFC: "SetCombine", 0xF5: "SetTile", 0xF2: "SetTileSize",
                 0xD7: "TextureState", 0xF3: "LoadBlock"}
    for root, program in enumerate(programs):
        vs, ts, before, after = [], [], [], []
        for slot, w0, w1 in program:
            op = w0 >> 24
            target = after if ts else before
            if op == 0x01:
                ref = f.pointer_at(slot + 4)
                count = (w0 >> 12) & 255
                assert ref.asset_id == 348 and ref.offset == (0x890, 0x970)[root]
                assert count == (14, 4)[root] and ((w0 >> 1) & 127) == count
                vs = [sm.decode_vertex(f, ref.offset + i * 16) for i in range(count)]
            elif op in (0x05, 0x06):
                ts.extend(sm.decode_triangles(op, w0, w1))
            elif op == 0xFD:
                ref = f.pointer_at(slot + 4)
                assert (ref.asset_id, ref.offset) == (348, (0x90, 8)[root])
                target.append(f'    ndsRendererRecordSetImage(stats, 0x{w0:08x}u, 0u);')
            elif op == 0xD9:
                target.append(f'    stats->geometry_mode = (stats->geometry_mode & 0x{w0:08x}u) | 0x{w1:08x}u;')
            elif op in (0xFA, 0xFB, 0xF9):
                field = {0xFA: "prim_color", 0xFB: "env_color", 0xF9: "blend_color"}[op]
                target.append(f'    stats->{field} = 0x{w1:08x}u;')
            elif op in (0xE2, 0xE3):
                target.append(f'    ndsRendererRecordOtherMode(stats, 0x{op:x}u, 0x{w0:08x}u, 0x{w1:08x}u);')
            elif op in functions:
                target.append(f'    ndsRendererRecord{functions[op]}(stats, 0x{w0:08x}u, 0x{w1:08x}u);')
            else:
                assert op in (0xE6, 0xE7, 0xDF), (slot, op)
        assert len(ts) == (12, 2)[root]
        assert all(0 <= index < len(vs) for tri in ts for index in tri)
        vertices.append(vs); triangles.append(ts); setup.append(before); finish.append(after)
    header = """/* Generated by generate_nds_native_kirby_vulcan.py. */
#ifndef NDS_NATIVE_KIRBY_VULCAN_GENERATED_H
#define NDS_NATIVE_KIRBY_VULCAN_GENERATED_H
#define NDS_NATIVE_KIRBY_VULCAN_ASSET 348u
#define NDS_NATIVE_KIRBY_VULCAN_ROOT0 0x09b0u
#define NDS_NATIVE_KIRBY_VULCAN_ROOT1 0x0a78u
#define NDS_NATIVE_KIRBY_VULCAN_BANKS 5u
#endif
"""
    out = ['/* Generated source geometry; RGBA32 becomes disjoint RGB5/A5 banks. */',
           '#include <nds/generated/nds_native_kirby_vulcan.generated.h>']
    for i, (pal, pixels) in enumerate(zip(palettes, banks)):
        out += [f'static const u16 sVulcanPalette{i}[8] = {{' + ','.join(f'0x{x:04x}' for x in pal) + '};',
                f'static const u8 sVulcanPixels{i}[{len(pixels)}] = {{']
        out += [','.join(f'0x{x:02x}' for x in pixels[j:j + 32]) + ',' for j in range(0, len(pixels), 32)]
        out += ['};']
    out += ['static const u16 *const sVulcanPalettes[5] = {' + ','.join(f'sVulcanPalette{i}' for i in range(5)) + '};',
            'static const u8 *const sVulcanPixels[5] = {' + ','.join(f'sVulcanPixels{i}' for i in range(5)) + '};']
    for i, (vs, ts) in enumerate(zip(vertices, triangles)):
        out += [f'static const s16 sVulcanVertices{i}[{len(vs) * 5}] = {{' + ','.join(str(x) for v in vs for x in v[:5]) + '};',
                f'static const u32 sVulcanColors{i}[{len(vs)}] = {{' + ','.join(f'0x{v[5]:08x}u' for v in vs) + '};',
                f'static const u16 sVulcanIndices{i}[{len(ts) * 3}] = {{' + ','.join(str(x) for t in ts for x in t) + '};',
                f'static void ndsVulcanSetup{i}(NDSRendererStats *stats) {{', *setup[i], '}',
                f'static void ndsVulcanFinish{i}(NDSRendererStats *stats) {{', *finish[i], '    (void)stats;', '}']
    return header, '\n'.join(out) + '\n'


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--emit', action='store_true'); ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    for path, data in zip((HEADER, PACKET), generate()):
        if args.emit and (not path.exists() or path.read_text() != data): path.write_text(data)
        if args.check or not args.emit: assert path.read_text() == data, path
    print('KIRBY_VULCAN_NATIVE_OK roots=2 source_triangles=14 banks=5 RGB5/A5 exact')


if __name__ == '__main__': main()
