#include "diagnostics_state.c"
#include "diagnostics_collision_runtime.c"
#include "diagnostics_renderer_census.c"
#include "diagnostics_mp_taskman_state.c"
#include "diagnostics_taskman_heap.c"
#include "diagnostics_opening_state.c"
