#include "nds_scene_harness_config.h"

static void *sNdsFighterFTManagerCommonFile;
static void *sNdsFighterMarioMainMotionFile;
static void *sNdsFighterMarioMainFile;
static void *sNdsFighterMarioSpecial1File;
static void *sNdsFighterMarioModelFile;
static void *sNdsFighterMarioSpecial3File;
static void *sNdsFighterMarioShieldPoseFile;
static void *sNdsFighterMarioSpecial2File;
static void *sNdsFighterFoxSpecial3File;
static void *sNdsFighterFoxMainMotionFile;
static void *sNdsFighterFoxMainFile;
static void *sNdsFighterFoxSpecial1File;
static void *sNdsFighterFoxModelFile;
static void *sNdsFighterFoxShieldPoseFile;
static void *sNdsFighterFoxSpecial4File;
static void *sNdsFighterFoxSpecial2File;
#if NDS_IMPORT_BATTLESHIP_FTMANAGER
/* The imported manager owns these pools (ftmanager.c:25/:31, allocated at
 * :144/:154).  Keep the historical DS proof names as source-storage aliases so
 * the old bounded probes still compile without reserving a second FTStruct or
 * FTParts image.  The parts allocation is flat in BattleShip but is laid out as
 * player-major [player][joint], exactly what the old 2-D declaration encoded. */
extern FTStruct *sFTManagerStructsAllocBuf;
extern FTParts *sFTManagerPartsAllocBuf;
#define sNdsFighterStructPool sFTManagerStructsAllocBuf
#define sNdsFighterPartsPool \
    ((FTParts (*)[nFTPartsJointNumMax])sFTManagerPartsAllocBuf)
/* BattleShip's VS battle allocates/iterates all GMCOMMON_PLAYERS_MAX slots.
 * Keep the DS live registry at the same capacity: this registry is the bridge
 * used by DS-native render/collision helpers to recover the source fighter
 * GObj for a player number.  A two-entry registry made source-created players
 * 2/3 disappear at that bridge even though scVSBattleStartBattle had created
 * them correctly. */
static GObj *sNdsFighterManagerLiveGObjs[GMCOMMON_PLAYERS_MAX];
#else
/* The compatibility-only fighter constructor predates the imported BattleShip
 * manager and needs its own structs.  Do NOT keep a second FTStruct array in an
 * imported-manager build: BattleShip already allocates the authoritative
 * `sFTManagerStructsAllocBuf` from the taskman arena, so a four-entry static
 * mirror is 12,048 bytes of duplicate fighter state.  P2-2's four-fighter RAM
 * audit found that duplicate while the real source structs were already the
 * values returned by ftGetStruct(). */
static FTStruct sNdsFighterStructPool[GMCOMMON_PLAYERS_MAX];
static FTParts sNdsFighterPartsPool[GMCOMMON_PLAYERS_MAX]
                                   [nFTPartsJointNumMax];
static u32 sNdsFighterStructPoolUsedMask;
#endif
extern u16 gMPCollisionUpdateTic;

static void ndsFighterManagerClearLiveGObjs(void)
{
#if NDS_IMPORT_BATTLESHIP_FTMANAGER
    bzero(sNdsFighterManagerLiveGObjs, sizeof(sNdsFighterManagerLiveGObjs));
#endif
}

static void ndsFighterMarioFoxResetFileSlots(void)
{
    ndsFighterManagerClearLiveGObjs();
    sNdsFighterFTManagerCommonFile = NULL;
    sNdsFighterMarioMainMotionFile = NULL;
    sNdsFighterMarioMainFile = NULL;
    sNdsFighterMarioSpecial1File = NULL;
    sNdsFighterMarioModelFile = NULL;
    sNdsFighterMarioSpecial3File = NULL;
    sNdsFighterMarioShieldPoseFile = NULL;
    sNdsFighterMarioSpecial2File = NULL;
    sNdsFighterFoxSpecial3File = NULL;
    sNdsFighterFoxMainMotionFile = NULL;
    sNdsFighterFoxMainFile = NULL;
    sNdsFighterFoxSpecial1File = NULL;
    sNdsFighterFoxModelFile = NULL;
    sNdsFighterFoxShieldPoseFile = NULL;
    sNdsFighterFoxSpecial4File = NULL;
    sNdsFighterFoxSpecial2File = NULL;

    gNdsFighterMarioMainMotionPtrReady = 0u;
    gNdsFighterMarioMainPtrReady = 0u;
    gNdsFighterMarioModelPtrReady = 0u;
    gNdsFighterMarioAttrPtrReady = 0u;
    gNdsFighterMarioCommonPartsReady = 0u;
    gNdsFighterFoxMainMotionPtrReady = 0u;
    gNdsFighterFoxMainPtrReady = 0u;
    gNdsFighterFoxModelPtrReady = 0u;
    gNdsFighterFoxAttrPtrReady = 0u;
    gNdsFighterFoxCommonPartsReady = 0u;

    if (ndsFighterMarioFoxStructProofEnabled() != FALSE)
    {
        ndsFighterStructResetPool();
    }
}
extern void gcSetupCustomDObjs(GObj *gobj, DObjDesc *dobjdesc, DObj **dobjs,
                               u8 tk1, u8 tk2, u8 tk3);
extern void func_80017EC0(GObj *gobj);

#define NDS_MARIOFOX_WALK_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WALK_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WALK_LOOP) || \
     NDS_MARIOFOX_DASH_RUN_HARNESS)

#define NDS_MARIOFOX_DASH_RUN_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DASH_RUN) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DASH_RUN) || \
     NDS_MARIOFOX_JUMP_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_JUMP_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_JUMP_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_JUMP_LOOP) || \
     NDS_MARIOFOX_LANDING_LOOP_HARNESS)

#define NDS_MARIOFOX_JUMP_ATTACKAIR_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_JUMP_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_JUMP_LOOP))

#define NDS_MARIOFOX_LANDING_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_LANDING_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_LANDING_LOOP) || \
     NDS_MARIOFOX_PROCESS_LOOP_HARNESS)

#define NDS_MARIOFOX_PROCESS_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_PROCESS_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_PROCESS_LOOP) || \
     NDS_MARIOFOX_SCHEDULER_LOOP_HARNESS)

#define NDS_MARIOFOX_SCHEDULER_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_SCHEDULER_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_SCHEDULER_LOOP) || \
     NDS_MARIOFOX_CONTROLLER_LOOP_HARNESS)

#define NDS_MARIOFOX_CONTROLLER_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_CONTROLLER_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_CONTROLLER_LOOP) || \
     NDS_MARIOFOX_PREVIEW_LOOP_HARNESS)

#define NDS_MARIOFOX_PREVIEW_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_PREVIEW_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_PREVIEW_LOOP) || \
     NDS_MARIOFOX_GCRUNALL_LOOP_HARNESS)

#define NDS_MARIOFOX_GCRUNALL_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_GCRUNALL_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_GCRUNALL_LOOP) || \
     NDS_MARIOFOX_GCDRAWALL_LOOP_HARNESS)

#define NDS_MARIOFOX_GCDRAWALL_LOOP_HARNESS \
    (NDS_MARIOFOX_STAGE_GCDRAWALL_LOOP_HARNESS || \
     NDS_MARIOFOX_LIVE_PREVIEW_HARNESS)

#define NDS_MARIOFOX_STAGE_GCDRAWALL_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_GCDRAWALL_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_GCDRAWALL_LOOP) || \
     NDS_MARIOFOX_STAGE_COLLISION_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_COLLISION_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_COLLISION_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_COLLISION_LOOP) || \
     NDS_MARIOFOX_STAGE_FLOOR_FOLLOW_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_FLOOR_FOLLOW_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_FLOOR_FOLLOW_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_FLOOR_FOLLOW_LOOP) || \
     NDS_MARIOFOX_STAGE_FLOOR_EDGE_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_FLOOR_EDGE_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_FLOOR_EDGE_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_FLOOR_EDGE_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPROCESS_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPPROCESS_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPPROCESS_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPPROCESS_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPUPDATE_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPUPDATE_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPUPDATE_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPUPDATE_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPSWEEP_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPSWEEP_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPSWEEP_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPSWEEP_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCROSS_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCROSS_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCROSS_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCROSS_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPADJUST_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPADJUST_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPADJUST_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPADJUST_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPEDGE_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPEDGE_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPEDGE_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPEDGE_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPWALL_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPWALL_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPWALL_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPWALL_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPWALLHIT_FLOOR_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPSTALE_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPWALLCOPY_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPWALLCOPY_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPWALLCOPY_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPASS_FLOOR_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPPLATFORM_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPPLATFORM_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPPLATFORM_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPLATFORM_ACTIVE_FLOOR_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPPLATFORM_ACTIVE_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPPLATFORM_ACTIVE_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPPLATFORM_ACTIVE_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPLATFORM_TICK_FLOOR_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPPLATFORM_TICK_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPPLATFORM_TICK_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPPLATFORM_TICK_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPASS_INPUT_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPPASS_INPUT_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPPASS_INPUT_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPPASS_INPUT_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPLATFORM_POS_FLOOR_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPPLATFORM_POS_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPPLATFORM_POS_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPPLATFORM_POS_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPLATFORM_SPEED_FLOOR_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPPLATFORM_SPEED_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPPLATFORM_SPEED_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPPLATFORM_SPEED_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_INISHIE_SCALE_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_INISHIE_SCALE_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_INISHIE_SCALE_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_INISHIE_SCALE_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPPASS_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPPASS_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPPASS_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPLATFORM_FLOOR_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPWALLHIT_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPWALLHIT_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPWALLHIT_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPWALLCOPY_FLOOR_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPSTALE_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPSTALE_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPSTALE_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPLIVESTALE_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPLIVESTALE_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPLIVESTALE_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPLIVESTALE_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPMOTIONSTALE_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPMOTIONSTALE_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPMOTIONSTALE_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPMOTIONSTALE_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFSTATUS_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFSTATUS_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFSTATUS_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFSTATUS_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFTICK_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFTICK_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFTICK_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFTICK_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPFALLMAP_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPFALLMAP_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPFALLMAP_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPFALLMAP_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPFALLLAND_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPFALLLAND_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPFALLLAND_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPFALLLAND_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCEIL_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCEIL_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCEIL_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCEIL_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCEILSTATUS_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCEILSTATUS_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCEILSTATUS_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCEILSTATUS_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFCATCH_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFCATCH_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFCATCH_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFCATCH_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFWAIT_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFLIVE_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFLIVE_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFLIVE_LOOP) || \
     NDS_MARIOFOX_STAGE_MPWALLHIT_FLOOR_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFLEDGE_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFLEDGE_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFLEDGE_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFLIVE_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPDOWNRECOVER_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPDOWNRECOVER_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPDOWNRECOVER_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFLEDGE_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_TURN_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_TURN_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_TURN_LOOP) || \
     NDS_MARIOFOX_STAGE_MPDOWNRECOVER_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPDOWNWAIT_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPDOWNWAIT_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPDOWNWAIT_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_TURN_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP) || \
     NDS_MARIOFOX_STAGE_MPDAMAGE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPDAMAGE_RECOVER_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPDAMAGE_RECOVER_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPDAMAGE_RECOVER_LOOP) || \
     NDS_MARIOFOX_STAGE_MPLIVEHIT_DAMAGE_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPLIVEHIT_STATUS_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPLIVEHIT_STATUS_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPLIVEHIT_STATUS_LOOP))

#define NDS_MARIOFOX_STAGE_MPLIVEHIT_DAMAGE_LOOP_HARNESS \
    NDS_MARIOFOX_STAGE_MPLIVEHIT_STATUS_LOOP_HARNESS

#define NDS_MARIOFOX_STAGE_MPPASSIVE_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPPASSIVE_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPPASSIVE_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPDOWNWAIT_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFWAIT_DAMAGE_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFWAIT_DAMAGE_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFWAIT_DAMAGE_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFWAIT_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFWAIT_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFWAIT_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFWAIT_DAMAGE_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPCLIFFESCAPE_ACTION_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPCLIFFCLIMB_FLOOR_LOOP_HARNESS || \
     NDS_MARIOFOX_STAGE_MPCLIFFATTACK_FLOOR_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFATTACK_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFATTACK_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFATTACK_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFATTACK_ACTION_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFCLIMB_FLOOR_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFCLIMB_FLOOR_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFCLIMB_FLOOR_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFCLIMB_ACTION_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFCLIMB_ACTION_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFCLIMB_ACTION_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFCLIMB_ACTION_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFCLIMB_COMMON2_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFCLIMB_FINISH_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFCLIMB_FINISH_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFCLIMB_FINISH_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFLEDGE_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFCLIMB_COMMON2_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFCLIMB_COMMON2_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFCLIMB_COMMON2_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFCLIMB_FINISH_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFATTACK_ACTION_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFATTACK_ACTION_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFATTACK_ACTION_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFCOMMON2_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFCOMMON2_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFCOMMON2_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFCOMMON2_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFESCAPE_ACTION_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFESCAPE_ACTION_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFESCAPE_ACTION_LOOP) || \
     NDS_MARIOFOX_STAGE_MPCLIFFESCAPE_COMMON2_LOOP_HARNESS)

#define NDS_MARIOFOX_STAGE_MPCLIFFESCAPE_COMMON2_LOOP_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STAGE_MPCLIFFESCAPE_COMMON2_LOOP) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STAGE_MPCLIFFESCAPE_COMMON2_LOOP) || \
     NDS_MARIOFOX_STAGE_MPPASSIVE_RECOVER_LOOP_HARNESS)

#define NDS_MARIOFOX_LIVE_PREVIEW_HARNESS \
    ((NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_LIVE_PREVIEW) || \
     (NDS_DEV_SCENE_HARNESS == \
        NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_LIVE_PREVIEW))

static sb32 ndsFighterMarioFoxModelProofEnabled(void)
{
#if (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_MODEL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_MODEL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STRUCT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STRUCT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_INIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_INIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT_TICK) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT_TICK) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT_GROUND) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT_GROUND) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WALK_INPUT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WALK_INPUT) || \
    NDS_MARIOFOX_WALK_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStructProofEnabled(void)
{
#if (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_STRUCT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_STRUCT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_INIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_INIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT_TICK) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT_TICK) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT_GROUND) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT_GROUND) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WALK_INPUT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WALK_INPUT) || \
    NDS_MARIOFOX_WALK_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxInitProofEnabled(void)
{
#if (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_INIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_INIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT_TICK) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT_TICK) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT_GROUND) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT_GROUND) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WALK_INPUT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WALK_INPUT) || \
    NDS_MARIOFOX_WALK_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxWaitProofEnabled(void)
{
#if (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT_TICK) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT_TICK) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT_GROUND) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT_GROUND) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WALK_INPUT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WALK_INPUT) || \
    NDS_MARIOFOX_WALK_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxWaitTickProofEnabled(void)
{
#if (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT_TICK) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT_TICK) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT_GROUND) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT_GROUND) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WALK_INPUT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WALK_INPUT) || \
    NDS_MARIOFOX_WALK_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxWaitGroundProofEnabled(void)
{
#if (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WAIT_GROUND) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WAIT_GROUND) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WALK_INPUT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WALK_INPUT) || \
    NDS_MARIOFOX_WALK_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxDisplayProofEnabled(void)
{
#if (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DISPLAY_PROBE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_SCAN) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_EXECUTE) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_MULTI) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WALK_INPUT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WALK_INPUT) || \
    NDS_MARIOFOX_WALK_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}



static sb32 ndsFighterMarioFoxDLAllDrawProofEnabled(void)
{
#if (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_DL_DRAW_ALL) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WALK_INPUT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WALK_INPUT) || \
    NDS_MARIOFOX_WALK_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxWalkInputProofEnabled(void)
{
#if (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_MARIOFOX_WALK_INPUT) || \
    (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_MENU_CHAIN_MARIOFOX_WALK_INPUT) || \
    NDS_MARIOFOX_WALK_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxWalkLoopProofEnabled(void)
{
#if NDS_MARIOFOX_WALK_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxDashRunProofEnabled(void)
{
#if NDS_MARIOFOX_DASH_RUN_HARNESS && !NDS_IMPORT_BATTLESHIP_FTMANAGER
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxJumpLoopProofEnabled(void)
{
#if NDS_MARIOFOX_JUMP_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxJumpAttackAirProofEnabled(void)
{
#if NDS_MARIOFOX_JUMP_ATTACKAIR_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxLandingLoopProofEnabled(void)
{
#if NDS_MARIOFOX_LANDING_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxProcessLoopProofEnabled(void)
{
#if NDS_MARIOFOX_PROCESS_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxSchedulerLoopProofEnabled(void)
{
#if NDS_MARIOFOX_SCHEDULER_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxControllerLoopProofEnabled(void)
{
#if NDS_MARIOFOX_CONTROLLER_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxPreviewLoopProofEnabled(void)
{
#if NDS_MARIOFOX_PREVIEW_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxGCRunAllLoopProofEnabled(void)
{
#if NDS_MARIOFOX_GCRUNALL_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxGCDrawAllLoopProofEnabled(void)
{
#if NDS_MARIOFOX_GCDRAWALL_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageGCDrawAllLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_GCDRAWALL_LOOP_HARNESS || \
    (NDS_IMPORT_BATTLESHIP_BATTLE_PLAYABLE && \
     (NDS_DEV_SCENE_HARNESS == NDS_DEV_SCENE_HARNESS_BATTLE_PLAYABLE))
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageCollisionLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_COLLISION_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageFloorFollowLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_FLOOR_FOLLOW_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageFloorEdgeLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_FLOOR_EDGE_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPProcessFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPPROCESS_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPUpdateFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPUPDATE_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPSweepFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPSWEEP_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCrossFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCROSS_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPAdjustFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPADJUST_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPEdgeFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPEDGE_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPWallFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPWALL_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPWallHitFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPWALLHIT_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPWallCopyFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPWALLCOPY_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPPassFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPPASS_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPPlatformFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPPLATFORM_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPPlatformActiveFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPPLATFORM_ACTIVE_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPPlatformTickFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPPLATFORM_TICK_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPPassInputLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPPASS_INPUT_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPPlatformPosFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPPLATFORM_POS_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPPlatformSpeedFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPPLATFORM_SPEED_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageInishieScaleLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_INISHIE_SCALE_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPStaleFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPSTALE_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPLiveStaleFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPLIVESTALE_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPMotionStaleFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPMOTIONSTALE_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffStatusFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFSTATUS_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffTickFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFTICK_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPFallMapFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPFALLMAP_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPFallLandFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPFALLLAND_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCeilFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCEIL_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCeilStatusFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCEILSTATUS_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffCatchFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFCATCH_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffWaitFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFWAIT_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffAttackFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFATTACK_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffClimbFloorLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFCLIMB_FLOOR_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffClimbActionLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFCLIMB_ACTION_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffClimbCommon2LoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFCLIMB_COMMON2_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffClimbFinishLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFCLIMB_FINISH_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffWaitDamageLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFWAIT_DAMAGE_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPPassiveLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPPASSIVE_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPDownWaitLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPDOWNWAIT_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageTurnLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_TURN_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPDownRecoverLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPDOWNRECOVER_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffLedgeLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFLEDGE_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffLiveLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFLIVE_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static void ndsStageMPDownWaitLoopAppendSourceOrder(u32 code)
{
    gNdsStageMPDownWaitLoopSourceOrder =
        ((gNdsStageMPDownWaitLoopSourceOrder << 4) | (code & 0xfu));
}

static void ndsStageMPDownWaitLoopAppendAttackOrder(u32 code)
{
    gNdsStageMPDownWaitLoopAttackSourceOrder =
        ((gNdsStageMPDownWaitLoopAttackSourceOrder << 4) | (code & 0xfu));
}

static void ndsStageMPDownWaitLoopAppendRollForwardOrder(u32 code)
{
    gNdsStageMPDownWaitLoopRollForwardSourceOrder =
        ((gNdsStageMPDownWaitLoopRollForwardSourceOrder << 4) |
         (code & 0xfu));
}

static void ndsStageMPDownWaitLoopAppendRollBackOrder(u32 code)
{
    gNdsStageMPDownWaitLoopRollBackSourceOrder =
        ((gNdsStageMPDownWaitLoopRollBackSourceOrder << 4) | (code & 0xfu));
}

static void ndsStageMPDownRecoverLoopAppendDownStandOrder(u32 code)
{
    gNdsStageMPDownRecoverLoopDownStandSourceOrder =
        ((gNdsStageMPDownRecoverLoopDownStandSourceOrder << 4) |
         (code & 0xfu));
}

static void ndsStageMPDownRecoverLoopAppendAttackOrder(u32 code)
{
    gNdsStageMPDownRecoverLoopAttackSourceOrder =
        ((gNdsStageMPDownRecoverLoopAttackSourceOrder << 4) |
         (code & 0xfu));
}

static void ndsStageMPDownRecoverLoopAppendRollForwardOrder(u32 code)
{
    gNdsStageMPDownRecoverLoopRollForwardSourceOrder =
        ((gNdsStageMPDownRecoverLoopRollForwardSourceOrder << 4) |
         (code & 0xfu));
}

static void ndsStageMPDownRecoverLoopAppendRollBackOrder(u32 code)
{
    gNdsStageMPDownRecoverLoopRollBackSourceOrder =
        ((gNdsStageMPDownRecoverLoopRollBackSourceOrder << 4) |
         (code & 0xfu));
}

static sb32 ndsFighterMarioFoxStageMPCliffAttackActionLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFATTACK_ACTION_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffCommon2LoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFCOMMON2_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffEscapeActionLoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFESCAPE_ACTION_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxStageMPCliffEscapeCommon2LoopProofEnabled(void)
{
#if NDS_MARIOFOX_STAGE_MPCLIFFESCAPE_COMMON2_LOOP_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static sb32 ndsFighterMarioFoxLivePreviewProofEnabled(void)
{
#if NDS_MARIOFOX_LIVE_PREVIEW_HARNESS
    return TRUE;
#else
    return FALSE;
#endif
}

static void ndsFighterStructResetPool(void)
{
#if !NDS_IMPORT_BATTLESHIP_FTMANAGER
    bzero(sNdsFighterStructPool, sizeof(sNdsFighterStructPool));
    bzero(sNdsFighterPartsPool, sizeof(sNdsFighterPartsPool));
    sNdsFighterStructPoolUsedMask = 0u;
#endif
}

/* DO NOT ADD AN ACCESSOR FOR sNdsFighterPartsPool. R2-07 L7's first draft did,
 * to give its oracle a flat array to walk, and the linker map answered a
 * question the board had got wrong: in the shipping-shaped configuration this
 * pool IS NOT LINKED. `.bss.sNdsFighterPartsPool` contributes 0 bytes to
 * build-tickhud and 33,152 the moment anything outside references it; the
 * imported-manager path has no runtime reference to this compatibility pool.
 *
 * Two consequences, both load-bearing. The FTParts collision reads through
 * ftGetParts do NOT come from here in that build, so "the port already owns the
 * structure collision reads" is false for the ROM that ships -- anything hooking
 * L7 on this pool would hook an array nothing populates. And a reference to it
 * costs 33,152 bytes of image, which is eight taskman arena steps: enough on its
 * own to drop the battle under ifCommonSetMaxNumGObj's 25 KiB latch. Walk the
 * live GObj/DObj tree instead; battleship_gmcollision.c does. */


static sb32 ndsFighterStructIsPoolPointer(const void *ptr)
{
#if NDS_IMPORT_BATTLESHIP_FTMANAGER
    (void)ptr;
    return FALSE;
#else
    const FTStruct *fp = ptr;

    if ((fp >= &sNdsFighterStructPool[0]) &&
        (fp < &sNdsFighterStructPool[GMCOMMON_PLAYERS_MAX]) &&
        (fp->nds_magic == NDS_FTSTRUCT_MAGIC))
    {
        return TRUE;
    }
    return FALSE;
#endif
}

#if NDS_IMPORT_BATTLESHIP_FTMANAGER
static GObj *ndsFighterManagerLiveGObj(u32 slot)
{
    if (slot >= ARRAY_COUNT(sNdsFighterManagerLiveGObjs))
    {
        return NULL;
    }
    return sNdsFighterManagerLiveGObjs[slot];
}

static FTStruct *ndsFighterManagerLiveStruct(u32 slot)
{
    GObj *fighter_gobj = ndsFighterManagerLiveGObj(slot);

    return (fighter_gobj != NULL) ? ftGetStruct(fighter_gobj) : NULL;
}

void ndsFighterManagerRegisterDisplayFighter(GObj *fighter_gobj, u32 slot)
{
    FTStruct *fp;

    if (slot >= ARRAY_COUNT(sNdsFighterManagerLiveGObjs))
    {
        return;
    }
    /* Scene-local fighters live in taskman arenas. A menu/results owner must
     * clear its registration before that arena is rewound or the next scene
     * can mistake a stale FTStruct address for a live fighter. */
    if (fighter_gobj == NULL)
    {
        sNdsFighterManagerLiveGObjs[slot] = NULL;
        return;
    }
    fp = ftGetStruct(fighter_gobj);
    if (fp == NULL)
    {
        return;
    }
    sNdsFighterManagerLiveGObjs[slot] = fighter_gobj;
    fp->nds_magic = NDS_FTSTRUCT_MAGIC;
    fp->nds_slot = slot;
}

static u32 ndsFighterManagerLiveMask(void)
{
    u32 mask = 0u;
    u32 i;

    for (i = 0u; i < ARRAY_COUNT(sNdsFighterManagerLiveGObjs); i++)
    {
        if (ndsFighterManagerLiveStruct(i) != NULL)
        {
            mask |= 1u << i;
        }
    }
    return mask;
}

#endif

/* Legacy proof reads ask "which player slots hold a live FTStruct".  The
 * imported manager owns that answer (live registry -> ftGetStruct); the old
 * compatibility pool tracked it with a static mask.  Branch-unified so the
 * remaining proof sites compile against either owner. */
static u32 ndsFighterStructUsedMask(void)
{
#if NDS_IMPORT_BATTLESHIP_FTMANAGER
    return ndsFighterManagerLiveMask();
#else
    return sNdsFighterStructPoolUsedMask;
#endif
}

static sb32 ndsFighterStructIsTrackedPointer(const void *ptr)
{
#if NDS_IMPORT_BATTLESHIP_FTMANAGER
    const FTStruct *fp = ptr;
    u32 i;
#endif

    if (ndsFighterStructIsPoolPointer(ptr) != FALSE)
    {
        return TRUE;
    }
#if NDS_IMPORT_BATTLESHIP_FTMANAGER
    for (i = 0u; i < ARRAY_COUNT(sNdsFighterManagerLiveGObjs); i++)
    {
        if ((fp == ndsFighterManagerLiveStruct(i)) &&
            (fp != NULL) &&
            (fp->nds_magic == NDS_FTSTRUCT_MAGIC))
        {
            return TRUE;
        }
    }
#endif
    return FALSE;
}

static FTStruct *ndsFighterMarioFoxProofStructForSlot(u32 slot)
{
#if NDS_IMPORT_BATTLESHIP_FTMANAGER
    return ndsFighterManagerLiveStruct(slot);
#else
    return (slot < GMCOMMON_PLAYERS_MAX) ? &sNdsFighterStructPool[slot] : NULL;
#endif
}

static GObj *ndsFighterMarioFoxProofGObjForSlot(u32 slot)
{
#if NDS_IMPORT_BATTLESHIP_FTMANAGER
    return ndsFighterManagerLiveGObj(slot);
#else
    return (slot < GMCOMMON_PLAYERS_MAX) ?
        sNdsFighterStructPool[slot].fighter_gobj : NULL;
#endif
}

static GObj *ndsFighterGetPlayerNumGObj(s32 player_num)
{
    GObj *fighter_gobj = gGCCommonLinks[nGCCommonLinkIDFighter];

    /* BattleShip ftparam.c:186-200. `player_num` is NOT the battle player
     * index: ftManagerGetNextStructAlloc seeds gFTManagerPlayersNum at 1 and
     * assigns a monotonically increasing instance number to every created
     * fighter.  The old DS helper accidentally treated it as slot 0..3, which
     * resolves the wrong attacker as soon as creation order differs from battle
     * slot order (and can never resolve player_num 4 in a four-fighter match).
     *
     * Keep the source's linked-list lookup exactly.  Damage/public-call paths
     * pass attacker_player_num here, and that field is the fighter instance
     * number recorded by the source hitlog rather than FTStruct::player. */
    while (fighter_gobj != NULL)
    {
        FTStruct *fp = ftGetStruct(fighter_gobj);

        if ((fp != NULL) && (fp->player_num == player_num))
        {
            return fighter_gobj;
        }
        fighter_gobj = fighter_gobj->link_next;
    }
    return NULL;
}



static void *ndsFighterLoadExternFile(const void *file_id)
{
    size_t size = lbRelocGetFileSize(file_id);
    void *heap;

    if (size == 0u)
    {
        gNdsFighterMarioFoxExternalFixupFailCount++;
        return NULL;
    }

    heap = syTaskmanMalloc(size, 0x10);
    if (heap == NULL)
    {
        gNdsFighterMarioFoxExternalFixupFailCount++;
        return NULL;
    }
    return lbRelocGetExternHeapFile(file_id, heap);
}

static void ndsFighterLoadOnce(const void *file_id, void **slot)
{
    if ((slot != NULL) && (*slot == NULL))
    {
        *slot = ndsFighterLoadExternFile(file_id);
        if (*slot != NULL)
        {
            gNdsFighterMarioFoxLoadedFileCount++;
        }
    }
}

static void ndsFighterMarioFoxSetupManagerFiles(void)
{
    ndsFighterLoadOnce(&llFTManagerCommonFileID,
                       &sNdsFighterFTManagerCommonFile);
    gNdsFighterMarioFoxSetupMask |=
        NDS_FIGHTER_MARIOFOX_SETUP_MANAGER_ALLOC;
}

static void ndsFighterMarioFoxUpdateFileDiagnostics(void)
{
    gNdsFighterMarioMainMotionPtrReady =
        (sNdsFighterMarioMainMotionFile != NULL) ? 1u : 0u;
    gNdsFighterMarioMainPtrReady =
        (sNdsFighterMarioMainFile != NULL) ? 1u : 0u;
    gNdsFighterMarioModelPtrReady =
        (sNdsFighterMarioModelFile != NULL) ? 1u : 0u;
    gNdsFighterFoxMainMotionPtrReady =
        (sNdsFighterFoxMainMotionFile != NULL) ? 1u : 0u;
    gNdsFighterFoxMainPtrReady =
        (sNdsFighterFoxMainFile != NULL) ? 1u : 0u;
    gNdsFighterFoxModelPtrReady =
        (sNdsFighterFoxModelFile != NULL) ? 1u : 0u;
}

static void ndsFighterMarioFoxSetupFilesKind(s32 fkind)
{
    if (fkind == nFTKindMario)
    {
        ndsFighterLoadOnce(&llMarioMainMotionFileID,
                           &sNdsFighterMarioMainMotionFile);
        ndsFighterLoadOnce(&llMarioMainFileID,
                           &sNdsFighterMarioMainFile);
        ndsFighterLoadOnce(&llMarioSpecial1FileID,
                           &sNdsFighterMarioSpecial1File);
        ndsFighterLoadOnce(&llMarioModelFileID,
                           &sNdsFighterMarioModelFile);
        ndsFighterLoadOnce(&llMarioSpecial3FileID,
                           &sNdsFighterMarioSpecial3File);
        ndsFighterLoadOnce(&llMarioShieldPoseFileID,
                           &sNdsFighterMarioShieldPoseFile);
        ndsFighterLoadOnce(&llMarioSpecial2FileID,
                           &sNdsFighterMarioSpecial2File);
        gNdsFighterMarioFoxSetupMask |=
            NDS_FIGHTER_MARIOFOX_SETUP_MARIO_FILES;
    }
    else if (fkind == nFTKindFox)
    {
        ndsFighterLoadOnce(&llFoxSpecial3FileID,
                           &sNdsFighterFoxSpecial3File);
        ndsFighterLoadOnce(&llFoxMainMotionFileID,
                           &sNdsFighterFoxMainMotionFile);
        ndsFighterLoadOnce(&llFoxMainFileID,
                           &sNdsFighterFoxMainFile);
        ndsFighterLoadOnce(&llFoxSpecial1FileID,
                           &sNdsFighterFoxSpecial1File);
        ndsFighterLoadOnce(&llFoxModelFileID,
                           &sNdsFighterFoxModelFile);
        ndsFighterLoadOnce(&llFoxShieldPoseFileID,
                           &sNdsFighterFoxShieldPoseFile);
        ndsFighterLoadOnce(&llFoxSpecial4FileID,
                           &sNdsFighterFoxSpecial4File);
        ndsFighterLoadOnce(&llFoxSpecial2FileID,
                           &sNdsFighterFoxSpecial2File);
        gNdsFighterMarioFoxSetupMask |=
            NDS_FIGHTER_MARIOFOX_SETUP_FOX_FILES;
    }
    ndsFighterMarioFoxUpdateFileDiagnostics();
}


static u32 ndsFighterCountDObjs(DObj *dobj)
{
    u32 count = 0;

    while (dobj != NULL)
    {
        count++;
        count += ndsFighterCountDObjs(dobj->child);
        dobj = dobj->sib_next;
    }
    return count;
}

static u32 ndsFighterCountMObjs(DObj *dobj)
{
    u32 count = 0;

    while (dobj != NULL)
    {
        MObj *mobj = dobj->mobj;

        while (mobj != NULL)
        {
            count++;
            mobj = mobj->next;
        }
        count += ndsFighterCountMObjs(dobj->child);
        dobj = dobj->sib_next;
    }
    return count;
}

static u32 ndsFighterCountAObjs(DObj *dobj)
{
    u32 count = 0;

    while (dobj != NULL)
    {
        AObj *aobj = dobj->aobj;

        while (aobj != NULL)
        {
            count++;
            aobj = aobj->next;
        }
        count += ndsFighterCountAObjs(dobj->child);
        dobj = dobj->sib_next;
    }
    return count;
}


static void ndsFighterManagerRecordCreatedFighter(GObj *fighter_gobj,
                                                   s32 player)
{
#if NDS_IMPORT_BATTLESHIP_FTMANAGER
    FTStruct *fp;
    u32 bit;
    u32 live_mask;
    u32 live_count = 0u;

    if ((fighter_gobj == NULL) || (player < 0) ||
        (player >= GMCOMMON_PLAYERS_MAX))
    {
        return;
    }
    fp = ftGetStruct(fighter_gobj);
    if (fp == NULL)
    {
        return;
    }
    bit = 1u << player;
    sNdsFighterManagerLiveGObjs[player] = fighter_gobj;
    fp->nds_magic = NDS_FTSTRUCT_MAGIC;
    fp->nds_slot = (u32)player;
    /* The imported BattleShip FTStruct is authoritative.  Earlier port proof
     * code copied all 3,012 bytes into a second static pool here; no gameplay
     * reader consumed that copy, while it permanently reduced the DS heap that
     * can back taskman.  Keep only the live GObj registry and DS identity tags. */

    if (fp->joints[nFTPartsJointTopN] != NULL)
    {
        DObj *root_dobj = fp->joints[nFTPartsJointTopN];

        if (player == 0)
        {
            gNdsFighterInitP0GA = (u32)fp->ga;
            gNdsFighterInitP0FloorLineID = (u32)fp->coll_data.floor_line_id;
            gNdsFighterInitP0RootTranslateXBits =
                ndsFloatBits(root_dobj->translate.vec.f.x);
            gNdsFighterInitP0RootTranslateYBits =
                ndsFloatBits(root_dobj->translate.vec.f.y);
        }
        else if (player == 1)
        {
            gNdsFighterInitP1GA = (u32)fp->ga;
            gNdsFighterInitP1FloorLineID = (u32)fp->coll_data.floor_line_id;
            gNdsFighterInitP1RootTranslateXBits =
                ndsFloatBits(root_dobj->translate.vec.f.x);
            gNdsFighterInitP1RootTranslateYBits =
                ndsFloatBits(root_dobj->translate.vec.f.y);
        }
    }

    /* P2-2 uses Mario/Fox mirrors in any of the four source player slots.
     * Do not let the old P0=Mario/P1=Fox proof convention define runtime
     * capacity.  The existing P0/P1 diagnostic fields below remain intentionally
     * slot-specific, but these masks/counts describe every supported live
     * battle fighter.
     *
     * P2-3r11: the fkind test that used to guard this was that intent written
     * as the then-complete list of playable kinds, and it went stale the moment
     * Luigi and Donkey Kong landed.  A Mario/Fox/Luigi/Donkey battle recorded
     * `gNdsSCVSBattleOriginalFighterGObjCount = 2` and active mask 3 with all
     * four fighters alive, which read as "two fighters were never created" and
     * cost a cycle of chasing a creation failure that had not happened.  The
     * only correct predicate is the one the comment above always described: a
     * live fighter GObj in a real player slot.  `fp` is non-NULL and `player` is
     * range-checked above, and the sole caller is
     * `ftParamInitPlayerBattleStats` out of `scVSBattleStartBattle`'s per-player
     * loop -- character-select previews never reach here -- so there is nothing
     * left for a kind list to exclude. */
    gNdsFighterManagerFighterMask |= bit;
    gNdsSCVSBattleOriginalActivePlayerMask |= bit;
    /* P2-3r15: one byte per player slot, holding `fkind + 1` so an empty
     * slot (0) stays distinct from Mario (nFTKindMario == 0). Written as a
     * clear-then-set field rather than an OR, so two creation paths writing
     * the same slot cannot fuse two kinds into one byte. */
    gNdsSCVSBattleOriginalFighterKinds =
        (gNdsSCVSBattleOriginalFighterKinds &
         ~(0xffu << ((u32)player * 8u))) |
        ((((u32)fp->fkind + 1u) & 0xffu) << ((u32)player * 8u));
    if ((fp->fkind >= 0) && (fp->fkind < nFTKindEnumCount) &&
        (fp->data == dFTManagerDataFiles[fp->fkind]) &&
        (fp->attr != NULL) && (fp->figatree_heap != NULL))
    {
        gNdsFighterManagerDataMask |= bit;
    }
    if (fp->status_id == nFTCommonStatusWait)
    {
        gNdsFighterManagerWaitMask |= bit;
    }
    if (fp->status_id == nFTCommonStatusEntry)
    {
        gNdsFighterManagerEntryMask |= bit;
    }

    live_mask = gNdsFighterManagerFighterMask;
    while (live_mask != 0u)
    {
        live_count += live_mask & 1u;
        live_mask >>= 1;
    }
    gNdsFighterManagerFighterCount = live_count;
    gNdsSCVSBattleOriginalFighterGObjCount =
        gNdsFighterManagerFighterCount;
    gNdsSCVSBattleOriginalFighterCreateCount =
        gNdsFighterManagerFighterCount;
    gNdsSCVSBattleOriginalActivePlayerCount =
        gNdsFighterManagerFighterCount;
    if (player == 0)
    {
        gNdsSCVSBattleOriginalP0FKind = (u32)fp->fkind;
        gNdsSCVSBattleOriginalP0LR = (u32)fp->lr;
    }
    else if (player == 1)
    {
        gNdsSCVSBattleOriginalP1FKind = (u32)fp->fkind;
        gNdsSCVSBattleOriginalP1LR = (u32)fp->lr;
    }
    gNdsSCVSBattleCompatManagerMask |= 1u << 3;
    gNdsSCVSBattleCompatMask |= NDS_SCVSBATTLE_COMPAT_FIGHTER_MANAGER;
    ndsFighterManagerRefreshProof();
#else
    (void)fighter_gobj;
    (void)player;
#endif
}
















static s32 ndsFloatToMilliSigned(f32 value)
{
    if (value >= 0.0F)
    {
        return (s32)((value * 1000.0F) + 0.5F);
    }
    return (s32)((value * 1000.0F) - 0.5F);
}

static void ndsFighterSyncLegacyVelToPhysics(FTStruct *fp)
{
    if (fp == NULL)
    {
        return;
    }
    fp->physics.vel_air = fp->vel_air;
    fp->physics.vel_ground = fp->vel_ground;
}

static void ndsFighterSyncPhysicsToLegacyVel(FTStruct *fp)
{
    if (fp == NULL)
    {
        return;
    }
    fp->vel_air = fp->physics.vel_air;
    fp->vel_ground = fp->physics.vel_ground;
}

static void ndsFTPhysicsSetGroundVelFrictionOriginal(FTStruct *fp,
                                                     f32 friction)
{
    if (fp->physics.vel_ground.x < 0.0F)
    {
        fp->physics.vel_ground.x += friction;
        if (fp->physics.vel_ground.x > 0.0F)
        {
            fp->physics.vel_ground.x = 0.0F;
        }
    }
    else
    {
        fp->physics.vel_ground.x -= friction;
        if (fp->physics.vel_ground.x < 0.0F)
        {
            fp->physics.vel_ground.x = 0.0F;
        }
    }
}

static void ndsFTPhysicsSetGroundVelTransferAirOriginal(GObj *fighter_gobj,
                                                        FTStruct *fp)
{
    DObj *root = DObjGetStruct(fighter_gobj);

    if ((fp == NULL) || (root == NULL))
    {
        return;
    }

    fp->physics.vel_air.x =
        ((fp->lr * fp->coll_data.floor_angle.y *
          fp->physics.vel_ground.x) + fp->physics.vel_jostle_x);
    fp->physics.vel_air.y =
        (fp->lr * -fp->coll_data.floor_angle.x *
         fp->physics.vel_ground.x);
    fp->physics.vel_air.z = fp->physics.vel_jostle_z;

    if (((fp->physics.vel_jostle_z > 0.0F) &&
         (root->translate.vec.f.z < 0.0F) &&
         ((root->translate.vec.f.z + fp->physics.vel_air.z) > 0.0F)) ||
        ((fp->physics.vel_air.z < 0.0F) &&
         (root->translate.vec.f.z > 0.0F) &&
         ((root->translate.vec.f.z + fp->physics.vel_air.z) < 0.0F)))
    {
        fp->physics.vel_air.z = -root->translate.vec.f.z;
    }
    if ((fp->physics.vel_air.z > 0.0F) &&
        ((root->translate.vec.f.z + fp->physics.vel_air.z) > 60.0F))
    {
        fp->physics.vel_air.z = 60.0F - root->translate.vec.f.z;
    }
    else if ((fp->physics.vel_air.z < 0.0F) &&
             ((root->translate.vec.f.z + fp->physics.vel_air.z) < -60.0F))
    {
        fp->physics.vel_air.z = -60.0F - root->translate.vec.f.z;
    }
    fp->physics.vel_air.z += fp->physics.vel_ground.z;
}

static void ndsFighterWaitGroundRecordMaterial(u32 slot, u32 material,
                                               f32 traction, f32 friction)
{
    if (slot == 0u)
    {
        gNdsFighterWaitGroundP0Material = material;
        gNdsFighterWaitGroundP0TractionMilli =
            (u32)ndsFloatToMilliSigned(traction);
        gNdsFighterWaitGroundP0FrictionMilli =
            (u32)ndsFloatToMilliSigned(friction);
    }
    else if (slot == 1u)
    {
        gNdsFighterWaitGroundP1Material = material;
        gNdsFighterWaitGroundP1TractionMilli =
            (u32)ndsFloatToMilliSigned(traction);
        gNdsFighterWaitGroundP1FrictionMilli =
            (u32)ndsFloatToMilliSigned(friction);
    }
}

static void ndsFTPhysicsApplyGroundVelFrictionBounded(GObj *fighter_gobj)
{
    FTStruct *fp = ftGetStruct(fighter_gobj);
    FTAttributes *attr;
    u32 material;
    f32 traction;
    f32 friction;

    if ((fp == NULL) || (ndsFighterStructIsPoolPointer(fp) == FALSE))
    {
        return;
    }
    attr = fp->attr;
    if (attr == NULL)
    {
        return;
    }

    material = fp->coll_data.floor_flags & MAP_VERTEX_MAT_MASK;
    material &= 0x0fu;
    traction = attr->traction;
    if (traction <= 0.0F)
    {
        traction = 1.0F;
    }
    friction = dMPCollisionMaterialFrictions[material] * traction;
    ndsFighterWaitGroundRecordMaterial(fp->player, material, traction,
                                       friction);

    ndsFighterSyncLegacyVelToPhysics(fp);
    ndsFTPhysicsSetGroundVelFrictionOriginal(fp, friction);
    ndsFTPhysicsSetGroundVelTransferAirOriginal(fighter_gobj, fp);
    ndsFighterSyncPhysicsToLegacyVel(fp);
}

static sb32 ndsMPCommonCheckFighterOnCliffEdgeBounded(GObj *fighter_gobj)
{
    FTStruct *fp = ftGetStruct(fighter_gobj);

    if ((fp == NULL) || (ndsFighterStructIsPoolPointer(fp) == FALSE))
    {
        return FALSE;
    }

    gNdsFighterWaitGroundMapCheckCount++;
    if (ndsStageFloorFollowLoopUpdateFighter(fighter_gobj) != FALSE)
    {
        gNdsFighterWaitGroundMapSafeFloorCount++;
        return TRUE;
    }
    if ((fp->ga == nMPKineticsGround) &&
        (fp->coll_data.floor_line_id == 0) &&
        ((fp->coll_data.mask_stat & MAP_FLAG_FLOOR) != 0u))
    {
        gNdsFighterWaitGroundMapSafeFloorCount++;
        fp->coll_data.is_coll_end = FALSE;
        return TRUE;
    }

    fp->coll_data.is_coll_end = TRUE;
    return FALSE;
}




static u32 ndsFighterCountDLReadyDObjs(DObj *dobj)
{
    u32 count = 0;

    while (dobj != NULL)
    {
        if (dobj->dl != NULL)
        {
            count++;
        }
        count += ndsFighterCountDLReadyDObjs(dobj->child);
        dobj = dobj->sib_next;
    }
    return count;
}

static u32 ndsFighterCountPartsPtrDObjs(DObj *dobj)
{
    u32 count = 0;

    while (dobj != NULL)
    {
        if (dobj->user_data.p != NULL)
        {
            count++;
        }
        count += ndsFighterCountPartsPtrDObjs(dobj->child);
        dobj = dobj->sib_next;
    }
    return count;
}

static void ndsFighterMarioFoxRecordDisplayProbe(GObj *fighter_gobj)
{
    FTStruct *fp = ftGetStruct(fighter_gobj);
    DObj *root;
    u32 player;
    u32 dobj_count;
    u32 mobj_count;
    u32 aobj_count;
    u32 dl_ready_count;
    u32 parts_ptr_count;

    if ((fp == NULL) || (ndsFighterStructIsPoolPointer(fp) == FALSE))
    {
        return;
    }
    player = (u32)fp->player;
    if (player > 1u)
    {
        return;
    }

    root = fp->joints[nFTPartsJointTopN];
    dobj_count = ndsFighterCountDObjs(root);
    mobj_count = ndsFighterCountMObjs(root);
    aobj_count = ndsFighterCountAObjs(root);
    dl_ready_count = ndsFighterCountDLReadyDObjs(root);
    parts_ptr_count = ndsFighterCountPartsPtrDObjs(root);

    gNdsFighterMarioFoxDisplayCallbackCount++;

    if (player == 0u)
    {
        gNdsFighterDisplayP0DObjCount = dobj_count;
        gNdsFighterDisplayP0MObjCount = mobj_count;
        gNdsFighterDisplayP0AObjCount = aobj_count;
        gNdsFighterDisplayP0DLReadyCount = dl_ready_count;
        gNdsFighterDisplayP0PartsPtrCount = parts_ptr_count;
        gNdsFighterDisplayP0StatusAfter = (u32)fp->status_id;
        gNdsFighterDisplayP0MotionAfter = (u32)fp->motion_id;
        gNdsFighterDisplayP0GAAfter = (u32)fp->ga;
        gNdsFighterDisplayP0RootXAfterBits =
            (root != NULL) ? ndsFloatBits(root->translate.vec.f.x) : 0u;
    }
    else
    {
        gNdsFighterDisplayP1DObjCount = dobj_count;
        gNdsFighterDisplayP1MObjCount = mobj_count;
        gNdsFighterDisplayP1AObjCount = aobj_count;
        gNdsFighterDisplayP1DLReadyCount = dl_ready_count;
        gNdsFighterDisplayP1PartsPtrCount = parts_ptr_count;
        gNdsFighterDisplayP1StatusAfter = (u32)fp->status_id;
        gNdsFighterDisplayP1MotionAfter = (u32)fp->motion_id;
        gNdsFighterDisplayP1GAAfter = (u32)fp->ga;
        gNdsFighterDisplayP1RootXAfterBits =
            (root != NULL) ? ndsFloatBits(root->translate.vec.f.x) : 0u;
    }
}
