#include "renderer_adapter_matrix.c"
#include "renderer_adapter_legacy_dl_probes.c"
#include "renderer_adapter_stage.c"
#include "renderer_adapter_legacy_raster_probes.c"
#include "renderer_adapter_fighter.c"
