#!/usr/bin/env python3
"""Fighter clip successor table for the motion prefetch (P2-2p8, 2026-09-30).

Input: lab clip traces -- run logs of a lab ROM built with
CPPFLAGS=-DNDS_LAB_CLIP_TRACE=1 (src/port/reloc_backend_assets.c), each
reading gNdsLabClipTraceCount and a slice of gNdsLabClipTrace[] through
-ExtraGlobals. A trace word is: clip index (asset - 499, 11 bits), outcome
(2), battle slot (2), frame (17). Slices of one run (same stage, roster and
ROM, so the same deterministic replay) are named `<prefix><k>_<run>` and are
merged by `<run>`.

For every clip, the two clips that most often followed it in the SAME
fighter's fetches, over all runs -- only clips the stream pack holds (--pack)
and seen following it at least twice. The runtime (ndsR2AnimPrefetchIdle)
reads those two into the motion ring asynchronously in the frame's idle time
after the clip is installed; a wrong guess costs ring space and an ARM7 read,
never a different frame, because a clip's bytes are the same wherever they
come from.

Output: include/nds/generated/nds_clip_successors.generated.h -- keys sorted
for a binary search, so only clips that were seen cost RAM.

Usage:
  generate_clip_successors.py --traces DIR --prefix cs [--prefix ct] --out HEADER
  generate_clip_successors.py ... --check   (exit 1 if HEADER differs)
"""
import argparse
import collections
import glob
import os
import re
import struct
import sys

FIRST_ID = 499


def load_runs(trace_dir, prefixes):
    runs = collections.defaultdict(dict)
    counts = collections.defaultdict(set)
    paths = []
    for prefix in prefixes:
        pat = re.compile('^' + re.escape(prefix) + r'(\d+)_(.+)-run\.log$')
        for path in sorted(glob.glob(os.path.join(trace_dir, prefix + '*-run.log'))):
            m = pat.search(os.path.basename(path))
            if m:
                paths.append((prefix + ':' + m.group(2), path))
    for run, path in paths:
        txt = open(path, encoding='utf-8', errors='replace').read()
        c = re.search(r'gNdsLabClipTraceCount=([\d,]+)', txt)
        if not c:
            raise SystemExit(f'{path}: no gNdsLabClipTraceCount (failed run?)')
        counts[run].add(int(c.group(1).replace(',', '')))
        for k, v in re.findall(r'gNdsLabClipTrace\[(\d+)\]=([\d,]+)', txt):
            runs[run][int(k)] = int(v.replace(',', ''))
    traces = {}
    for run, words in runs.items():
        if len(counts[run]) != 1:
            raise SystemExit(f'{run}: slices disagree on the fetch count {counts[run]}')
        n = min(counts[run].pop(), max(words) + 1 if words else 0)
        missing = [i for i in range(n) if i not in words]
        if missing:
            raise SystemExit(f'{run}: trace words missing, first {missing[:5]}')
        traces[run] = [{'asset': (words[i] & 0x7ff) + FIRST_ID,
                        'slot': (words[i] >> 13) & 3} for i in range(n)]
    return traces


def successor_counts(traces):
    tab = collections.defaultdict(collections.Counter)
    for tr in traces.values():
        prev = {}
        for e in tr:
            if e['slot'] in prev and prev[e['slot']] != e['asset']:
                tab[prev[e['slot']]][e['asset']] += 1
            prev[e['slot']] = e['asset']
    return tab


def stream_clips(pack_path):
    """Asset ids the stream pack holds (a prefetch can only read those)."""
    d = open(pack_path, 'rb').read()
    _, _, _, count, first, _, dir_off, _ = struct.unpack('<8I', d[:32])
    held = set()
    for i in range(count):
        _, size = struct.unpack('<2I', d[dir_off + 8 * i:dir_off + 8 * i + 8])
        if size:
            held.add(first + i)
    return held


def emit(tab, traces, out_path, held):
    rows = []
    for clip in sorted(tab):
        seen = [(b, c) for b, c in tab[clip].items() if b in held and c >= 2]
        best = [b for b, _ in sorted(seen, key=lambda kv: (-kv[1], kv[0]))[:2]]
        if not best:
            continue
        best += [0] * (2 - len(best))
        rows.append((clip, best[0], best[1]))
    fetches = sum(len(t) for t in traces.values())
    lines = [
        '/* GENERATED by scripts/motion/generate_clip_successors.py -- do not edit.',
        ' *',
        ' * Fighter clip successors for the motion prefetch (P2-2p8): for each',
        ' * stream clip asset id, the two clips that most often followed it in the',
        f' * same fighter\'s fetches over {len(traces)} lab clip traces ({fetches} fetches);',
        ' * only stream-pack clips seen following it at least twice. 0 = none.',
        ' * Keys ascend for a binary search. */',
        '#ifndef NDS_CLIP_SUCCESSORS_GENERATED_H',
        '#define NDS_CLIP_SUCCESSORS_GENERATED_H',
        '',
        f'#define NDS_CLIP_SUCCESSOR_ROWS {len(rows)}u',
        '',
        'static const u16 sNdsClipSuccessorKey[NDS_CLIP_SUCCESSOR_ROWS] = {',
    ]
    for i in range(0, len(rows), 10):
        lines.append('    ' + ', '.join(f'{r[0]}u' for r in rows[i:i + 10]) + ',')
    lines += ['};', '',
              'static const u16 sNdsClipSuccessorNext[NDS_CLIP_SUCCESSOR_ROWS][2] = {']
    for i in range(0, len(rows), 5):
        lines.append('    ' + ', '.join(f'{{ {r[1]}u, {r[2]}u }}' for r in rows[i:i + 5]) + ',')
    lines += ['};', '', '#endif', '']
    text = '\n'.join(lines)
    return text, len(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--traces', required=True)
    ap.add_argument('--prefix', action='append',
                    help='slice file prefix; repeat for several trace sets')
    ap.add_argument('--out', required=True)
    ap.add_argument('--pack', default=os.path.join(
        os.path.dirname(os.path.abspath(__file__)), '..', '..', 'assets',
        'animation', 'ftanim_stream_pack.bin'))
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    traces = load_runs(a.traces, a.prefix or ['cs'])
    if not traces:
        raise SystemExit('no traces')
    tab = successor_counts(traces)
    text, nrows = emit(tab, traces, a.out, stream_clips(a.pack))
    if a.check:
        old = open(a.out, encoding='utf-8').read() if os.path.exists(a.out) else ''
        if old != text:
            print(f'{a.out} is stale')
            return 1
        print(f'{a.out} up to date ({nrows} rows)')
        return 0
    open(a.out, 'w', encoding='utf-8', newline='\n').write(text)
    print(f'wrote {a.out}: {nrows} rows from {len(traces)} traces')
    return 0


if __name__ == '__main__':
    sys.exit(main())
