#if NDS_IMPORT_BATTLESHIP_MARIO_SPECIAL_HI

#include <ft/fighter.h>

#ifndef FTMARIO_SUPERJUMP_TURN_STICK_THRESHOLD
#define FTMARIO_SUPERJUMP_TURN_STICK_THRESHOLD 50
#endif
#ifndef FTMARIO_SUPERJUMP_TURN_MODEL_THRESHOLD
#define FTMARIO_SUPERJUMP_TURN_MODEL_THRESHOLD 20
#endif
#ifndef FTMARIO_SUPERJUMP_AIR_DRIFT
#define FTMARIO_SUPERJUMP_AIR_DRIFT 0.6F
#endif
#ifndef FTMARIO_SUPERJUMP_LANDING_LAG
#define FTMARIO_SUPERJUMP_LANDING_LAG 0.28F
#endif
#ifndef FTMARIO_SUPERJUMP_STICK_Y_UNK
#define FTMARIO_SUPERJUMP_STICK_Y_UNK -44
#endif

#include "../../decomp/BattleShip-main/decomp/src/ft/ftchar/ftmario/ftmariospecialhi.c"

#endif
