#!/usr/bin/env python3
"""Validate the project-local Nintendo DS Agent Skills pack."""

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
AGENTS = ROOT / ".agents" / "skills"
CLAUDE = ROOT / ".claude" / "skills"

# Two kinds of project-local skill live here.
#
# `smash64ds-opus-guardrails` is *about this repository*, so it carries the full
# canonical/bridge pair: canonical text under `.agents/skills/`, one-paragraph
# bridge under `.claude/skills/`.
#
# `nds-coding-practices` is deliberately canonical-only (owner, 2026-08-05). It
# briefly lived in the owner's global skills, which reached Claude and Codex but
# nothing else; it is back in-tree so that EVERY coding agent working this repo
# can read it, not just those two. Claude already receives it as the plugin skill
# `anthropic-skills:nds-coding-practices`, so a `.claude/` bridge would only add
# a duplicate surface -- hence no bridge is required, and one is treated as an
# error rather than silently accepted.
#
# `n64-to-nds-porting` is the companion pack for the N64 -> DS translation half
# (installed 2026-09-06). Unlike `nds-coding-practices` it has no plugin
# equivalent, so Claude only sees it through a `.claude/` bridge -- it therefore
# carries the full canonical/bridge pair.
#
# 2026-09-12: the owner installed byte-identical full copies of both DS skill
# packs under `.claude/skills/` (the project-scoped 2026-09-11 revisions). A
# `.claude/` entry is therefore accepted in one of two shapes: a one-paragraph
# bridge pointing at the canonical text, or a MIRROR whose every file is
# byte-identical to the canonical tree with no extra files. A mirror that
# drifts from its canonical is an error, so there is still exactly one source
# of truth. A bridge is still refused for the bridgeless skill.
# 2026-09-17: the owner ARCHIVED all three. Both trees are now a single
# `skills.zip` -- `.agents/skills/skills.zip` and `.claude/skills/skills.zip` --
# because they should not be loaded any more but should stay recoverable. That
# is a deliberate state, not the drift this validator exists to catch, so the
# expected set is empty and the checks below simply have nothing to compare.
#
# RESTORING ONE IS A ONE-LINE CHANGE: put its name back in this set and unzip
# the matching entries into both trees. The rules are unchanged and still
# encoded below, so a restored skill is validated exactly as before rather than
# coming back unchecked. Leave BRIDGELESS_SKILLS alone -- it records which skill
# refuses a bridge, and that is still true whenever nds-coding-practices exists.
EXPECTED_SKILLS: set[str] = set()
ARCHIVED_SKILLS = {
    "smash64ds-opus-guardrails",
    "nds-coding-practices",
    "n64-to-nds-porting",
}

# Canonical skills that intentionally have no `.claude/` bridge (a mirror is
# still allowed).
BRIDGELESS_SKILLS = {
    "nds-coding-practices",
}
EXPECTED_BRIDGES = EXPECTED_SKILLS - BRIDGELESS_SKILLS

NAME_RE = re.compile(r"^[a-z0-9-]{1,64}$")
FRONTMATTER_RE = re.compile(
    r"\A---\nname:\s*([^\n]+)\ndescription:\s*(.+?)\n---\n",
    re.DOTALL,
)
META_VALUE_RE = re.compile(
    r'^  (display_name|short_description|default_prompt): "([^"\n]*)"$',
    re.MULTILINE,
)
REFERENCE_RE = re.compile(r"references/[A-Za-z0-9._/-]+\.md")
SKILL_REF_RE = re.compile(r"\$([a-z0-9][a-z0-9-]{0,63})")
REQUIRED_SNIPPETS: dict[str, tuple[str, ...]] = {}

errors: list[str] = []


def directory_names(path: Path) -> set[str]:
    if not path.is_dir():
        errors.append(f"Missing directory: {path}")
        return set()
    return {entry.name for entry in path.iterdir() if entry.is_dir()}


canonical_names = directory_names(AGENTS)
bridge_names = directory_names(CLAUDE)


def tree_files(base: Path) -> dict[str, Path]:
    """Every source file under `base`, ignoring generated bytecode.

    `__pycache__` is gitignored (.gitignore:70) and regenerates the moment
    anyone runs a skill's own tests, so counting it made this validator fail on
    an action it is supposed to encourage: the mirror grew seven `.pyc` files
    and reported seven "extra file" errors for content git does not track. A
    validator that breaks when you exercise the thing it validates teaches
    people to stop running it.
    """
    return {
        path.relative_to(base).as_posix(): path
        for path in base.rglob("*")
        if path.is_file() and "__pycache__" not in path.parts
    }


def is_bridge(claude_skill_dir: Path, skill_name: str) -> bool:
    skill_file = claude_skill_dir / "SKILL.md"
    if not skill_file.is_file():
        return False
    expected_path = f"../../../.agents/skills/{skill_name}/SKILL.md"
    return expected_path in skill_file.read_text(encoding="utf-8")


def check_mirror(skill_name: str) -> None:
    """A `.claude/` mirror must be byte-identical to its canonical tree."""
    canonical = tree_files(AGENTS / skill_name)
    mirror = tree_files(CLAUDE / skill_name)
    for relative in sorted(set(canonical) - set(mirror)):
        errors.append(f"{CLAUDE / skill_name}: mirror lacks {relative}")
    for relative in sorted(set(mirror) - set(canonical)):
        errors.append(f"{CLAUDE / skill_name}: mirror has extra file {relative}")
    for relative in sorted(set(canonical) & set(mirror)):
        if canonical[relative].read_bytes() != mirror[relative].read_bytes():
            errors.append(
                f"{CLAUDE / skill_name}: mirror drifted from canonical at {relative}"
            )


for missing in sorted(EXPECTED_SKILLS - canonical_names):
    errors.append(f"Missing canonical skill: {missing}")
for extra in sorted(canonical_names - EXPECTED_SKILLS):
    errors.append(f"Unexpected canonical skill: {extra}")
for missing in sorted(EXPECTED_BRIDGES - bridge_names):
    errors.append(f"Missing Claude bridge or mirror: {missing}")
for extra in sorted(bridge_names - EXPECTED_SKILLS):
    errors.append(f"Unexpected Claude skill directory: {extra}")
for bridgeless in sorted(BRIDGELESS_SKILLS & bridge_names):
    if is_bridge(CLAUDE / bridgeless, bridgeless):
        errors.append(f"Unexpected Claude bridge: {bridgeless}")

for skill_name in sorted(EXPECTED_SKILLS & canonical_names):
    skill_dir = AGENTS / skill_name
    skill_file = skill_dir / "SKILL.md"
    if not skill_file.is_file():
        errors.append(f"{skill_dir}: missing SKILL.md")
        continue

    text = skill_file.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        errors.append(f"{skill_file}: invalid or missing YAML frontmatter")
        continue

    name = match.group(1).strip()
    description = " ".join(match.group(2).split())
    normalized_text = " ".join(text.split())
    if name != skill_name:
        errors.append(f"{skill_file}: name '{name}' does not match folder '{skill_name}'")
    if not NAME_RE.fullmatch(name):
        errors.append(f"{skill_file}: invalid skill name '{name}'")
    if len(description) < 80:
        errors.append(f"{skill_file}: description is too short to trigger reliably")
    if text.count("\n") + 1 > 500:
        errors.append(f"{skill_file}: exceeds the 500-line progressive-disclosure limit")
    if "TODO" in text or "[TODO" in text:
        errors.append(f"{skill_file}: contains a placeholder")

    for snippet in REQUIRED_SNIPPETS.get(name, ()):
        if snippet not in normalized_text:
            errors.append(f"{skill_file}: missing required contract '{snippet}'")

    for reference in sorted(set(REFERENCE_RE.findall(text))):
        if not (skill_dir / reference).is_file():
            errors.append(f"{skill_file}: missing referenced file {reference}")

    referenced_skills = set(SKILL_REF_RE.findall(text))
    for referenced_skill in sorted(referenced_skills):
        if referenced_skill not in EXPECTED_SKILLS:
            errors.append(
                f"{skill_file}: references unknown skill $" + referenced_skill
            )

    metadata = skill_dir / "agents" / "openai.yaml"
    if not metadata.is_file():
        errors.append(f"{skill_dir}: missing agents/openai.yaml")
    else:
        meta_text = metadata.read_text(encoding="utf-8")
        values = dict(META_VALUE_RE.findall(meta_text))
        for key in ("display_name", "short_description", "default_prompt"):
            if key not in values:
                errors.append(f"{metadata}: missing quoted {key}")
        short_description = values.get("short_description", "")
        if short_description and not 25 <= len(short_description) <= 64:
            errors.append(
                f"{metadata}: short_description length "
                f"{len(short_description)} is outside 25-64"
            )
        default_prompt = values.get("default_prompt", "")
        if default_prompt and "$" + name not in default_prompt:
            errors.append(f"{metadata}: default_prompt must mention $" + name)

    bridge = CLAUDE / skill_name / "SKILL.md"
    if not bridge.is_file():
        continue
    if not is_bridge(CLAUDE / skill_name, skill_name):
        # Not a bridge: it must then be an exact mirror of the canonical tree.
        check_mirror(skill_name)
        continue
    bridge_text = bridge.read_text(encoding="utf-8")
    bridge_match = FRONTMATTER_RE.match(bridge_text)
    if not bridge_match:
        errors.append(f"{bridge}: invalid or missing YAML frontmatter")
        continue
    bridge_name = bridge_match.group(1).strip()
    bridge_description = " ".join(bridge_match.group(2).split())
    if bridge_name != skill_name:
        errors.append(f"{bridge}: name '{bridge_name}' does not match folder '{skill_name}'")
    if bridge_description != description:
        errors.append(f"{bridge}: description drifted from canonical skill")

if errors:
    print("Skill validation failed:")
    for error in errors:
        print(f"  - {error}")
    sys.exit(1)

print(
    f"Validated {len(EXPECTED_SKILLS)} canonical skills, metadata files, "
    f"references, and Claude bridges."
)
