param(
    [string]$MelonDS = (Join-Path $PSScriptRoot '..\emulators\melonds\melonDS.exe'),
    [string]$Gdb = 'C:\devkitPro\devkitARM\bin\arm-none-eabi-gdb.exe',
    [int]$GdbPort = 3333,
    [int]$RunnerSlot = -1,
    [switch]$NoBuild,
    [int]$DelaySeconds = 5
)
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'lib\melonds.ps1')
. (Join-Path $PSScriptRoot 'lib\gdb-markers.ps1')
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$verifierContext = Initialize-MelonDSVerifierContext `
    -Root $root `
    -MelonDS $MelonDS `
    -RunnerSlot $RunnerSlot `
    -GdbPort $GdbPort `
    -GdbPortExplicit:$PSBoundParameters.ContainsKey('GdbPort') `
    -NoBuild:$NoBuild
$rom = Join-Path $root 'smash64ds-menu-chain-mariofox-dash-run.nds'
$elf = Join-Path $root 'smash64ds-menu-chain-mariofox-dash-run.elf'
$melonDsPath = $verifierContext.MelonDSPath
$melonDsDir = Split-Path -Parent $melonDsPath
$logDir = Get-MelonDSVerifierLogDir -Root $root -RunnerSlot (Get-MelonDSActiveRunnerSlot)
$stdout = Join-Path $logDir 'melonds.menu-chain-mariofox-dash-run-harness.stdout.log'
$stderr = Join-Path $logDir 'melonds.menu-chain-mariofox-dash-run-harness.stderr.log'
$configState = $null
$emulator = $null
$scriptName = '_menu_chain_mariofox_dash_run_harness.gdb'
function Assert-Condition {
    param([bool]$Condition, [string]$Message, [string]$Context)
    if (-not $Condition) { throw "$Message`n$Context" }
}
if (-not $env:DEVKITPRO) { $env:DEVKITPRO = 'C:/devkitPro' }
if (-not $env:DEVKITARM) { $env:DEVKITARM = 'C:/devkitPro/devkitARM' }
& make -C $root TARGET=smash64ds-menu-chain-mariofox-dash-run BUILD=build-menu-chain-mariofox-dash-run-harness NDS_DEV_SCENE_HARNESS=menu_chain_mariofox_dash_run -j16
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
if (-not (Test-Path $rom) -or -not (Test-Path $elf)) {
    throw 'Menu-chain Mario/Fox Dash-Run harness build did not produce the expected ROM and ELF.'
}
if (-not (Test-Path $melonDsPath)) { throw "melonDS executable not found: $melonDsPath" }
if (-not (Test-Path $Gdb)) { throw "GDB executable not found: $Gdb" }
New-Item -ItemType Directory -Path $logDir -Force | Out-Null
try {
    $configState = Enable-MelonDSGdbConfig -MelonDSPath $melonDsPath -GdbPort $verifierContext.GdbPort -Persistent:([bool]$verifierContext.PersistentConfig)
    Remove-Item $stdout, $stderr -Force -ErrorAction SilentlyContinue
    $emulator = Start-Process -FilePath $melonDsPath `
        -ArgumentList $rom `
        -WorkingDirectory $melonDsDir `
        -RedirectStandardOutput $stdout `
        -RedirectStandardError $stderr `
        -WindowStyle Hidden `
        -PassThru
    Wait-MelonDSGdbListener -Process $emulator -Port $verifierContext.GdbPort | Out-Null
    Start-Sleep -Seconds ([Math]::Max($DelaySeconds, 1))
    $gdbCommands = @(
        'set pagination off',
        'set confirm off',
        'set remotetimeout 5',
        ("target remote 127.0.0.1:{0}" -f (Get-MelonDSActiveGdbPort)),
        'printf "HARN=%#x,%u,%u,%u,%#x\n", gNdsSceneHarnessResult, gNdsSceneHarnessMode, gNdsSceneHarnessSceneCurr, gNdsSceneHarnessScenePrev, gNdsSceneHarnessReservedMask',
        'printf "SCENE=%u,%u,%u\n", gSCManagerSceneData.scene_curr, gSCManagerSceneData.scene_prev, gSCManagerSceneData.gkind',
        'printf "CHAIN=%#x,%#x,%#x,%#x,%#x,%#x\n", gNdsVSModeStartTransitionResult, gNdsVSModeStartTransitionMask, gNdsPlayersVSReadyTransitionResult, gNdsPlayersVSReadyTransitionMask, gNdsMapsSelectTransitionResult, gNdsMapsSelectTransitionMask',
        'printf "CHAIN_FINAL=%u,%u,%u,%u,%u\n", gNdsVSModeStartTransitionSceneCurrFinal, gNdsPlayersVSReadyTransitionSceneCurrFinal, gNdsMapsSelectTransitionSceneCurrFinal, gNdsMapsSelectTransitionScenePrevFinal, gNdsMapsSelectTransitionSelectedGKind',
        'printf "WALK_LOOP=%#x,%#x,%#x,%#x,%u\n", gNdsFighterMarioFoxWalkLoopResult, gNdsFighterMarioFoxWalkLoopSafeResult, gNdsFighterMarioFoxWalkLoopMask, gNdsFighterMarioFoxWalkLoopDeferredMask, gNdsFighterMarioFoxWalkLoopCount',
        'printf "DASH_RUN=%#x,%#x,%#x,%#x,%u\n", gNdsFighterMarioFoxDashRunResult, gNdsFighterMarioFoxDashRunSafeResult, gNdsFighterMarioFoxDashRunMask, gNdsFighterMarioFoxDashRunDeferredMask, gNdsFighterMarioFoxDashRunCount',
        'printf "DASH_RUN_STATUS=%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u\n", gNdsFighterDashRunP0StatusDash, gNdsFighterDashRunP1StatusDash, gNdsFighterDashRunP0MotionDash, gNdsFighterDashRunP1MotionDash, gNdsFighterDashRunP0StatusRun, gNdsFighterDashRunP1StatusRun, gNdsFighterDashRunP0MotionRun, gNdsFighterDashRunP1MotionRun, gNdsFighterDashRunP0StatusRunBrake, gNdsFighterDashRunP1StatusRunBrake, gNdsFighterDashRunP0MotionRunBrake, gNdsFighterDashRunP1MotionRunBrake',
        'printf "DASH_RUN_CALLS=%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u\n", gNdsFighterDashRunWaitInterruptCallCount, gNdsFighterDashRunGroundCheckCallCount, gNdsFighterDashRunOriginalDashCheckCallCount, gNdsFighterDashRunOriginalDashCheckSuccessCount, gNdsFighterDashRunDashSetStatusCount, gNdsFighterDashRunRunSetStatusCount, gNdsFighterDashRunRunBrakeSetStatusCount, gNdsFighterDashRunFtMainDashStatusCount, gNdsFighterDashRunFtMainRunStatusCount, gNdsFighterDashRunFtMainRunBrakeStatusCount, gNdsFighterDashRunDashInterruptCount, gNdsFighterDashRunRunInterruptCount, gNdsFighterDashRunRunBrakeInterruptCount, gNdsFighterDashRunDashPhysicsCount, gNdsFighterDashRunRunBrakePhysicsCount',
        'printf "DASH_RUN_TURNRUN=%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%#x,%#x,%u,%d,%d,%d,%d,%d,%d,%d,%d\n", gNdsFighterDashRunTurnRunCheckCallCount, gNdsFighterDashRunTurnRunCheckSuccessCount, gNdsFighterDashRunTurnRunSetStatusCount, gNdsFighterDashRunFtMainTurnRunStatusCount, gNdsFighterDashRunP0StatusTurnRun, gNdsFighterDashRunP1StatusTurnRun, gNdsFighterDashRunP0MotionTurnRun, gNdsFighterDashRunP1MotionTurnRun, gNdsFighterDashRunP0StatusTurnRunFinal, gNdsFighterDashRunP1StatusTurnRunFinal, gNdsFighterDashRunP0MotionTurnRunFinal, gNdsFighterDashRunP1MotionTurnRunFinal, gNdsFighterDashRunTurnRunCallbackMask, gNdsFighterDashRunTurnRunUpdateMask, gNdsFighterDashRunTurnRunTickCount, gNdsFighterDashRunP0TurnRunLRBefore, gNdsFighterDashRunP1TurnRunLRBefore, gNdsFighterDashRunP0TurnRunLRAfter, gNdsFighterDashRunP1TurnRunLRAfter, gNdsFighterDashRunP0TurnRunVelBeforeMilli, gNdsFighterDashRunP1TurnRunVelBeforeMilli, gNdsFighterDashRunP0TurnRunVelAfterMilli, gNdsFighterDashRunP1TurnRunVelAfterMilli',
        'printf "DASH_RUN_ATTACK11=%u,%u,%u,%u,%u,%u,%u,%u,%#x,%#x,%#x\n", gNdsFighterDashRunAttack1CheckCallCount, gNdsFighterDashRunAttack1CheckSuccessCount, gNdsFighterDashRunAttack11SetStatusCount, gNdsFighterDashRunFtMainAttack11StatusCount, gNdsFighterDashRunP0StatusAttack11, gNdsFighterDashRunP1StatusAttack11, gNdsFighterDashRunP0MotionAttack11, gNdsFighterDashRunP1MotionAttack11, gNdsFighterDashRunAttack11CallbackMask, gNdsFighterDashRunAttack11TickMask, gNdsFighterDashRunAttack11WaitProcMask',
        'printf "DASH_RUN_ATTACK12=%u,%u,%u,%u,%u,%u,%#x,%#x\n", gNdsFighterDashRunAttack12SetStatusCount, gNdsFighterDashRunFtMainAttack12StatusCount, gNdsFighterDashRunP0StatusAttack12, gNdsFighterDashRunP1StatusAttack12, gNdsFighterDashRunP0MotionAttack12, gNdsFighterDashRunP1MotionAttack12, gNdsFighterDashRunAttack12CallbackMask, gNdsFighterDashRunAttack12GotoMask',
        'printf "DASH_RUN_ATTACK13=%u,%u,%u,%u,%u,%u,%#x,%#x\n", gNdsFighterDashRunAttack13SetStatusCount, gNdsFighterDashRunFtMainAttack13StatusCount, gNdsFighterDashRunP0StatusAttack13, gNdsFighterDashRunP1StatusAttack13, gNdsFighterDashRunP0MotionAttack13, gNdsFighterDashRunP1MotionAttack13, gNdsFighterDashRunAttack13CallbackMask, gNdsFighterDashRunAttack13GotoMask',
        'printf "DASH_RUN_ATTACK100=%u,%u,%u,%u,%u,%#x,%#x\n", gNdsFighterDashRunAttack100StartCheckCallCount, gNdsFighterDashRunAttack100StartSetStatusCount, gNdsFighterDashRunFtMainAttack100StartStatusCount, gNdsFighterDashRunP1StatusAttack100Start, gNdsFighterDashRunP1MotionAttack100Start, gNdsFighterDashRunAttack100StartCallbackMask, gNdsFighterDashRunAttack100StartGotoMask',
        'printf "DASH_RUN_ATTACK100_LOOP=%u,%u,%u,%u,%#x,%#x,%#x\n", gNdsFighterDashRunAttack100LoopSetStatusCount, gNdsFighterDashRunFtMainAttack100LoopStatusCount, gNdsFighterDashRunP1StatusAttack100Loop, gNdsFighterDashRunP1MotionAttack100Loop, gNdsFighterDashRunAttack100LoopCallbackMask, gNdsFighterDashRunAttack100LoopGotoMask, gNdsFighterDashRunAttack100LoopTickMask',
        'printf "DASH_RUN_ATTACK=%u,%u,%u,%u,%u,%u,%u,%u,%#x,%#x,%#x\n", gNdsFighterDashRunAttackDashCheckCallCount, gNdsFighterDashRunAttackDashCheckSuccessCount, gNdsFighterDashRunAttackDashSetStatusCount, gNdsFighterDashRunFtMainAttackDashStatusCount, gNdsFighterDashRunP0StatusAttackDash, gNdsFighterDashRunP1StatusAttackDash, gNdsFighterDashRunP0MotionAttackDash, gNdsFighterDashRunP1MotionAttackDash, gNdsFighterDashRunAttackDashCallbackMask, gNdsFighterDashRunAttackDashTickMask, gNdsFighterDashRunAttackDashRunProcMask',
        'printf "DASH_RUN_ATTACK_ANIM=%#x\n", gNdsFighterDashRunAttackAnimEventsMask',
        'printf "DASH_RUN_ATTACK_EVENT=%#x,%#x,%#x,%u,%u,%u,%u,%u,%u,%u,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%#x\n", gNdsFighterDashRunAttackEventMask, gNdsFighterDashRunAttackEventScriptMask, gNdsFighterDashRunAttackEventNoHitMask, gNdsFighterDashRunAttackEventParseCount, gNdsFighterDashRunAttackEventLastPlayer, gNdsFighterDashRunAttackEventLastStatus, gNdsFighterDashRunAttackEventLastState, gNdsFighterDashRunAttackEventLastAttackID, gNdsFighterDashRunAttackEventLastGroupID, gNdsFighterDashRunAttackEventLastJointID, gNdsFighterDashRunAttackEventLastDamage, gNdsFighterDashRunAttackEventLastSize, gNdsFighterDashRunAttackEventLastOffsetX, gNdsFighterDashRunAttackEventLastOffsetY, gNdsFighterDashRunAttackEventLastOffsetZ, gNdsFighterDashRunAttackEventLastAngle, gNdsFighterDashRunAttackEventLastKBG, gNdsFighterDashRunAttackEventLastKBW, gNdsFighterDashRunAttackEventLastBKB, gNdsFighterDashRunAttackEventLastShield, gNdsFighterDashRunAttackEventLastFlags',
        'printf "DASH_RUN_ATTACK_EVENT_CMDS=%#x\n", gNdsFighterDashRunAttackEventCommandMask',
        'printf "DASH_RUN_ATTACK_EVENT_POS=%#x,%u,%u,%u,%d,%d,%d,%d,%d\n", gNdsFighterDashRunAttackEventPositionMask, gNdsFighterDashRunAttackEventPositionState, gNdsFighterDashRunAttackEventPositionAttackID, gNdsFighterDashRunAttackEventPositionJointID, gNdsFighterDashRunAttackEventPositionX, gNdsFighterDashRunAttackEventPositionY, gNdsFighterDashRunAttackEventPositionZ, gNdsFighterDashRunAttackEventPositionMatrixFlag, gNdsFighterDashRunAttackEventPositionMatrixValue',
        'printf "DASH_RUN_PROCPARAMS=%#x,%d,%d,%d,%d,%d,%u,%u,%u\n", gNdsFighterDashRunProcParamsMask, gNdsFighterDashRunProcParamsDamageBefore, gNdsFighterDashRunProcParamsDamageAfter, gNdsFighterDashRunProcParamsQueueBefore, gNdsFighterDashRunProcParamsLagBefore, gNdsFighterDashRunProcParamsHitlag, gNdsFighterDashRunProcParamsPaused, gNdsFighterDashRunProcParamsStatusBefore, gNdsFighterDashRunProcParamsStatusAfter',
        'printf "DASH_RUN_DAMAGE_STATUS=%#x,%u,%u,%u,%u,%u\n", gNdsFighterDashRunDamageStatusMask, gNdsFighterDashRunDamageStatusLevel, gNdsFighterDashRunDamageStatusIndex, gNdsFighterDashRunDamageStatusGround, gNdsFighterDashRunDamageStatusAir, gNdsFighterDashRunDamageStatusElectric',
        'printf "DASH_RUN_DAMAGE_SETUP=%#x,%u,%u,%u,%u,%d,%d,%d,%d,%d,%d\n", gNdsFighterDashRunDamageSetupMask, gNdsFighterDashRunDamageSetupStatusBefore, gNdsFighterDashRunDamageSetupStatusAfter, gNdsFighterDashRunDamageSetupMotionAfter, gNdsFighterDashRunDamageSetupGAAfter, gNdsFighterDashRunDamageSetupHitstunBefore, gNdsFighterDashRunDamageSetupHitstunAfter, gNdsFighterDashRunDamageSetupVelGroundMilli, gNdsFighterDashRunDamageSetupVelAirXMilli, gNdsFighterDashRunDamageSetupVelAirYMilli, gNdsFighterDashRunDamageSetupVelPhysicsMilli',
        'printf "DASH_RUN_GUARD=%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%#x,%#x,%#x,%u\n", gNdsFighterDashRunGuardCheckCallCount, gNdsFighterDashRunGuardCheckSuccessCount, gNdsFighterDashRunGuardSetStatusCount, gNdsFighterDashRunFtMainGuardOnStatusCount, gNdsFighterDashRunP0StatusGuardOn, gNdsFighterDashRunP1StatusGuardOn, gNdsFighterDashRunP0MotionGuardOn, gNdsFighterDashRunP1MotionGuardOn, gNdsFighterDashRunGuardEffectCount, gNdsFighterDashRunGuardFGMCount, gNdsFighterDashRunGuardLastFGM, gNdsFighterDashRunGuardAnimEventsMask, gNdsFighterDashRunGuardCallbackMask, gNdsFighterDashRunGuardStateMask, gNdsFighterDashRunGuardAnimEventsMask, gNdsFighterDashRunGuardFGMCount',
        'printf "DASH_RUN_GUARD_SETOFF=%u,%u,%#x,%#x,%d,%d\n", gNdsFighterDashRunGuardSetOffSetStatusCount, gNdsFighterDashRunFtMainGuardSetOffStatusCount, gNdsFighterDashRunGuardSetOffMask, gNdsFighterDashRunGuardSetOffCallbackMask, gNdsFighterDashRunGuardSetOffFramesMilli, gNdsFighterDashRunGuardSetOffVelMilli',
        'printf "DASH_RUN_ESCAPE=%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%#x,%#x,%#x,%u,%u,%u\n", gNdsFighterDashRunEscapeCheckCallCount, gNdsFighterDashRunEscapeCheckSuccessCount, gNdsFighterDashRunEscapeSetStatusCount, gNdsFighterDashRunFtMainEscapeStatusCount, gNdsFighterDashRunP0StatusEscape, gNdsFighterDashRunP1StatusEscape, gNdsFighterDashRunP0MotionEscape, gNdsFighterDashRunP1MotionEscape, gNdsFighterDashRunP0EscapeItemThrowBuffer, gNdsFighterDashRunP1EscapeItemThrowBuffer, gNdsFighterDashRunEscapeCallbackMask, gNdsFighterDashRunEscapeStateMask, gNdsFighterDashRunEscapeTickMask, gNdsFighterDashRunEscapeInterruptCount, gNdsFighterDashRunEscapePhysicsCount, gNdsFighterDashRunEscapeMapCount',
        'printf "DASH_RUN_MOVE=%d,%d,%d,%d,%d,%d,%u,%u,%u,%u,%u,%u,%u\n", gNdsFighterDashRunP0RootDeltaXMilli, gNdsFighterDashRunP1RootDeltaXMilli, gNdsFighterDashRunP0GroundVelRunMilli, gNdsFighterDashRunP1GroundVelRunMilli, gNdsFighterDashRunP0GroundVelBrakeMilli, gNdsFighterDashRunP1GroundVelBrakeMilli, gNdsFighterDashRunP0RootDirectionOK, gNdsFighterDashRunP1RootDirectionOK, gNdsFighterDashRunSafeFloorCount, gNdsFighterDashRunGObjDelta, gNdsFighterDashRunRootYDriftCount, gNdsFighterDashRunGADriftCount, gNdsFighterDashRunUnexpectedStatusCount',
        'printf "BOUNDARY=%#x,%u\n", gNdsSceneBoundaryResult, gNdsSceneBoundaryKind',
        'detach',
        'quit'
    )
    $gdbStdout = (Invoke-GdbMarkerScript -Gdb $Gdb -Elf $elf -Root $root -Commands $gdbCommands -ScriptName $scriptName).Stdout
    $harn = [regex]::Match($gdbStdout, 'HARN=(0x[0-9a-fA-F]+|0),([0-9]+),([0-9]+),([0-9]+),(0x[0-9a-fA-F]+|0)')
    $scene = [regex]::Match($gdbStdout, 'SCENE=([0-9]+),([0-9]+),([0-9]+)')
    $chain = [regex]::Match($gdbStdout, 'CHAIN=(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0)')
    $final = [regex]::Match($gdbStdout, 'CHAIN_FINAL=([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+)')
    $walkLoop = [regex]::Match($gdbStdout, 'WALK_LOOP=(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),([0-9]+)')
    $dashRun = [regex]::Match($gdbStdout, 'DASH_RUN=(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),([0-9]+)')
    $status = [regex]::Match($gdbStdout, 'DASH_RUN_STATUS=([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+)')
    $calls = [regex]::Match($gdbStdout, 'DASH_RUN_CALLS=([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+)')
    $turnRun = [regex]::Match($gdbStdout, 'DASH_RUN_TURNRUN=([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),([0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+)')
    $attack11 = [regex]::Match($gdbStdout, 'DASH_RUN_ATTACK11=([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0)')
    $attack12 = [regex]::Match($gdbStdout, 'DASH_RUN_ATTACK12=([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0)')
    $attack13 = [regex]::Match($gdbStdout, 'DASH_RUN_ATTACK13=([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0)')
    $attack100 = [regex]::Match($gdbStdout, 'DASH_RUN_ATTACK100=([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0)')
    $attack100Loop = [regex]::Match($gdbStdout, 'DASH_RUN_ATTACK100_LOOP=([0-9]+),([0-9]+),([0-9]+),([0-9]+),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0)')
    $attack = [regex]::Match($gdbStdout, 'DASH_RUN_ATTACK=([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0)')
    $attackAnim = [regex]::Match($gdbStdout, 'DASH_RUN_ATTACK_ANIM=(0x[0-9a-fA-F]+|0)')
    $attackEvent = [regex]::Match($gdbStdout, 'DASH_RUN_ATTACK_EVENT=(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(0x[0-9a-fA-F]+|0)')
    $attackEventCommands = [regex]::Match($gdbStdout, 'DASH_RUN_ATTACK_EVENT_CMDS=(0x[0-9a-fA-F]+|0)')
    $attackEventPos = [regex]::Match($gdbStdout, 'DASH_RUN_ATTACK_EVENT_POS=(0x[0-9a-fA-F]+|0),([0-9]+),([0-9]+),([0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+)')
    $procParams = [regex]::Match($gdbStdout, 'DASH_RUN_PROCPARAMS=(0x[0-9a-fA-F]+|0),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),([0-9]+),([0-9]+),([0-9]+)')
    $damageStatus = [regex]::Match($gdbStdout, 'DASH_RUN_DAMAGE_STATUS=(0x[0-9a-fA-F]+|0),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+)')
    $damageSetup = [regex]::Match($gdbStdout, 'DASH_RUN_DAMAGE_SETUP=(0x[0-9a-fA-F]+|0),([0-9]+),([0-9]+),([0-9]+),([0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+)')
    $guard = [regex]::Match($gdbStdout, 'DASH_RUN_GUARD=([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),([0-9]+)')
    $guardSetOff = [regex]::Match($gdbStdout, 'DASH_RUN_GUARD_SETOFF=([0-9]+),([0-9]+),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(-?[0-9]+),(-?[0-9]+)')
    $escape = [regex]::Match($gdbStdout, 'DASH_RUN_ESCAPE=([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),(0x[0-9a-fA-F]+|0),([0-9]+),([0-9]+),([0-9]+)')
    $move = [regex]::Match($gdbStdout, 'DASH_RUN_MOVE=(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),(-?[0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+),([0-9]+)')
    $boundary = [regex]::Match($gdbStdout, 'BOUNDARY=(0x[0-9a-fA-F]+|0),([0-9]+)')
    Assert-Condition ($harn.Success -and (Convert-MarkerUInt32 $harn.Groups[1].Value) -eq 0x4841524e -and [int]$harn.Groups[2].Value -eq 40 -and [int]$harn.Groups[3].Value -eq 9 -and [int]$harn.Groups[4].Value -eq 1 -and (Convert-MarkerUInt32 $harn.Groups[5].Value) -eq 0) 'Menu-chain Dash-Run harness did not select VS Mode from Title.' $gdbStdout
    Assert-Condition ($chain.Success -and (Convert-MarkerUInt32 $chain.Groups[1].Value) -eq 0x56535452 -and ((Convert-MarkerUInt32 $chain.Groups[2].Value) -band 0xff) -eq 0xff -and (Convert-MarkerUInt32 $chain.Groups[3].Value) -eq 0x50565452 -and ((Convert-MarkerUInt32 $chain.Groups[4].Value) -band 0xff) -eq 0xff -and (Convert-MarkerUInt32 $chain.Groups[5].Value) -eq 0x4d53454c -and ((Convert-MarkerUInt32 $chain.Groups[6].Value) -band 0xff) -eq 0xff) 'Menu-chain transitions did not reach Maps -> VSBattle cleanly.' $gdbStdout
    Assert-Condition ($final.Success -and [int]$final.Groups[1].Value -eq 16 -and [int]$final.Groups[2].Value -eq 21 -and [int]$final.Groups[3].Value -eq 22 -and [int]$final.Groups[4].Value -eq 21 -and [int]$final.Groups[5].Value -eq 6) 'Menu-chain final scene/gkind markers were not expected.' $gdbStdout
    Assert-Condition ($scene.Success -and [int]$scene.Groups[1].Value -eq 22 -and [int]$scene.Groups[2].Value -eq 21 -and [int]$scene.Groups[3].Value -eq 6) 'Live scene is not Pupupu VSBattle from Maps.' $gdbStdout
    Assert-Condition ($walkLoop.Success -and (Convert-MarkerUInt32 $walkLoop.Groups[1].Value) -eq 0x46574c50 -and (Convert-MarkerUInt32 $walkLoop.Groups[2].Value) -eq 0x46574c53 -and ((Convert-MarkerUInt32 $walkLoop.Groups[3].Value) -band 0x7ff) -eq 0x7ff -and (Convert-MarkerUInt32 $walkLoop.Groups[4].Value) -eq 0xff -and [int]$walkLoop.Groups[5].Value -eq 2) 'Prerequisite Walk-loop proof did not pass.' $gdbStdout
    Assert-Condition ($dashRun.Success -and (Convert-MarkerUInt32 $dashRun.Groups[1].Value) -eq 0x4644524e -and (Convert-MarkerUInt32 $dashRun.Groups[2].Value) -eq 0x46445253 -and ((Convert-MarkerUInt32 $dashRun.Groups[3].Value) -band 0x3fffffff) -eq 0x3fffffff -and (Convert-MarkerUInt32 $dashRun.Groups[4].Value) -eq 0xff -and [int]$dashRun.Groups[5].Value -eq 2) 'Dash-Run proof did not pass.' $gdbStdout
    Assert-Condition ($status.Success -and [int]$status.Groups[1].Value -eq 15 -and [int]$status.Groups[2].Value -eq 15 -and [int]$status.Groups[3].Value -eq 9 -and [int]$status.Groups[4].Value -eq 9 -and [int]$status.Groups[5].Value -eq 16 -and [int]$status.Groups[6].Value -eq 16 -and [int]$status.Groups[7].Value -eq 10 -and [int]$status.Groups[8].Value -eq 10 -and [int]$status.Groups[9].Value -eq 17 -and [int]$status.Groups[10].Value -eq 17 -and [int]$status.Groups[11].Value -eq 11 -and [int]$status.Groups[12].Value -eq 11) 'Dash/Run/RunBrake status or motion IDs were not expected.' $gdbStdout
    Assert-Condition ($calls.Success -and [int]$calls.Groups[1].Value -eq 4 -and [int]$calls.Groups[2].Value -eq 4 -and [int]$calls.Groups[3].Value -eq 2 -and [int]$calls.Groups[4].Value -eq 2 -and [int]$calls.Groups[5].Value -eq 2 -and [int]$calls.Groups[6].Value -eq 4 -and [int]$calls.Groups[7].Value -eq 2 -and [int]$calls.Groups[8].Value -eq 2 -and [int]$calls.Groups[9].Value -eq 4 -and [int]$calls.Groups[10].Value -eq 2 -and [int]$calls.Groups[11].Value -eq 2 -and [int]$calls.Groups[12].Value -eq 10 -and [int]$calls.Groups[13].Value -eq 4 -and [int]$calls.Groups[14].Value -eq 2 -and [int]$calls.Groups[15].Value -eq 4) 'Dash-Run original call counters were not expected.' $gdbStdout
    Assert-Condition ($turnRun.Success -and [int]$turnRun.Groups[1].Value -eq 2 -and [int]$turnRun.Groups[2].Value -eq 2 -and [int]$turnRun.Groups[3].Value -eq 2 -and [int]$turnRun.Groups[4].Value -eq 2 -and [int]$turnRun.Groups[5].Value -eq 19 -and [int]$turnRun.Groups[6].Value -eq 19 -and [int]$turnRun.Groups[7].Value -eq 13 -and [int]$turnRun.Groups[8].Value -eq 13 -and [int]$turnRun.Groups[9].Value -eq 16 -and [int]$turnRun.Groups[10].Value -eq 16 -and [int]$turnRun.Groups[11].Value -eq 10 -and [int]$turnRun.Groups[12].Value -eq 10 -and (Convert-MarkerUInt32 $turnRun.Groups[13].Value) -eq 0xff -and (Convert-MarkerUInt32 $turnRun.Groups[14].Value) -eq 0xf -and [int]$turnRun.Groups[15].Value -eq 4 -and [int]$turnRun.Groups[18].Value -eq (-[int]$turnRun.Groups[16].Value) -and [int]$turnRun.Groups[19].Value -eq (-[int]$turnRun.Groups[17].Value) -and [int]$turnRun.Groups[22].Value -eq (-[int]$turnRun.Groups[20].Value) -and [int]$turnRun.Groups[23].Value -eq (-[int]$turnRun.Groups[21].Value)) 'Original Run -> TurnRun -> Run proof did not pass.' $gdbStdout
    Assert-Condition ($attack11.Success -and [int]$attack11.Groups[1].Value -ge 2 -and [int]$attack11.Groups[2].Value -ge 2 -and [int]$attack11.Groups[3].Value -ge 2 -and [int]$attack11.Groups[4].Value -ge 2 -and [int]$attack11.Groups[5].Value -eq 190 -and [int]$attack11.Groups[6].Value -eq 190 -and [int]$attack11.Groups[7].Value -eq 165 -and [int]$attack11.Groups[8].Value -eq 165 -and (Convert-MarkerUInt32 $attack11.Groups[9].Value) -eq 0xff -and (Convert-MarkerUInt32 $attack11.Groups[10].Value) -eq 0xff -and (Convert-MarkerUInt32 $attack11.Groups[11].Value) -eq 0x3) 'Original Attack11 A-tap status/callback proof did not pass.' $gdbStdout
    Assert-Condition ($attack12.Success -and [int]$attack12.Groups[1].Value -eq 2 -and [int]$attack12.Groups[2].Value -eq 2 -and [int]$attack12.Groups[3].Value -eq 191 -and [int]$attack12.Groups[4].Value -eq 191 -and [int]$attack12.Groups[5].Value -eq 166 -and [int]$attack12.Groups[6].Value -eq 166 -and (Convert-MarkerUInt32 $attack12.Groups[7].Value) -eq 0xff -and (Convert-MarkerUInt32 $attack12.Groups[8].Value) -eq 0xf) 'Original Attack11 -> Attack12 follow-up proof did not pass.' $gdbStdout
    Assert-Condition ($attack13.Success -and [int]$attack13.Groups[1].Value -eq 1 -and [int]$attack13.Groups[2].Value -eq 1 -and [int]$attack13.Groups[3].Value -eq 220 -and [int]$attack13.Groups[4].Value -eq 191 -and [int]$attack13.Groups[5].Value -eq 195 -and [int]$attack13.Groups[6].Value -eq 166 -and (Convert-MarkerUInt32 $attack13.Groups[7].Value) -eq 0xf -and (Convert-MarkerUInt32 $attack13.Groups[8].Value) -eq 0x7) 'Original Attack12 -> Attack13 gate proof did not pass.' $gdbStdout
    Assert-Condition ($attack100.Success -and [int]$attack100.Groups[1].Value -eq 5 -and [int]$attack100.Groups[2].Value -eq 1 -and [int]$attack100.Groups[3].Value -eq 1 -and [int]$attack100.Groups[4].Value -eq 220 -and [int]$attack100.Groups[5].Value -eq 195 -and (Convert-MarkerUInt32 $attack100.Groups[6].Value) -eq 0xf -and (Convert-MarkerUInt32 $attack100.Groups[7].Value) -eq 0x3) 'Original Attack12 -> Fox Attack100Start gate proof did not pass.' $gdbStdout
    Assert-Condition ($attack100Loop.Success -and [int]$attack100Loop.Groups[1].Value -eq 0 -and [int]$attack100Loop.Groups[2].Value -eq 1 -and [int]$attack100Loop.Groups[3].Value -eq 221 -and [int]$attack100Loop.Groups[4].Value -eq 196 -and (Convert-MarkerUInt32 $attack100Loop.Groups[5].Value) -eq 0xf -and (Convert-MarkerUInt32 $attack100Loop.Groups[6].Value) -eq 0x3 -and (Convert-MarkerUInt32 $attack100Loop.Groups[7].Value) -eq 0xfff) 'Original Fox Attack100Start -> Attack100Loop/End proof did not pass.' $gdbStdout
    Assert-Condition ($attack.Success -and [int]$attack.Groups[1].Value -eq 2 -and [int]$attack.Groups[2].Value -eq 2 -and [int]$attack.Groups[3].Value -eq 2 -and [int]$attack.Groups[4].Value -eq 2 -and [int]$attack.Groups[5].Value -eq 192 -and [int]$attack.Groups[6].Value -eq 192 -and [int]$attack.Groups[7].Value -eq 167 -and [int]$attack.Groups[8].Value -eq 167 -and (Convert-MarkerUInt32 $attack.Groups[9].Value) -eq 0xff -and (Convert-MarkerUInt32 $attack.Groups[10].Value) -eq 0x3f -and (Convert-MarkerUInt32 $attack.Groups[11].Value) -eq 0x3) 'Original AttackDash A-tap status/callback proof did not pass.' $gdbStdout
    Assert-Condition ($attackAnim.Success -and (Convert-MarkerUInt32 $attackAnim.Groups[1].Value) -eq 0x3f) 'Original attack status animation-event hook proof did not pass.' $gdbStdout
    Assert-Condition ($attackEvent.Success -and (Convert-MarkerUInt32 $attackEvent.Groups[1].Value) -eq 0x1f -and (Convert-MarkerUInt32 $attackEvent.Groups[2].Value) -eq 0x3f -and (Convert-MarkerUInt32 $attackEvent.Groups[3].Value) -eq 0x20 -and [int]$attackEvent.Groups[4].Value -eq 10 -and [int]$attackEvent.Groups[5].Value -eq 1 -and [int]$attackEvent.Groups[6].Value -eq 191 -and [int]$attackEvent.Groups[7].Value -eq 1 -and [int]$attackEvent.Groups[8].Value -eq 1 -and [int]$attackEvent.Groups[9].Value -eq 0 -and [int]$attackEvent.Groups[10].Value -eq 14 -and [int]$attackEvent.Groups[11].Value -eq 4 -and [int]$attackEvent.Groups[12].Value -eq 100 -and [int]$attackEvent.Groups[13].Value -eq 0 -and [int]$attackEvent.Groups[14].Value -eq 0 -and [int]$attackEvent.Groups[15].Value -eq 0 -and [int]$attackEvent.Groups[16].Value -eq 70 -and [int]$attackEvent.Groups[17].Value -eq 100 -and [int]$attackEvent.Groups[18].Value -eq 0 -and [int]$attackEvent.Groups[19].Value -eq 0 -and [int]$attackEvent.Groups[20].Value -eq 0 -and (Convert-MarkerUInt32 $attackEvent.Groups[21].Value) -eq 0x7) 'Bounded original MakeAttackColl event decode proof did not pass.' $gdbStdout
    Assert-Condition ($attackEventCommands.Success -and (Convert-MarkerUInt32 $attackEventCommands.Groups[1].Value) -eq 0xf) 'Bounded original attack damage/size/clear command proof did not pass.' $gdbStdout
    Assert-Condition ($attackEventPos.Success -and ((Convert-MarkerUInt32 $attackEventPos.Groups[1].Value) -band 0x1ffff) -eq 0x1ffff -and [int]$attackEventPos.Groups[2].Value -eq 3 -and [int]$attackEventPos.Groups[3].Value -eq 1 -and [int]$attackEventPos.Groups[4].Value -eq 14 -and [int]$attackEventPos.Groups[8].Value -eq 0 -and [int]$attackEventPos.Groups[9].Value -eq 0) 'Bounded original MakeAttackColl Interpolate live position/range/rectangle/collide/record/hit-log/SFX/stats/proc-params proof did not pass.' $gdbStdout
    $procParamsRequiredMask = Convert-MarkerUInt32 '0xffffffff'
    Assert-Condition ($procParams.Success -and ((Convert-MarkerUInt32 $procParams.Groups[1].Value) -band $procParamsRequiredMask) -eq $procParamsRequiredMask -and ([int]$procParams.Groups[3].Value -eq ([int]$procParams.Groups[2].Value + [int]$procParams.Groups[4].Value)) -and [int]$procParams.Groups[4].Value -gt 0 -and [int]$procParams.Groups[5].Value -gt 0 -and [int]$procParams.Groups[6].Value -gt 0 -and [int]$procParams.Groups[7].Value -eq 1 -and [int]$procParams.Groups[8].Value -eq [int]$procParams.Groups[9].Value) 'Bounded source-shaped ftMainProcParams damage/hitlag scheduling proof did not pass.' $gdbStdout
    Assert-Condition ($damageStatus.Success -and ((Convert-MarkerUInt32 $damageStatus.Groups[1].Value) -band 0x1f) -eq 0x1f -and [int]$damageStatus.Groups[2].Value -ge 0 -and [int]$damageStatus.Groups[2].Value -le 3 -and [int]$damageStatus.Groups[3].Value -ge 0 -and [int]$damageStatus.Groups[3].Value -le 2 -and [int]$damageStatus.Groups[4].Value -ge 37 -and [int]$damageStatus.Groups[4].Value -le 56 -and [int]$damageStatus.Groups[5].Value -ge 46 -and [int]$damageStatus.Groups[5].Value -le 53 -and (([int]$damageStatus.Groups[6].Value -eq 49) -or ([int]$damageStatus.Groups[6].Value -eq 50))) 'Bounded original ftcommondamage status selection proof did not pass.' $gdbStdout
    $damageSetupVelocitySource = 0
    if ($damageSetup.Success) {
        $damageSetupVelocitySource = if ([int]$damageSetup.Groups[5].Value -eq 1) { [int]$damageSetup.Groups[9].Value } else { [int]$damageSetup.Groups[8].Value }
    }
    $damageSetupRequiredMask = Convert-MarkerUInt32 '0xffffffff'
    Assert-Condition ($damageSetup.Success -and ((Convert-MarkerUInt32 $damageSetup.Groups[1].Value) -band $damageSetupRequiredMask) -eq $damageSetupRequiredMask -and [int]$damageSetup.Groups[2].Value -eq [int]$procParams.Groups[8].Value -and [int]$damageSetup.Groups[3].Value -ge 37 -and [int]$damageSetup.Groups[3].Value -le 56 -and [int]$damageSetup.Groups[4].Value -ge 31 -and [int]$damageSetup.Groups[4].Value -le 49 -and [int]$damageSetup.Groups[5].Value -ge 0 -and [int]$damageSetup.Groups[5].Value -le 1 -and [int]$damageSetup.Groups[6].Value -gt 0 -and [int]$damageSetup.Groups[7].Value -eq ([int]$damageSetup.Groups[6].Value - 1) -and (([int]$damageSetup.Groups[8].Value -ne 0) -or ([int]$damageSetup.Groups[9].Value -ne 0) -or ([int]$damageSetup.Groups[10].Value -ne 0)) -and [Math]::Abs([int]$damageSetup.Groups[11].Value) -lt [Math]::Abs($damageSetupVelocitySource)) 'Bounded original ftcommondamage status setup/update/physics/flyroll/knockback-invincible/lag-update/hitlag-lifecycle/setup-tail/proc-passive dispatch/proc-passive status/air-map/interrupt/expiry/fall-physics/fastfall/map-floor-cliff/hammer-interrupt proof did not pass.' $gdbStdout
    $guardRequiredMask = Convert-MarkerUInt32 '0xfffffe0f'
    Assert-Condition ($guard.Success -and [int]$guard.Groups[1].Value -eq 2 -and [int]$guard.Groups[2].Value -eq 2 -and [int]$guard.Groups[3].Value -eq 2 -and [int]$guard.Groups[4].Value -eq 2 -and [int]$guard.Groups[5].Value -eq 152 -and [int]$guard.Groups[6].Value -eq 152 -and [int]$guard.Groups[7].Value -eq 134 -and [int]$guard.Groups[8].Value -eq 134 -and [int]$guard.Groups[9].Value -eq 2 -and [int]$guard.Groups[10].Value -eq 2 -and [int]$guard.Groups[11].Value -eq 13 -and [int]$guard.Groups[12].Value -eq 3 -and (Convert-MarkerUInt32 $guard.Groups[13].Value) -eq 0xff -and ((Convert-MarkerUInt32 $guard.Groups[14].Value) -band $guardRequiredMask) -eq $guardRequiredMask -and (Convert-MarkerUInt32 $guard.Groups[15].Value) -eq 0x3 -and [int]$guard.Groups[16].Value -eq 2) 'Original GuardOn/Guard/GuardOff Z-hold status/shield/update/handoff proof did not pass.' $gdbStdout
    Assert-Condition ($guardSetOff.Success -and [int]$guardSetOff.Groups[1].Value -eq 4 -and [int]$guardSetOff.Groups[2].Value -eq 4 -and ((Convert-MarkerUInt32 $guardSetOff.Groups[3].Value) -band 0xfff) -eq 0xfff -and (Convert-MarkerUInt32 $guardSetOff.Groups[4].Value) -eq 0xff -and [int]$guardSetOff.Groups[5].Value -eq 20200 -and [int]$guardSetOff.Groups[6].Value -eq -40400) 'Original Guard SetOff status/update proof did not pass.' $gdbStdout
    Assert-Condition ($escape.Success -and [int]$escape.Groups[1].Value -eq 2 -and [int]$escape.Groups[2].Value -eq 2 -and [int]$escape.Groups[3].Value -eq 2 -and [int]$escape.Groups[4].Value -eq 2 -and [int]$escape.Groups[5].Value -eq 156 -and [int]$escape.Groups[6].Value -eq 157 -and [int]$escape.Groups[7].Value -eq 136 -and [int]$escape.Groups[8].Value -eq 137 -and [int]$escape.Groups[9].Value -eq 5 -and [int]$escape.Groups[10].Value -eq 5 -and (Convert-MarkerUInt32 $escape.Groups[11].Value) -eq 0x3ff -and (Convert-MarkerUInt32 $escape.Groups[12].Value) -eq 0xff -and (Convert-MarkerUInt32 $escape.Groups[13].Value) -eq 0x3ff -and [int]$escape.Groups[14].Value -eq 2 -and [int]$escape.Groups[15].Value -eq 2 -and [int]$escape.Groups[16].Value -eq 2) 'Original Guard EscapeF/EscapeB proof did not pass.' $gdbStdout
    Assert-Condition ($move.Success -and [int]$move.Groups[1].Value -ne 0 -and [int]$move.Groups[2].Value -ne 0 -and [int]$move.Groups[5].Value -lt [int]$move.Groups[3].Value -and [int]$move.Groups[6].Value -lt [int]$move.Groups[4].Value -and [int]$move.Groups[7].Value -eq 1 -and [int]$move.Groups[8].Value -eq 1 -and [int]$move.Groups[9].Value -ge 14 -and [int]$move.Groups[10].Value -eq 0 -and [int]$move.Groups[11].Value -eq 0 -and [int]$move.Groups[12].Value -eq 0 -and [int]$move.Groups[13].Value -eq 0) 'Dash-Run movement or safety counters failed.' $gdbStdout
    Assert-Condition ($boundary.Success -and (Convert-MarkerUInt32 $boundary.Groups[1].Value) -eq 0x53434e45 -and [int]$boundary.Groups[2].Value -eq 22) 'VSBattle did not park at the bounded scene boundary after Dash-Run proof.' $gdbStdout
    Write-Output ("Menu-chain Mario/Fox Dash-Run harness passed: chain final=22/21 wait->attack11={0}/{1} cb={2} tick={3} waitproc={4}; guard={5}/{6} cb={7} state={8} fgm={9}; setoff={10}/{11} mask={12} cb={13} frame={14} vel={15}; escape={16}/{17} cb={18} state={19}; attack11->attack12={20}/{21} cb={22} goto={23}; attack12->attack13={24}/{25} foxblock={26}/{27} cb={28} goto={29}; fox attack100start={30}/{31} cb={32} goto={33}; fox attack100loop={34}/{35} cb={36} goto={37} tick={38}; anim={39}; event={40}/{41}/{42}/{43} dmg={44} size={45} off={46}/{47}/{48}; dash->run->runbrake + attackdash={49}/{50} cb={51} tick={52} runproc={53} root-dx={54}/{55} vel={56}/{57}->{58}/{59}" -f $attack11.Groups[5].Value, $attack11.Groups[7].Value, $attack11.Groups[9].Value, $attack11.Groups[10].Value, $attack11.Groups[11].Value, $guard.Groups[5].Value, $guard.Groups[7].Value, $guard.Groups[13].Value, $guard.Groups[14].Value, $guard.Groups[11].Value, $guardSetOff.Groups[1].Value, $guardSetOff.Groups[2].Value, $guardSetOff.Groups[3].Value, $guardSetOff.Groups[4].Value, $guardSetOff.Groups[5].Value, $guardSetOff.Groups[6].Value, $escape.Groups[5].Value, $escape.Groups[7].Value, $escape.Groups[11].Value, $escape.Groups[12].Value, $attack12.Groups[3].Value, $attack12.Groups[5].Value, $attack12.Groups[7].Value, $attack12.Groups[8].Value, $attack13.Groups[3].Value, $attack13.Groups[5].Value, $attack13.Groups[4].Value, $attack13.Groups[6].Value, $attack13.Groups[7].Value, $attack13.Groups[8].Value, $attack100.Groups[4].Value, $attack100.Groups[5].Value, $attack100.Groups[6].Value, $attack100.Groups[7].Value, $attack100Loop.Groups[3].Value, $attack100Loop.Groups[4].Value, $attack100Loop.Groups[5].Value, $attack100Loop.Groups[6].Value, $attack100Loop.Groups[7].Value, $attackAnim.Groups[1].Value, $attackEvent.Groups[1].Value, $attackEvent.Groups[2].Value, $attackEvent.Groups[3].Value, $attackEvent.Groups[4].Value, $attackEvent.Groups[11].Value, $attackEvent.Groups[12].Value, $attackEvent.Groups[13].Value, $attackEvent.Groups[14].Value, $attackEvent.Groups[15].Value, $attack.Groups[5].Value, $attack.Groups[7].Value, $attack.Groups[9].Value, $attack.Groups[10].Value, $attack.Groups[11].Value, $move.Groups[1].Value, $move.Groups[2].Value, $move.Groups[3].Value, $move.Groups[4].Value, $move.Groups[5].Value, $move.Groups[6].Value)
} finally {
    if ($null -ne $emulator) {
        $emulator.Refresh()
        if (-not $emulator.HasExited) {
            Stop-Process -Id $emulator.Id -Force
            $emulator.WaitForExit()
        }
    }
    Restore-MelonDSGdbConfig -State $configState
    Remove-GdbMarkerTemps -Root $root -ScriptName $scriptName
    Remove-Item $stdout, $stderr -Force -ErrorAction SilentlyContinue
}
