/**
 * acmd_trace.h — Port-side audio command (Acmd) trace system
 *
 * Captures every Acmd generated by the N64 audio synthesis pull chain
 * (n_alAudioFrame), producing structured per-task trace files that can
 * be compared against N64 emulator traces.
 *
 * Usage:
 *   Set environment variable SSB64_ACMD_TRACE=1 before launching.
 *   Traces are written to debug_traces/ in the working directory.
 *
 * Can also be enabled at runtime via:
 *   acmd_trace_set_enabled(1);
 */
#ifndef ACMD_TRACE_H
#define ACMD_TRACE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Initialize the audio trace system. Call once at startup.
 * Checks SSB64_ACMD_TRACE env var and opens the output directory.
 */
void acmd_trace_init(void);

/**
 * Shut down the trace system and flush any open files.
 */
void acmd_trace_shutdown(void);

/**
 * Enable or disable tracing at runtime.
 */
void acmd_trace_set_enabled(int enabled);

/**
 * Returns nonzero if tracing is currently active.
 */
int acmd_trace_is_enabled(void);

/**
 * Mark the beginning of a new audio task (one n_alAudioFrame call).
 */
void acmd_trace_begin_task(void);

/**
 * Mark the end of the current audio task and flush the trace buffer.
 */
void acmd_trace_end_task(void);

/**
 * Log a single Acmd during or after synthesis.
 * w0/w1 are the raw 32-bit command words from the Acmd union.
 */
void acmd_trace_log_cmd(uint32_t w0, uint32_t w1);

/**
 * Convenience: walk an Acmd buffer and log every command.
 * cmd_list points to the first Acmd, cmd_count is the number of commands.
 * Call between acmd_trace_begin_task / acmd_trace_end_task.
 */
void acmd_trace_log_buffer(const void *cmd_list, int cmd_count);

/**
 * Set the maximum number of audio tasks to trace (0 = unlimited).
 * Default: 600 (10 seconds at ~60 tasks/sec).
 * Controlled by SSB64_ACMD_TRACE_TASKS env var.
 */
void acmd_trace_set_max_tasks(int max_tasks);

#ifdef __cplusplus
}
#endif

#endif /* ACMD_TRACE_H */
