#ifndef SSB64_NDS_GM_GMSOUND_H
#define SSB64_NDS_GM_GMSOUND_H

typedef enum gmMusicID
{
    nSYAudioBGMPupupu = 0,
    nSYAudioBGMInishieHurry = 3,
    nSYAudioBGMWinDefault = 11,
    nSYAudioBGMWinMario = 12,
    nSYAudioBGMWinMetroid = 13,
    nSYAudioBGMWinDonkey = 14,
    nSYAudioBGMWinKirby = 15,
    nSYAudioBGMWinFox = 16,
    nSYAudioBGMWinMother = 17,
    nSYAudioBGMWinYoshi = 18,
    nSYAudioBGMWinFZero = 19,
    nSYAudioBGMWinPMonsters = 20,
    nSYAudioBGMWinZelda = 21,
    nSYAudioBGMResults = 22,
    nSYAudioBGMModeSelect = 44,
    nSYAudioBGMBattleSelect = 10,
    nSYAudioBGMStar = 46
} gmMusicID;

typedef enum gmFGMID
{
    nSYAudioFGMExplodeS = 0,
    nSYAudioFGMFireShoot1 = 2,
    nSYAudioFGMUnkSmallPing1 = 6,
    nSYAudioFGMGuardOn = 13,
    nSYAudioFGMGuardOff = 14,
    nSYAudioFGMShieldBreak = 15,
    nSYAudioFGMCatch = 19,
    nSYAudioFGMDeadUpStar = 12,
    nSYAudioFGMShockL = 22,
    nSYAudioFGMShockM = 23,
    nSYAudioFGMShockS = 24,
    nSYAudioFGMShockML = 29,
    nSYAudioFGMBurnL = 25,
    nSYAudioFGMBurnM = 27,
    nSYAudioFGMBurnS = 28,
    nSYAudioFGMKickL = 31,
    nSYAudioFGMKickM = 32,
    nSYAudioFGMKickS = 34,
    nSYAudioFGMPunchL = 37,
    nSYAudioFGMPunchM = 38,
    nSYAudioFGMPunchS = 40,
    nSYAudioFGMLightSwingL = 41,
    nSYAudioFGMLightSwingM = 42,
    nSYAudioFGMLightSwingS = 43,
    nSYAudioFGMHarisenHit = 51,
    nSYAudioFGMBatHit = 52,
    nSYAudioFGMStarGet = 54,
    nSYAudioFGMFoxLanding = 74,
    nSYAudioFGMMarioLanding = 77,
    nSYAudioFGMNessLanding = 78,
    /* The dodge. GuardOn/GuardOff (13/14) and GamePause (278) were already
     * declared above and below; only this one was missing. All four are core
     * P1 cues a BOTH-CPU stress match asks for and a single-CPU one never
     * reaches -- nobody dodges or shields when Mario stands still. */
    nSYAudioFGMEscape = 11,
    /* The light swing, reached only once every fireball spawned. */
    nSYAudioFGMLightSwingLw1 = 18,
    nSYAudioFGMUnkGrind4 = 85,
    nSYAudioFGMGroundGrind2 = 96,
    nSYAudioFGMGroundGrind3 = 98,
    nSYAudioFGMNessJump = 100,
    nSYAudioFGMMarioDash = 121,
    nSYAudioFGMSamusDash = 127,
    nSYAudioFGMMenuSelect = 158,
    nSYAudioFGMStageSelect = 159,
    nSYAudioFGMMenuScroll1 = 163,
    nSYAudioFGMMenuScroll2 = 164,
    nSYAudioFGMMenuDenied = 165,
    nSYAudioFGMAltitudeWarn = 153,
    nSYAudioFGMDeadExplodeL = 154,
    nSYAudioFGMDeadExplodeS = 155,
    nSYAudioFGMPlayerSlotClose = 166,
    nSYAudioFGMPlayerSlotWhoosh = 167,
    nSYAudioFGMFoxSpecialN = 185,
    nSYAudioFGMFoxSpecialHiStart = 186,
    nSYAudioFGMFoxSpecialHiFly = 187,
    nSYAudioFGMFoxSpecialLwStart = 189,
    nSYAudioFGMFoxAttackAirLw = 190,
    nSYAudioFGMKirbyStarPing1 = 200,
    nSYAudioFGMKirbySpecialNLoseCopy = 204,
    nSYAudioFGMMarioSpecialN = 215,
    nSYAudioFGMMarioSpecialHiCoin = 216,
    nSYAudioFGMMarioSpecialHiJump = 217,
    nSYAudioFGMMarioUnkSwing1 = 218,
    nSYAudioFGMMarioUnkSwing2 = 219,
    nSYAudioFGMMagnify = 271,
    nSYAudioFGMGamePause = 278,
    nSYAudioFGMSlashL = 261,
    nSYAudioFGMSlashM = 262,
    nSYAudioFGMSlashS = 263,
    nSYAudioFGMBladeSwing4 = 258,
    nSYAudioFGMBladeSwing3 = 259,
    nSYAudioFGMBladeDraw = 264,
    nSYAudioFGMPlayerHeal = 274,
    nSYAudioFGMStockSteal = 276,
    nSYAudioFGMJungleTaruCannShoot = 281,
    nSYAudioFGMJungleTaruCannEnter = 282,
    nSYAudioFGMHyruleTwisterAppear = 283,
    nSYAudioFGMHyruleTwisterTrapped = 284,
    nSYAudioFGMPupupuWhispyWind = 0x11d,
    nSYAudioFGMFloorDamageFire = 286,
    /* P2-3f13, Captain Falcon's ten. 73/106/117 share one wave with the
     * Mario/Fox landing family; 180/181 are the Falcon Flyer's engine;
     * 183/184 are the two halves of Falcon Punch. */
    nSYAudioFGMCaptainLanding = 73,
    nSYAudioFGMCaptainFoot = 106,
    nSYAudioFGMCaptainDash = 117,
    nSYAudioFGMCaptainAppearCar1 = 180,
    nSYAudioFGMCaptainAppearCar2 = 181,
    nSYAudioFGMCaptainSpecialHi = 182,
    nSYAudioFGMCaptainSpecialNStart = 183,
    nSYAudioFGMCaptainSpecialNPunch = 184,
    nSYAudioFGMCaptainDeadSlam = 288,
    nSYAudioFGMCaptainDownBounce = 299,
    nSYAudioFGMFoxDeadSlam = 289,
    nSYAudioFGMMarioDeadSlam = 292,
    nSYAudioFGMFoxDownBounce = 300,
    nSYAudioFGMMarioDownBounce = 303
} gmFGMID;

typedef enum gmVoiceID
{
    nSYAudioVoiceDonkeyFuraSleep = 324,
    nSYAudioVoiceDonkeyAppeal = 325,
    nSYAudioVoiceDonkeySmash1 = 326,
    nSYAudioVoiceDonkeySmash2 = 327,
    nSYAudioVoiceDonkeySmash3 = 328,
    nSYAudioVoiceDonkeySpecialN = 329,
    nSYAudioVoiceDonkeyDeadUp = 330,
    nSYAudioVoiceDonkeyFuraFura = 331,
    nSYAudioVoiceDonkeyDamage = 332,
    nSYAudioVoiceDonkeyDead1 = 333,
    nSYAudioVoiceDonkeyHeavyGet = 334,
    nSYAudioVoiceDonkeyHeavyUnk = 335,
    nSYAudioVoiceDonkeyDead2 = 336,
    /* P2-3f13, the complete Captain Falcon voice run 337..359. SpecialNFalcon
     * + SpecialNPunch are the two identity lines. */
    nSYAudioVoiceCaptainAppeal = 337,
    nSYAudioVoiceCaptainSpecialHi = 338,
    nSYAudioVoiceCaptainSmash1 = 339,
    nSYAudioVoiceCaptainSmash2 = 340,
    nSYAudioVoiceCaptainSmash3 = 341,
    nSYAudioVoiceCaptainSmash4 = 342,
    nSYAudioVoiceCaptainFinalComeOn = 343,
    nSYAudioVoiceCaptainSmash5 = 344,
    nSYAudioVoiceCaptainAttackS4 = 345,
    nSYAudioVoiceCaptainSpecialLw = 346,
    nSYAudioVoiceCaptainSpecialNPunch = 347,
    nSYAudioVoiceCaptainSpecialNFalcon = 348,
    nSYAudioVoiceCaptainDeadUp = 349,
    nSYAudioVoiceCaptainFuraFura = 350,
    nSYAudioVoiceCaptainDamage = 351,
    nSYAudioVoiceCaptainUnkPing1 = 352,
    nSYAudioVoiceCaptainJumpAerial = 353,
    nSYAudioVoiceCaptainHeavyGet = 354,
    nSYAudioVoiceCaptainDead = 355,
    nSYAudioVoiceCaptainFuraSleep = 356,
    nSYAudioVoiceCaptainUnkQuick = 357,
    nSYAudioVoiceCaptainUnkPing2 = 358,
    nSYAudioVoiceCaptainUnkPing3 = 359,
    nSYAudioVoiceFoxDeadUp = 360,
    nSYAudioVoiceFoxSpecialHi = 362,
    nSYAudioVoiceFoxJumpAerial = 363,
    nSYAudioVoiceFoxEscape = 364,
    nSYAudioVoiceFoxSelected = 365,
    /* The teeter on a ledge edge. */
    nSYAudioVoiceFoxOttotto = 369,
    nSYAudioVoiceFoxWin = 368,
    nSYAudioVoiceFoxDead = 370,
    nSYAudioVoiceFoxSmash1 = 372,
    nSYAudioVoiceFoxSmash2 = 373,
    nSYAudioVoiceFoxSmash3 = 374,
    nSYAudioVoiceFoxDamage = 375,
    nSYAudioVoiceLinkSmash1 = 401,
    nSYAudioVoiceLuigiFuraFura = 421,
    nSYAudioVoiceMarioSmash1 = 429,
    nSYAudioVoiceMarioSmash2 = 430,
    nSYAudioVoiceMarioSmash3 = 431,
    nSYAudioVoiceMarioSpecialLw = 432,
    nSYAudioVoiceMarioDeadUp = 433,
    nSYAudioVoiceMarioJumpAerial = 436,
    nSYAudioVoiceMarioHeavyGet = 438,
    nSYAudioVoiceMarioDead = 439,
    nSYAudioVoiceMarioDamage = 440,
    nSYAudioVoiceMarioHereWe = 441,
    nSYAudioVoiceAnnounceFailure = 460,
    nSYAudioVoiceAnnounceOne = 467,
    nSYAudioVoiceAnnounceTwo = 469,
    nSYAudioVoiceAnnounceThree = 470,
    nSYAudioVoiceAnnounceFour = 471,
    nSYAudioVoiceAnnounceFive = 472,
    nSYAudioVoiceAnnounceBlueTeam = 475,
    nSYAudioVoiceAnnounceComputerPlayer = 480,
    nSYAudioVoiceAnnounceDonkey = 483,
    nSYAudioVoiceAnnounceCaptain = 485,
    nSYAudioVoiceAnnounceFox = 486,
    nSYAudioVoiceAnnounceGameSet = 488,
    nSYAudioVoiceAnnounceGo = 490,
    nSYAudioVoiceAnnounceGreenTeam = 491,
    nSYAudioVoiceAnnounceKirby = 496,
    nSYAudioVoiceAnnounceLink = 497,
    nSYAudioVoiceAnnounceLuigi = 498,
    nSYAudioVoiceAnnounceMario = 499,
    nSYAudioVoiceAnnounceNess = 501,
    nSYAudioVoiceAnnouncePlayer1 = 503,
    nSYAudioVoiceAnnouncePlayer2 = 504,
    nSYAudioVoiceAnnouncePlayer3 = 505,
    nSYAudioVoiceAnnouncePlayer4 = 506,
    nSYAudioVoiceAnnouncePikachu = 507,
    nSYAudioVoiceAnnouncePurin = 508,
    nSYAudioVoiceAnnounceRedTeam = 510,
    nSYAudioVoiceAnnounceDefeated = 511,
    nSYAudioVoiceAnnounceFreeForAll = 512,
    nSYAudioVoicePikachuFuraSleep = 551,
    nSYAudioVoiceAnnounceSamus = 513,
    nSYAudioVoiceAnnounceSuddenDeath = 514,
    nSYAudioVoiceAnnounceTeamBattle = 526,
    nSYAudioVoiceAnnounceTimeUp = 527,
    nSYAudioVoiceAnnounceYoshi = 535,
    nSYAudioVoiceAnnounceNoContest = 502,
    nSYAudioVoiceAnnounceWins = 533,
    nSYAudioVoiceAnnounceWinnerIs = 534,
    nSYAudioVoiceSamusSmash1 = 573,
    nSYAudioVoiceYoshiAppeal = 583,
    nSYAudioVoiceYoshiSmash1 = 584,
    nSYAudioVoiceYoshiSmash2 = 585,
    /* The crowd. Values are the decomp's own run (gm/gmsound.h:700-726):
     * Captain 604 .. Yoshi 614 are the per-fighter chants, then the reactions.
     * Only the eleven a P1 Mario-vs-Fox match can reach are declared here --
     * the two chants ft/ftpublic.c picks from
     * dFTCommonDataPublicFighterCallFGMs, and the nine reactions
     * ftPublicDecideCall / DecideCommon / PlayCliffReact choose between. */
    /* The full per-fighter chant block, because
     * dFTCommonDataPublicFighterCallFGMs indexes it by fkind and the crowd
     * actor reads that table whole. Only Mario and Fox are reachable in P1 and
     * only those two are packed; the other ten resolve to a cue the pack does
     * not carry, which fails closed and is silent. Values are the decomp's
     * (gm/gmsound.h 0x25B..0x266) and check-decomp-header-mirror.py guards
     * them. */
    nSYAudioVoicePublicDonkey = 603,
    nSYAudioVoicePublicCaptain = 604,
    nSYAudioVoicePublicFox = 605,
    nSYAudioVoicePublicKirby = 606,
    nSYAudioVoicePublicLink = 607,
    nSYAudioVoicePublicLuigi = 608,
    nSYAudioVoicePublicMario = 609,
    nSYAudioVoicePublicNess = 610,
    nSYAudioVoicePublicPikachu = 611,
    nSYAudioVoicePublicPurin = 612,
    nSYAudioVoicePublicSamus = 613,
    nSYAudioVoicePublicYoshi = 614,
    nSYAudioVoicePublicGaspL = 615,
    nSYAudioVoicePublicGaspM = 616,
    nSYAudioVoicePublicGaspS = 617,
    nSYAudioVoicePublicCheer = 618,
    nSYAudioVoicePublicAmazed = 619,
    nSYAudioVoicePublicGaspClap = 620,
    nSYAudioVoicePublicWin = 621,
    nSYAudioVoicePublicDamageL = 622,
    nSYAudioVoicePublicDamageM = 623,
    nSYAudioVoicePublicNoContest = 624,
    nSYAudioVoicePublicDamageS = 625,
    nSYAudioVoicePublicExcited = 626,
    nSYAudioFGMVoiceEnd = 0x2B7
} gmVoiceID;

#endif
