#ifndef SSB64_NDS_GM_GMSOUND_H
#define SSB64_NDS_GM_GMSOUND_H

typedef enum gmMusicID
{
    nSYAudioBGMPupupu = 0,
    /* P2-4 Yoster. Decomp gm/gmsound.h:40, ninth entry = 8. Render pending;
     * until scripts/sfx/bgm renders it, the ground-data bgm_id fails closed
     * (silent) through gNdsAudioBgmUnsupportedTrackCount. */
    nSYAudioBGMYoster = 8,
    /* P2-4 Castle. Decomp gm/gmsound.h:37, seventh entry = 6. Rendered
     * 2026-09-03 from music sequence 6. */
    nSYAudioBGMCastle = 6,
    /* P2-4 stages 4 to 7. Counted in decomp gm/gmsound.h:31-40 from
     * nSYAudioBGMPupupu = 0, the same count that gave Castle 6 and
     * Yoshi's Island 8. */
    nSYAudioBGMZebes = 1,
    nSYAudioBGMHyrule = 9,
    nSYAudioBGMYamabuki = 7,
    nSYAudioBGMInishie = 2,
    nSYAudioBGMInishieHurry = 3,
    /* P2-4s3 and P2-4s8, by the same count from nSYAudioBGMPupupu = 0 that
     * gave Castle 6 and Hyrule 9: decomp gm/gmsound.h:32-41 orders Pupupu,
     * Zebes, Inishie, InishieHurry, Sector, Jungle, Castle, Yamabuki,
     * Yoster, Hyrule. The rendered sequences agree independently -- the
     * converter wrote bgm_sector from sequence 4 and bgm_jungle from 5. */
    nSYAudioBGMSector = 4,
    nSYAudioBGMJungle = 5,
    /* P2-5 Hammer. Same count from nSYAudioBGMPupupu = 0; it reproduces
     * Castle 6, Hyrule 9 and the two stage ids above exactly. */
    nSYAudioBGMHammer = 45,
    nSYAudioBGMWinDefault = 11,
    nSYAudioBGMWinMario = 12,
    nSYAudioBGMWinMetroid = 13,
    nSYAudioBGMWinDonkey = 14,
    nSYAudioBGMWinKirby = 15,
    nSYAudioBGMWinFox = 16,
    nSYAudioBGMWinMother = 17,
    nSYAudioBGMWinYoshi = 18,
    nSYAudioBGMWinFZero = 19,
    nSYAudioBGMWinPMonsters = 20,
    nSYAudioBGMWinZelda = 21,
    nSYAudioBGMResults = 22,
    nSYAudioBGMModeSelect = 44,
    nSYAudioBGMBattleSelect = 10,
    nSYAudioBGMStar = 46
} gmMusicID;

typedef enum gmFGMID
{
    nSYAudioFGMExplodeS = 0,
    nSYAudioFGMExplodeL = 1,
    nSYAudioFGMFireShoot1 = 2,
    nSYAudioFGMUnkSmallPing1 = 6,
    nSYAudioFGMGuardOn = 13,
    nSYAudioFGMGuardOff = 14,
    nSYAudioFGMShieldBreak = 15,
    nSYAudioFGMHeavySwing1 = 17,
    nSYAudioFGMCatch = 19,
    nSYAudioFGMDeadUpStar = 12,
    nSYAudioFGMShockL = 22,
    nSYAudioFGMShockM = 23,
    nSYAudioFGMShockS = 24,
    nSYAudioFGMShockML = 29,
    nSYAudioFGMBurnL = 25,
    nSYAudioFGMBurnM = 27,
    nSYAudioFGMBurnS = 28,
    nSYAudioFGMKickL = 31,
    nSYAudioFGMKickM = 32,
    nSYAudioFGMKickS = 34,
    nSYAudioFGMPunchL = 37,
    nSYAudioFGMPunchM = 38,
    nSYAudioFGMPunchS = 40,
    nSYAudioFGMLightSwingL = 41,
    nSYAudioFGMLightSwingM = 42,
    nSYAudioFGMLightSwingS = 43,
    nSYAudioFGMItemMapCollide = 46,
    nSYAudioFGMItemGet = 49,
    nSYAudioFGMHarisenHit = 51,
    nSYAudioFGMBatHit = 52,
    nSYAudioFGMStarGet = 54,
    /* P2-3f16 entry cues. 59 is the shared crate/barrel smash used by DK's
     * source entry; 191 is Fox's Arwing fly-by; 214 is the pipe cue shared by
     * Mario and Luigi. Values are the BattleShip gmFGMVoiceID ordinals. */
    nSYAudioFGMContainerSmash = 59,
    nSYAudioFGMFoxLanding = 74,
    nSYAudioFGMMarioLanding = 77,
    nSYAudioFGMNessLanding = 78,
    nSYAudioFGMSamusLanding = 81,
    /* The dodge. GuardOn/GuardOff (13/14) and GamePause (278) were already
     * declared above and below; only this one was missing. All four are core
     * P1 cues a BOTH-CPU stress match asks for and a single-CPU one never
     * reaches -- nobody dodges or shields when Mario stands still. */
    nSYAudioFGMEscape = 11,
    /* The light swing, reached only once every fireball spawned. */
    nSYAudioFGMLightSwingLw1 = 18,
    nSYAudioFGMUnkGrind4 = 85,
    nSYAudioFGMSamusJumpAerial = 92,
    nSYAudioFGMGroundGrind2 = 96,
    nSYAudioFGMGroundGrind3 = 98,
    nSYAudioFGMNessJump = 100,
    nSYAudioFGMGroundGrind4 = 103,
    nSYAudioFGMSamusFoot = 114,
    nSYAudioFGMMarioDash = 121,
    nSYAudioFGMSamusDash = 127,
    nSYAudioFGMGroundBrakeGrind = 128,
    nSYAudioFGMMenuSelect = 158,
    nSYAudioFGMStageSelect = 159,
    nSYAudioFGMMenuScroll1 = 163,
    nSYAudioFGMMenuScroll2 = 164,
    nSYAudioFGMMenuDenied = 165,
    nSYAudioFGMAltitudeWarn = 153,
    nSYAudioFGMDeadExplodeL = 154,
    nSYAudioFGMDeadExplodeS = 155,
    nSYAudioFGMPlayerSlotClose = 166,
    nSYAudioFGMPlayerSlotWhoosh = 167,
    nSYAudioFGMFoxSpecialN = 185,
    nSYAudioFGMFoxSpecialHiStart = 186,
    nSYAudioFGMFoxSpecialHiFly = 187,
    nSYAudioFGMFoxSpecialLwStart = 189,
    nSYAudioFGMFoxAttackAirLw = 190,
    nSYAudioFGMFoxAppearArwing = 191,
    nSYAudioFGMKirbyStarPing1 = 200,
    nSYAudioFGMKirbySpecialNLoseCopy = 204,
    nSYAudioFGMLinkSpecialLwGet = 205,
    nSYAudioFGMLinkSpecialNReturn = 206,
    nSYAudioFGMLinkSpecialNShoot = 207,
    nSYAudioFGMLinkSpecialNGet = 208,
    nSYAudioFGMLinkSpecialHi = 209,
    nSYAudioFGMLinkCatchHookshot = 210,
    nSYAudioFGMLinkAppear = 211,
    nSYAudioFGMMarioDokan = 214,
    nSYAudioFGMMarioSpecialN = 215,
    nSYAudioFGMMarioSpecialHiCoin = 216,
    nSYAudioFGMMarioSpecialHiJump = 217,
    nSYAudioFGMMarioUnkSwing1 = 218,
    nSYAudioFGMMarioUnkSwing2 = 219,
    nSYAudioFGMMagnify = 271,
    nSYAudioFGMGamePause = 278,
    nSYAudioFGMSlashL = 261,
    nSYAudioFGMSlashM = 262,
    nSYAudioFGMSlashS = 263,
    nSYAudioFGMBladeSwing4 = 258,
    nSYAudioFGMBladeSwing3 = 259,
    nSYAudioFGMBladeDraw = 264,
    nSYAudioFGMPlayerHeal = 274,
    /* P2-4 Yoster cloud vapor, decomp gm/gmsound.h:370. Ordinal 275: pinned by
     * the consecutive port run PlayerHeal 274 / StockSteal 276 / GamePause 278
     * / PupupuWhispyWind 0x11d / DonkeyDeadSlam 0x11f, matching decomp. */
    nSYAudioFGMYosterCloudVapor = 275,
    nSYAudioFGMStockSteal = 276,
    nSYAudioFGMJungleTaruCannShoot = 281,
    nSYAudioFGMJungleTaruCannEnter = 282,
    nSYAudioFGMHyruleTwisterAppear = 283,
    nSYAudioFGMHyruleTwisterTrapped = 284,
    nSYAudioFGMPupupuWhispyWind = 0x11d,
    nSYAudioFGMFloorDamageFire = 286,
    /* P2-4s6 Saffron City gate. Counted in decomp gm/gmsound.h gmFGMVoiceID
     * with the REGION_US arms honoured; the same count reproduces this
     * file's existing 29, 56, 57 and 286 exactly. */
    /* P2-4s8 Sector Z, counted the same way as the gate cue below. */
    nSYAudioFGMSectorArwingLaser = 265,
    nSYAudioFGMSectorAmbient1 = 266,
    nSYAudioFGMSectorAmbient2 = 267,
    nSYAudioFGMSectorAmbient3 = 268,
    nSYAudioFGMYamabukiGate = 270,
    /* P2-3f13, Captain Falcon's ten. 73/106/117 share one wave with the
     * Mario/Fox landing family; 180/181 are the Falcon Flyer's engine;
     * 183/184 are the two halves of Falcon Punch. */
    nSYAudioFGMCaptainLanding = 73,
    nSYAudioFGMCaptainFoot = 106,
    nSYAudioFGMCaptainDash = 117,
    nSYAudioFGMCaptainAppearCar1 = 180,
    nSYAudioFGMCaptainAppearCar2 = 181,
    nSYAudioFGMCaptainSpecialHi = 182,
    nSYAudioFGMCaptainSpecialNStart = 183,
    nSYAudioFGMCaptainSpecialNPunch = 184,
    nSYAudioFGMCaptainDeadSlam = 288,
    nSYAudioFGMCaptainDownBounce = 299,
    nSYAudioFGMFoxDeadSlam = 289,
    nSYAudioFGMMarioDeadSlam = 292,
    nSYAudioFGMFoxDownBounce = 300,
    nSYAudioFGMMarioDownBounce = 303,
    /* P2-3f14, Donkey Kong's eleven FGM cues plus the shared slap his
     * BossSlam/BossUnk1 fork. 105/116 are the programs Captain's Foot and
     * Dash already fork; 287 is the slam program 288/289/292 fork and 298 the
     * DownBounce program 299/300/303 fork -- packing DK's roots costs almost
     * nothing because the pack already carries those bodies. The three
     * Boss-named cues below are not Giant DK's: 212_DonkeyMainMotion.c plays
     * all three from ordinary DK actions. */
    nSYAudioFGMDonkeySlap1 = 9,
    nSYAudioFGMDonkeySlap2 = 10,
    nSYAudioFGMDonkeyLanding = 72,
    nSYAudioFGMDonkeyFoot = 105,
    nSYAudioFGMDonkeyDash = 116,
    nSYAudioFGMBossSlam = 175,
    nSYAudioFGMBossUnk1 = 176,
    nSYAudioFGMBossUnk2 = 177,
    nSYAudioFGMDonkeySpin = 178,
    nSYAudioFGMDonkeyCharge = 179,
    /* P2-3 Pikachu. BattleShip gmFGMID ordinals: 79/112/125 are his
     * landing/foot/dash family, 225..232 the electric set his motion scripts,
     * colanims and the Thunder Jolt/Thunder weapons play, and 294/305 fork
     * the DeadSlam/DownBounce programs the pack already carries. */
    nSYAudioFGMPikachuLanding = 79,
    nSYAudioFGMPikachuFoot = 112,
    nSYAudioFGMPikachuDash = 125,
    nSYAudioFGMPikachuElectric1 = 225,
    nSYAudioFGMPikachuElectric2 = 226,
    nSYAudioFGMPikachuElectric3 = 227,
    nSYAudioFGMPikachuElectric4 = 228,
    nSYAudioFGMPikachuElectric5 = 229,
    nSYAudioFGMPikachuElectricLoop = 230,
    nSYAudioFGMPikachuSpecialHiStart = 231,
    nSYAudioFGMPikachuSpecialLwThunder = 232,
    nSYAudioFGMPikachuDeadSlam = 294,
    nSYAudioFGMPikachuDownBounce = 305,
    /* P2-3 Yoshi. BattleShip gmFGMID ordinals (REGION_US): 82/115/130 are
     * his landing/foot/dash family, 252..257 the egg set his articles and the
     * victim egg play, 297/308 fork DeadSlam/DownBounce. */
    nSYAudioFGMYoshiLanding = 82,
    nSYAudioFGMYoshiFoot = 115,
    nSYAudioFGMYoshiDash = 130,
    nSYAudioFGMYoshiEggShatter1 = 252,
    nSYAudioFGMYoshiEggShatter2 = 253,
    nSYAudioFGMYoshiSpecialNTongue = 254,
    nSYAudioFGMYoshiEggShatter3 = 255,
    nSYAudioFGMYoshiSpecialHiThrow = 256,
    nSYAudioFGMYoshiEggLayShatter = 257,
    nSYAudioFGMYoshiDeadSlam = 297,
    nSYAudioFGMYoshiDownBounce = 308,
    /* Samus source weapon/motion cues. These are the BattleShip gmFGMID
     * ordinals immediately following CharacterUnk2/3 (233/234). Keeping the
     * real IDs here lets Charge Shot select its level-specific source SFX
     * table instead of collapsing every level onto a placeholder. */
    nSYAudioFGMSamusSpecialNShootF = 235,
    nSYAudioFGMSamusSpecialNShootL = 236,
    nSYAudioFGMSamusSpecialNShootM = 237,
    nSYAudioFGMSamusSpecialNShootS = 238,
    nSYAudioFGMSamusSpecialNCharge0 = 239,
    nSYAudioFGMSamusSpecialNCharge1 = 240,
    nSYAudioFGMSamusSpecialNCharge2 = 241,
    nSYAudioFGMSamusSpecialNCharge3 = 242,
    nSYAudioFGMSamusSpecialNCharge4 = 243,
    nSYAudioFGMSamusSpecialNCharge5 = 244,
    nSYAudioFGMSamusSpecialNCharge6 = 245,
    nSYAudioFGMSamusSpecialNCharge7 = 246,
    nSYAudioFGMSamusSpecialLw = 247,
    nSYAudioFGMSamusCatchGrappleBeam = 248,
    nSYAudioFGMSamusSpecialHi = 249,
    nSYAudioFGMSamusUnkSwing = 250,
    nSYAudioFGMSamusUnkCharge = 251,
    nSYAudioFGMDonkeyDeadSlam = 287,
    nSYAudioFGMDonkeyDownBounce = 298,
    nSYAudioFGMSamusDeadSlam = 296,
    nSYAudioFGMSamusDownBounce = 307,
    nSYAudioFGMCharacterUnkZip10 = 639,
    /* P2-3 Pikachu's motion scripts reach four shared cues no landed fighter
     * had asked for: the Master Ball opening (his Appear script), the
     * UnkZip8 whoosh and the two InflateJump programs. gmsound.h ordinals. */
    nSYAudioFGMInflateJump2 = 90,
    nSYAudioFGMInflateJump7 = 101,
    nSYAudioFGMMBallOpen = 139,
    nSYAudioFGMCharacterUnkZip8 = 637,
    /* P2-3 Yoshi's motion scripts reach two more shared cues no landed
     * fighter had asked for: the ShellHit clack and the UnkZip11 whoosh. */
    nSYAudioFGMShellHit = 56,
    nSYAudioFGMCharacterUnkZip11 = 640,
    /* P2-5i1 GBumper: its ROM ITAttributes (251_ITCommonData.c:1862) name
     * nSYAudioFGMBumperHit as hit_sfx, and source gmsound.h:137-140 places it
     * directly after FGMItemMapCollide (port ordinal 46 above). */
    nSYAudioFGMBumperHit = 47,
    /* P2-5 Star, counted the same way; the count reproduces BumperHit 47,
     * SectorArwingLaser 265, YamabukiGate 270 and JungleTaruCannShoot 281. */
    nSYAudioFGMStarMapCollide = 53,
    /* P2-3 Ness: every id his sources reach that the port lacked (BattleShip
     * gmsound.h REGION_US ordinals, admit_fighter.py). */
    nSYAudioFGMItemThrow = 57,
    nSYAudioFGMNessFoot = 111,
    nSYAudioFGMNessDash = 124,
    nSYAudioFGMCharacterUnk1 = 220,
    nSYAudioFGMNessPKThunderLoop = 221,
    nSYAudioFGMNessPSI = 222,
    nSYAudioFGMNessPSIAgain = 223,
    nSYAudioFGMNessSpecialLwStart = 224,
    nSYAudioFGMNessDeadSlam = 293,
    nSYAudioFGMNessDownBounce = 304,
    nSYAudioVoiceNessAppeal = 442,
    nSYAudioVoiceNessSmash1 = 443,
    nSYAudioVoiceNessSmash2 = 444,
    nSYAudioVoiceNessSmash3 = 445,
    nSYAudioVoiceNessUnkGrunt = 446,
    nSYAudioVoiceNessDeadUp = 447,
    nSYAudioVoiceNessFuraFura = 448,
    nSYAudioVoiceNessDamage = 449,
    nSYAudioVoiceNessUnkPing = 450,
    nSYAudioVoiceNessHeavyGet = 451,
    nSYAudioVoiceNessOttotto = 452,
    nSYAudioVoiceNessSpecialN = 453,
    nSYAudioVoiceNessFinalPK = 454,
    nSYAudioVoiceNessFinalStarstorm = 455,
    nSYAudioVoiceNessSpecialHi = 456,
    nSYAudioVoiceNessDead = 457,
    nSYAudioVoiceNessFuraSleep = 458,
    nSYAudioVoicePublicAbsorb = 627,
    nSYAudioFGMCharacterUnkZip7 = 636,
    /* P2-3 Purin: every id his sources reach that the port lacked (BattleShip
     * gmsound.h REGION_US ordinals, admit_fighter.py). */
    nSYAudioFGMPurinLanding = 80,
    nSYAudioFGMInflateJump3 = 91,
    nSYAudioFGMInflateJump8 = 102,
    nSYAudioFGMPurinFoot = 113,
    nSYAudioFGMPurinDash = 126,
    nSYAudioFGMCharacterUnk2 = 233,
    nSYAudioFGMCharacterUnk3 = 234,
    nSYAudioFGMPurinDeadSlam = 295,
    nSYAudioFGMPurinDownBounce = 306,
    nSYAudioVoicePurinAppeal = 557,
    nSYAudioVoicePurinSmash1 = 558,
    nSYAudioVoicePurinSmash2 = 559,
    nSYAudioVoicePurinSmash3 = 560,
    nSYAudioVoicePurinSpecialN = 561,
    nSYAudioVoicePurinDeadUp = 562,
    nSYAudioVoicePurinFuraFura = 563,
    nSYAudioVoicePurinDamage = 564,
    nSYAudioVoicePurinUnkGrunt1 = 565,
    nSYAudioVoicePurinUnkGrunt2 = 566,
    nSYAudioVoicePurinUnkGrunt3 = 567,
    nSYAudioVoicePurinUnkGrunt4 = 568,
    nSYAudioVoicePurinFuraSleep = 569,
    nSYAudioVoicePurinSpecialLwSleep = 570,
    nSYAudioVoicePurinSpecialLwWake = 571,
    nSYAudioVoicePurinSpecialHi = 572,
    nSYAudioFGMCharacterUnkZip9 = 638,
    /* P2-3 Kirby: every id his sources reach that the port lacked (BattleShip
     * gmsound.h REGION_US ordinals, admit_fighter.py). */
    nSYAudioFGMSamusJump1 = 8,
    nSYAudioFGMKirbyLanding = 75,
    nSYAudioFGMInflateJump1 = 86,
    nSYAudioFGMKirbyPurinJump = 94,
    nSYAudioFGMInflateJump5 = 97,
    nSYAudioFGMKirbyFoot = 108,
    nSYAudioFGMKirbyDash = 119,
    nSYAudioFGMUnkMechanical4 = 192,
    nSYAudioFGMUnkLongWind = 193,
    nSYAudioFGMKirbySpecialLwLanding = 194,
    nSYAudioFGMKirbyAttackAirHi = 195,
    nSYAudioFGMKirbySpecialNThrow = 196,
    nSYAudioFGMKirbySpecialNCopyEat = 197,
    nSYAudioFGMKirbySpecialNCopyThrow = 198,
    nSYAudioFGMKirbySpecialNCopyUnk = 199,
    nSYAudioFGMKirbyStarPing2 = 201,
    nSYAudioFGMKirbySpecialLwStart = 202,
    nSYAudioFGMKirbySpecialNStart = 203,
    nSYAudioFGMKirbyDeadSlam = 290,
    nSYAudioFGMKirbyDownBounce = 301,
    nSYAudioVoiceKirbyAppeal = 377,
    nSYAudioVoiceKirbySmash1 = 378,
    nSYAudioVoiceKirbySmash2 = 379,
    nSYAudioVoiceKirbySmash3 = 380,
    nSYAudioVoiceKirbyCopyLinkSpecialN = 381,
    nSYAudioVoiceKirbyCopyPikachuSpecialN = 382,
    nSYAudioVoiceKirbySpecialHi = 383,
    nSYAudioVoiceKirbyCopyCaptainSpecialNFalcon = 384,
    nSYAudioVoiceKirbyCopyCaptainSpecialNPunch = 385,
    nSYAudioVoiceKirbyCopyDonkeySpecialN = 386,
    nSYAudioVoiceKirbyCopyPurinSpecialN = 387,
    nSYAudioVoiceKirbyDeadUp = 388,
    nSYAudioVoiceKirbyFuraFura = 389,
    nSYAudioVoiceKirbyDamage = 390,
    nSYAudioVoiceKirbyUnkGrunt1 = 391,
    nSYAudioVoiceKirbyUnkGrunt2 = 392,
    nSYAudioVoiceKirbyHeavyGet = 393,
    nSYAudioVoiceKirbyOttotto = 394,
    nSYAudioVoiceKirbyCopyNessSpecialN = 395,
    nSYAudioVoiceKirbyDead = 396,
    nSYAudioVoiceKirbyFuraSleep = 397,
    nSYAudioVoiceKirbySpecialLw = 398,
    nSYAudioVoiceKirbyUnkPing = 399,
    nSYAudioFGMCharacterUnkZip4 = 633,
} gmFGMID;

typedef enum gmVoiceID
{
    nSYAudioVoiceDonkeyFuraSleep = 324,
    nSYAudioVoiceDonkeyAppeal = 325,
    nSYAudioVoiceDonkeySmash1 = 326,
    nSYAudioVoiceDonkeySmash2 = 327,
    nSYAudioVoiceDonkeySmash3 = 328,
    nSYAudioVoiceDonkeySpecialN = 329,
    nSYAudioVoiceDonkeyDeadUp = 330,
    nSYAudioVoiceDonkeyFuraFura = 331,
    nSYAudioVoiceDonkeyDamage = 332,
    nSYAudioVoiceDonkeyDead1 = 333,
    nSYAudioVoiceDonkeyHeavyGet = 334,
    nSYAudioVoiceDonkeyHeavyUnk = 335,
    nSYAudioVoiceDonkeyDead2 = 336,
    /* P2-3f13, the complete Captain Falcon voice run 337..359. SpecialNFalcon
     * + SpecialNPunch are the two identity lines. */
    nSYAudioVoiceCaptainAppeal = 337,
    nSYAudioVoiceCaptainSpecialHi = 338,
    nSYAudioVoiceCaptainSmash1 = 339,
    nSYAudioVoiceCaptainSmash2 = 340,
    nSYAudioVoiceCaptainSmash3 = 341,
    nSYAudioVoiceCaptainSmash4 = 342,
    nSYAudioVoiceCaptainFinalComeOn = 343,
    nSYAudioVoiceCaptainSmash5 = 344,
    nSYAudioVoiceCaptainAttackS4 = 345,
    nSYAudioVoiceCaptainSpecialLw = 346,
    nSYAudioVoiceCaptainSpecialNPunch = 347,
    nSYAudioVoiceCaptainSpecialNFalcon = 348,
    nSYAudioVoiceCaptainDeadUp = 349,
    nSYAudioVoiceCaptainFuraFura = 350,
    nSYAudioVoiceCaptainDamage = 351,
    nSYAudioVoiceCaptainUnkPing1 = 352,
    nSYAudioVoiceCaptainJumpAerial = 353,
    nSYAudioVoiceCaptainHeavyGet = 354,
    nSYAudioVoiceCaptainDead = 355,
    nSYAudioVoiceCaptainFuraSleep = 356,
    nSYAudioVoiceCaptainUnkQuick = 357,
    nSYAudioVoiceCaptainUnkPing2 = 358,
    nSYAudioVoiceCaptainUnkPing3 = 359,
    nSYAudioVoiceFoxDeadUp = 360,
    nSYAudioVoiceFoxSpecialHi = 362,
    nSYAudioVoiceFoxJumpAerial = 363,
    nSYAudioVoiceFoxEscape = 364,
    nSYAudioVoiceFoxSelected = 365,
    /* The teeter on a ledge edge. */
    nSYAudioVoiceFoxOttotto = 369,
    nSYAudioVoiceFoxWin = 368,
    nSYAudioVoiceFoxDead = 370,
    nSYAudioVoiceFoxSmash1 = 372,
    nSYAudioVoiceFoxSmash2 = 373,
    nSYAudioVoiceFoxSmash3 = 374,
    nSYAudioVoiceFoxDamage = 375,
    nSYAudioVoiceLinkSmash1 = 401,
    /* P2-3f15, Luigi's contiguous source voice run. 421 FuraFura landed at
     * P2-3 with his announcer line; the rest were failing closed while his
     * FTAttributes lanes and motion scripts named every one of them. His KO
     * slam is Mario's own 292 and his DownBounce is Mario's 303 -- the source
     * spells both that way -- so neither is a Luigi cue. */
    nSYAudioVoiceLuigiSmash1 = 416,
    nSYAudioVoiceLuigiSmash2 = 417,
    nSYAudioVoiceLuigiSmash3 = 418,
    nSYAudioVoiceLuigiSpecialLw = 419,
    nSYAudioVoiceLuigiDeadUp = 420,
    nSYAudioVoiceLuigiFuraFura = 421,
    nSYAudioVoiceLuigiDamage = 422,
    nSYAudioVoiceLuigiJump = 423,
    nSYAudioVoiceLuigiJumpAerial = 424,
    nSYAudioVoiceLuigiLets = 425,
    nSYAudioVoiceLuigiHeavyGet = 426,
    nSYAudioVoiceLuigiDead = 427,
    nSYAudioVoiceLuigiHereWe = 428,
    nSYAudioVoiceMarioSmash1 = 429,
    nSYAudioVoiceMarioSmash2 = 430,
    nSYAudioVoiceMarioSmash3 = 431,
    nSYAudioVoiceMarioSpecialLw = 432,
    nSYAudioVoiceMarioDeadUp = 433,
    nSYAudioVoiceMarioJumpAerial = 436,
    nSYAudioVoiceMarioHeavyGet = 438,
    nSYAudioVoiceMarioDead = 439,
    nSYAudioVoiceMarioDamage = 440,
    nSYAudioVoiceMarioHereWe = 441,
    nSYAudioVoiceAnnounceFailure = 460,
    nSYAudioVoiceAnnounceOne = 467,
    nSYAudioVoiceAnnounceTwo = 469,
    nSYAudioVoiceAnnounceThree = 470,
    nSYAudioVoiceAnnounceFour = 471,
    nSYAudioVoiceAnnounceFive = 472,
    nSYAudioVoiceAnnounceBlueTeam = 475,
    nSYAudioVoiceAnnounceComputerPlayer = 480,
    nSYAudioVoiceAnnounceDonkey = 483,
    nSYAudioVoiceAnnounceCaptain = 485,
    nSYAudioVoiceAnnounceFox = 486,
    nSYAudioVoiceAnnounceGameSet = 488,
    nSYAudioVoiceAnnounceGo = 490,
    nSYAudioVoiceAnnounceGreenTeam = 491,
    nSYAudioVoiceAnnounceKirby = 496,
    nSYAudioVoiceAnnounceLink = 497,
    nSYAudioVoiceAnnounceLuigi = 498,
    nSYAudioVoiceAnnounceMario = 499,
    nSYAudioVoiceAnnounceNess = 501,
    nSYAudioVoiceAnnouncePlayer1 = 503,
    nSYAudioVoiceAnnouncePlayer2 = 504,
    nSYAudioVoiceAnnouncePlayer3 = 505,
    nSYAudioVoiceAnnouncePlayer4 = 506,
    nSYAudioVoiceAnnouncePikachu = 507,
    nSYAudioVoiceAnnouncePurin = 508,
    nSYAudioVoiceAnnounceRedTeam = 510,
    nSYAudioVoiceAnnounceDefeated = 511,
    nSYAudioVoiceAnnounceFreeForAll = 512,
    nSYAudioVoicePikachuFuraSleep = 551,
    nSYAudioVoiceAnnounceSamus = 513,
    nSYAudioVoiceAnnounceSuddenDeath = 514,
    nSYAudioVoiceAnnounceTeamBattle = 526,
    nSYAudioVoiceAnnounceTimeUp = 527,
    nSYAudioVoiceAnnounceYoshi = 535,
    nSYAudioVoiceAnnounceNoContest = 502,
    nSYAudioVoiceAnnounceWins = 533,
    nSYAudioVoiceAnnounceWinnerIs = 534,
    /* P2-3 Pikachu's voice run, BattleShip gmsound.h Appeal..Dead; FuraSleep
     * (551) is declared above with the announcer. */
    nSYAudioVoicePikachuAppeal = 536,
    nSYAudioVoicePikachuSmash1 = 537,
    nSYAudioVoicePikachuSmash2 = 538,
    nSYAudioVoicePikachuSmash3 = 539,
    nSYAudioVoicePikachuSpecialN = 540,
    nSYAudioVoicePikachuSpecialLw = 541,
    nSYAudioVoicePikachuDeadUp = 542,
    nSYAudioVoicePikachuFuraFura = 543,
    nSYAudioVoicePikachuDamage = 544,
    nSYAudioVoicePikachuFinalPika = 545,
    nSYAudioVoicePikachuFinalChu = 546,
    nSYAudioVoicePikachuSpecialHi = 547,
    nSYAudioVoicePikachuHeavyGet = 548,
    nSYAudioVoicePikachuOttotto = 549,
    nSYAudioVoicePikachuDead = 550,
    nSYAudioVoiceSamusSmash1 = 573,
    nSYAudioVoiceSamusSmash2 = 574,
    nSYAudioVoiceSamusSmash3 = 575,
    nSYAudioVoiceSamusDeadUp = 576,
    nSYAudioVoiceSamusFura = 577,
    nSYAudioVoiceSamusAttackHi4 = 578,
    nSYAudioVoiceSamusUnkSlash = 579,
    nSYAudioVoiceSamusAppeal = 580,
    nSYAudioVoiceSamusDamage = 581,
    nSYAudioVoiceSamusDead = 582,
    nSYAudioVoiceYoshiAppeal = 583,
    nSYAudioVoiceYoshiSmash1 = 584,
    nSYAudioVoiceYoshiSmash2 = 585,
    /* P2-3 Yoshi's voice run, BattleShip gmsound.h Smash3..UnkVocalize. */
    nSYAudioVoiceYoshiSmash3 = 586,
    nSYAudioVoiceYoshiCatch = 587,
    nSYAudioVoiceYoshiDeadUp = 588,
    nSYAudioVoiceYoshiFuraFura = 589,
    nSYAudioVoiceYoshiDamage = 590,
    nSYAudioVoiceYoshiJump = 591,
    nSYAudioVoiceYoshiJumpAerial = 592,
    nSYAudioVoiceYoshiHeavyGet = 593,
    nSYAudioVoiceYoshiOttotto = 594,
    nSYAudioVoiceYoshiDead = 595,
    nSYAudioVoiceYoshiFuraSleep = 596,
    nSYAudioVoiceYoshiUnkGrunt1 = 597,
    nSYAudioVoiceYoshiSpecialLwJump = 598,
    nSYAudioVoiceYoshiSpecialLwFall = 599,
    nSYAudioVoiceYoshiUnkGrunt2 = 600,
    nSYAudioVoiceYoshiThrow = 601,
    nSYAudioVoiceYoshiUnkVocalize = 602,
    /* The crowd. Values are the decomp's own run (gm/gmsound.h:700-726):
     * Captain 604 .. Yoshi 614 are the per-fighter chants, then the reactions.
     * Only the eleven a P1 Mario-vs-Fox match can reach are declared here --
     * the two chants ft/ftpublic.c picks from
     * dFTCommonDataPublicFighterCallFGMs, and the nine reactions
     * ftPublicDecideCall / DecideCommon / PlayCliffReact choose between. */
    /* The full per-fighter chant block, because
     * dFTCommonDataPublicFighterCallFGMs indexes it by fkind and the crowd
     * actor reads that table whole. Only Mario and Fox are reachable in P1 and
     * only those two are packed; the other ten resolve to a cue the pack does
     * not carry, which fails closed and is silent. Values are the decomp's
     * (gm/gmsound.h 0x25B..0x266) and check-decomp-header-mirror.py guards
     * them. */
    nSYAudioVoicePublicDonkey = 603,
    nSYAudioVoicePublicCaptain = 604,
    nSYAudioVoicePublicFox = 605,
    nSYAudioVoicePublicKirby = 606,
    nSYAudioVoicePublicLink = 607,
    nSYAudioVoicePublicLuigi = 608,
    nSYAudioVoicePublicMario = 609,
    nSYAudioVoicePublicNess = 610,
    nSYAudioVoicePublicPikachu = 611,
    nSYAudioVoicePublicPurin = 612,
    nSYAudioVoicePublicSamus = 613,
    nSYAudioVoicePublicYoshi = 614,
    nSYAudioVoicePublicGaspL = 615,
    nSYAudioVoicePublicGaspM = 616,
    nSYAudioVoicePublicGaspS = 617,
    nSYAudioVoicePublicCheer = 618,
    nSYAudioVoicePublicAmazed = 619,
    nSYAudioVoicePublicGaspClap = 620,
    nSYAudioVoicePublicWin = 621,
    nSYAudioVoicePublicDamageL = 622,
    nSYAudioVoicePublicDamageM = 623,
    nSYAudioVoicePublicNoContest = 624,
    nSYAudioVoicePublicDamageS = 625,
    nSYAudioVoicePublicExcited = 626,
    nSYAudioFGMVoiceEnd = 0x2B7
} gmVoiceID;

#endif
