
const GeoLayout mario_geo_face_and_wings[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_front),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_right),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_left),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_up),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_down),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_dead),
            GEO_CLOSE_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_front),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_right),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_left),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_up),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_down),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_dead),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_cap_wings),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_cap_wings),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_left_hand[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_left_hand_closed),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_open),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_closed),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_right_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_peace),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_cap),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_cap),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_right_hand_cap_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_body[] = {
    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_move_mario_part_from_parent),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_geo_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_left_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_geo_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_right_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_geo_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_left_foot),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_right_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_medium_poly_left_hand[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_medium_poly_left_hand_closed),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_open),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_medium_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_medium_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_medium_poly_left_hand_closed),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_medium_poly_right_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_medium_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_peace),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_cap),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_cap),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_right_hand_cap_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_medium_poly_body[] = {
    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_move_mario_part_from_parent),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_medium_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_geo_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_left_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_medium_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_geo_medium_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_right_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_medium_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_geo_medium_poly_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_medium_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_medium_poly_left_foot),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_right_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_medium_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_medium_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_low_poly_face_and_wings[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_front),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_right),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_left),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_up),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_down),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_dead),
            GEO_CLOSE_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_front),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_right),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_left),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_up),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_down),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_dead),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_cap_wings),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_cap_wings),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_low_poly_left_hand[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_left_hand_closed),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_open),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_low_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_low_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_low_poly_left_hand_closed),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_low_poly_right_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_peace),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_cap),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_cap),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_right_hand_cap_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_low_poly_body[] = {
    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_move_mario_part_from_parent),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_low_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_geo_low_poly_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_left_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_low_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_geo_low_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_right_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_low_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_geo_low_poly_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_low_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_low_poly_left_foot),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_right_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_low_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_vanish_geo_face_and_wings[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_front),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_right),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_left),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_up),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_down),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_dead),
            GEO_CLOSE_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_front),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_right),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_left),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_up),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_down),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_dead),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_vanish_geo_left_hand[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_left_hand_closed),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_open),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_closed),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_vanish_geo_right_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_peace),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_cap),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_cap),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_right_hand_cap_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_vanish_geo_body[] = {
    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_move_mario_part_from_parent),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_vanish_geo_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_left_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_vanish_geo_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_right_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_vanish_geo_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_left_foot),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_right_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_vanish_geo_medium_poly_left_hand[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_medium_poly_left_hand_closed),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_open),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_medium_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_medium_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_medium_poly_left_hand_closed),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_vanish_geo_medium_poly_right_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_medium_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_peace),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_cap),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_cap),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_right_hand_cap_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_vanish_geo_medium_poly_body[] = {
    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_move_mario_part_from_parent),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_medium_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_vanish_geo_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_left_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_medium_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_vanish_geo_medium_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_right_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_medium_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_vanish_geo_medium_poly_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_medium_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_medium_poly_left_foot),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_right_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_medium_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_medium_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_vanish_geo_low_poly_face_and_wings[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_front),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_right),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_left),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_up),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_down),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_dead),
            GEO_CLOSE_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_front),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_right),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_left),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_up),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_down),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_dead),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_vanish_geo_low_poly_left_hand[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_left_hand_closed),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_open),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_low_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_low_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_low_poly_left_hand_closed),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_vanish_geo_low_poly_right_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_peace),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_cap),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_cap),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_right_hand_cap_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_vanish_geo_low_poly_body[] = {
    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_move_mario_part_from_parent),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_low_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_vanish_geo_low_poly_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_left_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_low_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_vanish_geo_low_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_right_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_low_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_vanish_geo_low_poly_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_low_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_low_poly_left_foot),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_right_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_low_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_geo_face_and_wings[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_cap_on_shared_dl),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_cap_off_shared_dl),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_cap_wings),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_cap_wings),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_geo_left_hand[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_left_hand_closed_shared_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_open_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_closed_shared_dl),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_geo_right_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_peace_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_right_hand_cap_shared_dl_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_geo_body[] = {
    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_metal_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_move_mario_part_from_parent),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_metal_torso_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_metal_geo_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_left_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_geo_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_right_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_geo_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_metal_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_left_foot_shared_dl),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_right_thigh_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_geo_medium_poly_left_hand[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_medium_poly_left_hand_closed_shared_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_open_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_medium_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_medium_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_medium_poly_left_hand_closed_shared_dl),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_geo_medium_poly_right_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_medium_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_peace_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_right_hand_cap_shared_dl_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_geo_medium_poly_body[] = {
    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_metal_medium_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_move_mario_part_from_parent),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_metal_medium_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_metal_geo_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_left_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_medium_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_geo_medium_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_right_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_medium_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_geo_medium_poly_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_metal_medium_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_medium_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_medium_poly_left_foot_shared_dl),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_right_thigh_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_medium_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_medium_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_geo_low_poly_face_and_wings[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_low_poly_cap_on),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_low_poly_cap_off),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_cap_wings),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_cap_wings),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_geo_low_poly_left_hand[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_left_hand_closed_shared_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_open_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_low_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_low_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_low_poly_left_hand_closed_shared_dl),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_geo_low_poly_right_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_low_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_peace_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_right_hand_cap_shared_dl_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_geo_low_poly_body[] = {
    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_metal_low_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_move_mario_part_from_parent),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_metal_low_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_metal_geo_low_poly_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_left_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_low_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_geo_low_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_right_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_low_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_geo_low_poly_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_metal_low_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_low_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_low_poly_left_foot_shared_dl),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_right_thigh_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_low_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_low_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_vanish_geo_face_and_wings[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_cap_on_shared_dl),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_cap_off_shared_dl),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_vanish_geo_left_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_left_hand_closed_shared_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_open_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_closed_shared_dl),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_vanish_geo_right_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_peace_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_right_hand_cap_shared_dl_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_vanish_geo_body[] = {
    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_metal_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_move_mario_part_from_parent),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_metal_torso_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_metal_vanish_geo_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_left_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_vanish_geo_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_right_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_vanish_geo_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_metal_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_left_foot_shared_dl),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_right_thigh_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_vanish_geo_medium_poly_left_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_medium_poly_left_hand_closed_shared_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_open_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_medium_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_medium_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_medium_poly_left_hand_closed_shared_dl),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_vanish_geo_medium_poly_right_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_medium_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_peace_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_right_hand_cap_shared_dl_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_vanish_geo_medium_poly_body[] = {
    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_metal_medium_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_move_mario_part_from_parent),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_metal_medium_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_metal_vanish_geo_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_left_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_medium_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_vanish_geo_medium_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_right_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_medium_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_SWITCH_CASE(0, geo_switch_mario_hand),
                                GEO_OPEN_NODE(),
                                    GEO_BRANCH(1, mario_metal_vanish_geo_medium_poly_right_hand),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_metal_medium_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_medium_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_medium_poly_left_foot_shared_dl),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_right_thigh_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_medium_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_medium_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_vanish_geo_low_poly_face_and_wings[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_low_poly_cap_on),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_low_poly_cap_off),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_vanish_geo_low_poly_left_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_left_hand_closed_shared_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_open_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_low_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_low_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_low_poly_left_hand_closed_shared_dl),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_vanish_geo_low_poly_right_hand[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_low_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, geo_switch_mario_hand_grab_pos),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_peace_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_right_hand_cap_shared_dl_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_metal_vanish_geo_low_poly_body[] = {
    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_metal_low_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_move_mario_part_from_parent),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_metal_low_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_metal_vanish_geo_low_poly_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_left_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_low_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_vanish_geo_low_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_right_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_low_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_vanish_geo_low_poly_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_metal_low_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_low_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_low_poly_left_foot_shared_dl),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_right_thigh_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_low_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_low_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_load_body[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
    GEO_OPEN_NODE(),
        GEO_BRANCH(1, mario_geo_body),
        GEO_BRANCH(1, mario_vanish_geo_body),
        GEO_BRANCH(1, mario_metal_geo_body),
        GEO_BRANCH(1, mario_metal_vanish_geo_body),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_load_medium_poly_body[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
    GEO_OPEN_NODE(),
        GEO_BRANCH(1, mario_geo_medium_poly_body),
        GEO_BRANCH(1, mario_vanish_geo_medium_poly_body),
        GEO_BRANCH(1, mario_metal_geo_medium_poly_body),
        GEO_BRANCH(1, mario_metal_vanish_geo_medium_poly_body),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_load_low_poly_body[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
    GEO_OPEN_NODE(),
        GEO_BRANCH(1, mario_geo_low_poly_body),
        GEO_BRANCH(1, mario_vanish_geo_low_poly_body),
        GEO_BRANCH(1, mario_metal_geo_low_poly_body),
        GEO_BRANCH(1, mario_metal_vanish_geo_low_poly_body),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo_render_body[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_RENDER_RANGE(-2048, 600),
        GEO_OPEN_NODE(),
            GEO_BRANCH(1, mario_geo_load_body),
        GEO_CLOSE_NODE(),
        GEO_RENDER_RANGE(600, 1600),
        GEO_OPEN_NODE(),
            GEO_BRANCH(1, mario_geo_load_medium_poly_body),
        GEO_CLOSE_NODE(),
        GEO_RENDER_RANGE(1600, 32767),
        GEO_OPEN_NODE(),
            GEO_BRANCH(1, mario_geo_load_low_poly_body),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
};

const GeoLayout mario_geo[] = {
    GEO_SHADOW(SHADOW_CIRCLE_PLAYER, 0xB4, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0x00, 16384),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mirror_mario_backface_culling),
            GEO_ASM(0, geo_mirror_mario_set_alpha),
            GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
            GEO_OPEN_NODE(),
                GEO_BRANCH(1, mario_geo_load_body),
                GEO_BRANCH(1, mario_geo_render_body),
            GEO_CLOSE_NODE(),
            GEO_ASM(1, geo_mirror_mario_backface_culling),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
