/* Auto-generated from BattleShip ftchar storage TUs; do not edit by hand. */
#ifndef SSB64_NDS_FTDATA_FILE_SLOTS_H
#define SSB64_NDS_FTDATA_FILE_SLOTS_H

#include <PR/ultratypes.h>

extern void * gFTDataBossMain;
extern void * gFTDataBossMainMotion;
extern void * gFTDataBossModel;
extern s32 gFTDataBossParticleBankID;
extern void * gFTDataCaptainMain;
extern void * gFTDataCaptainMainMotion;
extern void * gFTDataCaptainModel;
extern s32 gFTDataCaptainParticleBankID;
extern void * gFTDataCaptainSpecial2;
extern void * gFTDataCaptainSpecial3;
extern void * gFTDataDonkeyMain;
extern void * gFTDataDonkeyMainMotion;
extern void * gFTDataDonkeyModel;
extern s32 gFTDataDonkeyParticleBankID;
extern void * gFTDataDonkeySpecial2;
extern void * gFTDataFoxMain;
extern void * gFTDataFoxMainMotion;
extern void * gFTDataFoxModel;
extern s32 gFTDataFoxParticleBankID;
extern void * gFTDataFoxSpecial1;
extern void * gFTDataFoxSpecial2;
extern void * gFTDataFoxSpecial3;
extern void * gFTDataFoxSpecial4;
extern void * gFTDataGDonkeyMain;
extern void * gFTDataGDonkeyModel;
extern s32 gFTDataGDonkeyParticleBankID;
extern void * gFTDataGDonkeySpecial2;
extern void * gFTDataGDonkeySubMotion;
extern void * gFTDataKirbyMain;
extern void * gFTDataKirbyMainMotion;
extern void * gFTDataKirbyModel;
extern s32 gFTDataKirbyParticleBankID;
extern void * gFTDataKirbySpecial2;
extern void * gFTDataLinkMain;
extern void * gFTDataLinkMainMotion;
extern void * gFTDataLinkModel;
extern s32 gFTDataLinkParticleBankID;
extern void * gFTDataLinkSpecial1;
extern void * gFTDataLinkSpecial2;
extern void * gFTDataLinkSpecial3;
extern void * gFTDataLuigiMain;
extern void * gFTDataLuigiMainMotion;
extern void * gFTDataLuigiModel;
extern s32 gFTDataLuigiParticleBankID;
extern void * gFTDataLuigiSpecial1;
extern void * gFTDataLuigiSpecial2;
extern void * gFTDataLuigiSpecial3;
extern void * gFTDataMMarioMain;
extern void * gFTDataMMarioMainMotion;
extern void * gFTDataMMarioModel;
extern s32 gFTDataMMarioParticleBankID;
extern void * gFTDataMMarioSpecial1;
extern void * gFTDataMMarioSpecial2;
extern void * gFTDataMMarioSpecial3;
extern void * gFTDataMMarioSubMotion;
extern void * gFTDataNCaptainMain;
extern void * gFTDataNCaptainModel;
extern s32 gFTDataNCaptainPad0x80131060;
extern s32 gFTDataNCaptainParticleBankID;
extern void * gFTDataNCaptainSubMotion;
extern void * gFTDataNDonkeyMain;
extern void * gFTDataNDonkeyModel;
extern s32 gFTDataNDonkeyPad0x80130F00;
extern s32 gFTDataNDonkeyParticleBankID;
extern void * gFTDataNDonkeySubMotion;
extern void * gFTDataNFoxMain;
extern void * gFTDataNFoxModel;
extern s32 gFTDataNFoxPad0x80130EC0;
extern s32 gFTDataNFoxParticleBankID;
extern void * gFTDataNFoxSubMotion;
extern void * gFTDataNKirbyMain;
extern void * gFTDataNKirbyModel;
extern s32 gFTDataNKirbyPad0x801310A0;
extern s32 gFTDataNKirbyParticleBankID;
extern void * gFTDataNKirbySubMotion;
extern void * gFTDataNLinkMain;
extern void * gFTDataNLinkModel;
extern s32 gFTDataNLinkPad0x80130FE0;
extern s32 gFTDataNLinkParticleBankID;
extern void * gFTDataNLinkSubMotion;
extern void * gFTDataNLuigiMain;
extern void * gFTDataNLuigiModel;
extern s32 gFTDataNLuigiPad0x80130FA0;
extern s32 gFTDataNLuigiParticleBankID;
extern void * gFTDataNLuigiSubMotion;
extern void * gFTDataNMarioMain;
extern void * gFTDataNMarioModel;
extern s32 gFTDataNMarioPad0x80130E80;
extern s32 gFTDataNMarioParticleBankID;
extern void * gFTDataNMarioSubMotion;
extern void * gFTDataNNessMain;
extern void * gFTDataNNessModel;
extern s32 gFTDataNNessPad0x80131160;
extern s32 gFTDataNNessParticleBankID;
extern void * gFTDataNNessSubMotion;
extern void * gFTDataNPikachuMain;
extern void * gFTDataNPikachuModel;
extern s32 gFTDataNPikachuPad0x801310E0;
extern s32 gFTDataNPikachuParticleBankID;
extern void * gFTDataNPikachuSubMotion;
extern void * gFTDataNPurinMain;
extern void * gFTDataNPurinModel;
extern s32 gFTDataNPurinPad0x80131120;
extern s32 gFTDataNPurinParticleBankID;
extern void * gFTDataNPurinSubMotion;
extern void * gFTDataNSamusMain;
extern void * gFTDataNSamusModel;
extern s32 gFTDataNSamusParticleBankID;
extern void * gFTDataNSamusSubMotion;
extern void * gFTDataNYoshiMain;
extern void * gFTDataNYoshiModel;
extern s32 gFTDataNYoshiPad0x80131020;
extern s32 gFTDataNYoshiParticleBankID;
extern void * gFTDataNYoshiSubMotion;
extern void * gFTDataPikachuMain;
extern void * gFTDataPikachuMainMotion;
extern void * gFTDataPikachuModel;
extern s32 gFTDataPikachuParticleBankID;
extern void * gFTDataPikachuSpecial1;
extern void * gFTDataPikachuSpecial2;
extern void * gFTDataPikachuSpecial3;
extern void * gFTDataPurinMain;
extern void * gFTDataPurinMainMotion;
extern void * gFTDataPurinModel;
extern s32 gFTDataPurinParticleBankID;
extern void * gFTDataPurinSpecial2;
extern void * gFTDataSamusMain;
extern void * gFTDataSamusMainMotion;
extern void * gFTDataSamusModel;
extern s32 gFTDataSamusParticleBankID;
extern void * gFTDataSamusSpecial1;
extern void * gFTDataSamusSpecial2;
extern void * gFTDataSamusSpecial3;
extern void * gFTDataYoshiMain;
extern void * gFTDataYoshiMainMotion;
extern void * gFTDataYoshiModel;
extern s32 gFTDataYoshiParticleBankID;
extern void * gFTDataYoshiSpecial2;
extern void * gFTDataYoshiSpecial3;
extern void * gFTMarioFileMain;
extern void * gFTMarioFileMainMotion;
extern void * gFTMarioFileModel;
extern void * gFTMarioFileSpecial1;
extern void * gFTMarioFileSpecial2;
extern void * gFTMarioFileSpecial3;
extern s32 gFTMarioParticleBankID;
extern void * gFTNessFileMain;
extern void * gFTNessFileMainMotion;
extern void * gFTNessFileModel;
extern void * gFTNessFileSpecial1;
extern void * gFTNessFileSpecial2;
extern void * gFTNessFileSpecial3;
extern s32 gFTNessParticleBankID;

#endif
