#!/usr/bin/env python3
"""
generate_reloc_table.py — Reads yamls/<version>/reloc_*.yml and generates
the file_id-to-resource-path lookup table (RelocFileTable.cpp) plus its
header (RelocFileTable.h, which carries the per-version RELOC_FILE_COUNT).

Usage:
    python tools/generate_reloc_table.py [--version {us,jp}]

  us (default): yamls/us -> port/resource/RelocFileTable.us.{cpp,h}
                (RELOC_FILE_COUNT = 2132)
  jp          : yamls/jp -> port/resource/RelocFileTable.jp.{cpp,h}
                (RELOC_FILE_COUNT = 2107)

port/resource/RelocFileTable.h is a committed selector shim that
#includes RelocFileTable.<REGION>.h, mirroring the decomp's
reloc_data.h design so both versions coexist in the source tree.
"""

import argparse
import os
import re
import sys
from pathlib import Path

# US keeps the legacy unsuffixed output names so its generated files are
# byte-for-byte unchanged; other versions get version-suffixed siblings.
VERSIONS = {
    "us": {"yaml_dir": "yamls/us", "stem": "RelocFileTable.us", "file_count": 2132},
    "jp": {"yaml_dir": "yamls/jp", "stem": "RelocFileTable.jp", "file_count": 2107},
}

# Defaults (US) so the module is importable without selecting a version.
YAML_DIR   = Path(VERSIONS["us"]["yaml_dir"])
OUTPUT     = Path(f"port/resource/{VERSIONS['us']['stem']}.cpp")
OUTPUT_H   = Path(f"port/resource/{VERSIONS['us']['stem']}.h")
FILE_COUNT = VERSIONS["us"]["file_count"]


def select_version(version):
    """Repoint the input/output/count globals at the chosen version."""
    global YAML_DIR, OUTPUT, OUTPUT_H, FILE_COUNT
    cfg = VERSIONS[version]
    YAML_DIR   = Path(cfg["yaml_dir"])
    OUTPUT     = Path(f"port/resource/{cfg['stem']}.cpp")
    OUTPUT_H   = Path(f"port/resource/{cfg['stem']}.h")
    FILE_COUNT = cfg["file_count"]


def parse_yaml_entries(yaml_dir: Path) -> dict[int, str]:
    """Parse all reloc_*.yml files and return {file_id: "dir/entry_name"}.

    The directory prefix is the YAML filename stem (e.g., reloc_menus.yml
    produces paths like "reloc_menus/MNIndex"), matching how Torch stores
    resources inside the .o2r archive.
    """
    entries = {}

    for fname in sorted(yaml_dir.iterdir()):
        if not fname.name.startswith("reloc_") or not fname.suffix == ".yml":
            continue

        prefix = fname.stem  # e.g. "reloc_menus"
        content = fname.read_text(encoding="cp1252")
        current_name = None

        for line in content.split("\n"):
            m = re.match(r"^([A-Za-z_]\w*):\s*$", line)
            if m:
                current_name = m.group(1)
                continue
            if current_name:
                m2 = re.match(r"^\s+file_id:\s+(\d+)", line)
                if m2:
                    fid = int(m2.group(1))
                    full_path = f"{prefix}/{current_name}"
                    if fid in entries:
                        print(f"WARNING: duplicate file_id {fid}: "
                              f"{entries[fid]} vs {full_path}", file=sys.stderr)
                    entries[fid] = full_path
                    current_name = None

    return entries


def generate(entries: dict[int, str], output: Path) -> None:
    """Write the C++ lookup table."""
    lines = []
    lines.append("/**")
    lines.append(" * RelocFileTable.cpp - Auto-generated file_id to resource path mapping.")
    lines.append(" *")
    lines.append(" * Generated by: python tools/generate_reloc_table.py")
    lines.append(" * DO NOT EDIT BY HAND.")
    lines.append(" */")
    lines.append("")
    lines.append('#include "RelocFileTable.h"')
    lines.append("")
    # NULL isn't a keyword. Desktop toolchains pick it up transitively from
    # RelocFileTable.h's preceding #pragma once / extern "C" headers, but
    # NDK r29's stricter header set doesn't, so add the explicit include.
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append(f"const char* const gRelocFileTable[RELOC_FILE_COUNT] = {{")

    for i in range(FILE_COUNT):
        name = entries.get(i)
        if name is None:
            lines.append(f"\tNULL, /* {i} - MISSING */")
        else:
            lines.append(f'\t"{name}", /* {i} */')

    lines.append("};")
    lines.append("")

    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {output} ({len(entries)} entries)")


def generate_header(output_h: Path) -> None:
    """Write RelocFileTable.<version>.h carrying RELOC_FILE_COUNT + the
    gRelocFileTable extern. The committed RelocFileTable.h shim selects
    the right one by REGION_*. The 'us' body is the same content the
    previously hand-maintained RelocFileTable.h carried (count 2132).
    """
    lines = [
        "#pragma once",
        "",
        f"#define RELOC_FILE_COUNT {FILE_COUNT}",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "/**",
        f" * Maps file_id (0–{FILE_COUNT - 1}) to the resource path in the .o2r archive.",
        f" * Auto-generated from {YAML_DIR.as_posix()}/reloc_*.yml by tools/generate_reloc_table.py.",
        " */",
        "extern const char* const gRelocFileTable[RELOC_FILE_COUNT];",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]
    output_h.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {output_h} (RELOC_FILE_COUNT={FILE_COUNT})")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", choices=sorted(VERSIONS), default="us",
                        help="ROM version (default: us)")
    select_version(parser.parse_args().version)

    os.chdir(Path(__file__).resolve().parent.parent)
    entries = parse_yaml_entries(YAML_DIR)

    if len(entries) != FILE_COUNT:
        print(f"WARNING: expected {FILE_COUNT} entries, got {len(entries)}",
              file=sys.stderr)

    missing = set(range(FILE_COUNT)) - set(entries.keys())
    if missing:
        print(f"WARNING: missing file_ids: {sorted(missing)[:20]}...",
              file=sys.stderr)

    generate(entries, OUTPUT)
    generate_header(OUTPUT_H)


if __name__ == "__main__":
    main()
