#!/usr/bin/env python3
"""
png_to_c_array.py — Convert a PNG to a C header containing a static
                    const unsigned char[] of big-endian RGBA16 pixels.

Usage:
    python3 tools/png_to_c_array.py <input.png> <output.h> <symbol_prefix>

The generated header defines:
    static const unsigned char k<SymbolPrefix>RGBA16[W * H * 2];
    static const int           k<SymbolPrefix>Width  = W;
    static const int           k<SymbolPrefix>Height = H;

where <SymbolPrefix> = capitalize(symbol_prefix).

RGBA16 encoding (big-endian, 2 bytes per pixel):
    pixel = ((r>>3)<<11) | ((g>>3)<<6) | ((b>>3)<<1) | (a>>7)
    stored as: [high_byte, low_byte]

Anti-aliasing note:
    This tool encodes whatever PNG is provided without further AA processing.
    For AA, pre-process the source PNG (e.g., with generate_arrow_svg.py).

Idempotency: CMake's add_custom_command tracks source PNG mtime; if the PNG
hasn't changed since the last configure, CMake skips regeneration and the
header's mtime is unchanged, so dependent .cpp files are not recompiled.

This script has NO non-stdlib dependencies beyond Pillow (PIL).
"""

import sys
import struct
from pathlib import Path


def _banner(script_name: str, src_name: str) -> str:
    return (
        f"// Auto-generated by {script_name} from {src_name}.\n"
        "// Do not edit by hand — regenerated from the source PNG on every rebuild.\n"
        "// To update: edit the PNG and rebuild; CMake will re-invoke this script.\n"
    )


def encode_png_to_rgba16_header(src_path: str, dst_path: str,
                                 symbol_prefix: str) -> None:
    try:
        from PIL import Image
    except ImportError:
        sys.exit("ERROR: Pillow is required.  Install with: pip install Pillow")

    img = Image.open(src_path).convert("RGBA")
    w, h = img.size
    raw = img.tobytes()  # flat RGBA8: [r, g, b, a, r, g, b, a, ...]
    npx = w * h

    # Build the big-endian RGBA16 byte list
    rows = []
    for i in range(0, npx * 4, 64):  # 16 pixels = 32 bytes = 16*4 = 64 rgba8 bytes
        chunk_rgba8 = raw[i:i + 64]
        pixel_hex = []
        for p in range(0, len(chunk_rgba8), 4):
            r, g, b, a = chunk_rgba8[p], chunk_rgba8[p+1], chunk_rgba8[p+2], chunk_rgba8[p+3]
            px = ((r >> 3) << 11) | ((g >> 3) << 6) | ((b >> 3) << 1) | (a >> 7)
            hi = (px >> 8) & 0xFF
            lo = px & 0xFF
            pixel_hex.append(f"0x{hi:02x}, 0x{lo:02x}")
        rows.append(", ".join(pixel_hex))

    arr_body = ",\n    ".join(rows)

    # Capitalise first letter for the C symbol
    sym = symbol_prefix[0].upper() + symbol_prefix[1:]
    script_name = Path(__file__).name
    src_name = Path(src_path).name

    header = f"""{_banner(script_name, src_name)}
#pragma once

static const int k{sym}Width  = {w};
static const int k{sym}Height = {h};
static const unsigned char k{sym}RGBA16[{w * h * 2}] = {{
    {arr_body}
}};
"""

    out = Path(dst_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header, encoding="utf-8")
    print(f"png_to_c_array: {src_path} ({w}x{h}) -> {dst_path} "
          f"({w*h*2} bytes, symbol k{sym}RGBA16)")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)
    encode_png_to_rgba16_header(sys.argv[1], sys.argv[2], sys.argv[3])
