#ifndef MARIO_GEO_SWITCH_CASE_IDS_H
#define MARIO_GEO_SWITCH_CASE_IDS_H

enum MarioEyesGSCId {
     MARIO_EYES_BLINK,
     MARIO_EYES_OPEN,
     MARIO_EYES_HALF_CLOSED,
     MARIO_EYES_CLOSED,
     MARIO_EYES_LOOK_LEFT,
     MARIO_EYES_LOOK_RIGHT,
     MARIO_EYES_LOOK_UP,
     MARIO_EYES_LOOK_DOWN,
     MARIO_EYES_DEAD
};

enum MarioHandGSCId {
     MARIO_HAND_FISTS,
     MARIO_HAND_OPEN,
     MARIO_HAND_PEACE_SIGN,
     MARIO_HAND_HOLDING_CAP,
     MARIO_HAND_HOLDING_WING_CAP,
     MARIO_HAND_RIGHT_OPEN
};

enum MarioCapGSCId {
     MARIO_HAS_DEFAULT_CAP_ON,
     MARIO_HAS_DEFAULT_CAP_OFF,
     MARIO_HAS_WING_CAP_ON,
     MARIO_HAS_WING_CAP_OFF
};

enum MarioGrabPosGSCId {
     GRAB_POS_NULL,
     GRAB_POS_LIGHT_OBJ,
     GRAB_POS_HEAVY_OBJ,
     GRAB_POS_BOWSER
};

#endif
